// This file is generated

F_name_0 = [
"Famille de , \u0623\u062d\u0645\u062f et , \u0631\u064a\u062d\u0627\u0646\u0629",
"Famille de , \u0623\u062d\u0645\u062f et \u0627\u0644\u0641\u0636\u0644, \u0627\u0644\u0639\u0628\u0627\u0633\u0629",
"Famille de , \u0645\u062d\u0645\u062f et , \u062e\u062f\u064a\u062c\u0629",
"Famille de , \u0645\u062d\u0645\u062f et , \u0639\u0627\u0626\u0634\u0629",
"Famille de Adams, William et Aguilar, Eleanor",
"Famille de Adkins, John et Adams, Jane",
"Famille de Adkins, Robert Sr. et Nielsen, Martha",
"Family of Aguilar, John",
"Famille de Allen, Benjamin et Griffith, Experience",
"Famille de Allen, Gershom et Kennedy, Ann",
"Famille de Allen, John et Dennis, Mary (Hannah?)",
"Famille de Allen, Joseph et Barker, Mary",
"Famille de Alonso, Joseph et Hansen, Monica",
"Famille de Alvarado, Cadwallader et Mendez, Martha",
"Famille de Alvarado, Col. Charles et Parent, Eleanor",
"Famille de Alvarado, Franklin et Hodges, Comfort",
"Famille de Alvarado, Jack D. et Warner, Shirley Kay",
"Famille de Alvarado, Jeffery et Cruz, Patti Jo",
"Family of Alvarado, Jeffrey",
"Famille de Alvarado, John et James, Pamela",
"Famille de Alvarado, Marshall et Bouchard, Jane",
"Famille de Alvarado, Thomas C. et \u041c\u0435\u0434\u0432\u0435\u0434\u0435\u0432, Mary",
"Famille de Alvarado, Wayne et Boucher, Sharon",
"Famille de Alvarado, William et Moody, Martha",
"Famille de \u00c1lvarez et Porter, Mahala J.",
"Famille de Andersen, Samuel et Moreno, Delilah",
"Famille de Anderson, Rev. John et Christiansen, Martha",
"Famille de Anderson, Samuel et \u0424\u0438\u043b\u0438\u043f\u043f\u043e\u0432, Elizabeth",
"Famille de Anderson, Thomas et Carpenter, Sarah",
"Famille de Andrews, Harold et Garner, Cecile Elizabeth",
"Famille de Armstrong, Teddy C. et Cross, Gertrude",
"Famille de Arnold, ??????? et \u042f\u043a\u043e\u0432\u043b\u0435\u0432, Esther Faye",
"Famille de Austin, Hans et Burke, Maria",
"Famille de Austin, Johannas et Jenkins, Margaret",
"Famille de Baldwin, Peter et \u041d\u0438\u043a\u0438\u0444\u043e\u0440\u043e\u0432",
"Famille de Ball, Ezekiel et Reese",
"Famille de Ball, Jasper et \u0417\u044b\u043a\u043e\u0432, Angeline",
"Famille de Ball, Matthias Sr. et Maxwell, Ann",
"Famille de Ball, Matthias, Jr. et Gonzalez, Eliza Jane",
"Famille de Ball, Matthias, Jr. et Moreno, Abigail Chapman",
"Famille de Ball, Matthias, Jr. et Snyder, Ann Louisa",
"Famille de Ball, Thomas et \u0428\u0430\u0434\u0440\u0438\u043d, Mary",
"Famille de Ball, William M. et Moreno, Phebe J.",
"Famille de Bates, William Robert et \u0414\u0430\u043d\u0438\u043b\u043e\u0432, Elaine Suzanne",
"Famille de Beaulieu, Johann Adam et Michaud, Anna Eva",
"Famille de Beaulieu, Johann Franciskus et Barnett, Anna Gertrude",
"Famille de Beaulieu, Johann Michael et L\u00f3pez, Anna Elisabeth",
"Famille de Beaulieu, Johann Simon et Holland, Anna Margaretha",
"Famille de Beaulieu, Johann Simon et \u0410\u043b\u0435\u043a\u0441\u0430\u043d\u0434\u0440\u043e\u0432, Anna Margaretha",
"Famille de Beaulieu, Johann Simon et \u0413\u0440\u0438\u0433\u043e\u0440\u044c\u0435\u0432, Anna Maria",
"Famille de Beaulieu, Johann Theobald et Sutton, Anna Maria",
"Famille de Beaulieu, Johann Valentin et Frazier, Maria Margaretha",
"Famille de Beaulieu, Johann Valentin et Morgan, Elisabeth Margaretha",
"Famille de Beck, Jack et Garner, Bernadette",
"Famille de Becker et Hawkins, Jean",
"Famille de B\u00e9dard, Swanson et \u0414\u043c\u0438\u0442\u0440\u0438\u0435\u0432, Mary",
"Famille de B\u00e9langer, Adrian et Neal, Helen M.",
"Famille de B\u00e9langer, Donald et Pierce, Joanne",
"Famille de B\u00e9langer, James et Garner, Bernetha Ellen",
"Famille de Bell, Gary Richard et Cruz, Judy Denise",
"Family of Benson, David",
"Famille de Benson, Hugh et Ouellet, Rebecca",
"Family of Benson, John",
"Famille de Benson, Joseph Louis(Jr.) et Richard, Jeanne",
"Famille de Benson, Joseph Louis(Sr.) et Simard, Sarah",
"Famille de Benson, Samuel Sr. et Wong, Jane",
"Famille de Benson, Walter et Ellis, Margaret Steel",
"Family of Benson, William",
"Famille de Bergeron, John W. et \u0411\u044b\u043a\u043e\u0432, Bettie",
"Famille de Berry et Reed, Carmel",
"Famille de Bishop, Quirinus et Simmons, Maria",
"Famille de Blais, ?? et L\u00e9vesque, Mary",
"Famille de Blake, Conrad et Ruiz, Catherine",
"Famille de Blake, George et Cunningham, Sally Sarah",
"Famille de Blanco, Bendicht et Fisher, Bendichtli",
"Famille de Blanco, Gerhard et \u0411\u0435\u043b\u043e\u0443\u0441\u043e\u0432, Catharine",
"Famille de Blanco, Hans et Buchanan, Elsbeth",
"Famille de Blanco, Hans(Johannes) et Sullivan, Anna",
"Famille de Blanco, Heinrich et Schmidt, Barbli",
"Famille de Blanco, Henry et Fournier, Peggy",
"Famille de Blanco, John Sr. et Lucas, Christina",
"Famille de Blanco, Milton et Landry, Sarah",
"Famille de Blanco, Peter et Glover, Elizabeth",
"Famille de Blanco, Peter et Leonard, Catherine",
"Famille de Blanco, Rufus et Rodriquez, Mariam",
"Famille de Boucher, David et Morrison, Nancy",
"Famille de Boucher, James et Dub\u00e9, Rose",
"Famille de Boucher, John et \u041d\u0438\u043a\u0438\u0442\u0438\u043d, Monica",
"Family of Boucher, John",
"Famille de Boucher, Michael et Boucher, Anne",
"Famille de Boucher, Michael et Boucher, Honora",
"Famille de Boucher, Michael et Gil, Nora",
"Famille de Boucher, Michael Shannon et Iglesias, Kate",
"Famille de Boucher, Patrick et Dennis, Susan",
"Family of Boucher, Patrick",
"Famille de Boucher, Roger Joseph et Page, Sylvia Louise",
"Famille de Boucher, Sean et Gardner, Mary",
"Famille de Boucher, Stephen Francis et Gardner, Mary Jane",
"Famille de Boucher, Steven Joseph et Nelson, Arlene",
"Famille de Boucher, Thomas et Thompson, Bridget",
"Famille de Boucher, Thomas W. et Szyma\u0144ski, Mary",
"Famille de Boucher, William et Fields, Bridget M.",
"Famille de Boucher, William et Savard, Honora",
"Famille de Boucher, William et Walters, Mary",
"Famille de Boucher, William Bernard et Reeves, Maria",
"Famille de Boucher, William J. et Howell, Marie",
"Family of Boucher, woman",
"Famille de Boyd, Capt. et Alvarado, Eliza",
"Famille de Boyd, Charles Newton et Jones, Martha Elizabeth",
"Famille de Boyd, Charles Newton et Lessard, Izora",
"Famille de Brady, Michael et Boucher, Agnes",
"Famille de Brady, Tony et Boucher, Bridget",
"Famille de Brock, Stephen et Welch, Annabelle Elaine",
"Family of Brooks, Guillaume de",
"Famille de Brooks, Major Marquis II et Rubio, Winifred",
"Famille de Brooks, Marquis I et Guzman, Isabella",
"Famille de Brooks, William Waller et \u0412\u0430\u0441\u0438\u043b\u044c\u0435\u0432, Lucy",
"Famille de Brown, ????? et \u0422\u0438\u0445\u043e\u043d\u043e\u0432, Mary Ellen",
"Famille de Burgess, Edward et Garner, Marie",
"Famille de Burns, Jonathan et Rubio, Dorcas",
"Famille de Bush, James et Boucher, Catherine",
"Famille de Butler, George et Farmer, Eva",
"Famille de Caldwell, Paul et Boucher, Martha",
"Famille de Carroll, Jacob A. et \u041d\u0438\u043a\u043e\u043b\u0430\u0435\u0432, Maria Catharina",
"Famille de Carroll, Matthias Sr. et \u0412\u043e\u0440\u043e\u0431\u044c\u0435\u0432, Eva",
"Famille de Chambers, William et Moreno, Leah",
"Famille de Christensen, William et Cruz, Judy Denise",
"Famille de Christiansen, Christopher et Gomez, Jane Joane",
"Famille de Christiansen, Christopher et Jones, Ann",
"Famille de Christiansen, Edward et Abbott, Frances",
"Famille de Christiansen, Edward et Thomas, Elizabeth",
"Family of Christiansen, Edward",
"Famille de Christiansen, John et Harmon, Martha",
"Family of Christiansen, John",
"Famille de Christiansen, Joseph et Allen, Joanna",
"Famille de Christiansen, Joseph et Gonz\u00e1lez, Elizabeth",
"Famille de Christiansen, Nathaniel et Grenier, Mary",
"Famille de Christiansen, Samuel et Alvarado, Mary",
"Famille de Cobb, Merrick et Boucher, Cynthia Louise",
"Famille de Coleman et Garner, Louella Marie",
"Famille de Collins, Loren et Rhodes, Mary Jane",
"Famille de Colon, William et Guti\u00e9rrez, Dorothy Jean",
"Famille de Cook, John et Rodriquez, Mary",
"Famille de Cooper, ??????? et Garner, Maude",
"Famille de C\u00f4t\u00e9, Raymond Patrick et Russell, Beth Ann",
"Famille de Cox, Robert C. et Garner, Jane McClellan",
"Famille de Cross, Thomas et Page, Anna",
"Famille de Cruz, Arthur Ray et Robbins, Myrabel",
"Famille de Cruz, Dale Eugene et Gill, Linda",
"Famille de Cruz, David Wayne et Nunez, Barbara Ann",
"Famille de Cruz, Everett et Lessard, Susanna Marie",
"Famille de Cruz, Gerald Ray et Rasmussen, Marilyn Joan",
"Famille de Cruz, Ivan Wayne et Gagnon, Bettie Lou",
"Famille de Cruz, James Richard et Morales, Penelope Margot",
"Famille de Cruz, Paul Eugene et Lambert, Marguerite",
"Famille de Cruz, Thomas Everett et Briggs, Joyce Inez",
"Famille de Cruz, William Everett et Hawkins, Ellen Marie",
"Famille de Cunningham, Peter Sr. et Dunn, Margaret Mary?",
"Famille de Cunningham, William Philip et Park, Susannah",
"Famille de Curry, Kenner S. et Jim\u00e9nez, Rebecca",
"Famille de Curtis, John et Gibbs, Margaret",
"Famille de Daniels et Page, Edith (Dolly)",
"Famille de Davis, Benjamin et Alexander, Mary",
"Famille de Davis, John et Knight, Hannah",
"Famille de Davis, Jonathan et Mitchell, Mary",
"Famille de Dawson et Reed, Anastasia",
"Famille de Day, Charles et Serrano, Dot",
"Famille de Dean, John et Reed, Catherine",
"Famille de Delgado et Tyler, Mary A.",
"Famille de Demers, ?? et \u0421\u0435\u0440\u0433\u0435\u0435\u0432, Adria Maria",
"Famille de Desjardins, J. et Reeves, Catherine",
"Famille de Diaz, James et Woods, Nancy",
"Famille de Diaz, William et Baldwin, Anne",
"Famille de Diaz, William et \u041a\u043e\u043c\u0430\u0440\u043e\u0432, Jane",
"Famille de Diaz, William (Rev.) et Hoffman, Fay",
"Famille de D\u00edez, William George et Garner, Barbara Jo",
"Famille de Dixon, Thomas et Warner, Mary",
"Famille de Dom\u00ednguez, George et \u041c\u0430\u043a\u0441\u0438\u043c\u043e\u0432, Nancy",
"Famille de Douglas, Abraham et Alvarado, Nancy",
"Famille de Douglas, Abraham et Greer, Mary Wein",
"Family of Douglas, Alfred",
"Famille de Douglas, Frederick et Stanley, Barbara",
"Famille de Douglas, Hans Peter et Cummings, Leonnah",
"Famille de Douglas, Hans Peter et Howard, Juliana",
"Famille de Douglas, John Jr. et Johnson, Elizabeth",
"Famille de Douglas, John Jr. et Rogers, Barbara",
"Famille de Douglas, John Sr. et Larson, Christena Wiseman",
"Famille de Douglas, John Sr. et Moran, Ann Delilah \"Tilley\"",
"Famille de Douglas, Joseph et Carroll, Grace",
"Famille de Doyle, Robert Gove et Diaz, Mary Polly",
"Famille de Dub\u00e9, Jacob et Farmer, Anna Marie",
"Famille de Duncan et Reed, Joan",
"Famille de Elliott, Lodowick et \u041a\u043e\u0432\u0430\u043b\u0435\u0432, Sarah",
"Famille de Erickson, Charles et \u0414\u043c\u0438\u0442\u0440\u0438\u0435\u0432, Lucy",
"Famille de Evans, ?m.MaryJane et Rhodes, Mary Jane",
"Famille de Evans, James Patrick et Stevenson, Susan",
"Famille de Farmer, Benjamin H. et Mills, Isabella",
"Famille de Farmer, George William et Bradley, Mary",
"Famille de Farmer, Jacob et \u041c\u043e\u0440\u043e\u0437\u043e\u0432, Mary Elizabeth",
"Famille de Farmer, Michael et Dub\u00e9, Elizabeth",
"Famille de Farmer, Peter Simon et Bowen, Elizabeth",
"Famille de Farmer, Simon et \u0411\u0430\u0440\u0430\u043d\u043e\u0432, Susan",
"Famille de Farmer, Valentine et Miller, Anna Catherine",
"Family of Ferguson, Lord Samuel",
"Famille de Fernandez, Thomas et Couture, Honora",
"Famille de Fernandez, Thomas et Holloway, Sarah",
"Famille de Fernandez, Thomas et Ortega, Catherine",
"Famille de Fillin, C et Fillin, D",
"Famille de Fillin, E et Fillin, F",
"Famille de Fillin, G et Fillin, H",
"Famille de Fillin, I et Fillin, J",
"Famille de Fillin, K et Fillin, L",
"Famille de Fillin, M et Fillin, N",
"Famille de Fitzgerald, David Lee et \u041b\u043e\u043f\u0430\u0442\u0438\u043d, Donna Elaine",
"Famille de Floyd, Henry et Benson, Nancy",
"Famille de Floyd, John Morgan et Carr, Zelpha Josephine",
"Famille de Floyd, John S. et Coleman, Mary",
"Famille de Floyd, Robert William et \u0414\u0430\u043d\u0438\u043b\u043e\u0432, Kathryn Louise",
"Famille de Ford et Moreno, Elizabeth",
"Famille de Ford, Phillip D. et Webb, Joan Lorinda",
"Famille de Ford, Samuel et Farmer, Catharine",
"Famille de Ford, Stephen Jacob et Garner, Iola Elizabeth Betty",
"Famille de Ford, William et Payne, Winifred",
"Famille de Fortin, Matthias et Baker, Margaret",
"Famille de Foster, John et Ryan, Elizabeth",
"Famille de Foster, John et Ryan, Elizabeth",
"Famille de Foster, Thomas et Koz\u0142owski, Margret",
"Famille de Foster, Thomas et Spencer, Ann",
"Famille de Foster, William et Sanders, Mary",
"Famille de Fox, David et Green, Frances",
"Famille de Fox, David et Harris, Mary",
"Famille de Fox, Jacob, Sr. et Palmer, Sarah",
"Famille de Fox, Samuel et Mason, Susannah",
"Famille de Fox, William et Mason, Hannah",
"Famille de Frazier, Johann Adam et Hicks, Anna Eva",
"Famille de Frazier, Johann Walter et Beaulieu, Anna Margaretha",
"Famille de French, Jimmy Michael et Warner, Martha Ellen",
"Famille de Gagn\u00e9, Thomas et Reeves, Ann",
"Famille de Gardner, Michael et Hansen, Nula",
"Family of Gardner, Patrick",
"Famille de Garner, Barry Joseph et V\u00e1zquez, April Lynn",
"Famille de Garner, Daniel Webster et Jackson, Cora Ellen",
"Famille de Garner, Eugene Stanley et Reed, Frances Lucille (Babe)",
"Famille de Garner, Eugene Stanley, Jr. et Pelletier, Josephine",
"Famille de Garner, Eugene Stanley, Jr. et Washington, Pearline",
"Famille de Garner, Francis William et Gibbs, Connie",
"Famille de Garner, Gerard Stephen et George, Elizabeth",
"Famille de Garner, Howard Lane et Mar\u00edn, Mary Anne",
"Famille de Garner, Jason Richard et Harper, ??",
"Famille de Garner, Jesse V. et Taylor, Viola",
"Famille de Garner, John Joseph et Crawford, Lori",
"Famille de Garner, John Roger et \u0411\u0440\u044e\u0445\u0430\u043d\u043e\u0432, Violet Louise",
"Famille de Garner, Joseph et Edwards, Lucy",
"Famille de Garner von Zieli\u0144ski, Lewis Anderson Sr et Martel, Luella Jacques",
"Famille de Garner, Mark Gerard et Gibbs, Lori",
"Famille de Garner, Michael Stanley et Gibbs, Sharon",
"Famille de Garner, Peter George et Gibbs, Joy",
"Famille de Garner, Raymond Scott et P\u00e9rez, Angela Gay",
"Famille de Garner, Raymond Webster et Bryant, Kathryn Ladon",
"Famille de Garner, Richard Eugene et Gibbs, Elaine",
"Famille de Garner, Robert F. et Cannon, Mary Jane",
"Famille de Garner, Robert W. et Zieli\u0144ski, Phoebe Emily",
"Famille de Garner, Thomas James et \u0421\u043e\u0440\u043e\u043a\u0438\u043d, Holly Ruth",
"Famille de Garner, Walter E. et Garc\u00eda, Maude",
"Famille de Garrett, Terry Lee et Holloway, Gail",
"Famille de Garrett, William Forest et Perkins, Wilma Mae",
"Famille de Garrett, William Walker et Lessard, Laura Eloise",
"Family of Gibbs, Rosina M.",
"Famille de Gibson, Mr. et James, Mary",
"Famille de Gilbert, ?? et L\u00e9vesque, Wilma",
"Famille de Gill, Lawrence et Webb, Joan Lorinda",
"Family of Gill, Lawrence",
"Family of Gomez, Culthbert",
"Famille de Gonz\u00e1lez et Ball, Martha",
"Famille de Goodman, Ralph et Powell, Martha",
"Famille de Goodwin et Sandoval, Liz",
"Famille de Gosselin, Martin Kelly et Warner, Marcia Jane",
"Famille de Grabowski, Mr. et Waters, Lola",
"Famille de Graham, Steve et Cruz, Laura Joy",
"Famille de Green, Edward et Lefebvre, Mary",
"Famille de Green, Edward et \u041c\u0430\u043a\u0441\u0438\u043c\u043e\u0432, Christina",
"Famille de Green, James et Christiansen, Frances",
"Famille de Green, Randolph et Davis, Sabra",
"Famille de Green, Yelverton et Robertson, Elizabeth",
"Famille de Grenier, Joseph et Peters, Rose",
"Famille de Gross et Peters, Dorothy",
"Family of Guerrero, Robert",
"Family of Guerrero, Robert",
"Family of Guerrero, Walter",
"Family of Guerrero, Walter",
"Family of Guerrero, Walter",
"Famille de Gutierrez, Thomas et Boucher, Nora A.",
"Famille de Guti\u00e9rrez, Walter Harmon et Boyd, Lauretta Esther",
"Famille de Hale, Lawrence Paul et Garner, Anne Therese",
"Famille de Hamilton, John et Boucher, Miread",
"Famille de Hammond, Roy et Serrano, Carrie",
"Famille de Hansen, Noel et Ramirez, Helen",
"Famille de Hansen, Thomas et Boucher, Rose Mary",
"Famille de Hanson, Robert et Schwartz, Helewisa",
"Famille de Hardy, Jakob et Beaulieu, Anna Maria",
"Famille de Harris, Lawrence et Landry, Alice",
"Famille de Harrison, Edward et Allen, Sarah",
"Famille de Harrison, Paul Allen et \u0414\u0430\u043d\u0438\u043b\u043e\u0432, Lucinda Elinor",
"Famille de Hart, Gerry et Boucher, Mary",
"Family of Harvey, John",
"Famille de Hawkins, Beckham et \u0410\u0444\u0430\u043d\u0430\u0441\u044c\u0435\u0432, Angie",
"Family of Hawkins, Richard W.",
"Famille de Hawkins, William Melvin et Gibbs, Ruth",
"Family of Hawkins, William Melvin",
"Famille de Haynes, Marc W. et Warner, Laura Gail",
"Famille de H\u00e9bert, Mr. et Page, Mary",
"Family of Henry, John",
"Famille de Hernandez, John et Norris, Elizabeth",
"Famille de Hern\u00e1ndez, Thomas et Douglas, Elizabeth",
"Famille de Hill et Garner, Louella Marie",
"Famille de Hines et Douglas, Eliza Jane",
"Famille de Holloway, John(?) et \u041e\u0440\u043b\u043e\u0432, Margaret(?)",
"Family of Howard, Michael",
"Famille de Howell, John et Yates, Sarah",
"Family of Howell, JOHN",
"Famille de Hunt, Isaac et \u0414\u043c\u0438\u0442\u0440\u0438\u0435\u0432, Nancy Ann",
"Famille de James, Hugh Jr. et Wi\u015bniewski, D.",
"Famille de James, Hugh Sr. et Serrano, Caroline",
"Famille de James, Isaac et Andersen, Martha",
"Family of James, James",
"Famille de James, Joseph et Floyd, Nancy",
"Famille de James, Robert et Pratt, Sarah",
"Famille de James, Thomas et Marshall, Kate Teel",
"Famille de James, Thomas et Parent, Betsy",
"Famille de James, Thomas Sr. et Benson, Martha Ellen M.",
"Famille de James, Walter Crockett et Hern\u00e1ndez, Nancy",
"Famille de James, Walter Crockett et \u0417\u0430\u0445\u0430\u0440\u043e\u0432, Margaret",
"Famille de Jankowski, George et Page, Margaret",
"Famille de Jenkins, Peter et Marsh, Margaret",
"Famille de Jimenez et Reed, Maureen",
"Famille de Jim\u00e9nez, Andrew et Palmer, Sarah",
"Famille de Jim\u00e9nez, Cornelius et Blair, Jane",
"Famille de Jim\u00e9nez, George Henry, III et Blake, M. Susannah",
"Famille de Jim\u00e9nez, George Henry, Jr. et Silva, Mildred",
"Famille de Jim\u00e9nez, George, Sr. et Henry, Elizabeth",
"Famille de Jim\u00e9nez, John et Palmer, Mary",
"Famille de Johnson, Henry et Sparks, Catherine",
"Famille de Johnson, Richard F. et Garner, Betty Jane",
"Famille de Johnston et Sandoval, Jean",
"Famille de Jones, Hugh et \u041a\u0438\u0440\u0438\u043b\u043b\u043e\u0432, ??",
"Famille de Jordan, William et Reed, Frances Lucille (Babe)",
"Famille de J\u00f8rgensen, Jeffrey et Osborne, Julia Marie",
"Famille de Joseph, Alfred et Moreno, Minerva",
"Famille de Kami\u0144ski et Reed, Jane",
"Family of Keller, Mathew",
"Famille de Kelley, Thomas et Douglas, Catherine",
"Famille de Kim, Frank et Kristensen, Catherine Virginia",
"Famille de King, Henry et \u0411\u044b\u043a\u043e\u0432, Annie",
"Famille de Knudsen, John et Huff, Isabel",
"Famille de Knudsen, Ralph et Huff, Isabel",
"Famille de Knudsen, Ralph et Walton, Theophania(Tiffany)",
"Famille de Knudsen, Ranulf et Huff, Bertrama",
"Famille de Knudsen, Robert et Schwartz, Helewisa",
"Famille de Kowalski, John et Wells, Alice",
"Famille de Kowalski, Thomas et Santos, Alice",
"Famille de Krawczyk, Douglas et Cruz, Patti Jo",
"Famille de Kristensen, John Francis\"Chick\" et \u4f0a\u85e4, Mary",
"Famille de Landry, John Anthony et Harris, Ella Mae",
"Famille de Landry, Maurice T. et Estrada, Mary Claire",
"Famille de Landry, Maurice T. et Vargas, Caroline Metzger",
"Famille de Landry, Michael Edward et Brady, CatherineJosephine",
"Famille de Lane, Joseph Edward et \u041a\u043e\u0437\u043b\u043e\u0432, Linda Mae",
"Famille de Lane, Joseph Robert et Thornton, Dorothy Eleanor",
"Famille de Lane, Remo et Barnes, Ernestina",
"Famille de Lapointe, John et Madsen, Catherine",
"Family of Lapointe, Sir Thomas",
"Family of Lapointe, William",
"Famille de Lavoie, Henry et James, Patsy",
"Famille de Lawson, Mr. et Parent, Polly",
"Famille de Lefebvre, Joseph et Gregory, Mary",
"Famille de Lefebvre, Rev. John L. et Kowalski, Hannah",
"Family of Lefebvre, Rev. John L.",
"Famille de Lefebvre, Robert et \u0413\u043e\u043d\u0447\u0430\u0440\u043e\u0432, Ellen",
"Famille de Lessard et Castro, ???",
"Famille de Lessard, ??? et Castro, ???",
"Famille de Lessard, Carl Tolbert et Webb, Luella Florence",
"Famille de Lessard, Ira Willis et Jim\u00e9nez, Lucinda Ellen",
"Famille de Lessard, Isaac et Dom\u00ednguez, Mary E.",
"Famille de Lessard, Ralph Raymond et Davidson, Bernice",
"Famille de Lessard, Robert et Webb, Joan Lorinda",
"Famille de L\u00e9vesque, James W. et Lessard, Emma Jane",
"Famille de Lewandowski, Thomas et Jankowski, Isabella Belle",
"Famille de Lindsey, John et Warner, Martha Ellen",
"Famille de Little, O. D. et Webb, Anna Mabel",
"Famille de Logan, Joseph et \u0411\u044b\u043a\u043e\u0432, Janie",
"Famille de L\u00f3pez, Hans Valentin et Beaulieu, Anna Ottilia",
"Famille de Love et Reed, Carmel",
"Famille de Mack, ?? et L\u00e9vesque, Elsie",
"Family of Maldonado, Edward",
"Famille de Mar\u00edn, Alfred Franklin(Frank) et Floyd, Martha Frances \"Fannie\"",
"Famille de Mar\u00edn, Moses Wallace et Landry, Eleanor (Nellie) Therese",
"Famille de Mar\u00edn, Walter Matthew et Boucher, Mary Cecilia",
"Famille de Mar\u00edn, William et Francis, Elizabeth",
"Famille de Mar\u00edn, Willis H. et Floyd, Sarah (Sally)",
"Famille de Martel, Henry et H\u00e9bert, Ruth Ann",
"Famille de Martin et Moreno, Mary Ann",
"Famille de Mart\u00edn et Garner, Melissa Sue",
"Famille de Martinez et Reed, Catherine",
"Famille de Mart\u00ednez et Serrano, Reh Dawn",
"Famille de Massey, John et \u041c\u0430\u043b\u044c\u0446\u0435\u0432, Joan",
"Famille de Matthews, Mark John et Warner, Andrea Susan",
"Famille de Maxwell, William et Nielsen, Elizabeth",
"Famille de Mazur, William et Crawford, Margaret",
"Famille de Mcbride, Paul et \u0414\u0430\u043d\u0438\u043b\u043e\u0432, Barbara Joanne",
"Famille de McCarthy, Valentine Thomas et Jim\u00e9nez, Sarah",
"Famille de McCormick, Dean et Page, Florence",
"Famille de McCoy, Francis et Reed, Sarah",
"Famille de McCoy, Thomas Michael et Howell, Mary",
"Famille de Medina, Wesley G. et Guti\u00e9rrez, Joan Arlene",
"Famille de Mendoza, James et Allen, Abigail",
"Family of Meyer, P.D.",
"Famille de Michaud, Valentin et Beaulieu, Anna Eva",
"Family of Molina, Robert",
"Famille de Moore, George et \u0411\u044b\u043a\u043e\u0432, Margaret",
"Famille de Moran, Andrew et Sharp, ???",
"Family of Moran, Andrew",
"Famille de Moreno, Aaron et \u0417\u043b\u043e\u0431\u0438\u043d, Martha",
"Famille de Moreno, Christian et Price, Mary",
"Famille de Moreno, Christian, I et Mann, Agnes",
"Famille de Moreno, Darius et Craig, Mary J.",
"Famille de Moreno, Esau et Caron, Mary E.",
"Family of Moreno, Herman",
"Famille de Moreno, Johann Christian II et \u041c\u0430\u0442\u0432\u0435\u0435\u0432, Elizabeth",
"Family of Moreno, Johann Henrich",
"Famille de Moreno, Maj. Christopher et Bass, Mary",
"Famille de Moreno, Solon et Perkins, Lydia",
"Famille de Moreno, Thomas H. et D\u0105browski, Letitia C.",
"Famille de Morin et Page, Belle",
"Famille de Morris, Adam et Oliver, Elizabeth",
"Famille de Morris, Cyrus et Graves, Martha",
"Famille de Mortensen, Daniel et Warner, Sarah Jane",
"Famille de Moss, Christy et Page, Matilda",
"Famille de Mullins, Robert? et Houston, Ellender",
"Famille de Munoz, Shadrach M. et Mar\u00edn, Nancy H.",
"Family of Murray, Nicholas",
"Famille de Myers, James et Boucher, Catherine",
"Famille de Neal, James et Page, Elizabeth",
"Famille de Neal, John et Schneider, Belle Irene",
"Famille de Nguyen, John Harry et Walker, Sharon Lynette",
"Famille de Norris, John et Howell, Mary (Sarah)",
"Famille de Norris, John et \u041d\u043e\u0432\u0438\u043a\u043e\u0432, Sarah",
"Family of Norris, William",
"Famille de Nowak, John H. et Page, Eleanor Maude",
"Family of Oliver, Hans Michael",
"Famille de Oliver, Harmonas I et Malone, Mary",
"Famille de Oliver, Harmonas II et Harvey, Lydia",
"Famille de Olson, ??????? et Mar\u00edn, Alice",
"Famille de Ortiz, Don et Welch, Shirley",
"Famille de Ortiz, Raymond et Page, Ferne",
"Famille de Osborne, Dwight Billington et Lessard, Mary Alice",
"Famille de Osborne, Paul Daniel et Hawkins, Jennifer Leigh",
"Famille de Owens, Wilford et Jankowski, Matilda",
"Famille de Padilla, Otis Earl et Page, Eleanor Irene",
"Famille de Page, Andrew Vincent et Zimmerman, Edith Irene",
"Famille de Page, David et Douglas, Elizabeth",
"Famille de Page, Dwayne Alan et Scott, Cheryl Lee",
"Famille de Page, John et Kaczmarek, Isabella",
"Famille de Page, John James et Adkins, Minnie",
"Famille de Page, John James et Mcdaniel, Margaret",
"Famille de Page, Kenneth Fritz et Pittman, June Christine",
"Famille de Page, Marvin Ray et Morton, Gail Darlene",
"Famille de Page, Mr. et James, Martha",
"Famille de Page, Richard C. et Rodriguez, Helen M.",
"Famille de Page, Robert et Neal, Belle",
"Famille de Page, Vernett Gail et Norman, Dorothy Louise",
"Famille de Palmer, Robert et \u041f\u043e\u043f\u043e\u0432, ???????",
"Famille de Parent, Capt.Jacob C. et James, Jane",
"Family of Parent, John Sr.",
"Famille de Parent, Montgomery et Alvarado, Patsy",
"Family of Park, James",
"Famille de Parker, Frank R. et Garner, Anetta",
"Famille de Parks, Cliff et Gill, Lorie Ann",
"Famille de Parsons, Henry et Douglas, Ellen",
"Famille de Patrick, Melvin et Todd, Lucille",
"Famille de Patterson, George et Farmer, Elizabeth",
"Famille de Patton, Adolph et Moreno, Lelia L.",
"Famille de Payne, Alexander et Kami\u0144ski, Elizabeth",
"Famille de Payne, Alexander et Salazar, Catherine",
"Famille de Payne, Fielding et Lawrence, Dorcas C.",
"Famille de Payne, George et Diaz, Frances",
"Famille de Payne, Leonard et Hall, Elizabeth",
"Famille de Payne, Leonard? et Brooks, Elizabeth\"Betty\"",
"Famille de Pedersen, William et Benson, Elizabeth",
"Famille de Pelletier, Esiquio et Leclerc, Sesaria",
"Famille de Perry, M. et Reeves, Elizabeth",
"Famille de Person, The First et Fillin, B",
"Famille de Peters, Frank O. et Cross, Alta M.",
"Famille de Peters, George Sr. et Ramsey, Joan",
"Family of Peters, John",
"Famille de Peters, John C. et Cruz, Joyce Marie",
"Famille de Petersen, William et \u0414\u043c\u0438\u0442\u0440\u0438\u0435\u0432, Margaret Jane",
"Famille de Piotrowski, John et Todd, Olive",
"Family of Piotrowski, Sir John",
"Famille de Poirier, James A. et Walker, Sharon Lynette",
"Famille de Poole, Dr. John et James, Jane",
"Famille de Pope, John et Kristensen, Mary Elizabeth",
"Famille de Porter, David et Moreno, Mary H.",
"Famille de Poulin et Reed, Rose",
"Famille de Poulsen, Randall Lee et Welch, Lisa Dawn",
"Famille de Quinn, Abraham et Blanco, Malvina",
"Famille de Ram\u00edrez, John B. et Garner, Rebecca Catharine",
"Family of Ramos, John",
"Famille de Reed, Edward et Reed, Ellen",
"Family of Reed, Edward",
"Famille de Reed, Francis Vincent et \u041a\u0430\u0437\u0430\u043d\u0446\u0435\u0432, Katherine",
"Famille de Reed, Francis Vincent et \u0422\u0438\u0445\u043e\u043d\u043e\u0432, Catherine Virginia",
"Famille de Reed, John et Bernier, Margaret",
"Famille de Reed, John et Goodwin, Sarah",
"Famille de Reed, Matthew et Gibbs, Mary",
"Famille de Reed, Michael et Gibbs, Mary",
"Famille de Reed, Michael et Goodwin, Alice",
"Family of Reed, Owen",
"Famille de Reed, Patrick et Gibbs, Elizabeth",
"Famille de Reed, Peter et \u041a\u0443\u0437\u043d\u0435\u0446\u043e\u0432, Hanora",
"Famille de Reed, Peter James? et Reed, Catherine",
"Famille de Reed, Terrence et Gibbs, Maria",
"Famille de Reed, Terrence (TyNed) et Gibbs, Jennie",
"Family of Reed, Thomas",
"Famille de Reeves, James et Meyer, Catherine",
"Famille de Reeves, John et Flowers, Mary A.",
"Famille de Reeves, John et McCarthy, Mary",
"Famille de Reid, Hans et \u0421\u0435\u043c\u0435\u043d\u043e\u0432, Cathern",
"Famille de Reyes et Armstrong, Sarah",
"Famille de Reynolds, Col. John et Mazur, Elizabeth",
"Famille de Reynolds, David et Vaughn, Mary Meriwether",
"Famille de Reynolds, John et Newman, Margaret",
"Famille de Reynolds, John et Stevens, Elizabeth",
"Famille de Reynolds, John et \u041a\u043e\u0432\u0430\u043b\u0435\u0432, Sarah",
"Famille de Reynolds, Nicholas et Murray, Susannah",
"Family of Reynolds, William",
"Famille de Rhodes, William Sr. et Kristensen, Anna June",
"Famille de Riley, Thomas et Edwards, Lucy",
"Famille de Robinson, Clarence et Garner, Bertha P.",
"Famille de Rodgers, John et Garrett, Doris Mae",
"Family of Rodriquez",
"Famille de Rodriquez, John et \u041f\u043e\u043b\u044f\u043a\u043e\u0432, Eve",
"Famille de Rodriquez, Mordica et \u0412\u043e\u0440\u043e\u043d\u043e\u0432, Katherine",
"Famille de Rodriquez, Mordica et \u041a\u0430\u0437\u0430\u043a\u043e\u0432, Jane",
"Famille de Rodriquez, Richard et \u0416\u0443\u043a\u043e\u0432, Hannah",
"Famille de Rodriquez, William M. et Douglas, Mary\"Polly\"",
"Famille de Romero, Ernest et Jankowski, Minnie",
"Famille de Roy, Prince Alfred et Mar\u00edn, Frances Coppage",
"Family of Rubio, John III",
"Famille de Russell, Bruce Lynn et Henderson, Cathy Sue",
"Famille de Russell, Melvin Glen et Manning, Judith Ann",
"Famille de Russell, Norman et Lessard, Helen Belle",
"Famille de S\u00e1nchez, David Andrew et Welch, Rosalie Jane",
"Famille de Sanchez, John et Curtis, Margaret",
"Famille de Sanders, Henry et Rose, Ann",
"Family of Sandoval, John Joe",
"Famille de Sandoval, Johnnie et Reed, Minnie",
"Famille de Santiago, Mathias et James, Molly",
"Famille de Sanz, John et Jankowski, Sarah",
"Famille de Savard, Walter et Russell, Janet Gail",
"Famille de Schneider et Neal, Margaret",
"Famille de Schultz, John et Payne, Jane Coppage",
"Famille de Schultz, Rev.Isaac et Turner, Mary",
"Family of Serrano, Abraham",
"Famille de Serrano, Archibald et Delgado, Catherine",
"Famille de Serrano, Joseph et Quinn, Elizabeth Marium",
"Family of Serrano, Joseph",
"Famille de Shelton, Peter et Farmer, Caroline",
"Family of Simard, Thomas",
"Famille de St-Pierre, Joe et Boucher, Norene",
"Famille de Steele, Valentine et Beaulieu, Anna Elisabeth",
"Famille de Stephens, Adam et Blanco, Anna Maria",
"Famille de Stewart et Hawkins, Janelle",
"Famille de Stokes, Gabriel et McCoy, Celine Bridget",
"Famille de Stone, Alfred Wayne et Guti\u00e9rrez, Virginia Elizabeth",
"Famille de Strickland, Col. Robert et James, Patsy",
"Famille de Swanson, Richard et Fernandez El Fern\u00e1ndez, Avis III",
"Famille de Swanson, William et Jensen, Elizabeth",
"Family of Swanson, William",
"Famille de Taylor, Jacob et Farmer, Susanna",
"Famille de Taylor, Philip et \u0411\u044b\u043a\u043e\u0432, Harriet",
"Famille de Terry, J. et Reeves, Bridget",
"Famille de Thomas, Elder Thomas et Barrett, Anne",
"Famille de Thomsen, new et Farmer, Elizabeth",
"Famille de Thornton, Arthur Otto et Mar\u00edn, Lilla Estella",
"Famille de Thornton, James Arthur et Lachance, Helen",
"Famille de Thornton, Phillip James et \u0411\u0435\u043b\u043e\u0432, Katherine",
"Famille de Thornton, Romaine et Soto, Harriet",
"Famille de Todd, Charles et Cole, Eurydice",
"Famille de Todd, George W. et Morris, Jane",
"Famille de Todd, Hodges et Piotrowski, Lucy",
"Famille de Todd, John et Warner, Elizabeth",
"Famille de Todd, John et \u041b\u0430\u043b\u0435\u0442\u0438\u043d, Elizabeth",
"Famille de Todd, John M. et Farmer, Elizabeth Ellen",
"Famille de Todd, William et \u6e21\u8fba, Mary (Polly)",
"Famille de Torres et Hawkins, Gail",
"Famille de Townsend, Mark et \u041c\u0430\u043a\u0441\u0438\u043c\u043e\u0432, Heather Michelle",
"Famille de Valdez et Reed, Noreen",
"Famille de Walker, Andrew Vincent et Pearson, Eileen Ruth",
"Famille de Wallace, Abraham et Greene, Marcy",
"Family of Walters, Daniel",
"Famille de Ward, David J. et Warner, Margaret Ruth",
"Famille de Warner, Allen Carl et Garner, Rita Marie",
"Famille de Warner, Andrew et Maldonado, Eunice",
"Famille de Warner, Arthur Maurice et Phillips, Anita Irene",
"Famille de Warner, Capt. Andrew et Christiansen, Hannah",
"Famille de Warner, Capt. Francis et Ingram, Mary",
"Famille de Warner, Capt. George et Alvarez, Mary",
"Famille de Warner, Daniel et Higgins, Charity",
"Famille de Warner, David Luther et Robbins, Merida Lorene",
"Famille de Warner, David Warren et Simpson, Geraldine Ann",
"Famille de Warner, Edward et Anderson, Mary Molly",
"Famille de Warner, Fred Loren et Flores, Jamie Lee",
"Famille de Warner, George et Nichols, Elizabeth",
"Famille de Warner, George Edward et Lessard, Elinor Jane",
"Famille de Warner, Harold Lowell et Powers, Nancy Lou",
"Family of Warner, John",
"Famille de Warner, John William et Miles, Rebecca J.",
"Famille de Warner, Johnathon et Montgomery, Mary",
"Famille de Warner, Martin Bogarte et Klein, Alma Katherine",
"Famille de Warner, Martin Bogarte et Page, Clara Belle",
"Famille de Warner, Michael Louis et Warren, Pansy L.",
"Famille de Warner, Michael Warren et \u0427\u0435\u0440\u043d\u044b\u0445, Mary Helen",
"Famille de Warner, Noah et Burns, Margaret",
"Famille de Warner, Piatt D. et Fox, Julia Colville",
"Family of Warner, Rev. Edmund",
"Famille de Warner, Richard Kenneth et Wade, Joy A.",
"Famille de Warner, Richard Kenneth et \u041c\u0435\u043b\u044c\u043d\u0438\u043a\u043e\u0432, Marylou",
"Family of Warner, Robert",
"Famille de Warner, Robert Douglas et Norton, Christina",
"Famille de Warner, Robert Eugene et Barber, Mary Elizabeth",
"Famille de Warner, Stephen Paul et \u0425\u0443\u0434\u043e\u043d\u043e\u0433\u043e\u0432, Patricia",
"Famille de Warner, Stuart Bogarte et Richards, Diana",
"Famille de Warner, Thomas et Black, Jane",
"Famille de Warner, Thomas Frederick et Carter, Debra J.",
"Famille de Warner, Warren W. et Ball, Abigail",
"Famille de Waters et Webb, Mary",
"Famille de Waters, Cecil et \u0424\u043e\u043c\u0438\u043d, Grace",
"Famille de Waters, Cecil Glenn et Hubbard, Donna",
"Famille de Waters, John et Webb, Mary",
"Famille de Waters, William et Neal, Matilda",
"Famille de Watkins, Bruce Edward et Warner, Mary Christine",
"Famille de Watson, Alvin E. et Warner, Beverly Ann",
"Famille de Weaver, Steven Matthew et Warner, JenniferMae(Ganoe)",
"Famille de Webb, Alex et \u041c\u0430\u043a\u0430\u0440\u043e\u0432, Nancy",
"Famille de Webb, Alexander et Delgado, Mary Ann",
"Famille de Webb, Andrew et Webb, Margaret Margarite?",
"Famille de Webb, Elias et Gibbs, Nancy",
"Family of Webb, Ernest Arlington",
"Famille de Webb, Francis Irvin et Todd, Louella Jane",
"Famille de Webb, James Marshall et Ballard, Judith Ellen",
"Famille de Webb, John Raymond et Ford, Lorinda Catherine",
"Famille de Webb, Joseph LeRoy et Boucher, Bridget",
"Famille de Webb, Lewis I. et \u0417\u0430\u0439\u0446\u0435\u0432, Ruth L.",
"Famille de Webb, Livingstone Martin et Blanco, Lucinda Catherine",
"Family of Webb, William Herman",
"Famille de Webb, William John et Wagner, Martha Ann",
"Famille de Webster, Conrad et Castillo, Margaretha",
"Famille de Webster, Johanne(John) et Saunders, Ursula",
"Famille de Welch, Christopher Paul et Hayes, LeAnn",
"Famille de Welch, Irwin Arthur et Page, Eleanor Irene",
"Famille de Welch, Michael et Osborne, Anita June",
"Famille de Welch, Paul Allen et Cruz, Linda Helen",
"Famille de Welch, Russell Eugene et Norton, Dorothy",
"Famille de Welch, Russell Eugene et Walsh, Penelope",
"Famille de West, Ronald David et Cruz, Melinda Lou",
"Famille de Wheeler, Don et \u041b\u043e\u043f\u0430\u0442\u0438\u043d, Carmen Diana",
"Famille de Wheeler, Jacob Earl et \u041b\u043e\u043f\u0430\u0442\u0438\u043d, Carmen Diana",
"Famille de White et Reed, Mary Ann",
"Famille de Williams, Thomas Jr. et Jim\u00e9nez, Elizabeth",
"Famille de Willis, Corey et Poirier, Janelle Marie",
"Famille de Wilson, Douglas et Cruz, Marsha Ann",
"Famille de Wise, Thomas et Ramos, Mary",
"Famille de W\u00f3jcik, Arnold et Garner, Helen Bernice",
"Famille de Wong et Page, Mildred",
"Famille de Wood, Peter et Gibbs, Lucy",
"Famille de Woods, James et \u0417\u044b\u0440\u044f\u043d\u043e\u0432, Mary",
"Famille de Wo\u017aniak, Thomas et Page, Debra Dale",
"Famille de Young, Mr. et Waters, Edith",
"Famille de \u0394\u03b5\u03bb\u03b7\u03c0\u03ad\u03c4\u03c1\u03bf\u03c5, \u0391\u03b3\u03b1\u03bc\u03ad\u03bc\u03bd\u03c9\u03bd et \u0399\u03c9\u03ac\u03bd\u03bd\u03bf\u03c5, \u0395\u03c5\u03c4\u03ad\u03c1\u03c0\u03b7",
"Famille de \u0394\u03b5\u03bb\u03b7\u03c0\u03ad\u03c4\u03c1\u03bf\u03c5, \u0399\u03ac\u03c3\u03c9\u03bd et \u0391\u03bd\u03b1\u03b3\u03bd\u03c9\u03c3\u03c4\u03bf\u03c0\u03bf\u03cd\u03bb\u03bf\u03c5, \u0392\u03b5\u03bd\u03b5\u03c4\u03af\u03b1",
"Famille de \u0399\u03c9\u03ac\u03bd\u03bd\u03bf\u03c5, \u0395\u03c0\u03b1\u03bc\u03b5\u03b9\u03bd\u03ce\u03bd\u03b4\u03b1\u03c2 et \u039a\u03b1\u03bb\u03ad\u03c1\u03b3\u03b7, \u0399\u03bf\u03c5\u03bb\u03af\u03b1",
"Famille de \u0410\u043b\u0435\u043a\u0441\u0430\u043d\u0434\u0440\u043e\u0432, Johann Adam et Beaulieu, Anna Margaretha",
"Famille de \u0410\u043b\u0435\u043a\u0441\u0435\u0435\u0432, Jacob et Benson, Mary",
"Famille de \u0410\u043d\u0434\u0440\u0435\u0435\u0432, William et Douglas, Susan",
"Famille de \u0411\u0435\u043b\u043e\u0443\u0441\u043e\u0432, Jacob et Su\u00e1rez, Marie",
"Famille de \u0411\u0435\u043b\u043e\u0443\u0441\u043e\u0432, Johannas Jacob et Reid, Anna Catherina",
"Famille de \u0411\u0435\u043b\u044f\u0435\u0432 et Reed, Peggy",
"Famille de \u0411\u043e\u0433\u0434\u0430\u043d\u043e\u0432, Dr. Brent et Cruz, Ann Lynn",
"Famille de \u0411\u043e\u0440\u0438\u0441\u043e\u0432 et Boyd, Carmen Alberta",
"Famille de \u0411\u044b\u043a\u043e\u0432, Charles et Girard, Margaret",
"Famille de \u0411\u044b\u043a\u043e\u0432, Herod et Parent, Polly",
"Famille de \u0411\u044b\u043a\u043e\u0432, Samuel et Larsen, Nelly",
"Famille de \u0412\u043b\u0430\u0441\u043e\u0432, John et Floyd, Martha Frances \"Fannie\"",
"Family of \u0412\u043e\u0440\u043e\u0431\u044c\u0435\u0432, Rev. Samuel",
"Famille de \u0413\u0435\u0440\u0430\u0441\u0438\u043c\u043e\u0432, John et Garrett, Doris Mae",
"Family of \u0413\u043e\u043d\u0447\u0430\u0440\u043e\u0432, Thomas",
"Famille de \u0413\u043e\u0440\u0431\u0443\u043d\u043e\u0432, Matt et Garner, Cecilia",
"Famille de \u0414\u0430\u0432\u044b\u0434\u043e\u0432 et Ball, Jane",
"Famille de \u0414\u0430\u043d\u0438\u043b\u043e\u0432, Darrell Edwin et Ross, Evelyn Almazon",
"Famille de \u0414\u0430\u043d\u0438\u043b\u043e\u0432, Earl William et Lessard, Dorothy Louise",
"Famille de \u0414\u043c\u0438\u0442\u0440\u0438\u0435\u0432, Alexander Carroll Sr. et Woods, Mary Polly",
"Famille de \u0414\u043c\u0438\u0442\u0440\u0438\u0435\u0432, Charles Sr. et Lapointe, Lucy aka Sarah",
"Famille de \u0414\u043c\u0438\u0442\u0440\u0438\u0435\u0432, Moses Aaron et Reynolds, Mary Jane",
"Famille de \u0414\u043c\u0438\u0442\u0440\u0438\u0435\u0432, Travis et Payne, Elizabeth",
"Famille de \u0414\u043c\u0438\u0442\u0440\u0438\u0435\u0432, William et Page, Sarah",
"Famille de \u0414\u043c\u0438\u0442\u0440\u0438\u0435\u0432, William et Wood, Polly",
"Famille de \u0415\u0433\u043e\u0440\u043e\u0432, Dr. Charles J. et Page, Edith Mae",
"Famille de \u0416\u0443\u043a\u043e\u0432, Curtis Dale et Gordon, Heather Kathleen",
"Famille de \u0416\u0443\u043a\u043e\u0432, David et Russell, Janet Gail",
"Famille de \u0417\u043b\u043e\u0431\u0438\u043d, Col. Joseph et Rice, Virginia Margaret",
"Family of \u0417\u043b\u043e\u0431\u0438\u043d, John",
"Famille de \u0417\u043b\u043e\u0431\u0438\u043d, Joseph Jr. et Adkins, Martha",
"Famille de \u0417\u044b\u043a\u043e\u0432, John et Hopkins, Mary Eve",
"Famille de \u0418\u043b\u044c\u0438\u043d, Gary et Webb, Marilyn Jean",
"Famille de \u041a\u0430\u0440\u043f\u043e\u0432, Damian et Hansen, Irene",
"Famille de \u041a\u0438\u0441\u0435\u043b\u0435\u0432, Dennis John et Warner, Nancy Elizabeth",
"Famille de \u041a\u043e\u0437\u043b\u043e\u0432, Samuel C. et Pena, Julia",
"Famille de \u041b\u0435\u0431\u0435\u0434\u0435\u0432, Trustum et Warner, Johanna",
"Famille de \u041b\u043e\u0433\u0438\u043d\u043e\u0432, Guy et Kristensen, Margaret Agnes\"Maudy\"",
"Famille de \u041b\u043e\u043f\u0430\u0442\u0438\u043d, Raymond A. et Garrett, Carmen Eloise",
"Family of \u041c\u0430\u043a\u0430\u0440\u043e\u0432, Joseph",
"Famille de \u041c\u0430\u043a\u0441\u0438\u043c\u043e\u0432 et Allen, Abigail",
"Famille de \u041c\u0430\u043a\u0441\u0438\u043c\u043e\u0432, George et \u0416\u0443\u043a\u043e\u0432, Annabell Gordon",
"Famille de \u041c\u0430\u043a\u0441\u0438\u043c\u043e\u0432, Rodney Herman et Cruz, Janis Marlene",
"Famille de \u041c\u0430\u0440\u0442\u044b\u043d\u043e\u0432 et Reed, Jane",
"Family of \u041d\u0438\u043a\u043e\u043b\u0430\u0435\u0432, Veltin",
"Famille de \u041d\u043e\u0432\u0438\u043a\u043e\u0432, Thomas et Allen, Rachel",
"Famille de \u041f\u0430\u0432\u043b\u043e\u0432, Reuben et Douglas, Lucinda J.",
"Famille de \u041f\u043e\u043d\u043e\u043c\u0430\u0440\u0435\u0432, Ralph et Rodr\u00edguez, Agatha",
"Famille de \u041f\u043e\u0442\u044b\u043b\u0438\u0446\u0438\u043d, Edward et B\u00e9langer, Linda Ellen",
"Famille de \u0420\u043e\u043c\u0430\u043d\u043e\u0432, John et Moreno, Delilah",
"Famille de \u0421\u0435\u0440\u0433\u0435\u0435\u0432, Dennis et Garner, Kathryn Mary",
"Famille de \u0421\u043c\u0438\u0440\u043d\u043e\u0432, Eudo et Rios, Agnes",
"Famille de \u0421\u043c\u0438\u0440\u043d\u043e\u0432, Ribald et Gray, Beatrix",
"Famille de \u0421\u043e\u0440\u043e\u043a\u0438\u043d, Robert et \u0421\u043e\u0440\u043e\u043a\u0438\u043d, Candy",
"Famille de \u0422\u0430\u0440\u0430\u0441\u043e\u0432, Simon et Todd, Flora Belle",
"Famille de \u0422\u0438\u0445\u043e\u043d\u043e\u0432, Miles? et Smith, Anastasia?",
"Famille de \u0422\u0438\u0445\u043e\u043d\u043e\u0432, Moses et Holt, Bridget",
"Famille de \u0424\u0435\u0434\u043e\u0440\u043e\u0432 et Reed, Bridget",
"Family of \u0424\u0435\u0434\u043e\u0440\u043e\u0432, Patrick",
"Famille de \u0427\u0435\u0440\u043a\u0430\u0448\u0438\u043d, Thomas et Jankowski, Margaret Jane \"Maggie\"",
"Famille de \u0428\u0435\u0441\u0442\u0430\u043a\u043e\u0432, George et Daniels, Phoebe",
"Famille de \u042f\u043a\u043e\u0432\u043b\u0435\u0432, George et Garner, Jennie S.",
"Famille de \u4e2d\u6751, Thomas et Jim\u00e9nez, Polly Mary",
"Famille de \u5c0f\u6797, Mr. et Waters, Nellie",
"Famille de \u5c71\u672c, Antoine Desaure Perronett et \u0421\u043e\u043a\u043e\u043b\u043e\u0432, Louise",
"Family of \u5c71\u672c, Gabriel Gustave",
"Famille de \u658e\u85e4, Zariakius Cyriacus et Bishop, Anna Barbara",
"Famille de \u9234\u6728, Allen et Mar\u00edn, Alice",
"Famille de \u9234\u6728, Robert B. et Blanco, Mary F."
]
Dwr.ScriptLoaded('dwr_db_F_name_0.js');
