// This file is generated

S_attr_0 = [
[],
[
{
"cita": [],
"note": "",
"type": "Creation date",
"value": "24 APR 1999"
},
{
"cita": [],
"note": "",
"type": "Generated by",
"value": "ROOTSV 5.01"
}
],
[
{
"cita": [],
"note": "",
"type": "Book Cover Type",
"value": "Paperback"
}
],
[]
]
Dwr.ScriptLoaded('dwr_db_S_attr_0.js');
