// This file is generated

_place_name_0 = [
    "Aberdeen, SD, USA",
    "Aberdeen, WA, USA",
    "Acadia, LA, USA",
    "Ada, OK, USA",
    "Adams, IL-MO, USA",
    "Adams, IN, USA",
    "Adjuntas, PR, USA",
    "Adrian, MI, USA",
    "Aguadilla, PR, USA",
    "AK, USA",
    "Akron, OH, USA",
    "AL, USA",
    "Alachua, FL, USA",
    "Alameda, CA, USA",
    "Alamogordo, NM, USA",
    "Albany, Albany, NY, USA",
    "Albany, Dougherty, GA, USA",
    "Albany, NY, USA",
    "Albany, OR, USA",
    "Albert Lea, MN, USA",
    "Albertville, Marshall, AL, USA",
    "Albuquerque, NM, USA",
    "Alexandria, MD, USA",
    "Alexandria, MN, USA",
    "Alexandria, Rapides, LA, USA",
    "Alice, Jim Wells, TX, USA",
    "Allegan, MI, USA",
    "Allen, IN, USA",
    "Allentown, PA, USA",
    "Alma, MI, USA",
    "Alpena, MI, USA",
    "Altoona, PA, USA",
    "Altus, OK, USA",
    "Amarillo, Potter, TX, USA",
    "Americus, Sumter, GA, USA",
    "Ames, Story, IA, USA",
    "Amsterdam, Montgomery, NY, USA",
    "Anchorage, AK, USA",
    "Anderson, Madison, IN, USA",
    "Anderson, SC, USA",
    "Andrews, Andrews, TX, USA",
    "Andrews, TX, USA",
    "Angelina, TX, USA",
    "Angola, Steuben, IN, USA",
    "Ann Arbor, MI, USA",
    "Anniston, Calhoun, AL, USA",
    "AR-OK, USA",
    "AR, USA",
    "Arcadia, DeSoto, FL, USA",
    "Ardmore, OK, USA",
    "Arkadelphia, Clark, AR, USA",
    "Arlington, VA, USA",
    "Asheville, NC, USA",
    "Ashland, OH, USA",
    "Ashtabula, OH, USA",
    "Astoria, OR, USA",
    "Atchison, Atchison, KS, USA",
    "Atchison, KS, USA",
    "Athens, Clarke, GA, USA",
    "Athens, Henderson, TX, USA",
    "Athens, OH, USA",
    "Atlanta, Fulton, GA, USA",
    "Auburn, Cayuga, NY, USA",
    "Auburn, Lee, AL, USA",
    "Augusta, ME, USA",
    "Austin, MN, USA",
    "AZ, USA",
    "Bainbridge, Decatur, GA, USA",
    "Baldwin, AL, USA",
    "Baldwin, GA, USA",
    "Baltimore, MD, USA",
    "Bangor, ME, USA",
    "Bannock, ID, USA",
    "Baraboo, WI, USA",
    "Barnstable Town, MA, USA",
    "Barren, KY, USA",
    "Bartholomew, IN, USA",
    "Bartlesville, OK, USA",
    "Batavia, Genesee, NY, USA",
    "Batesville, Independence, AR, USA",
    "Baton Rouge, East Baton Rouge, LA, USA",
    "Battle Creek, MI, USA",
    "Bay City, Matagorda, TX, USA",
    "Bay City, MI, USA",
    "Bay, FL, USA",
    "Beaumont, Jefferson, TX, USA",
    "Beaver Dam, WI, USA",
    "Beckley, WV, USA",
    "Bedford, Lawrence, IN, USA",
    "Bee, TX, USA",
    "Beeville, Bee, TX, USA",
    "Bell, TX, USA",
    "Bellingham, WA, USA",
    "Bemidji, MN, USA",
    "Ben Hill, GA, USA",
    "Bennettsville, SC, USA",
    "Bennington, VT, USA",
    "Berkshire, MA, USA",
    "Berlin, NH, USA",
    "Bethesda, MD, USA",
    "Bexar, TX, USA",
    "Bibb, GA, USA",
    "Big Rapids, MI, USA",
    "Big Spring, Howard, TX, USA",
    "Billings, MT, USA",
    "Bingham, ID, USA",
    "Binghamton, Broome, NY, USA",
    "Birmingham, Jefferson, AL, USA",
    "Bishop, Inyo, CA, USA",
    "Bismarck, ND, USA",
    "Blackfoot, Bingham, ID, USA",
    "Blacksburg, VA, USA",
    "Bloomington, Monroe, IN, USA",
    "Bloomsburg, PA, USA",
    "Bluefield, WV-VA, USA",
    "Blytheville, Mississippi, AR, USA",
    "Bogalusa, Washington, LA, USA",
    "Boise City, ID, USA",
    "Bonneville, ID, USA",
    "Boone, AR, USA",
    "Boone, Boone, IA, USA",
    "Boone, IA, USA",
    "Boone, NC, USA",
    "Boston, Suffolk, MA, USA",
    "Boulder, Boulder, CO, USA",
    "Boulder, CO, USA",
    "Bowling Green, Warren, KY, USA",
    "Boyle, KY, USA",
    "Bozeman, MT, USA",
    "Brainerd, MN, USA",
    "Branson, MO, USA",
    "Brazos, TX, USA",
    "Bremerton, WA, USA",
    "Brenham, Washington, TX, USA",
    "Brevard, FL, USA",
    "Brevard, NC, USA",
    "Bridgeport, Fairfield, CT, USA",
    "Bridgeton, NJ, USA",
    "Brookhaven, MS, USA",
    "Brookings, OR, USA",
    "Broome, NY, USA",
    "Broward, FL, USA",
    "Brownsville, Cameron, TX, USA",
    "Brownsville, TN, USA",
    "Brownwood, Harris, TX, USA",
    "Bucyrus, OH, USA",
    "Buena Vista, IA, USA",
    "Buffalo, Erie, NY, USA",
    "Bulloch, GA, USA",
    "Burley, Cassia, ID, USA",
    "Burlington, Des Moines, IA, USA",
    "Burlington, NC, USA",
    "Burlington, VT, USA",
    "Butte, CA, USA",
    "Butte, MT, USA",
    "CA, USA",
    "Cabo Rojo, PR, USA",
    "Caddo, LA, USA",
    "Cadillac, MI, USA",
    "Caguas, PR, USA",
    "Calcasieu, LA, USA",
    "Calhoun, AL, USA",
    "Cambridge, MD, USA",
    "Cambridge, Middlesex, MA, USA",
    "Cambridge, OH, USA",
    "Camden, NJ, USA",
    "Camden, Ouachita, AR, USA",
    "Cameron, TX, USA",
    "Campbellsville, Taylor, KY, USA",
    "Canon City, CO, USA",
    "Canton, Fulton, IL, USA",
    "Canton, OH, USA",
    "Cape Coral-Fort Myers, FL, USA",
    "Cape Girardeau, MO, USA",
    "Carbondale, Jackson, IL, USA",
    "Carlsbad, NM, USA",
    "Carson City, NV, USA",
    "Casper, WY, USA",
    "Cassia, ID, USA",
    "Cattaraugus, NY, USA",
    "Cayuga, NY, USA",
    "Cedar City, UT, USA",
    "Cedartown, Polk, GA, USA",
    "Celina, OH, USA",
    "Central City, Muhlenberg, KY, USA",
    "Centralia, Marion, IL, USA",
    "Centralia, WA, USA",
    "Chambers, AL, USA",
    "Champaign, Champaign, IL, USA",
    "Champaign, IL, USA",
    "Charleston, SC, USA",
    "Charleston, WV, USA",
    "Charlotte, FL, USA",
    "Charlotte, NC, USA",
    "Chatham, GA, USA",
    "Chattanooga, TN-GA, USA",
    "Chattooga, GA, USA",
    "Chemung, NY, USA",
    "Cherokee, TX, USA",
    "Chester, SC, USA",
    "Cheyenne, WY, USA",
    "Chicago, Cook, IL, USA",
    "Chico, Butte, CA, USA",
    "Chillicothe, OH, USA",
    "Christian, IL, USA",
    "Cincinnati, OH, USA",
    "Citrus, FL, USA",
    "City of The Dalles, OR, USA",
    "Clark, AR, USA",
    "Clarke, GA, USA",
    "Clarksburg, WV, USA",
    "Clarksdale, MS, USA",
    "Clay, IA, USA",
    "Clearlake, Lake, CA, USA",
    "Clearwater, Pinellas, FL, USA",
    "Cleveland, MS, USA",
    "Cleveland, OH, USA",
    "Cleveland, TN, USA",
    "Clinton, Clinton, IA, USA",
    "Clinton, IA, USA",
    "Clinton, IN, USA",
    "Clinton, NY, USA",
    "Clovis, NM, USA",
    "CO, USA",
    "Coamo, PR, USA",
    "Cochise, AZ, USA",
    "Coconino, AZ, USA",
    "Coeur d'Alene, Kootenai, ID, USA",
    "Coffee, AL, USA",
    "Coffee, GA, USA",
    "Coffeyville, Montgomery, KS, USA",
    "Coldwater, MI, USA",
    "College Station, Brazos, TX, USA",
    "Collier, FL, USA",
    "Colorado Springs, El Paso, CO, USA",
    "Colquitt, GA, USA",
    "Columbia, AR, USA",
    "Columbia, FL, USA",
    "Columbia, MO, USA",
    "Columbia, NY, USA",
    "Columbia, SC, USA",
    "Columbia, TN, USA",
    "Columbus, Bartholomew, IN, USA",
    "Columbus, Jefferson, GA-AL, USA",
    "Columbus, MS, USA",
    "Columbus, NE, USA",
    "Columbus, OH, USA",
    "Concord, NH, USA",
    "Connersville, Fayette, IN, USA",
    "Cook, IL, USA",
    "Cookeville, TN, USA",
    "Coos Bay, OR, USA",
    "Corbin, Whitley, KY, USA",
    "Cordele, Crisp, GA, USA",
    "Corinth, MS, USA",
    "Cornelia, Habersham, GA, USA",
    "Corning, Steuben, NY, USA",
    "Corpus Christi, Nueces, TX, USA",
    "Corsicana, Navarro, TX, USA",
    "Cortland, Cortland, NY, USA",
    "Cortland, NY, USA",
    "Corvallis, OR, USA",
    "Coshocton, OH, USA",
    "Cowley, KS, USA",
    "Craighead, AR, USA",
    "Crawford, KS, USA",
    "Crawfordsville, Montgomery, IN, USA",
    "Crescent City North, CA, USA",
    "Crisp, GA, USA",
    "Crossville, TN, USA",
    "Crowley, Acadia, LA, USA",
    "CT, USA",
    "Cullman, AL, USA",
    "Cullman, Cullman, AL, USA",
    "Dallas, AL, USA",
    "Dallas, Dallas, TX, USA",
    "Dallas, TX, USA",
    "Dalton, Madison, GA, USA",
    "Danville, Boyle, KY, USA",
    "Danville, VA, USA",
    "Danville, Vermilion, IL, USA",
    "Daphne, Baldwin, AL, USA",
    "Davenport, Scott, IA, USA",
    "Daviess, IN, USA",
    "Daviess, KY, USA",
    "Dawson, TX, USA",
    "Dayton, OH, USA",
    "DC, USA",
    "De Ridder, LA, USA",
    "DE-MD-NJ, USA",
    "DE, USA",
    "Deaf Smith, TX, USA",
    "Decatur, Adams, IN, USA",
    "Decatur, GA, USA",
    "Decatur, IN, USA",
    "Decatur, Macon, IL, USA",
    "Decatur, Morgan, AL, USA",
    "Defiance, OH, USA",
    "Del Rio, Val Verde, TX, USA",
    "Delaware, IN, USA",
    "Deltona, Volusia, FL, USA",
    "Deming, NM, USA",
    "Denver-Aurora, CO, USA",
    "Des Moines, IA, USA",
    "Des Moines, Polk, IA, USA",
    "DeSoto, FL, USA",
    "Detroit, MI, USA",
    "Dickinson, IA, USA",
    "Dickinson, ND, USA",
    "District of Columbia, DC, USA",
    "Dixon, Lee, IL, USA",
    "Dodge City, Ford, KS, USA",
    "Dothan, Houston, AL, USA",
    "Dougherty, GA, USA",
    "Douglas, Coffee, GA, USA",
    "Douglas, KS, USA",
    "Dover, Kent, DE, USA",
    "Dublin, Laurens, GA, USA",
    "Dubois, IN, USA",
    "DuBois, PA, USA",
    "Dubuque, Dubuque, IA, USA",
    "Dubuque, IA, USA",
    "Duluth, MN, USA",
    "Dumas, Moore, TX, USA",
    "Duncan, OK, USA",
    "Dunn, NC, USA",
    "Durango, La Plata, CO, USA",
    "Durant, OK, USA",
    "Durham, NC, USA",
    "Dutchess, NY, USA",
    "Duval, FL, USA",
    "Dyersburg, TN, USA",
    "Eagle Pass, Maverick, TX, USA",
    "Eagle, CO, USA",
    "East Baton Rouge, LA, USA",
    "East Liverpool, OH, USA",
    "East Stroudsburg, PA, USA",
    "Easton, MD, USA",
    "Eau Claire, WI, USA",
    "Edison, NJ, USA",
    "Edwards, Eagle, CO, USA",
    "Edwards, IL, USA",
    "Effingham, Effingham, IL, USA",
    "Effingham, IL, USA",
    "El Campo, Wharton, TX, USA",
    "El Centro, Imperial, CA, USA",
    "El Paso, CO, USA",
    "Elizabeth City, NC, USA",
    "Elkhart, Elkhart, IN, USA",
    "Elkhart, IN, USA",
    "Ellensburg, WA, USA",
    "Ellis, KS, USA",
    "Elmira, Chemung, NY, USA",
    "Elmore, ID, USA",
    "Emporia, Lyon, KS, USA",
    "Enid, OK, USA",
    "Enterprise, Coffee, AL, USA",
    "Erath, TX, USA",
    "Erie, NY, USA",
    "Erie, PA, USA",
    "Escambia, FL, USA",
    "Escanaba, MI, USA",
    "Etowah, AL, USA",
    "Eugene, OR, USA",
    "Eureka, Humboldt, CA, USA",
    "Evanston, WY, USA",
    "Evansville, Vanderburgh, IN, USA",
    "Fairbanks, AK, USA",
    "Fairfield, CT, USA",
    "Fairmont, MN, USA",
    "Fairmont, WV, USA",
    "Fajardo, PR, USA",
    "Fallon, NV, USA",
    "Fargo, ND, USA",
    "Faribault-Northfield, MN, USA",
    "Farmington, MO, USA",
    "Farmington, NM, USA",
    "Fayette, IN, USA",
    "Fayette, KY, USA",
    "Fayetteville, Washington, AR, USA",
    "Fergus Falls, MN, USA",
    "Findlay, OH, USA",
    "Finney, KS, USA",
    "Fitzgerald, Ben Hill, GA, USA",
    "FL, USA",
    "Flagler, FL, USA",
    "Flagstaff, Coconino, AZ, USA",
    "Flint, MI, USA",
    "Florence, Lauderdale, AL, USA",
    "Florence, SC, USA",
    "Floyd, GA, USA",
    "Fond du Lac, WI, USA",
    "Ford, KS, USA",
    "Forest City, NC, USA",
    "Forrest City, St. Francis, AR, USA",
    "Fort Collins, Larimer, CO, USA",
    "Fort Dodge, Webster, IA, USA",
    "Fort Lauderdale, Broward, FL, USA",
    "Fort Leonard Wood, MO, USA",
    "Fort Morgan, Morgan, CO, USA",
    "Fort Polk South, LA, USA",
    "Fort Smith, Sebastian, AR-OK, USA",
    "Fort Valley, Peach, GA, USA",
    "Fort Walton Beach, Okaloosa, FL, USA",
    "Fort Wayne, Allen, IN, USA",
    "Fort Worth, Tarrant, TX, USA",
    "Fostoria, OH, USA",
    "Frankfort, Clinton, IN, USA",
    "Frankfort, Franklin, KY, USA",
    "Franklin, KY, USA",
    "Franklin, NY, USA",
    "Frederick, MD, USA",
    "Fremont, NE, USA",
    "Fresno, CA, USA",
    "Fresno, Fresno, CA, USA",
    "Fulton, GA, USA",
    "Fulton, IL, USA",
    "Fulton, NY, USA",
    "GA-AL, USA",
    "GA, USA",
    "Gadsden, Etowah, AL, USA",
    "Gaffney, SC, USA",
    "Gainesville, Alachua, FL, USA",
    "Gainesville, Hall, GA, USA",
    "Gainesville, Llano, TX, USA",
    "Gaithersburg, MD, USA",
    "Gallup, NM, USA",
    "Garden City, Finney, KS, USA",
    "Gardnerville Ranchos, NV, USA",
    "Garland, AR, USA",
    "Gary, Lake, IN, USA",
    "Genesee, NY, USA",
    "George, UT, USA",
    "Georgetown, SC, USA",
    "Gettysburg, PA, USA",
    "Gila, AZ, USA",
    "Gillette, WY, USA",
    "Glasgow, Barren, KY, USA",
    "Glens Falls, Warren, NY, USA",
    "Gloversville, Fulton, NY, USA",
    "Goldsboro, NC, USA",
    "Graham, AZ, USA",
    "Granbury, Hood, TX, USA",
    "Grand Forks, ND, USA",
    "Grand Junction, Mesa, CO, USA",
    "Grand Rapids, MI, USA",
    "Grant, IN, USA",
    "Grants Pass, OR, USA",
    "Grants, NM, USA",
    "Graves, KY, USA",
    "Gray, TX, USA",
    "Great Falls, MT, USA",
    "Greeley, Weld, CO, USA",
    "Green Bay, WI, USA",
    "Greene, AR, USA",
    "Greeneville, TN, USA",
    "Greensboro, NC, USA",
    "Greensburg, Decatur, IN, USA",
    "Greenville, MS, USA",
    "Greenville, NC, USA",
    "Greenville, OH, USA",
    "Greenville, SC, USA",
    "Greenwood, MS, USA",
    "Greenwood, SC, USA",
    "Gregg, TX, USA",
    "Grenada, MS, USA",
    "Guayama, PR, USA",
    "Guaynabo, PR, USA",
    "Gulfport, MS, USA",
    "Guymon, OK, USA",
    "Habersham, GA, USA",
    "Hagerstown, MD, USA",
    "Hall, GA, USA",
    "Hammond, Tangipahoa, LA, USA",
    "Hampden, MA, USA",
    "Hanford-Corcoran, CA, USA",
    "Hannibal, MO, USA",
    "Hanover, PA, USA",
    "Hardee, FL, USA",
    "Harriman, TN, USA",
    "Harris, TX, USA",
    "Harrisburg, PA, USA",
    "Harrison, Boone, AR, USA",
    "Harrison, TX, USA",
    "Harrisonburg, VA, USA",
    "Hartford, CT, USA",
    "Hartford, Hartford, CT, USA",
    "Hastings, NE, USA",
    "Hattiesburg, MS, USA",
    "Havre, MT, USA",
    "Hays, Ellis, KS, USA",
    "Hayward, Alameda, CA, USA",
    "Helena, MT, USA",
    "Hempstead, AR, USA",
    "Henderson, NC, USA",
    "Henderson, TX, USA",
    "Henry, IN, USA",
    "Hereford, Deaf Smith, TX, USA",
    "HI, USA",
    "Hickory-Morganton-Lenoir, NC, USA",
    "Hidalgo, TX, USA",
    "Hillsborough, FL, USA",
    "Hilo, HI, USA",
    "Hilton Head Island-Beaufort, SC, USA",
    "Hinesville, Liberty, GA, USA",
    "Hobbs, NM, USA",
    "Hockley, TX, USA",
    "Holland-Grand Haven, MI, USA",
    "Homosassa Springs, Citrus, FL, USA",
    "Honolulu, HI, USA",
    "Hood River, OR, USA",
    "Hood, TX, USA",
    "Hope, Hempstead, AR, USA",
    "Hopkins, TX, USA",
    "Hot Springs, Garland, AR, USA",
    "Houma, Terrebonne, LA, USA",
    "Houston, AL, USA",
    "Houston, GA, USA",
    "Houston, Harris, TX, USA",
    "Houston, TX, USA",
    "Howard, IN, USA",
    "Howard, TX, USA",
    "Hudson, Columbia, NY, USA",
    "Humboldt, CA, USA",
    "Huntsville, Madison, AL, USA",
    "Huntsville, Walker, TX, USA",
    "Huron, SD, USA",
    "Hutchinson, MN, USA",
    "Hutchinson, Reno, KS, USA",
    "IA-NE-SD, USA",
    "IA, USA",
    "ID, USA",
    "Idaho Falls, Bonneville, ID, USA",
    "IL-MO, USA",
    "IL, USA",
    "Imperial, CA, USA",
    "IN, USA",
    "Independence, AR, USA",
    "Indian River, FL, USA",
    "Indiana, PA, USA",
    "Indianola, MS, USA",
    "Inyo, CA, USA",
    "Iowa City, Johnson, IA, USA",
    "Iron Mountain, MI, USA",
    "Isabela, PR, USA",
    "Jackson, IL, USA",
    "Jackson, IN, USA",
    "Jackson, MI, USA",
    "Jackson, TN, USA",
    "Jackson, WY, USA",
    "Jacksonville, Cherokee, TX, USA",
    "Jacksonville, Duval, FL, USA",
    "Jacksonville, NC, USA",
    "Jamestown, ND, USA",
    "Jamestowna, NY, USA",
    "Janesville, WI, USA",
    "Jasper, Dubois, IN, USA",
    "Jasper, IA, USA",
    "Jefferson City, MO, USA",
    "Jefferson Davis, LA, USA",
    "Jefferson, AL, USA",
    "Jefferson, GA-AL, USA",
    "Jefferson, IN, USA",
    "Jefferson, KY, USA",
    "Jefferson, TX, USA",
    "Jennings, IN, USA",
    "Jennings, Jefferson Davis, LA, USA",
    "Jesup, Wayne, GA, USA",
    "Jim Wells, TX, USA",
    "Johnson, IA, USA",
    "Johnstown, PA, USA",
    "Jonesboro, Craighead, AR, USA",
    "Joplin, MO, USA",
    "Juneau, AK, USA",
    "Kahului, HI, USA",
    "Kalamazoo, MI, USA",
    "Kansas City, MO, USA",
    "Kapaa, HI, USA",
    "Kearney, NE, USA",
    "Keene, NH, USA",
    "Kendallville, Noble, IN, USA",
    "Kennett, MO, USA",
    "Kennewick, WA, USA",
    "Kent, DE, USA",
    "Keokuk, Lee, IA, USA",
    "Kerr, TX, USA",
    "Kerrville, Kerr, TX, USA",
    "Ketchikan, AK, USA",
    "Key West-Marathon, FL, USA",
    "Kill Devil Hills, NC, USA",
    "Killeen, Bell, TX, USA",
    "Kingsport, TN, USA",
    "Kingston, Ulster, NY, USA",
    "Kingsville, Kleberg, TX, USA",
    "Kinston, NC, USA",
    "Klamath Falls, OR, USA",
    "Kleberg, TX, USA",
    "Knoxville, TN, USA",
    "Kokomo, Howard, IN, USA",
    "Kootenai, ID, USA",
    "Kosciusko, IN, USA",
    "KS, USA",
    "KY-IL, USA",
    "KY, USA",
    "La Crosse, WI, USA",
    "La Follette, TN, USA",
    "La Grande, OR, USA",
    "La Plata, CO, USA",
    "La Salle, IL, USA",
    "LA, USA",
    "Laconia, NH, USA",
    "Lafayette, LA, USA",
    "Lafayette, Lafayette, LA, USA",
    "Lafayette, Tippecanoe, IN, USA",
    "LaGrange, GA, USA",
    "Lake Charles, Calcasieu, LA, USA",
    "Lake City, Columbia, FL, USA",
    "Lake County, IL, USA",
    "Lake Havasu City, Mohave, AZ, USA",
    "Lake, CA, USA",
    "Lake, IN, USA",
    "Lakeland, Polk, FL, USA",
    "Lamesa, Dawson, TX, USA",
    "Lancaster, PA, USA",
    "Lancaster, SC, USA",
    "Lansing, MI, USA",
    "LaPorte, IN, USA",
    "Laramie, WY, USA",
    "Laredo, Webb, TX, USA",
    "Larimer, CO, USA",
    "Las Cruces, NM, USA",
    "Las Vegas, NM, USA",
    "Las Vegas, NV, USA",
    "Latah, ID, USA",
    "Lauderdale, AL, USA",
    "Laurel, KY, USA",
    "Laurel, MS, USA",
    "Laurens, GA, USA",
    "Laurinburg, NC, USA",
    "Lawrence, Douglas, KS, USA",
    "Lawrence, IN, USA",
    "Lawrenceburg, TN, USA",
    "Lawton, OK, USA",
    "Lebanon, MO, USA",
    "Lebanon, PA, USA",
    "Lee, AL, USA",
    "Lee, IA, USA",
    "Lee, IL, USA",
    "Leon, FL, USA",
    "Levelland, Hockley, TX, USA",
    "Lewisburg, PA, USA",
    "Lewiston, ME, USA",
    "Lewiston, Nez Perce, ID, USA",
    "Lewistown, PA, USA",
    "Lexington Park, MD, USA",
    "Lexington, Fayette, KY, USA",
    "Lexington, NC, USA",
    "Lexington, NE, USA",
    "Liberal, Seward, KS, USA",
    "Liberty, GA, USA",
    "Lima, OH, USA",
    "Limestone, TX, USA",
    "Lincoln, LA, USA",
    "Lincoln, Logan, IL, USA",
    "Lincoln, NE, USA",
    "Litchfield, CT, USA",
    "Little Rock, Pulaski, AR, USA",
    "Livonia, MI, USA",
    "Llano, TX, USA",
    "Lock Haven, PA, USA",
    "Logan, CO, USA",
    "Logan, IL, USA",
    "Logan, UT-ID, USA",
    "London, Laurel, KY, USA",
    "Longview-Kelso, WA, USA",
    "Longview, Gregg, TX, USA",
    "Los Angeles, CA, USA",
    "Los Angeles, Los Angeles, CA, USA",
    "Louis, St, Louis, MO-IL, USA",
    "Louisville, Jefferson, KY, USA",
    "Loveland, Larimer, CO, USA",
    "Lowndes, GA, USA",
    "Lucie, FL, USA",
    "Lufkin, Angelina, TX, USA",
    "Lumberton, NC, USA",
    "Lynchburg, VA, USA",
    "Lyon, KS, USA",
    "MA, USA",
    "Macomb, McDonough, IL, USA",
    "Macon, AL, USA",
    "Macon, Bibb, GA, USA",
    "Macon, IL, USA",
    "Madera, CA, USA",
    "Madera, Madera, CA, USA",
    "Madison, AL, USA",
    "Madison, GA, USA",
    "Madison, ID, USA",
    "Madison, IN, USA",
    "Madison, Jefferson, IN, USA",
    "Madison, KY, USA",
    "Madison, LA, USA",
    "Madison, WI, USA",
    "Magnolia, Columbia, AR, USA",
    "Mahaska, IA, USA",
    "Malone, Franklin, NY, USA",
    "Manchester, NH, USA",
    "Manhattan, Riley, KS, USA",
    "Manitowoc, WI, USA",
    "Mankato, MN, USA",
    "Maricopa, AZ, USA",
    "Marietta, WV, USA",
    "Marinette, WI-MI, USA",
    "Marion, Edwards, IL, USA",
    "Marion, FL, USA",
    "Marion, Grant, IN, USA",
    "Marion, IL, USA",
    "Marion, OH, USA",
    "Marquette, MI, USA",
    "Marshall, AL, USA",
    "Marshall, Harrison, TX, USA",
    "Marshall, IA, USA",
    "Marshall, IN, USA",
    "Marshall, MN, USA",
    "Marshall, MO, USA",
    "Marshalltown, Marshall, IA, USA",
    "Marshfield, WI, USA",
    "Martinsville, VA, USA",
    "Marys, St, Marys, PA, USA",
    "Marysville, Yuba, CA, USA",
    "Maryville, MO, USA",
    "Mason, KY, USA",
    "Matagorda, TX, USA",
    "Maverick, TX, USA",
    "Mayag\u00fcez, PR, USA",
    "Mayfield, Graves, KY, USA",
    "Maysville, Mason, KY, USA",
    "McAlester, OK, USA",
    "McAllen, Hidalgo, TX, USA",
    "McComb, MS, USA",
    "McCracken, KY-IL, USA",
    "McDonough, IL, USA",
    "McLennan, TX, USA",
    "McMinnville, TN, USA",
    "McPherson, KS, USA",
    "McPherson, McPherson, KS, USA",
    "MD, USA",
    "ME, USA",
    "Medford, OR, USA",
    "Memphis, TN, USA",
    "Mendocino, CA, USA",
    "Menomonie, WI, USA",
    "Merced, CA, USA",
    "Merced, Merced, CA, USA",
    "Meridian, MS, USA",
    "Merrill, WI, USA",
    "Mesa, CO, USA",
    "Mexico, MO, USA",
    "MI, USA",
    "Miami Beach, Miami-Dade, FL, USA",
    "Miami-Dade, FL, USA",
    "Miami, IN, USA",
    "Miami, Miami-Dade, FL, USA",
    "Miami, OK, USA",
    "Michigan City, LaPorte, IN, USA",
    "Middlesborough, KY, USA",
    "Middlesex, MA, USA",
    "Midland, MI, USA",
    "Midland, Midland, TX, USA",
    "Midland, TX, USA",
    "Milledgeville, Baldwin, GA, USA",
    "Miller, AR, USA",
    "Milwaukee, WI, USA",
    "Minden, Webster, LA, USA",
    "Mineral Wells, Palo Pinto, TX, USA",
    "Minneapolis, MN, USA",
    "Minot, ND, USA",
    "Mississippi, AR, USA",
    "Missoula, MT, USA",
    "Mitchell, SD, USA",
    "MN, USA",
    "MO, USA",
    "Moberly, MO, USA",
    "Mobile, AL, USA",
    "Mobile, Mobile, AL, USA",
    "Modesto, Stanislaus, CA, USA",
    "Mohave, AZ, USA",
    "Monroe, IN, USA",
    "Monroe, MI, USA",
    "Monroe, Ouachita, LA, USA",
    "Monroe, WI, USA",
    "Monterey, CA, USA",
    "Montgomery, AL, USA",
    "Montgomery, IN, USA",
    "Montgomery, KS, USA",
    "Montgomery, KY, USA",
    "Montgomery, Montgomery, AL, USA",
    "Montgomery, NY, USA",
    "Montrose, CO, USA",
    "Montrose, Montrose, CO, USA",
    "Moore, TX, USA",
    "Mooresville, NC, USA",
    "Morehead City, NC, USA",
    "Morgan City, St. Mary, LA, USA",
    "Morgan, AL, USA",
    "Morgan, CO, USA",
    "Morgantown, WV, USA",
    "Morristown, TN, USA",
    "Moscow, Latah, ID, USA",
    "Moses Lake, WA, USA",
    "Moultrie, Colquitt, GA, USA",
    "Mount Airy, NC, USA",
    "Mount Pleasant, Taylor, TX, USA",
    "Mount Sterling, Montgomery, KY, USA",
    "Mount Vernon, OH, USA",
    "Mount Vernon, WA, USA",
    "Mountain Home, Elmore, ID, USA",
    "Mountain Home, White, AR, USA",
    "MS-LA, USA",
    "MS, USA",
    "MT, USA",
    "Muhlenberg, KY, USA",
    "Muncie, Delaware, IN, USA",
    "Muscatine, IA, USA",
    "Muscatine, Muscatine, IA, USA",
    "Muskegon, MI, USA",
    "Muskogee, OK, USA",
    "Myrtle Beach, SC, USA",
    "Napa, CA, USA",
    "Napa, Napa, CA, USA",
    "Naples, Collier, FL, USA",
    "Nashville, TN, USA",
    "Natchez, Natchitoches, MS-LA, USA",
    "Natchitoches, MS-LA, USA",
    "Navarro, TX, USA",
    "NC, USA",
    "ND, USA",
    "NE, USA",
    "New Bern, NC, USA",
    "New Castle, DE-MD-NJ, USA",
    "New Castle, Henry, IN, USA",
    "New Castle, PA, USA",
    "New Haven, CT, USA",
    "New Haven, New Haven, CT, USA",
    "New London, CT, USA",
    "New Orleans, Orleans, LA, USA",
    "New Philadelphia, OH, USA",
    "New Ulm, MN, USA",
    "Newberry, SC, USA",
    "Newport, TN, USA",
    "Newton, Jasper, IA, USA",
    "Nez Perce, ID, USA",
    "NH, USA",
    "Niles, MI, USA",
    "NJ, USA",
    "NM, USA",
    "Noble, IN, USA",
    "Nogales, Santa Cruz, AZ, USA",
    "Nolan, TX, USA",
    "Norfolk, NE, USA",
    "North Platte, NE, USA",
    "North Vernon, Jennings, IN, USA",
    "Norwalk, OH, USA",
    "Norwich, New London, CT, USA",
    "Nueces, TX, USA",
    "NV, USA",
    "NY, USA",
    "Oakland, Alameda, CA, USA",
    "Ocala, Marion, FL, USA",
    "Ocean City, NJ, USA",
    "Ocean Pines, MD, USA",
    "Ogden, UT, USA",
    "Ogdensburg, St. Lawrence, NY, USA",
    "OH, USA",
    "Oil City, PA, USA",
    "OK, USA",
    "Okaloosa, FL, USA",
    "Oklahoma City, OK, USA",
    "Olean, Cattaraugus, NY, USA",
    "Olympia, WA, USA",
    "Omaha, NE, USA",
    "Oneonta, Otsego, NY, USA",
    "Onondaga, NY, USA",
    "Ontario, OR-ID, USA",
    "OR-ID, USA",
    "OR, USA",
    "Orange, CA, USA",
    "Orange, FL, USA",
    "Orangeburg, SC, USA",
    "Orlando, Orange, FL, USA",
    "Orleans, LA, USA",
    "Oshkosh, WI, USA",
    "Oskaloosa, Mahaska, IA, USA",
    "Otsego, NY, USA",
    "Ottawa, La Salle, IL, USA",
    "Ottumwa, Wapello, IA, USA",
    "Ouachita, AR, USA",
    "Ouachita, LA, USA",
    "Owensboro, Daviess, KY, USA",
    "Owosso, MI, USA",
    "Oxford, MS, USA",
    "Oxnard, Ventura, CA, USA",
    "PA, USA",
    "Paducah, McCracken, KY-IL, USA",
    "Pahrump, NV, USA",
    "Palatka, Putnam, FL, USA",
    "Palestine, Hopkins, TX, USA",
    "Palm Bay, Brevard, FL, USA",
    "Palm Beach, FL, USA",
    "Palm Coast, Flagler, FL, USA",
    "Palo Pinto, TX, USA",
    "Pampa, Gray, TX, USA",
    "Panama City, Bay, FL, USA",
    "Paragould, Greene, AR, USA",
    "Paris, TN, USA",
    "Payson, Gila, AZ, USA",
    "Peach, GA, USA",
    "Pecos, Reeves, TX, USA",
    "Pendleton-Hermiston, OR, USA",
    "Pensacola, Escambia, FL, USA",
    "Peoria, IL, USA",
    "Peoria, Peoria, IL, USA",
    "Peru, Miami, IN, USA",
    "Philadelphia, PA, USA",
    "Philadelphia, PA, USA",
    "Phillips, AR, USA",
    "Phoenix Lake, Tuolumne, CA, USA",
    "Phoenix, Maricopa, AZ, USA",
    "Picayune, MS, USA",
    "Pierre, SD, USA",
    "Pike, AL, USA",
    "Pima, AZ, USA",
    "Pinellas, FL, USA",
    "Pittsburg, Crawford, KS, USA",
    "Pittsburgh, PA, USA",
    "Pittsfield, Berkshire, MA, USA",
    "Plainview, Houston, TX, USA",
    "Plattsburgh, Clinton, NY, USA",
    "Plymouth, Marshall, IN, USA",
    "Pocatello, Bannock, ID, USA",
    "Point Pleasant, WV, USA",
    "Polk, FL, USA",
    "Polk, GA, USA",
    "Polk, IA, USA",
    "Ponca City, OK, USA",
    "Ponce, PR, USA",
    "Pontiac, St. Clair, IL, USA",
    "Pope, AR, USA",
    "Poplar Bluff, MO, USA",
    "Port Angeles, WA, USA",
    "Port St, Lucie, FL, USA",
    "Portales, NM, USA",
    "Porterville, Tulare, CA, USA",
    "Portland, ME, USA",
    "Portland, OR, USA",
    "Portsmouth, OH, USA",
    "Potter, TX, USA",
    "Pottsville, PA, USA",
    "Poughkeepsie, Dutchess, NY, USA",
    "PR, USA",
    "Providence, RI, USA",
    "Provo, UT, USA",
    "Pueblo, CO, USA",
    "Pueblo, Pueblo, CO, USA",
    "Puerto Rico",
    "Pulaski, AR, USA",
    "Pulaski, KY, USA",
    "Pullman, WA, USA",
    "Punta Gorda, Charlotte, FL, USA",
    "Putnam, FL, USA",
    "Quincy, Adams, IL-MO, USA",
    "Racine, WI, USA",
    "Raleigh-Cary, NC, USA",
    "Rapides, LA, USA",
    "Reading, PA, USA",
    "Red Bluff, Tehama, CA, USA",
    "Red Wing, MN, USA",
    "Redding, Shasta, CA, USA",
    "Redwood City, San Mateo, CA, USA",
    "Reeves, TX, USA",
    "Reno-Sparks, NV, USA",
    "Reno, KS, USA",
    "Rexburg, Madison, ID, USA",
    "RI, USA",
    "Richmond, Madison, KY, USA",
    "Richmond, VA, USA",
    "Richmond, Wayne, IN, USA",
    "Riley, KS, USA",
    "Rio Grande City, Starr, TX, USA",
    "Riverside, CA, USA",
    "Riverton, WY, USA",
    "Roanoke Rapids, NC, USA",
    "Roanoke, VA, USA",
    "Rochester, MN, USA",
    "Rock Springs, WY, USA",
    "Rockford, Winnebago, IL, USA",
    "Rockingham County, NH, USA",
    "Rockingham, NC, USA",
    "Rockland, ME, USA",
    "Rocky Mount, NC, USA",
    "Rolla, MO, USA",
    "Rome, Floyd, GA, USA",
    "Roseburg, OR, USA",
    "Roswell, NM, USA",
    "Rusk, TX, USA",
    "Russellville, Pope, AR, USA",
    "Ruston, Lincoln, LA, USA",
    "Safford, Graham, AZ, USA",
    "Saginaw, MI, USA",
    "Salem, OR, USA",
    "Salina, Saline, KS, USA",
    "Salinas, Monterey, CA, USA",
    "Saline, KS, USA",
    "Salisbury, NC, USA",
    "Salt Lake City, UT, USA",
    "San Angelo, Tom Green, TX, USA",
    "San Antonio, Bexar, TX, USA",
    "San Diego, CA, USA",
    "San Diego, San Diego, CA, USA",
    "San Francisco, CA, USA",
    "San Francisco, San Francisco, CA, USA",
    "San Germ\u00e1n, PR, USA",
    "San Joaquin, CA, USA",
    "San Juan, PR, USA",
    "San Luis Obispo, CA, USA",
    "San Luis Obispo, San Luis Obispo, CA, USA",
    "San Mateo, CA, USA",
    "San Sebasti\u00e1n, PR, USA",
    "Sandusky, OH, USA",
    "Sanford, NC, USA",
    "Sangamon, IL, USA",
    "Santa Ana, Orange, CA, USA",
    "Santa Cruz, AZ, USA",
    "Santa Cruz, CA, USA",
    "Santa Cruz, Santa Cruz, CA, USA",
    "Santa Fe, NM, USA",
    "Santa Isabel, PR, USA",
    "Santa Rosa-Petaluma, CA, USA",
    "Sault Ste, MI, USA",
    "Savannah, Chatham, GA, USA",
    "SC, USA",
    "Scott, IA, USA",
    "Scott, IN, USA",
    "Scottsbluff, NE, USA",
    "Scottsburg, Scott, IN, USA",
    "Scranton, PA, USA",
    "SD, USA",
    "Seaford, Sussex, DE, USA",
    "Searcy, White, AR, USA",
    "Seattle, WA, USA",
    "Sebastian, AR-OK, USA",
    "Selinsgrove, PA, USA",
    "Selma, Dallas, AL, USA",
    "Seneca Falls, Seneca, NY, USA",
    "Seneca, NY, USA",
    "Seneca, SC, USA",
    "Sevierville, TN, USA",
    "Seward, KS, USA",
    "Seymour, Jackson, IN, USA",
    "Shasta, CA, USA",
    "Shawnee, KS, USA",
    "Shawnee, OK, USA",
    "Sheboygan, WI, USA",
    "Shelby, NC, USA",
    "Shelbyville, TN, USA",
    "Shelton, WA, USA",
    "Sheridan, WY, USA",
    "Sherman-Denison, TX, USA",
    "Shreveport, Caddo, LA, USA",
    "Sidney, OH, USA",
    "Sierra Vista, Cochise, AZ, USA",
    "Sikeston, MO, USA",
    "Silver City, NM, USA",
    "Silverthorne, Summit, CO, USA",
    "Sioux City, Woodbury, IA-NE-SD, USA",
    "Sioux Falls, SD, USA",
    "Smith, TX, USA",
    "Solano, CA, USA",
    "Somerset, PA, USA",
    "Somerset, Pulaski, KY, USA",
    "South Bend, St. Joseph, IN, USA",
    "Southern Pines, NC, USA",
    "Spartanburg, SC, USA",
    "Spearfish, SD, USA",
    "Spencer, Clay, IA, USA",
    "Spirit Lake, Dickinson, IA, USA",
    "Spokane, WA, USA",
    "Springfield, Hampden, MA, USA",
    "Springfield, MO, USA",
    "Springfield, OH, USA",
    "Springfield, Sangamon, IL, USA",
    "St, FL, USA",
    "St, George, UT, USA",
    "St, Louis, St, Louis, MO-IL, USA",
    "St, Marys, St, Marys, PA, USA",
    "St. Clair, IL, USA",
    "St. Francis, AR, USA",
    "St. Joseph, IN, USA",
    "St. Lawrence, NY, USA",
    "St. Mary, LA, USA",
    "Stanislaus, CA, USA",
    "Starkville, MS, USA",
    "Starr, TX, USA",
    "State College, PA, USA",
    "Statesboro, Bulloch, GA, USA",
    "Staunton-Waynesboro, VA, USA",
    "Stephens, GA, USA",
    "Stephenville, Erath, TX, USA",
    "Sterling, Logan, CO, USA",
    "Sterling, Whiteside, IL, USA",
    "Steuben, IN, USA",
    "Steuben, NY, USA",
    "Steubenville, OH, USA",
    "Stevens Point, WI, USA",
    "Stillwater, OK, USA",
    "Stockton, San Joaquin, CA, USA",
    "Storm Lake, Buena Vista, IA, USA",
    "Story, IA, USA",
    "Sturgis, MI, USA",
    "Suffolk, MA, USA",
    "Sulphur Springs, Rusk, TX, USA",
    "Summerville, Chattooga, GA, USA",
    "Summit, CO, USA",
    "Sumter, FL, USA",
    "Sumter, GA, USA",
    "Sunbury, PA, USA",
    "Sussex, DE, USA",
    "Sutter, CA, USA",
    "Sweetwater, Nolan, TX, USA",
    "Sylacauga, Talladega, AL, USA",
    "Syracuse, Onondaga, NY, USA",
    "Tahlequah, OK, USA",
    "Talladega, AL, USA",
    "Tallahassee, Leon, FL, USA",
    "Tallulah, Madison, LA, USA",
    "Tampa, Hillsborough, FL, USA",
    "Tangipahoa, LA, USA",
    "Taos, NM, USA",
    "Tarrant, TX, USA",
    "Taylor, KY, USA",
    "Taylor, TX, USA",
    "Taylorville, Christian, IL, USA",
    "Tehama, CA, USA",
    "Terre Haute, Vigo, IN, USA",
    "Terrebonne, LA, USA",
    "Texarkana, Miller, AR, USA",
    "The Villages, Sumter, FL, USA",
    "Thomaston, Upson, GA, USA",
    "Thomasville, Fulton, GA, USA",
    "Tift, GA, USA",
    "Tifton, Tift, GA, USA",
    "Tippecanoe, IN, USA",
    "TN-GA, USA",
    "TN, USA",
    "Toccoa, Stephens, GA, USA",
    "Toledo, OH, USA",
    "Tom Green, TX, USA",
    "Topeka, Shawnee, KS, USA",
    "Torrington, Litchfield, CT, USA",
    "Traverse City, MI, USA",
    "Troy, Pike, AL, USA",
    "Tucson, Pima, AZ, USA",
    "Tulare, CA, USA",
    "Tullahoma, TN, USA",
    "Tuolumne, CA, USA",
    "Tupelo, MS, USA",
    "Tuscaloosa, AL, USA",
    "Tuscaloosa, Tuscaloosa, AL, USA",
    "Tuskegee, Macon, AL, USA",
    "Twin Falls, ID, USA",
    "Twin Falls, Twin Falls, ID, USA",
    "TX, USA",
    "Tyler, Smith, TX, USA",
    "Ukiah, Mendocino, CA, USA",
    "Ulster, NY, USA",
    "Union City, TN, USA",
    "Union, SC, USA",
    "Upson, GA, USA",
    "Urbana, OH, USA",
    "USA",
    "UT-ID, USA",
    "UT, USA",
    "Utica-Rome, NY, USA",
    "Uvalde, TX, USA",
    "Uvalde, Uvalde, TX, USA",
    "VA, USA",
    "Val Verde, TX, USA",
    "Valdosta, Lowndes, GA, USA",
    "Vallejo, Solano, CA, USA",
    "Valley, Chambers, AL, USA",
    "Van Wert, OH, USA",
    "Vanderburgh, IN, USA",
    "Ventura, CA, USA",
    "Vermilion, IL, USA",
    "Vernal, UT, USA",
    "Vernon, Wilbarger, TX, USA",
    "Vero Beach, Indian River, FL, USA",
    "Vicksburg, MS, USA",
    "Victoria, Limestone, TX, USA",
    "Vigo, IN, USA",
    "Virginia Beach, VA, USA",
    "Visalia, Tulare, CA, USA",
    "Volusia, FL, USA",
    "VT, USA",
    "WA, USA",
    "Wabash, IN, USA",
    "Wabash, Wabash, IN, USA",
    "Waco, McLennan, TX, USA",
    "Wahpeton, ND, USA",
    "Walker, TX, USA",
    "Walterboro, SC, USA",
    "Wapello, IA, USA",
    "Ware, GA, USA",
    "Warner Robins, Houston, GA, USA",
    "Warren-Farmington Hills-Troy, MI, USA",
    "Warren, KY, USA",
    "Warren, NY, USA",
    "Warren, PA, USA",
    "Warrensburg, MO, USA",
    "Warsaw, Kosciusko, IN, USA",
    "Washington, AR, USA",
    "Washington, Daviess, IN, USA",
    "Washington, District of Columbia, DC, USA",
    "Washington, LA, USA",
    "Washington, NC, USA",
    "Washington, OH, USA",
    "Washington, TX, USA",
    "Waterloo-Cedar Falls, IA, USA",
    "Watertown-Fort Drum, NY, USA",
    "Watertown, SD, USA",
    "Wauchula, Hardee, FL, USA",
    "Wausau, WI, USA",
    "Waycross, Ware, GA, USA",
    "Wayne, GA, USA",
    "Wayne, IN, USA",
    "Webb, TX, USA",
    "Webster, IA, USA",
    "Webster, LA, USA",
    "Weirton, WV, USA",
    "Weld, CO, USA",
    "Wenatchee, WA, USA",
    "West Helena, Phillips, AR, USA",
    "West Palm Beach, Palm Beach, FL, USA",
    "West Plains, MO, USA",
    "Wharton, TX, USA",
    "Wheeling, WV-OH, USA",
    "White, AR, USA",
    "Whiteside, IL, USA",
    "Whitewater, WI, USA",
    "Whitley, KY, USA",
    "WI-MI, USA",
    "WI, USA",
    "Wichita Falls, Wichita, TX, USA",
    "Wichita, TX, USA",
    "Wilbarger, TX, USA",
    "Williamsport, PA, USA",
    "Willimantic, Windham, CT, USA",
    "Williston, ND, USA",
    "Willmar, MN, USA",
    "Wilmington, NC, USA",
    "Wilmington, New Castle, DE-MD-NJ, USA",
    "Wilmington, OH, USA",
    "Winchester, VA, USA",
    "Windham, CT, USA",
    "Winfield, Cowley, KS, USA",
    "Winnebago, IL, USA",
    "Winona, MN, USA",
    "Winston-Salem, NC, USA",
    "Wisconsin Rapids, WI, USA",
    "Woodbury, IA-NE-SD, USA",
    "Woodward, OK, USA",
    "Wooster, OH, USA",
    "Worcester, MA, USA",
    "Worcester, Worcester, MA, USA",
    "Worthington, MN, USA",
    "WV-OH, USA",
    "WV-VA, USA",
    "WV, USA",
    "WY, USA",
    "Yakima, WA, USA",
    "Yankton, SD, USA",
    "Yauco, PR, USA",
    "Yazoo City, MS, USA",
    "York, PA, USA",
    "Youngstown, OH, USA",
    "Yuba City, Sutter, CA, USA",
    "Yuba, CA, USA",
    "Yuma, AZ, USA",
    "Yuma, Yuma, AZ, USA",
    "\u0386\u03c1\u03b3\u03bf\u03c2",
    "\u0394\u03c1\u03ac\u03bc\u03b1",
    "\u0398\u03b5\u03c3\u03c3\u03b1\u03bb\u03bf\u03bd\u03af\u03ba\u03b7",
    "\u0399\u03c9\u03ac\u03bd\u03bd\u03b9\u03bd\u03b1",
    "\u039c\u03b5\u03c3\u03bf\u03bb\u03cc\u03b3\u03b3\u03b9",
    "\u03a3\u03b9\u03ac\u03c4\u03b9\u03c3\u03c4\u03b1"
]