// This file is generated

_sour_attr_0 = [
    [],
    [
        {
            "cita": [],
            "note": "",
            "type": "Creation date",
            "value": "24 APR 1999"
        },
        {
            "cita": [],
            "note": "",
            "type": "Generated by",
            "value": "ROOTSV 5.01"
        }
    ],
    [
        {
            "cita": [],
            "note": "",
            "type": "Book Cover Type",
            "value": "Paperback"
        }
    ],
    []
]