// This file is generated

_fam_name_0 = [
    "Family of , \u0623\u062d\u0645\u062f and , \u0631\u064a\u062d\u0627\u0646\u0629",
    "Family of , \u0623\u062d\u0645\u062f and \u0627\u0644\u0641\u0636\u0644, \u0627\u0644\u0639\u0628\u0627\u0633\u0629",
    "Family of , \u0645\u062d\u0645\u062f and , \u062e\u062f\u064a\u062c\u0629",
    "Family of , \u0645\u062d\u0645\u062f and , \u0639\u0627\u0626\u0634\u0629",
    "Family of Adams, William and Aguilar, Eleanor",
    "Family of Adkins, John and Adams, Jane",
    "Family of Adkins, Robert Sr. and Nielsen, Martha",
    "Family of Aguilar, John",
    "Family of Allen, Benjamin and Griffith, Experience",
    "Family of Allen, Gershom and Kennedy, Ann",
    "Family of Allen, John and Dennis, Mary (Hannah?)",
    "Family of Allen, Joseph and Barker, Mary",
    "Family of Alonso, Joseph and Hansen, Monica",
    "Family of Alvarado, Cadwallader and Mendez, Martha",
    "Family of Alvarado, Col. Charles and Parent, Eleanor",
    "Family of Alvarado, Franklin and Hodges, Comfort",
    "Family of Alvarado, Jack D. and Warner, Shirley Kay",
    "Family of Alvarado, Jeffery and Cruz, Patti Jo",
    "Family of Alvarado, Jeffrey",
    "Family of Alvarado, John and James, Pamela",
    "Family of Alvarado, Marshall and Bouchard, Jane",
    "Family of Alvarado, Thomas C. and \u041c\u0435\u0434\u0432\u0435\u0434\u0435\u0432, Mary",
    "Family of Alvarado, Wayne and Boucher, Sharon",
    "Family of Alvarado, William and Moody, Martha",
    "Family of \u00c1lvarez and Porter, Mahala J.",
    "Family of Andersen, Samuel and Moreno, Delilah",
    "Family of Anderson, Rev. John and Christiansen, Martha",
    "Family of Anderson, Samuel and \u0424\u0438\u043b\u0438\u043f\u043f\u043e\u0432, Elizabeth",
    "Family of Anderson, Thomas and Carpenter, Sarah",
    "Family of Andrews, Harold and Garner, Cecile Elizabeth",
    "Family of Armstrong, Teddy C. and Cross, Gertrude",
    "Family of Arnold, ??????? and \u042f\u043a\u043e\u0432\u043b\u0435\u0432, Esther Faye",
    "Family of Austin, Hans and Burke, Maria",
    "Family of Austin, Johannas and Jenkins, Margaret",
    "Family of Baldwin, Peter and \u041d\u0438\u043a\u0438\u0444\u043e\u0440\u043e\u0432",
    "Family of Ball, Ezekiel and Reese",
    "Family of Ball, Jasper and \u0417\u044b\u043a\u043e\u0432, Angeline",
    "Family of Ball, Matthias Sr. and Maxwell, Ann",
    "Family of Ball, Matthias, Jr. and Gonzalez, Eliza Jane",
    "Family of Ball, Matthias, Jr. and Moreno, Abigail Chapman",
    "Family of Ball, Matthias, Jr. and Snyder, Ann Louisa",
    "Family of Ball, Thomas and \u0428\u0430\u0434\u0440\u0438\u043d, Mary",
    "Family of Ball, William M. and Moreno, Phebe J.",
    "Family of Bates, William Robert and \u0414\u0430\u043d\u0438\u043b\u043e\u0432, Elaine Suzanne",
    "Family of Beaulieu, Johann Adam and Michaud, Anna Eva",
    "Family of Beaulieu, Johann Franciskus and Barnett, Anna Gertrude",
    "Family of Beaulieu, Johann Michael and L\u00f3pez, Anna Elisabeth",
    "Family of Beaulieu, Johann Simon and Holland, Anna Margaretha",
    "Family of Beaulieu, Johann Simon and \u0410\u043b\u0435\u043a\u0441\u0430\u043d\u0434\u0440\u043e\u0432, Anna Margaretha",
    "Family of Beaulieu, Johann Simon and \u0413\u0440\u0438\u0433\u043e\u0440\u044c\u0435\u0432, Anna Maria",
    "Family of Beaulieu, Johann Theobald and Sutton, Anna Maria",
    "Family of Beaulieu, Johann Valentin and Frazier, Maria Margaretha",
    "Family of Beaulieu, Johann Valentin and Morgan, Elisabeth Margaretha",
    "Family of Beck, Jack and Garner, Bernadette",
    "Family of Becker and Hawkins, Jean",
    "Family of B\u00e9dard, Swanson and \u0414\u043c\u0438\u0442\u0440\u0438\u0435\u0432, Mary",
    "Family of B\u00e9langer, Adrian and Neal, Helen M.",
    "Family of B\u00e9langer, Donald and Pierce, Joanne",
    "Family of B\u00e9langer, James and Garner, Bernetha Ellen",
    "Family of Bell, Gary Richard and Cruz, Judy Denise",
    "Family of Benson, David",
    "Family of Benson, Hugh and Ouellet, Rebecca",
    "Family of Benson, John",
    "Family of Benson, Joseph Louis(Jr.) and Richard, Jeanne",
    "Family of Benson, Joseph Louis(Sr.) and Simard, Sarah",
    "Family of Benson, Samuel Sr. and Wong, Jane",
    "Family of Benson, Walter and Ellis, Margaret Steel",
    "Family of Benson, William",
    "Family of Bergeron, John W. and \u0411\u044b\u043a\u043e\u0432, Bettie",
    "Family of Berry and Reed, Carmel",
    "Family of Bishop, Quirinus and Simmons, Maria",
    "Family of Blais, ?? and L\u00e9vesque, Mary",
    "Family of Blake, Conrad and Ruiz, Catherine",
    "Family of Blake, George and Cunningham, Sally Sarah",
    "Family of Blanco, Bendicht and Fisher, Bendichtli",
    "Family of Blanco, Gerhard and \u0411\u0435\u043b\u043e\u0443\u0441\u043e\u0432, Catharine",
    "Family of Blanco, Hans and Buchanan, Elsbeth",
    "Family of Blanco, Hans(Johannes) and Sullivan, Anna",
    "Family of Blanco, Heinrich and Schmidt, Barbli",
    "Family of Blanco, Henry and Fournier, Peggy",
    "Family of Blanco, John Sr. and Lucas, Christina",
    "Family of Blanco, Milton and Landry, Sarah",
    "Family of Blanco, Peter and Glover, Elizabeth",
    "Family of Blanco, Peter and Leonard, Catherine",
    "Family of Blanco, Rufus and Rodriquez, Mariam",
    "Family of Boucher, David and Morrison, Nancy",
    "Family of Boucher, James and Dub\u00e9, Rose",
    "Family of Boucher, John and \u041d\u0438\u043a\u0438\u0442\u0438\u043d, Monica",
    "Family of Boucher, John",
    "Family of Boucher, Michael and Boucher, Anne",
    "Family of Boucher, Michael and Boucher, Honora",
    "Family of Boucher, Michael and Gil, Nora",
    "Family of Boucher, Michael Shannon and Iglesias, Kate",
    "Family of Boucher, Patrick and Dennis, Susan",
    "Family of Boucher, Patrick",
    "Family of Boucher, Roger Joseph and Page, Sylvia Louise",
    "Family of Boucher, Sean and Gardner, Mary",
    "Family of Boucher, Stephen Francis and Gardner, Mary Jane",
    "Family of Boucher, Steven Joseph and Nelson, Arlene",
    "Family of Boucher, Thomas and Thompson, Bridget",
    "Family of Boucher, Thomas W. and Szyma\u0144ski, Mary",
    "Family of Boucher, William and Fields, Bridget M.",
    "Family of Boucher, William and Savard, Honora",
    "Family of Boucher, William and Walters, Mary",
    "Family of Boucher, William Bernard and Reeves, Maria",
    "Family of Boucher, William J. and Howell, Marie",
    "Family of Boucher, woman",
    "Family of Boyd, Capt. and Alvarado, Eliza",
    "Family of Boyd, Charles Newton and Jones, Martha Elizabeth",
    "Family of Boyd, Charles Newton and Lessard, Izora",
    "Family of Brady, Michael and Boucher, Agnes",
    "Family of Brady, Tony and Boucher, Bridget",
    "Family of Brock, Stephen and Welch, Annabelle Elaine",
    "Family of Brooks, Guillaume de",
    "Family of Brooks, Major Marquis II and Rubio, Winifred",
    "Family of Brooks, Marquis I and Guzman, Isabella",
    "Family of Brooks, William Waller and \u0412\u0430\u0441\u0438\u043b\u044c\u0435\u0432, Lucy",
    "Family of Brown, ????? and \u0422\u0438\u0445\u043e\u043d\u043e\u0432, Mary Ellen",
    "Family of Burgess, Edward and Garner, Marie",
    "Family of Burns, Jonathan and Rubio, Dorcas",
    "Family of Bush, James and Boucher, Catherine",
    "Family of Butler, George and Farmer, Eva",
    "Family of Caldwell, Paul and Boucher, Martha",
    "Family of Carroll, Jacob A. and \u041d\u0438\u043a\u043e\u043b\u0430\u0435\u0432, Maria Catharina",
    "Family of Carroll, Matthias Sr. and \u0412\u043e\u0440\u043e\u0431\u044c\u0435\u0432, Eva",
    "Family of Chambers, William and Moreno, Leah",
    "Family of Christensen, William and Cruz, Judy Denise",
    "Family of Christiansen, Christopher and Gomez, Jane Joane",
    "Family of Christiansen, Christopher and Jones, Ann",
    "Family of Christiansen, Edward and Abbott, Frances",
    "Family of Christiansen, Edward and Thomas, Elizabeth",
    "Family of Christiansen, Edward",
    "Family of Christiansen, John and Harmon, Martha",
    "Family of Christiansen, John",
    "Family of Christiansen, Joseph and Allen, Joanna",
    "Family of Christiansen, Joseph and Gonz\u00e1lez, Elizabeth",
    "Family of Christiansen, Nathaniel and Grenier, Mary",
    "Family of Christiansen, Samuel and Alvarado, Mary",
    "Family of Cobb, Merrick and Boucher, Cynthia Louise",
    "Family of Coleman and Garner, Louella Marie",
    "Family of Collins, Loren and Rhodes, Mary Jane",
    "Family of Colon, William and Guti\u00e9rrez, Dorothy Jean",
    "Family of Cook, John and Rodriquez, Mary",
    "Family of Cooper, ??????? and Garner, Maude",
    "Family of C\u00f4t\u00e9, Raymond Patrick and Russell, Beth Ann",
    "Family of Cox, Robert C. and Garner, Jane McClellan",
    "Family of Cross, Thomas and Page, Anna",
    "Family of Cruz, Arthur Ray and Robbins, Myrabel",
    "Family of Cruz, Dale Eugene and Gill, Linda",
    "Family of Cruz, David Wayne and Nunez, Barbara Ann",
    "Family of Cruz, Everett and Lessard, Susanna Marie",
    "Family of Cruz, Gerald Ray and Rasmussen, Marilyn Joan",
    "Family of Cruz, Ivan Wayne and Gagnon, Bettie Lou",
    "Family of Cruz, James Richard and Morales, Penelope Margot",
    "Family of Cruz, Paul Eugene and Lambert, Marguerite",
    "Family of Cruz, Thomas Everett and Briggs, Joyce Inez",
    "Family of Cruz, William Everett and Hawkins, Ellen Marie",
    "Family of Cunningham, Peter Sr. and Dunn, Margaret Mary?",
    "Family of Cunningham, William Philip and Park, Susannah",
    "Family of Curry, Kenner S. and Jim\u00e9nez, Rebecca",
    "Family of Curtis, John and Gibbs, Margaret",
    "Family of Daniels and Page, Edith (Dolly)",
    "Family of Davis, Benjamin and Alexander, Mary",
    "Family of Davis, John and Knight, Hannah",
    "Family of Davis, Jonathan and Mitchell, Mary",
    "Family of Dawson and Reed, Anastasia",
    "Family of Day, Charles and Serrano, Dot",
    "Family of Dean, John and Reed, Catherine",
    "Family of Delgado and Tyler, Mary A.",
    "Family of Demers, ?? and \u0421\u0435\u0440\u0433\u0435\u0435\u0432, Adria Maria",
    "Family of Desjardins, J. and Reeves, Catherine",
    "Family of Diaz, James and Woods, Nancy",
    "Family of Diaz, William and Baldwin, Anne",
    "Family of Diaz, William and \u041a\u043e\u043c\u0430\u0440\u043e\u0432, Jane",
    "Family of Diaz, William (Rev.) and Hoffman, Fay",
    "Family of D\u00edez, William George and Garner, Barbara Jo",
    "Family of Dixon, Thomas and Warner, Mary",
    "Family of Dom\u00ednguez, George and \u041c\u0430\u043a\u0441\u0438\u043c\u043e\u0432, Nancy",
    "Family of Douglas, Abraham and Alvarado, Nancy",
    "Family of Douglas, Abraham and Greer, Mary Wein",
    "Family of Douglas, Alfred",
    "Family of Douglas, Frederick and Stanley, Barbara",
    "Family of Douglas, Hans Peter and Cummings, Leonnah",
    "Family of Douglas, Hans Peter and Howard, Juliana",
    "Family of Douglas, John Jr. and Johnson, Elizabeth",
    "Family of Douglas, John Jr. and Rogers, Barbara",
    "Family of Douglas, John Sr. and Larson, Christena Wiseman",
    "Family of Douglas, John Sr. and Moran, Ann Delilah \"Tilley\"",
    "Family of Douglas, Joseph and Carroll, Grace",
    "Family of Doyle, Robert Gove and Diaz, Mary Polly",
    "Family of Dub\u00e9, Jacob and Farmer, Anna Marie",
    "Family of Duncan and Reed, Joan",
    "Family of Elliott, Lodowick and \u041a\u043e\u0432\u0430\u043b\u0435\u0432, Sarah",
    "Family of Erickson, Charles and \u0414\u043c\u0438\u0442\u0440\u0438\u0435\u0432, Lucy",
    "Family of Evans, ?m.MaryJane and Rhodes, Mary Jane",
    "Family of Evans, James Patrick and Stevenson, Susan",
    "Family of Farmer, Benjamin H. and Mills, Isabella",
    "Family of Farmer, George William and Bradley, Mary",
    "Family of Farmer, Jacob and \u041c\u043e\u0440\u043e\u0437\u043e\u0432, Mary Elizabeth",
    "Family of Farmer, Michael and Dub\u00e9, Elizabeth",
    "Family of Farmer, Peter Simon and Bowen, Elizabeth",
    "Family of Farmer, Simon and \u0411\u0430\u0440\u0430\u043d\u043e\u0432, Susan",
    "Family of Farmer, Valentine and Miller, Anna Catherine",
    "Family of Ferguson, Lord Samuel",
    "Family of Fernandez, Thomas and Couture, Honora",
    "Family of Fernandez, Thomas and Holloway, Sarah",
    "Family of Fernandez, Thomas and Ortega, Catherine",
    "Family of Fillin, C and Fillin, D",
    "Family of Fillin, E and Fillin, F",
    "Family of Fillin, G and Fillin, H",
    "Family of Fillin, I and Fillin, J",
    "Family of Fillin, K and Fillin, L",
    "Family of Fillin, M and Fillin, N",
    "Family of Fitzgerald, David Lee and \u041b\u043e\u043f\u0430\u0442\u0438\u043d, Donna Elaine",
    "Family of Floyd, Henry and Benson, Nancy",
    "Family of Floyd, John Morgan and Carr, Zelpha Josephine",
    "Family of Floyd, John S. and Coleman, Mary",
    "Family of Floyd, Robert William and \u0414\u0430\u043d\u0438\u043b\u043e\u0432, Kathryn Louise",
    "Family of Ford and Moreno, Elizabeth",
    "Family of Ford, Phillip D. and Webb, Joan Lorinda",
    "Family of Ford, Samuel and Farmer, Catharine",
    "Family of Ford, Stephen Jacob and Garner, Iola Elizabeth Betty",
    "Family of Ford, William and Payne, Winifred",
    "Family of Fortin, Matthias and Baker, Margaret",
    "Family of Foster, John and Ryan, Elizabeth",
    "Family of Foster, John and Ryan, Elizabeth",
    "Family of Foster, Thomas and Koz\u0142owski, Margret",
    "Family of Foster, Thomas and Spencer, Ann",
    "Family of Foster, William and Sanders, Mary",
    "Family of Fox, David and Green, Frances",
    "Family of Fox, David and Harris, Mary",
    "Family of Fox, Jacob, Sr. and Palmer, Sarah",
    "Family of Fox, Samuel and Mason, Susannah",
    "Family of Fox, William and Mason, Hannah",
    "Family of Frazier, Johann Adam and Hicks, Anna Eva",
    "Family of Frazier, Johann Walter and Beaulieu, Anna Margaretha",
    "Family of French, Jimmy Michael and Warner, Martha Ellen",
    "Family of Gagn\u00e9, Thomas and Reeves, Ann",
    "Family of Gardner, Michael and Hansen, Nula",
    "Family of Gardner, Patrick",
    "Family of Garner, Barry Joseph and V\u00e1zquez, April Lynn",
    "Family of Garner, Daniel Webster and Jackson, Cora Ellen",
    "Family of Garner, Eugene Stanley and Reed, Frances Lucille (Babe)",
    "Family of Garner, Eugene Stanley, Jr. and Pelletier, Josephine",
    "Family of Garner, Eugene Stanley, Jr. and Washington, Pearline",
    "Family of Garner, Francis William and Gibbs, Connie",
    "Family of Garner, Gerard Stephen and George, Elizabeth",
    "Family of Garner, Howard Lane and Mar\u00edn, Mary Anne",
    "Family of Garner, Jason Richard and Harper, ??",
    "Family of Garner, Jesse V. and Taylor, Viola",
    "Family of Garner, John Joseph and Crawford, Lori",
    "Family of Garner, John Roger and \u0411\u0440\u044e\u0445\u0430\u043d\u043e\u0432, Violet Louise",
    "Family of Garner, Joseph and Edwards, Lucy",
    "Family of Garner von Zieli\u0144ski, Lewis Anderson Sr and Martel, Luella Jacques",
    "Family of Garner, Mark Gerard and Gibbs, Lori",
    "Family of Garner, Michael Stanley and Gibbs, Sharon",
    "Family of Garner, Peter George and Gibbs, Joy",
    "Family of Garner, Raymond Scott and P\u00e9rez, Angela Gay",
    "Family of Garner, Raymond Webster and Bryant, Kathryn Ladon",
    "Family of Garner, Richard Eugene and Gibbs, Elaine",
    "Family of Garner, Robert F. and Cannon, Mary Jane",
    "Family of Garner, Robert W. and Zieli\u0144ski, Phoebe Emily",
    "Family of Garner, Thomas James and \u0421\u043e\u0440\u043e\u043a\u0438\u043d, Holly Ruth",
    "Family of Garner, Walter E. and Garc\u00eda, Maude",
    "Family of Garrett, Terry Lee and Holloway, Gail",
    "Family of Garrett, William Forest and Perkins, Wilma Mae",
    "Family of Garrett, William Walker and Lessard, Laura Eloise",
    "Family of Gibbs, Rosina M.",
    "Family of Gibson, Mr. and James, Mary",
    "Family of Gilbert, ?? and L\u00e9vesque, Wilma",
    "Family of Gill, Lawrence and Webb, Joan Lorinda",
    "Family of Gill, Lawrence",
    "Family of Gomez, Culthbert",
    "Family of Gonz\u00e1lez and Ball, Martha",
    "Family of Goodman, Ralph and Powell, Martha",
    "Family of Goodwin and Sandoval, Liz",
    "Family of Gosselin, Martin Kelly and Warner, Marcia Jane",
    "Family of Grabowski, Mr. and Waters, Lola",
    "Family of Graham, Steve and Cruz, Laura Joy",
    "Family of Green, Edward and Lefebvre, Mary",
    "Family of Green, Edward and \u041c\u0430\u043a\u0441\u0438\u043c\u043e\u0432, Christina",
    "Family of Green, James and Christiansen, Frances",
    "Family of Green, Randolph and Davis, Sabra",
    "Family of Green, Yelverton and Robertson, Elizabeth",
    "Family of Grenier, Joseph and Peters, Rose",
    "Family of Gross and Peters, Dorothy",
    "Family of Guerrero, Robert",
    "Family of Guerrero, Robert",
    "Family of Guerrero, Walter",
    "Family of Guerrero, Walter",
    "Family of Guerrero, Walter",
    "Family of Gutierrez, Thomas and Boucher, Nora A.",
    "Family of Guti\u00e9rrez, Walter Harmon and Boyd, Lauretta Esther",
    "Family of Hale, Lawrence Paul and Garner, Anne Therese",
    "Family of Hamilton, John and Boucher, Miread",
    "Family of Hammond, Roy and Serrano, Carrie",
    "Family of Hansen, Noel and Ramirez, Helen",
    "Family of Hansen, Thomas and Boucher, Rose Mary",
    "Family of Hanson, Robert and Schwartz, Helewisa",
    "Family of Hardy, Jakob and Beaulieu, Anna Maria",
    "Family of Harris, Lawrence and Landry, Alice",
    "Family of Harrison, Edward and Allen, Sarah",
    "Family of Harrison, Paul Allen and \u0414\u0430\u043d\u0438\u043b\u043e\u0432, Lucinda Elinor",
    "Family of Hart, Gerry and Boucher, Mary",
    "Family of Harvey, John",
    "Family of Hawkins, Beckham and \u0410\u0444\u0430\u043d\u0430\u0441\u044c\u0435\u0432, Angie",
    "Family of Hawkins, Richard W.",
    "Family of Hawkins, William Melvin and Gibbs, Ruth",
    "Family of Hawkins, William Melvin",
    "Family of Haynes, Marc W. and Warner, Laura Gail",
    "Family of H\u00e9bert, Mr. and Page, Mary",
    "Family of Henry, John",
    "Family of Hernandez, John and Norris, Elizabeth",
    "Family of Hern\u00e1ndez, Thomas and Douglas, Elizabeth",
    "Family of Hill and Garner, Louella Marie",
    "Family of Hines and Douglas, Eliza Jane",
    "Family of Holloway, John(?) and \u041e\u0440\u043b\u043e\u0432, Margaret(?)",
    "Family of Howard, Michael",
    "Family of Howell, John and Yates, Sarah",
    "Family of Howell, JOHN",
    "Family of Hunt, Isaac and \u0414\u043c\u0438\u0442\u0440\u0438\u0435\u0432, Nancy Ann",
    "Family of James, Hugh Jr. and Wi\u015bniewski, D.",
    "Family of James, Hugh Sr. and Serrano, Caroline",
    "Family of James, Isaac and Andersen, Martha",
    "Family of James, James",
    "Family of James, Joseph and Floyd, Nancy",
    "Family of James, Robert and Pratt, Sarah",
    "Family of James, Thomas and Marshall, Kate Teel",
    "Family of James, Thomas and Parent, Betsy",
    "Family of James, Thomas Sr. and Benson, Martha Ellen M.",
    "Family of James, Walter Crockett and Hern\u00e1ndez, Nancy",
    "Family of James, Walter Crockett and \u0417\u0430\u0445\u0430\u0440\u043e\u0432, Margaret",
    "Family of Jankowski, George and Page, Margaret",
    "Family of Jenkins, Peter and Marsh, Margaret",
    "Family of Jimenez and Reed, Maureen",
    "Family of Jim\u00e9nez, Andrew and Palmer, Sarah",
    "Family of Jim\u00e9nez, Cornelius and Blair, Jane",
    "Family of Jim\u00e9nez, George Henry, III and Blake, M. Susannah",
    "Family of Jim\u00e9nez, George Henry, Jr. and Silva, Mildred",
    "Family of Jim\u00e9nez, George, Sr. and Henry, Elizabeth",
    "Family of Jim\u00e9nez, John and Palmer, Mary",
    "Family of Johnson, Henry and Sparks, Catherine",
    "Family of Johnson, Richard F. and Garner, Betty Jane",
    "Family of Johnston and Sandoval, Jean",
    "Family of Jones, Hugh and \u041a\u0438\u0440\u0438\u043b\u043b\u043e\u0432, ??",
    "Family of Jordan, William and Reed, Frances Lucille (Babe)",
    "Family of J\u00f8rgensen, Jeffrey and Osborne, Julia Marie",
    "Family of Joseph, Alfred and Moreno, Minerva",
    "Family of Kami\u0144ski and Reed, Jane",
    "Family of Keller, Mathew",
    "Family of Kelley, Thomas and Douglas, Catherine",
    "Family of Kim, Frank and Kristensen, Catherine Virginia",
    "Family of King, Henry and \u0411\u044b\u043a\u043e\u0432, Annie",
    "Family of Knudsen, John and Huff, Isabel",
    "Family of Knudsen, Ralph and Huff, Isabel",
    "Family of Knudsen, Ralph and Walton, Theophania(Tiffany)",
    "Family of Knudsen, Ranulf and Huff, Bertrama",
    "Family of Knudsen, Robert and Schwartz, Helewisa",
    "Family of Kowalski, John and Wells, Alice",
    "Family of Kowalski, Thomas and Santos, Alice",
    "Family of Krawczyk, Douglas and Cruz, Patti Jo",
    "Family of Kristensen, John Francis\"Chick\" and \u4f0a\u85e4, Mary",
    "Family of Landry, John Anthony and Harris, Ella Mae",
    "Family of Landry, Maurice T. and Estrada, Mary Claire",
    "Family of Landry, Maurice T. and Vargas, Caroline Metzger",
    "Family of Landry, Michael Edward and Brady, CatherineJosephine",
    "Family of Lane, Joseph Edward and \u041a\u043e\u0437\u043b\u043e\u0432, Linda Mae",
    "Family of Lane, Joseph Robert and Thornton, Dorothy Eleanor",
    "Family of Lane, Remo and Barnes, Ernestina",
    "Family of Lapointe, John and Madsen, Catherine",
    "Family of Lapointe, Sir Thomas",
    "Family of Lapointe, William",
    "Family of Lavoie, Henry and James, Patsy",
    "Family of Lawson, Mr. and Parent, Polly",
    "Family of Lefebvre, Joseph and Gregory, Mary",
    "Family of Lefebvre, Rev. John L. and Kowalski, Hannah",
    "Family of Lefebvre, Rev. John L.",
    "Family of Lefebvre, Robert and \u0413\u043e\u043d\u0447\u0430\u0440\u043e\u0432, Ellen",
    "Family of Lessard and Castro, ???",
    "Family of Lessard, ??? and Castro, ???",
    "Family of Lessard, Carl Tolbert and Webb, Luella Florence",
    "Family of Lessard, Ira Willis and Jim\u00e9nez, Lucinda Ellen",
    "Family of Lessard, Isaac and Dom\u00ednguez, Mary E.",
    "Family of Lessard, Ralph Raymond and Davidson, Bernice",
    "Family of Lessard, Robert and Webb, Joan Lorinda",
    "Family of L\u00e9vesque, James W. and Lessard, Emma Jane",
    "Family of Lewandowski, Thomas and Jankowski, Isabella Belle",
    "Family of Lindsey, John and Warner, Martha Ellen",
    "Family of Little, O. D. and Webb, Anna Mabel",
    "Family of Logan, Joseph and \u0411\u044b\u043a\u043e\u0432, Janie",
    "Family of L\u00f3pez, Hans Valentin and Beaulieu, Anna Ottilia",
    "Family of Love and Reed, Carmel",
    "Family of Mack, ?? and L\u00e9vesque, Elsie",
    "Family of Maldonado, Edward",
    "Family of Mar\u00edn, Alfred Franklin(Frank) and Floyd, Martha Frances \"Fannie\"",
    "Family of Mar\u00edn, Moses Wallace and Landry, Eleanor (Nellie) Therese",
    "Family of Mar\u00edn, Walter Matthew and Boucher, Mary Cecilia",
    "Family of Mar\u00edn, William and Francis, Elizabeth",
    "Family of Mar\u00edn, Willis H. and Floyd, Sarah (Sally)",
    "Family of Martel, Henry and H\u00e9bert, Ruth Ann",
    "Family of Martin and Moreno, Mary Ann",
    "Family of Mart\u00edn and Garner, Melissa Sue",
    "Family of Martinez and Reed, Catherine",
    "Family of Mart\u00ednez and Serrano, Reh Dawn",
    "Family of Massey, John and \u041c\u0430\u043b\u044c\u0446\u0435\u0432, Joan",
    "Family of Matthews, Mark John and Warner, Andrea Susan",
    "Family of Maxwell, William and Nielsen, Elizabeth",
    "Family of Mazur, William and Crawford, Margaret",
    "Family of Mcbride, Paul and \u0414\u0430\u043d\u0438\u043b\u043e\u0432, Barbara Joanne",
    "Family of McCarthy, Valentine Thomas and Jim\u00e9nez, Sarah",
    "Family of McCormick, Dean and Page, Florence",
    "Family of McCoy, Francis and Reed, Sarah",
    "Family of McCoy, Thomas Michael and Howell, Mary",
    "Family of Medina, Wesley G. and Guti\u00e9rrez, Joan Arlene",
    "Family of Mendoza, James and Allen, Abigail",
    "Family of Meyer, P.D.",
    "Family of Michaud, Valentin and Beaulieu, Anna Eva",
    "Family of Molina, Robert",
    "Family of Moore, George and \u0411\u044b\u043a\u043e\u0432, Margaret",
    "Family of Moran, Andrew and Sharp, ???",
    "Family of Moran, Andrew",
    "Family of Moreno, Aaron and \u0417\u043b\u043e\u0431\u0438\u043d, Martha",
    "Family of Moreno, Christian and Price, Mary",
    "Family of Moreno, Christian, I and Mann, Agnes",
    "Family of Moreno, Darius and Craig, Mary J.",
    "Family of Moreno, Esau and Caron, Mary E.",
    "Family of Moreno, Herman",
    "Family of Moreno, Johann Christian II and \u041c\u0430\u0442\u0432\u0435\u0435\u0432, Elizabeth",
    "Family of Moreno, Johann Henrich",
    "Family of Moreno, Maj. Christopher and Bass, Mary",
    "Family of Moreno, Solon and Perkins, Lydia",
    "Family of Moreno, Thomas H. and D\u0105browski, Letitia C.",
    "Family of Morin and Page, Belle",
    "Family of Morris, Adam and Oliver, Elizabeth",
    "Family of Morris, Cyrus and Graves, Martha",
    "Family of Mortensen, Daniel and Warner, Sarah Jane",
    "Family of Moss, Christy and Page, Matilda",
    "Family of Mullins, Robert? and Houston, Ellender",
    "Family of Munoz, Shadrach M. and Mar\u00edn, Nancy H.",
    "Family of Murray, Nicholas",
    "Family of Myers, James and Boucher, Catherine",
    "Family of Neal, James and Page, Elizabeth",
    "Family of Neal, John and Schneider, Belle Irene",
    "Family of Nguyen, John Harry and Walker, Sharon Lynette",
    "Family of Norris, John and Howell, Mary (Sarah)",
    "Family of Norris, John and \u041d\u043e\u0432\u0438\u043a\u043e\u0432, Sarah",
    "Family of Norris, William",
    "Family of Nowak, John H. and Page, Eleanor Maude",
    "Family of Oliver, Hans Michael",
    "Family of Oliver, Harmonas I and Malone, Mary",
    "Family of Oliver, Harmonas II and Harvey, Lydia",
    "Family of Olson, ??????? and Mar\u00edn, Alice",
    "Family of Ortiz, Don and Welch, Shirley",
    "Family of Ortiz, Raymond and Page, Ferne",
    "Family of Osborne, Dwight Billington and Lessard, Mary Alice",
    "Family of Osborne, Paul Daniel and Hawkins, Jennifer Leigh",
    "Family of Owens, Wilford and Jankowski, Matilda",
    "Family of Padilla, Otis Earl and Page, Eleanor Irene",
    "Family of Page, Andrew Vincent and Zimmerman, Edith Irene",
    "Family of Page, David and Douglas, Elizabeth",
    "Family of Page, Dwayne Alan and Scott, Cheryl Lee",
    "Family of Page, John and Kaczmarek, Isabella",
    "Family of Page, John James and Adkins, Minnie",
    "Family of Page, John James and Mcdaniel, Margaret",
    "Family of Page, Kenneth Fritz and Pittman, June Christine",
    "Family of Page, Marvin Ray and Morton, Gail Darlene",
    "Family of Page, Mr. and James, Martha",
    "Family of Page, Richard C. and Rodriguez, Helen M.",
    "Family of Page, Robert and Neal, Belle",
    "Family of Page, Vernett Gail and Norman, Dorothy Louise",
    "Family of Palmer, Robert and \u041f\u043e\u043f\u043e\u0432, ???????",
    "Family of Parent, Capt.Jacob C. and James, Jane",
    "Family of Parent, John Sr.",
    "Family of Parent, Montgomery and Alvarado, Patsy",
    "Family of Park, James",
    "Family of Parker, Frank R. and Garner, Anetta",
    "Family of Parks, Cliff and Gill, Lorie Ann",
    "Family of Parsons, Henry and Douglas, Ellen",
    "Family of Patrick, Melvin and Todd, Lucille",
    "Family of Patterson, George and Farmer, Elizabeth",
    "Family of Patton, Adolph and Moreno, Lelia L.",
    "Family of Payne, Alexander and Kami\u0144ski, Elizabeth",
    "Family of Payne, Alexander and Salazar, Catherine",
    "Family of Payne, Fielding and Lawrence, Dorcas C.",
    "Family of Payne, George and Diaz, Frances",
    "Family of Payne, Leonard and Hall, Elizabeth",
    "Family of Payne, Leonard? and Brooks, Elizabeth\"Betty\"",
    "Family of Pedersen, William and Benson, Elizabeth",
    "Family of Pelletier, Esiquio and Leclerc, Sesaria",
    "Family of Perry, M. and Reeves, Elizabeth",
    "Family of Person, The First and Fillin, B",
    "Family of Peters, Frank O. and Cross, Alta M.",
    "Family of Peters, George Sr. and Ramsey, Joan",
    "Family of Peters, John",
    "Family of Peters, John C. and Cruz, Joyce Marie",
    "Family of Petersen, William and \u0414\u043c\u0438\u0442\u0440\u0438\u0435\u0432, Margaret Jane",
    "Family of Piotrowski, John and Todd, Olive",
    "Family of Piotrowski, Sir John",
    "Family of Poirier, James A. and Walker, Sharon Lynette",
    "Family of Poole, Dr. John and James, Jane",
    "Family of Pope, John and Kristensen, Mary Elizabeth",
    "Family of Porter, David and Moreno, Mary H.",
    "Family of Poulin and Reed, Rose",
    "Family of Poulsen, Randall Lee and Welch, Lisa Dawn",
    "Family of Quinn, Abraham and Blanco, Malvina",
    "Family of Ram\u00edrez, John B. and Garner, Rebecca Catharine",
    "Family of Ramos, John",
    "Family of Reed, Edward and Reed, Ellen",
    "Family of Reed, Edward",
    "Family of Reed, Francis Vincent and \u041a\u0430\u0437\u0430\u043d\u0446\u0435\u0432, Katherine",
    "Family of Reed, Francis Vincent and \u0422\u0438\u0445\u043e\u043d\u043e\u0432, Catherine Virginia",
    "Family of Reed, John and Bernier, Margaret",
    "Family of Reed, John and Goodwin, Sarah",
    "Family of Reed, Matthew and Gibbs, Mary",
    "Family of Reed, Michael and Gibbs, Mary",
    "Family of Reed, Michael and Goodwin, Alice",
    "Family of Reed, Owen",
    "Family of Reed, Patrick and Gibbs, Elizabeth",
    "Family of Reed, Peter and \u041a\u0443\u0437\u043d\u0435\u0446\u043e\u0432, Hanora",
    "Family of Reed, Peter James? and Reed, Catherine",
    "Family of Reed, Terrence and Gibbs, Maria",
    "Family of Reed, Terrence (TyNed) and Gibbs, Jennie",
    "Family of Reed, Thomas",
    "Family of Reeves, James and Meyer, Catherine",
    "Family of Reeves, John and Flowers, Mary A.",
    "Family of Reeves, John and McCarthy, Mary",
    "Family of Reid, Hans and \u0421\u0435\u043c\u0435\u043d\u043e\u0432, Cathern",
    "Family of Reyes and Armstrong, Sarah",
    "Family of Reynolds, Col. John and Mazur, Elizabeth",
    "Family of Reynolds, David and Vaughn, Mary Meriwether",
    "Family of Reynolds, John and Newman, Margaret",
    "Family of Reynolds, John and Stevens, Elizabeth",
    "Family of Reynolds, John and \u041a\u043e\u0432\u0430\u043b\u0435\u0432, Sarah",
    "Family of Reynolds, Nicholas and Murray, Susannah",
    "Family of Reynolds, William",
    "Family of Rhodes, William Sr. and Kristensen, Anna June",
    "Family of Riley, Thomas and Edwards, Lucy",
    "Family of Robinson, Clarence and Garner, Bertha P.",
    "Family of Rodgers, John and Garrett, Doris Mae",
    "Family of Rodriquez",
    "Family of Rodriquez, John and \u041f\u043e\u043b\u044f\u043a\u043e\u0432, Eve",
    "Family of Rodriquez, Mordica and \u0412\u043e\u0440\u043e\u043d\u043e\u0432, Katherine",
    "Family of Rodriquez, Mordica and \u041a\u0430\u0437\u0430\u043a\u043e\u0432, Jane",
    "Family of Rodriquez, Richard and \u0416\u0443\u043a\u043e\u0432, Hannah",
    "Family of Rodriquez, William M. and Douglas, Mary\"Polly\"",
    "Family of Romero, Ernest and Jankowski, Minnie",
    "Family of Roy, Prince Alfred and Mar\u00edn, Frances Coppage",
    "Family of Rubio, John III",
    "Family of Russell, Bruce Lynn and Henderson, Cathy Sue",
    "Family of Russell, Melvin Glen and Manning, Judith Ann",
    "Family of Russell, Norman and Lessard, Helen Belle",
    "Family of S\u00e1nchez, David Andrew and Welch, Rosalie Jane",
    "Family of Sanchez, John and Curtis, Margaret",
    "Family of Sanders, Henry and Rose, Ann",
    "Family of Sandoval, John Joe",
    "Family of Sandoval, Johnnie and Reed, Minnie",
    "Family of Santiago, Mathias and James, Molly",
    "Family of Sanz, John and Jankowski, Sarah",
    "Family of Savard, Walter and Russell, Janet Gail",
    "Family of Schneider and Neal, Margaret",
    "Family of Schultz, John and Payne, Jane Coppage",
    "Family of Schultz, Rev.Isaac and Turner, Mary",
    "Family of Serrano, Abraham",
    "Family of Serrano, Archibald and Delgado, Catherine",
    "Family of Serrano, Joseph and Quinn, Elizabeth Marium",
    "Family of Serrano, Joseph",
    "Family of Shelton, Peter and Farmer, Caroline",
    "Family of Simard, Thomas",
    "Family of St-Pierre, Joe and Boucher, Norene",
    "Family of Steele, Valentine and Beaulieu, Anna Elisabeth",
    "Family of Stephens, Adam and Blanco, Anna Maria",
    "Family of Stewart and Hawkins, Janelle",
    "Family of Stokes, Gabriel and McCoy, Celine Bridget",
    "Family of Stone, Alfred Wayne and Guti\u00e9rrez, Virginia Elizabeth",
    "Family of Strickland, Col. Robert and James, Patsy",
    "Family of Swanson, Richard and Fernandez El Fern\u00e1ndez, Avis III",
    "Family of Swanson, William and Jensen, Elizabeth",
    "Family of Swanson, William",
    "Family of Taylor, Jacob and Farmer, Susanna",
    "Family of Taylor, Philip and \u0411\u044b\u043a\u043e\u0432, Harriet",
    "Family of Terry, J. and Reeves, Bridget",
    "Family of Thomas, Elder Thomas and Barrett, Anne",
    "Family of Thomsen, new and Farmer, Elizabeth",
    "Family of Thornton, Arthur Otto and Mar\u00edn, Lilla Estella",
    "Family of Thornton, James Arthur and Lachance, Helen",
    "Family of Thornton, Phillip James and \u0411\u0435\u043b\u043e\u0432, Katherine",
    "Family of Thornton, Romaine and Soto, Harriet",
    "Family of Todd, Charles and Cole, Eurydice",
    "Family of Todd, George W. and Morris, Jane",
    "Family of Todd, Hodges and Piotrowski, Lucy",
    "Family of Todd, John and Warner, Elizabeth",
    "Family of Todd, John and \u041b\u0430\u043b\u0435\u0442\u0438\u043d, Elizabeth",
    "Family of Todd, John M. and Farmer, Elizabeth Ellen",
    "Family of Todd, William and \u6e21\u8fba, Mary (Polly)",
    "Family of Torres and Hawkins, Gail",
    "Family of Townsend, Mark and \u041c\u0430\u043a\u0441\u0438\u043c\u043e\u0432, Heather Michelle",
    "Family of Valdez and Reed, Noreen",
    "Family of Walker, Andrew Vincent and Pearson, Eileen Ruth",
    "Family of Wallace, Abraham and Greene, Marcy",
    "Family of Walters, Daniel",
    "Family of Ward, David J. and Warner, Margaret Ruth",
    "Family of Warner, Allen Carl and Garner, Rita Marie",
    "Family of Warner, Andrew and Maldonado, Eunice",
    "Family of Warner, Arthur Maurice and Phillips, Anita Irene",
    "Family of Warner, Capt. Andrew and Christiansen, Hannah",
    "Family of Warner, Capt. Francis and Ingram, Mary",
    "Family of Warner, Capt. George and Alvarez, Mary",
    "Family of Warner, Daniel and Higgins, Charity",
    "Family of Warner, David Luther and Robbins, Merida Lorene",
    "Family of Warner, David Warren and Simpson, Geraldine Ann",
    "Family of Warner, Edward and Anderson, Mary Molly",
    "Family of Warner, Fred Loren and Flores, Jamie Lee",
    "Family of Warner, George and Nichols, Elizabeth",
    "Family of Warner, George Edward and Lessard, Elinor Jane",
    "Family of Warner, Harold Lowell and Powers, Nancy Lou",
    "Family of Warner, John",
    "Family of Warner, John William and Miles, Rebecca J.",
    "Family of Warner, Johnathon and Montgomery, Mary",
    "Family of Warner, Martin Bogarte and Klein, Alma Katherine",
    "Family of Warner, Martin Bogarte and Page, Clara Belle",
    "Family of Warner, Michael Louis and Warren, Pansy L.",
    "Family of Warner, Michael Warren and \u0427\u0435\u0440\u043d\u044b\u0445, Mary Helen",
    "Family of Warner, Noah and Burns, Margaret",
    "Family of Warner, Piatt D. and Fox, Julia Colville",
    "Family of Warner, Rev. Edmund",
    "Family of Warner, Richard Kenneth and Wade, Joy A.",
    "Family of Warner, Richard Kenneth and \u041c\u0435\u043b\u044c\u043d\u0438\u043a\u043e\u0432, Marylou",
    "Family of Warner, Robert",
    "Family of Warner, Robert Douglas and Norton, Christina",
    "Family of Warner, Robert Eugene and Barber, Mary Elizabeth",
    "Family of Warner, Stephen Paul and \u0425\u0443\u0434\u043e\u043d\u043e\u0433\u043e\u0432, Patricia",
    "Family of Warner, Stuart Bogarte and Richards, Diana",
    "Family of Warner, Thomas and Black, Jane",
    "Family of Warner, Thomas Frederick and Carter, Debra J.",
    "Family of Warner, Warren W. and Ball, Abigail",
    "Family of Waters and Webb, Mary",
    "Family of Waters, Cecil and \u0424\u043e\u043c\u0438\u043d, Grace",
    "Family of Waters, Cecil Glenn and Hubbard, Donna",
    "Family of Waters, John and Webb, Mary",
    "Family of Waters, William and Neal, Matilda",
    "Family of Watkins, Bruce Edward and Warner, Mary Christine",
    "Family of Watson, Alvin E. and Warner, Beverly Ann",
    "Family of Weaver, Steven Matthew and Warner, JenniferMae(Ganoe)",
    "Family of Webb, Alex and \u041c\u0430\u043a\u0430\u0440\u043e\u0432, Nancy",
    "Family of Webb, Alexander and Delgado, Mary Ann",
    "Family of Webb, Andrew and Webb, Margaret Margarite?",
    "Family of Webb, Elias and Gibbs, Nancy",
    "Family of Webb, Ernest Arlington",
    "Family of Webb, Francis Irvin and Todd, Louella Jane",
    "Family of Webb, James Marshall and Ballard, Judith Ellen",
    "Family of Webb, John Raymond and Ford, Lorinda Catherine",
    "Family of Webb, Joseph LeRoy and Boucher, Bridget",
    "Family of Webb, Lewis I. and \u0417\u0430\u0439\u0446\u0435\u0432, Ruth L.",
    "Family of Webb, Livingstone Martin and Blanco, Lucinda Catherine",
    "Family of Webb, William Herman",
    "Family of Webb, William John and Wagner, Martha Ann",
    "Family of Webster, Conrad and Castillo, Margaretha",
    "Family of Webster, Johanne(John) and Saunders, Ursula",
    "Family of Welch, Christopher Paul and Hayes, LeAnn",
    "Family of Welch, Irwin Arthur and Page, Eleanor Irene",
    "Family of Welch, Michael and Osborne, Anita June",
    "Family of Welch, Paul Allen and Cruz, Linda Helen",
    "Family of Welch, Russell Eugene and Norton, Dorothy",
    "Family of Welch, Russell Eugene and Walsh, Penelope",
    "Family of West, Ronald David and Cruz, Melinda Lou",
    "Family of Wheeler, Don and \u041b\u043e\u043f\u0430\u0442\u0438\u043d, Carmen Diana",
    "Family of Wheeler, Jacob Earl and \u041b\u043e\u043f\u0430\u0442\u0438\u043d, Carmen Diana",
    "Family of White and Reed, Mary Ann",
    "Family of Williams, Thomas Jr. and Jim\u00e9nez, Elizabeth",
    "Family of Willis, Corey and Poirier, Janelle Marie",
    "Family of Wilson, Douglas and Cruz, Marsha Ann",
    "Family of Wise, Thomas and Ramos, Mary",
    "Family of W\u00f3jcik, Arnold and Garner, Helen Bernice",
    "Family of Wong and Page, Mildred",
    "Family of Wood, Peter and Gibbs, Lucy",
    "Family of Woods, James and \u0417\u044b\u0440\u044f\u043d\u043e\u0432, Mary",
    "Family of Wo\u017aniak, Thomas and Page, Debra Dale",
    "Family of Young, Mr. and Waters, Edith",
    "Family of \u0394\u03b5\u03bb\u03b7\u03c0\u03ad\u03c4\u03c1\u03bf\u03c5, \u0391\u03b3\u03b1\u03bc\u03ad\u03bc\u03bd\u03c9\u03bd and \u0399\u03c9\u03ac\u03bd\u03bd\u03bf\u03c5, \u0395\u03c5\u03c4\u03ad\u03c1\u03c0\u03b7",
    "Family of \u0394\u03b5\u03bb\u03b7\u03c0\u03ad\u03c4\u03c1\u03bf\u03c5, \u0399\u03ac\u03c3\u03c9\u03bd and \u0391\u03bd\u03b1\u03b3\u03bd\u03c9\u03c3\u03c4\u03bf\u03c0\u03bf\u03cd\u03bb\u03bf\u03c5, \u0392\u03b5\u03bd\u03b5\u03c4\u03af\u03b1",
    "Family of \u0399\u03c9\u03ac\u03bd\u03bd\u03bf\u03c5, \u0395\u03c0\u03b1\u03bc\u03b5\u03b9\u03bd\u03ce\u03bd\u03b4\u03b1\u03c2 and \u039a\u03b1\u03bb\u03ad\u03c1\u03b3\u03b7, \u0399\u03bf\u03c5\u03bb\u03af\u03b1",
    "Family of \u0410\u043b\u0435\u043a\u0441\u0430\u043d\u0434\u0440\u043e\u0432, Johann Adam and Beaulieu, Anna Margaretha",
    "Family of \u0410\u043b\u0435\u043a\u0441\u0435\u0435\u0432, Jacob and Benson, Mary",
    "Family of \u0410\u043d\u0434\u0440\u0435\u0435\u0432, William and Douglas, Susan",
    "Family of \u0411\u0435\u043b\u043e\u0443\u0441\u043e\u0432, Jacob and Su\u00e1rez, Marie",
    "Family of \u0411\u0435\u043b\u043e\u0443\u0441\u043e\u0432, Johannas Jacob and Reid, Anna Catherina",
    "Family of \u0411\u0435\u043b\u044f\u0435\u0432 and Reed, Peggy",
    "Family of \u0411\u043e\u0433\u0434\u0430\u043d\u043e\u0432, Dr. Brent and Cruz, Ann Lynn",
    "Family of \u0411\u043e\u0440\u0438\u0441\u043e\u0432 and Boyd, Carmen Alberta",
    "Family of \u0411\u044b\u043a\u043e\u0432, Charles and Girard, Margaret",
    "Family of \u0411\u044b\u043a\u043e\u0432, Herod and Parent, Polly",
    "Family of \u0411\u044b\u043a\u043e\u0432, Samuel and Larsen, Nelly",
    "Family of \u0412\u043b\u0430\u0441\u043e\u0432, John and Floyd, Martha Frances \"Fannie\"",
    "Family of \u0412\u043e\u0440\u043e\u0431\u044c\u0435\u0432, Rev. Samuel",
    "Family of \u0413\u0435\u0440\u0430\u0441\u0438\u043c\u043e\u0432, John and Garrett, Doris Mae",
    "Family of \u0413\u043e\u043d\u0447\u0430\u0440\u043e\u0432, Thomas",
    "Family of \u0413\u043e\u0440\u0431\u0443\u043d\u043e\u0432, Matt and Garner, Cecilia",
    "Family of \u0414\u0430\u0432\u044b\u0434\u043e\u0432 and Ball, Jane",
    "Family of \u0414\u0430\u043d\u0438\u043b\u043e\u0432, Darrell Edwin and Ross, Evelyn Almazon",
    "Family of \u0414\u0430\u043d\u0438\u043b\u043e\u0432, Earl William and Lessard, Dorothy Louise",
    "Family of \u0414\u043c\u0438\u0442\u0440\u0438\u0435\u0432, Alexander Carroll Sr. and Woods, Mary Polly",
    "Family of \u0414\u043c\u0438\u0442\u0440\u0438\u0435\u0432, Charles Sr. and Lapointe, Lucy aka Sarah",
    "Family of \u0414\u043c\u0438\u0442\u0440\u0438\u0435\u0432, Moses Aaron and Reynolds, Mary Jane",
    "Family of \u0414\u043c\u0438\u0442\u0440\u0438\u0435\u0432, Travis and Payne, Elizabeth",
    "Family of \u0414\u043c\u0438\u0442\u0440\u0438\u0435\u0432, William and Page, Sarah",
    "Family of \u0414\u043c\u0438\u0442\u0440\u0438\u0435\u0432, William and Wood, Polly",
    "Family of \u0415\u0433\u043e\u0440\u043e\u0432, Dr. Charles J. and Page, Edith Mae",
    "Family of \u0416\u0443\u043a\u043e\u0432, Curtis Dale and Gordon, Heather Kathleen",
    "Family of \u0416\u0443\u043a\u043e\u0432, David and Russell, Janet Gail",
    "Family of \u0417\u043b\u043e\u0431\u0438\u043d, Col. Joseph and Rice, Virginia Margaret",
    "Family of \u0417\u043b\u043e\u0431\u0438\u043d, John",
    "Family of \u0417\u043b\u043e\u0431\u0438\u043d, Joseph Jr. and Adkins, Martha",
    "Family of \u0417\u044b\u043a\u043e\u0432, John and Hopkins, Mary Eve",
    "Family of \u0418\u043b\u044c\u0438\u043d, Gary and Webb, Marilyn Jean",
    "Family of \u041a\u0430\u0440\u043f\u043e\u0432, Damian and Hansen, Irene",
    "Family of \u041a\u0438\u0441\u0435\u043b\u0435\u0432, Dennis John and Warner, Nancy Elizabeth",
    "Family of \u041a\u043e\u0437\u043b\u043e\u0432, Samuel C. and Pena, Julia",
    "Family of \u041b\u0435\u0431\u0435\u0434\u0435\u0432, Trustum and Warner, Johanna",
    "Family of \u041b\u043e\u0433\u0438\u043d\u043e\u0432, Guy and Kristensen, Margaret Agnes\"Maudy\"",
    "Family of \u041b\u043e\u043f\u0430\u0442\u0438\u043d, Raymond A. and Garrett, Carmen Eloise",
    "Family of \u041c\u0430\u043a\u0430\u0440\u043e\u0432, Joseph",
    "Family of \u041c\u0430\u043a\u0441\u0438\u043c\u043e\u0432 and Allen, Abigail",
    "Family of \u041c\u0430\u043a\u0441\u0438\u043c\u043e\u0432, George and \u0416\u0443\u043a\u043e\u0432, Annabell Gordon",
    "Family of \u041c\u0430\u043a\u0441\u0438\u043c\u043e\u0432, Rodney Herman and Cruz, Janis Marlene",
    "Family of \u041c\u0430\u0440\u0442\u044b\u043d\u043e\u0432 and Reed, Jane",
    "Family of \u041d\u0438\u043a\u043e\u043b\u0430\u0435\u0432, Veltin",
    "Family of \u041d\u043e\u0432\u0438\u043a\u043e\u0432, Thomas and Allen, Rachel",
    "Family of \u041f\u0430\u0432\u043b\u043e\u0432, Reuben and Douglas, Lucinda J.",
    "Family of \u041f\u043e\u043d\u043e\u043c\u0430\u0440\u0435\u0432, Ralph and Rodr\u00edguez, Agatha",
    "Family of \u041f\u043e\u0442\u044b\u043b\u0438\u0446\u0438\u043d, Edward and B\u00e9langer, Linda Ellen",
    "Family of \u0420\u043e\u043c\u0430\u043d\u043e\u0432, John and Moreno, Delilah",
    "Family of \u0421\u0435\u0440\u0433\u0435\u0435\u0432, Dennis and Garner, Kathryn Mary",
    "Family of \u0421\u043c\u0438\u0440\u043d\u043e\u0432, Eudo and Rios, Agnes",
    "Family of \u0421\u043c\u0438\u0440\u043d\u043e\u0432, Ribald and Gray, Beatrix",
    "Family of \u0421\u043e\u0440\u043e\u043a\u0438\u043d, Robert and \u0421\u043e\u0440\u043e\u043a\u0438\u043d, Candy",
    "Family of \u0422\u0430\u0440\u0430\u0441\u043e\u0432, Simon and Todd, Flora Belle",
    "Family of \u0422\u0438\u0445\u043e\u043d\u043e\u0432, Miles? and Smith, Anastasia?",
    "Family of \u0422\u0438\u0445\u043e\u043d\u043e\u0432, Moses and Holt, Bridget",
    "Family of \u0424\u0435\u0434\u043e\u0440\u043e\u0432 and Reed, Bridget",
    "Family of \u0424\u0435\u0434\u043e\u0440\u043e\u0432, Patrick",
    "Family of \u0427\u0435\u0440\u043a\u0430\u0448\u0438\u043d, Thomas and Jankowski, Margaret Jane \"Maggie\"",
    "Family of \u0428\u0435\u0441\u0442\u0430\u043a\u043e\u0432, George and Daniels, Phoebe",
    "Family of \u042f\u043a\u043e\u0432\u043b\u0435\u0432, George and Garner, Jennie S.",
    "Family of \u4e2d\u6751, Thomas and Jim\u00e9nez, Polly Mary",
    "Family of \u5c0f\u6797, Mr. and Waters, Nellie",
    "Family of \u5c71\u672c, Antoine Desaure Perronett and \u0421\u043e\u043a\u043e\u043b\u043e\u0432, Louise",
    "Family of \u5c71\u672c, Gabriel Gustave",
    "Family of \u658e\u85e4, Zariakius Cyriacus and Bishop, Anna Barbara",
    "Family of \u9234\u6728, Allen and Mar\u00edn, Alice",
    "Family of \u9234\u6728, Robert B. and Blanco, Mary F."
]