// This file is generated

I_death_place_15 = [
    "",
    "",
    "Sevier Co, TN, Richardson Cove Cem. [P9035] [P10894]",
    "",
    "",
    "Holders Grove Cem [P9322] [P37105]",
    "",
    "",
    "",
    "",
    "Worthington, MN [P20520] [P39152]",
    "",
    "Ottawa, IL [P20143] [P38772]",
    "Spearfish, SD [P20736] [P39371]",
    "Ottawa, IL [P20143] [P38772]",
    "Ottawa, IL [P20143] [P38772]",
    "Midland, MI [P20392] [P39024]",
    "",
    "Worthington, MN [P20520] [P39152]",
    "",
    "",
    "",
    "",
    "Worthington, MN [P20520] [P39152]",
    "Hutchinson, KS [P20302] [P38934]",
    "Lewisburg, PA [P20573] [P39207]",
    "",
    "Ottawa, IL [P20143] [P38772]",
    "",
    "Dustin, OK [P9935] [P22332]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Fremont, NE [P1487] [P1487]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Milledgeville, GA [P1560] [P1560]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502] [P51939]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Oakland, CA [P51053]",
    "",
    "Columbus, IN [P59778]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Columbus, IN [P59778]",
    "",
    "Baraboo, WI [P59557]",
    "",
    "Paragould, AR [P61589]",
    "",
    "Gary, IN [P59200]",
    "",
    "Hays, KS [P59136]",
    "",
    "Twin Falls, ID [P59897]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Killeen, TX [P59161]",
    "",
    "",
    "Columbus, IN [P59778]",
    "Cedar City, UT [P59129]",
    "",
    "",
    "Shawnee, OK [P59766]",
    "",
    "Twin Falls, ID [P59897]",
    "Twin Falls, ID [P59897]",
    "",
    "Ottawa, IL [P59236]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Astoria, OR [P59155]",
    "",
    "",
    "Alice, TX [P59222]",
    "",
    "",
    "",
    "Marshalltown, IA [P61595]",
    "Portsmouth, OH [P59626]",
    "",
    "",
    "",
    "",
    "",
    "Battle Creek, MI [P59750]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Beckley, WV",
    "",
    "",
    "",
    "",
    "Ottawa, IL [P59236]",
    "",
    "Washington Co, NC [P59976]",
    "",
    "",
    "",
    "Ottawa, IL [P59236]",
    "",
    "",
    "Buckhorn Twsp, Harnett Co, NC [P10115] [P50568]",
    "",
    "",
    "",
    "",
    "Haywood, NC [P9949] [P52430]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Caswell Co, NC [P8849] [P51220]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Marshall, MN",
    "Savannah, GA",
    "Merced, CA",
    "",
    "",
    "",
    "Berkhamsted [P3674] [P3674]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P2618] [P41311]",
    "Harnett Co, NC [P2618] [P41311]",
    "",
    "Cumberland UnionBaptChurCem, Harnett Co, NC [P2787] [P41474]",
    "",
    "",
    "",
    "City Cem, Sanford, NC [P2847] [P41534]",
    "",
    "",
    "",
    "Riverside, CA [P1363] [P8108]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Helena, MT [P20154] [P38783]",
    "Myrtle Beach, SC [P20766] [P39402]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cleveland Co, NC [P3081] [P3081]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Nr Cassel,France",
    "#6 Via Dilluvio, Borgetto, Sicily, Italy",
    "",
    "",
    "",
    "Sevier Co, TN, White Oak Flats Cem.",
    "",
    "",
    "",
    "",
    "",
    "",
    "Freehold, NJ [P10184]",
    "Rutherford, NJ [P10181]",
    "",
    "NY City, NY [P10198]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Wake Co, NC [P9535] [P21932] [P40602]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Maybe Wake Co., NC [P10123] [P18866] [P37495]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Portsmouth, VA [P2803] [P41490]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Chalk Level, Harnett Co, NC [P19501] [P38130]",
    "Harnett Co, NC [P2618] [P41311]",
    "Sevier Co, TN, Mt. Pleasant Cem., Jones Cove",
    "Sevier Co, TN, Shiloh Cem.",
    "Knoxville, TN [P20612] [P39246]",
    "Wethersfield, Hartford, CT",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Golf Course Cem., Pigeon Forge [P1784]",
    "",
    "Sevier Co, TN [P8763]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Died in North Carolina [P1815]",
    "",
    "",
    "",
    "",
    "Anderson Co, TN; buried Sevier Co, TN, Shiloh Cem. [P1717]",
    "Whole career 1969- at DOE Y-12 Plant in Oak Ridge, TN [P1707]",
    "",
    "McCreary Co, KY, Bethel Baptist Cem. [P1743]",
    "Sevier Co, TN, Shiloh Cem. [P1732]",
    "",
    "",
    "",
    "",
    "",
    "Whitley Co, KY, Wolf Creek Cem. [P8769]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "South Carolina [P1836]",
    "Whitley Co, KY [P8765]",
    "Whitley Co, KY, Wolf Creek Cem. [P8769]",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P1732]",
    "",
    "McCreary Co, KY, Davenport-Ball Cemetery [P9433]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Washington Co, NC [P1772]",
    "Whitley Co, KY, Wolf Creek Cem. [P8769]",
    "Tyrrell Co, NC [P8772]",
    "",
    "",
    "",
    "",
    "Washington Co, NC [P1772]",
    "died August ?, 1843 (indistinct), and [P8872]",
    "",
    "Colonial Militia, 1754 [P8776]",
    "",
    "",
    "",
    "Sevier Co, TN [P8763]",
    "",
    "See Notes. [P1722]",
    "Sevier Co, TN, Headrick Cem. [P1816]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN [P8763]",
    "Sevier Co, TN, Shiloh Cem. [P1732]",
    "",
    "",
    "",
    "Sevier Co, TN, Galilee Cem., Seymour [P1818]",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P1732]",
    "Blount Co, TN, Sherwood Memorial Cem. [P1733]",
    "",
    "McCreary Co, KY [P1752]",
    "Family lived Lantana, FL [P8764]",
    "Whitley Co, KY, Jellico Baptist Creek Cem. [P1807]",
    "Another Mary (?) Davenport married Zebedee Hassell, 3/15/1770 [P1826]",
    "",
    "Washington Co, NC [P1772]",
    "",
    "",
    "",
    "",
    "",
    "Code: 0-10,   10-16,   16-26,   26-45,   45-up [P9221]",
    "Whitley Co, KY, Jellico Creek Baptist Cem. [P1802]",
    "",
    "",
    "Probably Washington Co, NC [P9226]",
    "Sevier Co, TN, Shiloh Cem. [P1732]",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P1732]",
    "",
    "",
    "",
    "Sevier Co, TN, Mattox Cem. [P9195]",
    "McCreary Co, KY [P1752]",
    "",
    "",
    "",
    "Tyrrell Co, NC [P8772]",
    "",
    "",
    "",
    "Sevier C0, TN [P1796]",
    "",
    "",
    "",
    "Kansas [P1787]",
    "",
    "",
    "",
    "Pigeon Forge, Sevier Co, TN, Shiloh Cem. [P1729]",
    "",
    "",
    "",
    "Whitley Co, KY, Wolf Creek Cem. [P8769]",
    "Sevier Co, TN, Shiloh Cem. [P1732]",
    "McCreary Co, KY, Bethel Baptist Cem. [P1743]",
    "",
    "Tyrrell Co, NC [P8772]",
    "Pigeon Forge, Sevier Co, TN, Shiloh Cem. [P1729]",
    "",
    "Another, older Stephen m. Elizabeth Alexander, 1778 [P9230]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Whitley Co, KY, Wolf Creek Cem. [P8769]",
    "",
    "Knox Co, TN, Galilee Cem, Seymour [P1809]",
    "Washington Co, NC [P1772]",
    "",
    "",
    "",
    "Little Rock, Arkansas [P9435]",
    "Whitley Co, KY, Speculate Wolf Creek Cem. [P1761]",
    "",
    "Sevier C0, TN [P1796]",
    "",
    "Borgetto, Sicily, Italy [P9600]",
    "Living in April 1994 [P10217]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Keene, NH [P1392]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Worthington, MN [P1385] [P61476]",
    "",
    "New Hill, , , NC [P9788] [P37150]",
    "Shallow Well, Lee Co, NC [P9999] [P11858]",
    "",
    "Brickhaven, NC [P9857] [P11716]",
    "Chatham Co, NC [P9508] [P11367]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Whitley Co, KY, Bethel Baptist Cem [P19211] [P37840]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Greenville, SC [P20046] [P38675]",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Shults-Whaley Cem., Hwy 321 [P19415] [P38044]",
    "Sevier C0, TN, Spurgeon Cem [P2442] [P2442]",
    "Sevier C0, TN, Webbs Creek Cem [P2530] [P41254]",
    "",
    "",
    "",
    "Huskey Cem [P2437] [P41209]",
    "",
    "Sevier CO, TN, Headrick Cem [P19432] [P38061]",
    "",
    "",
    "",
    "Los Angeles, CA [P20216] [P38847]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Evanston, WY [P20105] [P38734]",
    "",
    "Havre, MT [P20761] [P39397]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Memorial Cem, Hwy 401 S., Raleigh, NC [P3118] [P3118]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Mattox Cem. [P2311] [P2311]",
    "",
    "",
    "",
    "Cocke Co, TN, Rocky Creek Valentine Cem [P2533] [P2533]",
    "",
    "",
    "",
    "",
    "",
    "Pittsburg, PA [P19516] [P38145]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cameron, Lee County, NC [P3441] [P3441]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Rex Hospital, , Raleigh, NC [P2590] [P41285]",
    "Cocke Co, TN, Waters-Large Cem [P19422] [P38051]",
    "",
    "",
    "Sevier Co, TN, Proffitt Cem. [P2157] [P40222]",
    "Jackson Co, AL, McMahan Cem., McMahan Cove [P1907] [P1907]",
    "Sevier Co, TN, McMahan Cem., Pearl Valley [P1904] [P1904]",
    "Sevier Co, TN, Old McMahan Cem. [P19230] [P37859]",
    "Sevier Co, TN, Richardson Cove Cem. [P19226] [P37855]",
    "Cocke Co, TN [P1930] [P1930]",
    "",
    "",
    "Sevier Co, TN, Church in Forks Baptist Cem. [P19224] [P37853]",
    "Sevier Co, TN, Church in Forks Baptist Cem. [P19224] [P37853]",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Richardson Cove Cem. [P19226] [P37855]",
    "Sevier Co, TN, McMahan Cem. [P19398] [P38027]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Webbs Creek Cem. [P19417] [P38046]",
    "",
    "Sevier Co, TN [P1726] [P1726]",
    "Sevier Co, TN, Emerts Cove Cem. [P20944] [P39580]",
    "",
    "",
    "",
    "Sevier Co, TN [P1726] [P1726]",
    "",
    "Yancy Co, NC [P19238] [P37867]",
    "",
    "",
    "",
    "Jackson Co, TN [P2161] [P40266]",
    "Sevier Co, TN, Howard-Campbell Cem. [P19231] [P37860]",
    "",
    "Cocke Co, TN [P1930] [P1930]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Tenn. Technological Univ.: MS Edu. Psychology 1972 [P20813] [P39449]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Truelove Cem, Pascal Truelove Plc, Harnett Co, NC [P2632]",
    "",
    "",
    "Stockholm,Sweden [P0094]",
    "",
    "Barking Abbey,Essex,England [P0485]",
    "",
    "",
    "Peterborough,Castle [P0420]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Evesham [P0353]",
    "",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P1732] [P61823]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Newton, IA [P1061] [P1061] [P36996]",
    "",
    "",
    "",
    "",
    "Newton, IA [P1061] [P1061] [P36996]",
    "",
    "",
    "",
    "",
    "",
    "Wake Co?, NC [P10022]",
    "",
    "",
    "Johnston Memorial Hospital, Johnston County, NC [P10113]",
    "Durham Co, Durham, NC [P9907]",
    "Johnston County, NC [P10314]",
    "",
    "",
    "",
    "Harnett  Co, NC [P9507]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Unknown [P9716]",
    "",
    "",
    "",
    "Mother was full-blooded Indian from Arkansas [P9189] [P21586]",
    "",
    "",
    "",
    "",
    "Houston, AR [P10328]",
    "",
    "Jackson Parish, LA [P10174] [P50633]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier C0, TN, Burchfield Memorial Cem [P9320] [P21717]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Union Co, GA [P10284] [P10284]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Duncan, Harnett Co, NC [P2849] [P41536]",
    "",
    "",
    "Fuquay Varina, Wake Co, NC [P3073] [P41755]",
    "",
    "",
    "",
    "",
    "",
    "Chatham Co, NC [P9508] [P11367]",
    "Chatham Co, NC [P9508] [P11367]",
    "Fayetteville, Cumberland Co, NC [P9779] [P11638]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Fowler Cemetery [P8924] [P21321]",
    "",
    "",
    "Plainview, TX [P1183] [P7930]",
    "Caguas, PR [P1368] [P8113]",
    "",
    "",
    "",
    "",
    "Wake County, NC [P9594] [P21991] [P56748]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Rolla, MO [P1093]",
    "",
    "London, KY [P1344]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Ridings-Williams Cem. [P43557]",
    "",
    "",
    "",
    "Sevier Co, TN, Hendron's Chapel Cem. [P43741]",
    "Had 3 sons [P43740]",
    "Killed in streetcar collision, Knoxville, 1912 [P2026]",
    "",
    "",
    "",
    "Sevier Co, TN, Hendron's Chapel Cem. [P43741]",
    "",
    "",
    "Sevier Co, TN, Walnut Grove Cem. [P42281]",
    "Sevier Co, TN, Galilee Baptist Cem. [P43738]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett  Co, NC [P9507]",
    "",
    "",
    "Wethersfield, Hartford, Ct. [P10161]",
    "",
    "Wethersfield, Hartford, Ct. [P10161]",
    "",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P1732] [P61823]",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P1732] [P61823]",
    "Sevier Co, TN, Shiloh Cem. [P1732] [P61823]",
    "Sevier Co, TN, McMahan Cem. [P9252] [P51664]",
    "",
    "Sevier Co, TN, Shiloh Cem. [P1732] [P61823]",
    "",
    "Sevier Co, TN, Trundle Family Cem. [P8798] [P51164]",
    "Sevier Co, TN, McMahan Cem. [P9252] [P51664]",
    "Sevier Co, TN, Shiloh Cem. [P1732] [P61823]",
    "Sevier Co, TN, Trundle Family Cem. [P8798] [P51164]",
    "Virginia [P1842] [P61932]",
    "Sevier Co, TN, Shiloh Cem. [P1732] [P61823]",
    "Roane Co, TN, killed by Indians near Crab Orchard [P8857] [P51229]",
    "Sevier Co, TN, Shiloh Cem. [P1732] [P61823]",
    "Marshall, TX [P20536] [P39169]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Ridings-Williams Cem. [P8777] [P21174] [P55849]",
    "",
    "Code:  5-10-15-20-30-40 [P9155] [P21552] [P56265]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier CO, TN, Williams-Ridings Cem [P9104]",
    "Holly SprsBptChur, Harnett Co, NC [P9556]",
    "",
    "",
    "",
    "",
    "Berea, Marion Co, TX [P10107]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Tennessee [P1808]",
    "",
    "",
    "Summerville, GA [P1097]",
    "Harnett Co, NC [P9502]",
    "",
    "",
    "",
    "Springfield, MA [P1444] [P61535]",
    "",
    "",
    "",
    "Sevier C0, TN, Jos. &amp;amp;amp;amp; Salina Shults Cem [P9334] [P51754]",
    "",
    "",
    "Sevier C0, TN, Williams Cem, Jones Cove [P9418] [P51846]",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Rome, Sumner, KS [P10102]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Washington Co, VA [P9440]",
    "",
    "Cocke Co, TN, Shults Cem., Cosby [P9151]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "NY City, NY [P3314] [P41799]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN [P8763] [P21160]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Ottawa, IL [P0978] [P0978]",
    "Oshkosh, WI [P0951] [P0951]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Worthington, MN [P1385] [P8130]",
    "",
    "",
    "Dublin, GA [P0898] [P42804]",
    "Ottawa, IL [P0978] [P42879]",
    "Ogden, UT [P1554] [P43287]",
    "",
    "Lake Charles, LA [P1373] [P43174]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Van Wert, OH [P1565] [P43298]",
    "",
    "",
    "",
    "",
    "",
    "Westminster,Palace,London,England [P0314] [P0314] [P0314]",
    "",
    "",
    "London,England [P0028] [P0028] [P0028]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "NJ [P9584] [P11443]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cadillac, MI [P20724] [P39359]",
    "Kapaa, HI [P20720] [P39355]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC",
    "",
    "Wake Co, NC",
    "",
    "",
    "Harnett Co, NC",
    "Cokesbury, Harnett Co, NC",
    "",
    "",
    "Cokesbury, Harnett Co, NC",
    "",
    "",
    "Depot Street, Fuquay Springs, NC",
    "",
    "",
    "Harnett Co, NC",
    "",
    "Harnett Co, NC",
    "",
    "",
    "",
    "Home, Cokesbury Road, Harnett Co, NC",
    "",
    "",
    "",
    "",
    "Sevier Co, TN",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Elizabeth City, NC",
    "Safford, AZ",
    "Lake County, IL",
    "",
    "Red Bluff, CA",
    "Poplar Bluff, MO",
    "",
    "Lake County, IL",
    "Chillicothe, OH",
    "",
    "Poplar Bluff, MO",
    "Poplar Bluff, MO",
    "",
    "",
    "Southington, CT",
    "",
    "Southerning, CT",
    "New Bern?, NC",
    "",
    "John Brown Plc, , Harnett Co, NC",
    "Clayton, Johnston Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "NC",
    "",
    "Moncure Methodist Cem, Moncure, NC",
    "",
    "Wethersfield, Hartford, CT",
    "",
    "Wethersfield, Hartford, CT",
    "",
    "",
    "",
    "",
    "",
    "NC",
    "",
    "",
    "Near Chalk Level, Northern Harnett Co, NC",
    "",
    "",
    "",
    "",
    "Newington, CT",
    "",
    "",
    "Apex, Wake Co, NC",
    "",
    "Haywood, , Chatham Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Jackson, MI [P1310]",
    "Toledo, OH [P0976]",
    "",
    "Redding, CA [P1249]",
    "",
    "",
    "",
    "",
    "Coldwater, MI [P1109]",
    "McAlester, OK [P1112]",
    "",
    "",
    "",
    "",
    "Kingsport, TN [P59734]",
    "",
    "Sioux Falls, SD [P59693]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Worcester, MA [P61500]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Buncombe Co, NC [P10279] [P19022] [P37651]",
    "Williston, ND [P1700] [P1700] [P1700]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Lumberton, NC [P0908] [P0908]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Bydgoszcz, Poland",
    "",
    "",
    "",
    "",
    "",
    "",
    "NYC?, NY [P3326] [P41802]",
    "",
    "",
    "",
    "",
    "New York City, NY [P2892] [P41579]",
    "",
    "TN [P19554] [P38183]",
    "",
    "",
    "",
    "See Note [P3295] [P41796]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502] [P11361]",
    "Andrews, TX [P59358]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Lutesville, MO, Lincoln Cem. [P19401] [P38030]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Wake County, NC [P9594] [P52040]",
    "",
    "",
    "Duncan Bpt, ChurCem, Harnett Co, NC [P3207] [P3207]",
    "Monroe, LA [P20674] [P39308]",
    "",
    "",
    "",
    "",
    "",
    "Marquette, MI [P1228] [P1228] [P52528]",
    "",
    "",
    "",
    "",
    "",
    "Sanford, NC [P1481] [P1481] [P52781]",
    "Guaynabo, PR [P1312] [P1312] [P52612]",
    "Effingham, IL [P1651] [P1651] [P52951]",
    "Marquette, MI [P1228] [P1228] [P52528]",
    "",
    "New Ulm, MN [P1410] [P1410] [P52710]",
    "",
    "",
    "Kendallville, IN [P1501] [P1501] [P52801]",
    "Marquette, MI [P1228] [P1228] [P52528]",
    "",
    "",
    "New Ulm, MN [P1410] [P1410] [P52710]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Pigeon Forge Methodist Cem [P9211] [P11070]",
    "Sevier Co, TN, Methodist Cem., Pigeon forge [P9024] [P10883]",
    "",
    "",
    "Sevier Co, TN, Alderbranch Cem. [P9111] [P37072]",
    "Sevier Co, TN, Emerts Cove Cem. [P1863] [P43588]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cosby, TN, Holders Grove Cem. [P9132] [P37077]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Middle Creek Methodist Cem. [P43706]",
    "Sevier Co, TN [P43458]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Bogart, Ga [P44132]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Richmond Co, NC [P10109] [P10109]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Frederick Co, MD",
    "",
    "",
    "",
    "",
    "Sevier Co, TN",
    "Frederick Co, MD",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Banner Cem.",
    "",
    "",
    "Sevier Co, TN, Old Roberts Cem., Richardson's Cove",
    "",
    "",
    "",
    "Sevier Co, TN, Middle Creek Methodist Cem.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Passaic, NJ [P44652]",
    "Poland [P44669]",
    "Shelby, NC [P1154] [P1154]",
    "",
    "",
    "",
    "Palatka, FL [P42066]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Hot Springs, AR [P1295] [P1295]",
    "",
    "",
    "",
    "Norfolk, NE [P1002] [P1002]",
    "Syracuse, NY [P1265] [P1265]",
    "Orlando, FL [P1129] [P1129]",
    "",
    "Olean, NY [P1056] [P1056]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Emerts Cove Cem. [P20944]",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Emerts Cove Cem. [P20944]",
    "",
    "Sevier Co, TN, Emerts Cove Cem. [P20944]",
    "Carter Co, TN [P2526]",
    "Sullivan Co, TN [P19465]",
    "Washington Co, MD [P2524]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Burks Co, PA [P1879]",
    "",
    "Sylacauga, AL [P20159] [P54732]",
    "",
    "Sevier Co, TN, Emerts Cove Cem. [P42264]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Greensboro, NC [P1694] [P61785]",
    "",
    "Greensboro, NC [P1694] [P61785]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Greensboro, NC [P1694] [P61785]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502] [P51939]",
    "NC [P1749] [P61840]",
    "",
    "",
    "",
    "",
    "#6 Via Dilluvio, Borgetto, Sicily, Italy [P10215] [P10215]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "#6 Via Dilluvio, Borgetto, Sicily, Italy [P10215] [P10215]",
    "Zion, Mercer Co, NJ [P10097] [P10097]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Zion, Mercer Co, NJ [P10097] [P10097]",
    "",
    "Hopewell, NJ [P9601] [P11460]",
    "",
    "",
    "St Alfonsis, Catholic Chur, Hopewell, NJ [P9499] [P11358]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502] [P51939]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Home, Durham, NC [P62698]",
    "",
    "Durham Co, Durham, NC [P62779]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sicily, Italy [P2954] [P41637]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Newport, TN [P1191] [P1191] [P52491]",
    "",
    "",
    "Castle Pelesch,Sinaia,Romania [P0084] [P60314]",
    "Villa Mar y Sol,Estoril,Portugal [P0204] [P60434]",
    "",
    "",
    "Cannes,France [P0203] [P60433]",
    "Sinaia,Romania [P0168] [P60398]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Port of Spain, Trinidad, West Indies [P9690] [P22087] [P56853]",
    "",
    "McColl, SC [P9651] [P22048] [P56810]",
    "",
    "",
    "",
    "Sanford, Lee Co, NC [P10149] [P18892] [P53339]",
    "",
    "",
    "",
    "",
    "",
    "Coamo, PR [P0925] [P0925] [P50366]",
    "",
    "Hospital, Wake Co, NC [P10012] [P18755] [P53188]",
    "",
    "",
    "Lee Co, NC [P9799] [P22196] [P56973]",
    "Vance Co, NC [P9751] [P22148] [P56920]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Brunswick County NC [P10293] [P19036] [P53497]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Raleigh, NC [P9524] [P21921] [P56671]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Ashtabula, OH",
    "",
    "",
    "Norfolk, NE",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Home Plc, , Raleigh, NC [P9581] [P52026]",
    "NC [P1749] [P61840]",
    "Green Lawn, , Fuquay-Varina, NC [P9609] [P52056]",
    "NC [P1749] [P61840]",
    "",
    "",
    "",
    "",
    "Del Rio, TX [P8744] [P51105]",
    "Del Rio, TX [P8744] [P51105]",
    "",
    "",
    "",
    "Unknown [P9716] [P52174]",
    "",
    "",
    "Lee Co, NC [P9799] [P52265]",
    "",
    "Ottawa, IL [P0978] [P61071]",
    "NC [P1749] [P61840]",
    "",
    "NC [P1749] [P61840]",
    "",
    "",
    "",
    "",
    "",
    "Cumberland Co, (Harnett), NC [P9930] [P52409]",
    "",
    "",
    "",
    "Harnett  Co, NC [P9507] [P51944]",
    "",
    "Cameron, NC [P10062] [P50510]",
    "Raeford, NC [P10323] [P50797]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett  Co, NC [P9507] [P51944]",
    "",
    "",
    "",
    "",
    "",
    "Cumberland Co, (Harnett), NC [P9930] [P52409]",
    "",
    "",
    "",
    "",
    "Grainger Co, TN, Shiloh Cem.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Elkhart, IN [P1114]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Wake Co, NC [P9535] [P21932] [P56683]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502] [P21899] [P56646]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, White Oak Flats Cem.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Milwaukee, WI [P59611]",
    "",
    "NC [P59957]",
    "",
    "",
    "",
    "",
    "Shelbyville, TN [P59533]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P2618] [P41311]",
    "",
    "",
    "Cocke Co, TN, Shults Cem., Cosby [P19322] [P37951]",
    "",
    "",
    "",
    "Wethersfield, Hartford, Ct. [P10161] [P18904]",
    "",
    "",
    "Hatfield, Hampshire, Mass. [P10169] [P18912]",
    "",
    "",
    "Essex, England [P10171] [P18914]",
    "Providence, , Rhode Island [P10172] [P18915]",
    "Wethersfield, Hartford, Ct. [P10161] [P18904]",
    "England [P0155] [P0155]",
    "Wethersfield, Hartford, Ct. [P10161] [P18904]",
    "Wethersfield, Hartford, Ct. [P10161] [P18904]",
    "",
    "Hadley, Hampshire, Mass. [P10166] [P18909]",
    "Shalford, Essex, England [P10163] [P18906]",
    "Ct. [P10167] [P18910]",
    "",
    "Colchester, Essex, England [P10160] [P18903]",
    "",
    "",
    "",
    "Sevier Co, TN, Boogertown Cem.",
    "",
    "",
    "",
    "",
    "Madrid, Spain [P10365] [P10365]",
    "",
    "Sandusky, OH [P1302] [P61394]",
    "Visalia, CA [P1471] [P61562]",
    "",
    "",
    "",
    "Manhattan, KS [P20574] [P39208]",
    "Las Cruces, NM [P20663] [P39297]",
    "",
    "",
    "",
    "Ottawa, IL [P0978] [P0978]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Clearlake, CA [P20771] [P39407]",
    "Hutchinson, MN [P20687] [P39322]",
    "",
    "",
    "Spencer, IA [P20353] [P38985]",
    "",
    "",
    "",
    "Kokomo, IN [P20483] [P39115]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Campbellsville, KY [P20753] [P39389]",
    "Harriman, TN [P20329] [P38961]",
    "Campbellsville, KY [P20753] [P39389]",
    "",
    "",
    "",
    "",
    "",
    "Santa Fe, NM [P20194] [P38824]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Towns Co, GA [P3049] [P41731]",
    "",
    "",
    "",
    "Albany, NY [P20571] [P39205]",
    "",
    "",
    "Greensboro, NC [P1694] [P61785]",
    "",
    "Pottsville, PA [P20030] [P38659]",
    "",
    "Pleasant Grove, Rest Home,  Wake Co, NC [P9628] [P22025] [P40700]",
    "",
    "Silver City, NM [P20657] [P39291]",
    "",
    "",
    "",
    "Sevier Co, TN, Alderbranch Cem. [P19289] [P37918]",
    "",
    "",
    "Garden City, KS [P0985] [P0985] [P0985]",
    "Buckhorn Twnsp, Harnett Co, NC [P9617] [P22014] [P40688]",
    "Fayetteville, AR [P20294] [P38926]",
    "Sevier Co, TN [P1726] [P1726]",
    "",
    "Anchorage, AK [P1133] [P1133] [P37121]",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Alder Branch Cem. [P1925] [P1925]",
    "",
    "",
    "",
    "",
    "Fargo, ND [P20082] [P38711]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ",,,Ireland [P19796] [P38425]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "South Hill, Virginia [P9726] [P52185]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cambridge, MA [P20198] [P38828]",
    "",
    "",
    "",
    "Henderson, Vance Co, NC [P3420] [P3420]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Wilmington, OH [P1611] [P1611]",
    "",
    "",
    "Hilo, HI [P1304] [P1304]",
    "Portales, NM [P1083] [P1083]",
    "",
    "",
    "",
    "",
    "Olive Branch Cem, Kipling, Harnett Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Family Graveyard, Harnett Co, NC",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC",
    "",
    "",
    "",
    "",
    "",
    "(Harnett Co), NC",
    "",
    "",
    "Harnett  Co, NC",
    "Cokesbury United, Meth Chur, Harnett Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC",
    "",
    "",
    "Cotten Cem, Harnett Co, NC",
    "",
    "",
    "",
    "",
    "",
    "Dixon, IL [P1408]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Point Pleasant, WV [P1451]",
    "",
    "",
    "",
    "",
    "",
    "Dover, DE [P1075]",
    "Terre Haute, IN [P1357]",
    "",
    "Dixon, IL [P1408]",
    "",
    "",
    "",
    "Bemidji, MN [P8750]",
    "Rome, GA [P1601]",
    "Selinsgrove, PA [P1404]",
    "",
    "Marshall, MN [P1556]",
    "",
    "",
    "",
    "",
    "Tuskegee, AL [P1218]",
    "",
    "",
    "",
    "",
    "",
    "Cookeville, TN [P1641]",
    "",
    "",
    "Whitley Co, KY, Wolf Creek Cem. [P8769]",
    "",
    "",
    "",
    "Cooksville,Near Toronto,Ontario,Canada [P4002]",
    "",
    "",
    "",
    "",
    "",
    "Donegal Bay,County Sligo,Ireland [P3528] [P3528]",
    "Stockholm,Sweden [P3536] [P3536]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Stevens Point, WI [P1507] [P61598]",
    "Anderson, SC",
    "Morgantown, WV [P1144] [P43035]",
    "West Virginia [P8986] [P37033]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P1732] [P43464]",
    "Sevier Co, TN, Shiloh Cem. [P1732] [P43464]",
    "",
    "Sevier Co, TN, Shiloh Cem. [P1732] [P43464]",
    "",
    "",
    "Palatka, FL [P1594] [P1594] [P1594]",
    "Allegan, MI [P4504]",
    "Burlington, IA [P4281]",
    "",
    "",
    "Tower of London,London,England [P0315] [P60545]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Howard View Cem [P9323] [P51742]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Howard-Campbell Cem. [P9042] [P51433]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Greenwich,,England [P19653] [P38282]",
    "",
    "",
    "",
    "Del Rio, TX [P8744] [P51105]",
    "",
    "Newberry, SC [P1219] [P61312]",
    "",
    "Anchorage, AK [P1133] [P61226]",
    "",
    "",
    "",
    "Sevier Co, TN, Fowler Cem. [P8898] [P21295]",
    "Whitley Co, KY, Wolf Creek Cem.",
    "",
    "",
    "",
    "",
    "Thomasville, GA [P1248] [P1248]",
    "Arlington, VA [P1126] [P1126]",
    "",
    "",
    "Springfield, MO [P1277] [P1277]",
    "",
    "Bridgeton, NJ [P1069] [P1069]",
    "",
    "",
    "",
    "",
    "Pecos, TX [P1068] [P1068]",
    "",
    "Raleigh-Cary, NC [P1631] [P1631]",
    "",
    "",
    "Wilmington, OH [P42076]",
    "",
    "",
    "",
    "Ft Worth, TX",
    "Cameron, Lee County, NC [P63167]",
    "",
    "",
    "",
    "Little Rock, AR [P1547] [P1547]",
    "",
    "",
    "",
    "",
    "Fort Walton Beach, FL [P59745]",
    "",
    "",
    "Greenville, SC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Minot, ND [P59811]",
    "Arlington, VA [P51054]",
    "",
    "Sevier Co, TN, Fowler Cem. [P62099]",
    "",
    "Keene, NH [P59630]",
    "",
    "",
    "Sunset Cem., Cleveland Co, Shelby, NC [P58033]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Roswell, NM [P59587]",
    "Poplar Bluff, MO [P59883]",
    "",
    "",
    "",
    "",
    "",
    "Tower of London,Tower Green,London,England [P58745]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P62437]",
    "",
    "",
    "",
    "",
    "Roseboro, NC [P62621]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Rex Hospital, Raleigh, NC [P62590]",
    "",
    "",
    "",
    "Harnett Co, NC [P62437]",
    "Raleigh, NC [P62457]",
    "Cokesbury Meth, Chur Cem, Harnett Co, NC [P62715]",
    "",
    "",
    "",
    "",
    "",
    "Ottawa, IL [P4282]",
    "",
    "",
    "Ottawa, IL [P4282]",
    "",
    "Athens, GA [P4324]",
    "Ottawa, IL [P4282]",
    "",
    "",
    "Pleasant Grove, Rest Home,  Wake Co, NC [P9628]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Montrose, CO",
    "",
    "Grand Forks, ND",
    "",
    "",
    "",
    "Claiborne Co, TN, Sycamore Creek area [P62232]",
    "",
    "",
    "",
    "",
    "Carter Co, TN",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Berlin, NH [P1146] [P43037]",
    "",
    "",
    "",
    "",
    "",
    "Tower of London,Tower Green,London,England [P0349]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cosby, TN, Holders Grove Cem [P9009] [P51396]",
    "",
    "",
    "Sevier Co, TN, Trundle Family Cem. [P8798] [P51164]",
    "",
    "Sevier Co, TN, behind Shults Grove Methodist Cem. [P1857]",
    "Jefferson Co, Tn, Duggan Fam. Burying Ground [P8935]",
    "",
    "",
    "2n Sgt Tenn Mounted Inf, War 1812 [P8787]",
    "Sevier Co, TN, Mt. Pleasant Cem. [P1896]",
    "",
    "Sevier Co, TN, Mt. Pleasant Cem., Jones Cove [P8941]",
    "Sevier Co, TN, Allen Cem. [P8932]",
    "",
    "",
    "Sevier Co, TN, Henry's Crossroads Cem. [P8933]",
    "",
    "Sevier Co, TN [P8763]",
    "Sevier CO, Tennessee [P8957]",
    "",
    "Sevier Co, TN, TN, Mt. Pleasant Cem., Jones Cove [P8942]",
    "Sevier Co, TN, Emerts Cove Cem., unmarked [P9298]",
    "",
    "Knox Co, TN, Thorn Grove Cem. [P8940]",
    "Sevier Co, TN [P8763]",
    "",
    "",
    "",
    "Harnett Co, NC [P9502] [P51939]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Dumas, TX [P1506] [P37330]",
    "",
    "",
    "",
    "",
    "Columbus, MS [P1167]",
    "",
    "",
    "Tyrrell County, North Carolina [P8774]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "San Angelo, TX [P1330]",
    "",
    "",
    "Marquette, MI",
    "San Diego, CA",
    "Morristown, TN",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Shults Grove Cem. [P9137] [P10996]",
    "",
    "",
    "",
    "Macedonia BapChurCem, Harnett Co, NC [P62501]",
    "",
    "Estoril,Portugal [P0385] [P42518]",
    "",
    "Hospital in KY",
    "",
    "",
    "",
    "Cosby, TN, Holders Grove Cem",
    "Tampa, Florida [P10188] [P18931]",
    "",
    "",
    "",
    "Harnett  Co, NC [P19481] [P38110]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sicily, Italy [P9838] [P22235] [P40921]",
    "Monreale, Sicily, Italy [P10248] [P18991] [P37620]",
    "",
    "",
    "",
    "",
    "",
    "Topeka, Shawnee Co, KS [P58379]",
    "",
    "",
    "Sevier Co, TN, White Oak Flats Cem. [P1890] [P43615]",
    "Sevier CO, TN, Shults Cem 11.2 mi from Gatlinburg [P9267] [P51680]",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN [P8763] [P51126]",
    "",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P1732] [P61823]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Parkers Creek, Harnett Co, NC [P9791] [P22188]",
    "",
    "Ottawa, IL [P59236]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "McAlester, OK [P59366]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Emerts Cove Cem. [P20944] [P55596]",
    "St. James Palace,London,England [P0125] [P60355]",
    "",
    "",
    "",
    "",
    "Staunton-Waynesboro, VA [P20308] [P38940]",
    "Ottawa, IL [P20143] [P38772]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co., NC [P9544] [P21941] [P40611]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Owen Co, Jefferson Twsp, IN [P3235] [P58189]",
    "Sterling, IL [P20200] [P54778]",
    "",
    "Living in Knightdale, NC 266-1767 [P3426] [P58380]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Point Pleasant, WV [P1451] [P1451] [P52751]",
    "",
    "",
    "Sevier Co, TN [P8763] [P10622]",
    "",
    "",
    "",
    "",
    "",
    "Mount Vernon, WA [P1001] [P1001]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sunset Cem., Cleveland Co, Shelby, NC [P3079]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Grand Junction, CO [P1626] [P43359]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Duluth, MN [P51075]",
    "",
    "",
    "Blount Co, TN, Clarks Grove Cem. [P62336]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Ottawa, IL [P4282]",
    "",
    "",
    "",
    "Paris,France [P44880]",
    "",
    "",
    "",
    "",
    "Waterloo-Cedar Falls, IA [P20672] [P55297]",
    "Coffeyville, KS [P20235] [P54816]",
    "",
    "",
    "Marshall, MN [P20667] [P55291]",
    "",
    "",
    "",
    "Orlando, FL [P20287] [P54873]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Marshall, MN [P20667] [P55291]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Adjuntas, PR [P4583]",
    "",
    "Ottawa, IL [P4282]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Ottawa, IL [P4282]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Midland, MI [P4538]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Home Plc, Harnett Co, NC [P44051]",
    "",
    "",
    "",
    "",
    "",
    "Troy, AL [P20575] [P55190]",
    "Troy, AL [P20575] [P55190]",
    "Troy, AL [P20575] [P55190]",
    "Troy, AL [P20575] [P55190]",
    "Troy, AL [P20575] [P55190]",
    "Troy, AL [P20575] [P55190]",
    "Troy, AL [P20575] [P55190]",
    "Palm Coast, FL [P4235] [P59189]",
    "Troy, AL [P20575] [P55190]",
    "Troy, AL [P20575] [P55190]",
    "Palm Coast, FL [P4235] [P59189]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Venice,Italy [P0216] [P7100]",
    "",
    "",
    "",
    "",
    "Windsor Castle,Windsor,Berkshire,England [P63258]",
    "Augusta Lodge,Windsor,Berkshire,England [P63289]",
    "Cavendish Square,,London,England [P63323]",
    "The Hague [P63322]",
    "London,England [P63192]",
    "Clarence House,St. James [P63282]",
    "Kensington Palac [P63285]",
    "St. James Palace,,,England [P58574]",
    "",
    "Celle [P63331]",
    "Claremont House,Esher,Surrey,England [P63268]",
    "Furstenhof,Hanover [P63293]",
    "Ludwigsburg [P63280]",
    "",
    "",
    "",
    "Sidmouth,Devon,,England [P63264]",
    "Monaco [P63329]",
    "Gloucester House [P63330]",
    "Frankfurt,-am-Main [P63283]",
    "Kew Palace [P63261]",
    "St. James Palac [P58539]",
    "",
    "",
    "",
    "",
    "",
    "Herrenhausen [P63284]",
    "",
    "Madrid,Spain [P50959]",
    "Rutland House,Arlington St.,London,England [P63277]",
    "Leicester-House,,London,England [P63321]",
    "Leicester House [P58575]",
    "",
    "",
    "",
    "Kensington,Palace,London,England [P63168]",
    "",
    "Osnabruck [P63332]",
    "Kensington,Palace,London,England [P63168]",
    "Windsor Castle,Windsor,Berkshire,England [P63258]",
    "Windsor Castle,Berkshire,England [P63172]",
    "Paris,France [P63267]",
    "",
    "",
    "",
    "London,,,England [P58576]",
    "Christiansborg,Denmark [P63326]",
    "Carlton House [P58509]",
    "",
    "",
    "",
    "Gloucester House,Piccadilly,London,England [P63286]",
    "",
    "Hanau [P63324]",
    "",
    "",
    "Kew Palace [P63261]",
    "",
    "",
    "",
    "Vicarage Place,Kensington [P63287]",
    "",
    "Monbijou Palace,,Berlin,Germany [P63334]",
    "Osborne House,Isle of Wight,England [P63169]",
    "London,,,England [P58576]",
    "Windsor Castle,Windsor,Berkshire,England [P63258]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sicily, Italy [P44339]",
    "",
    "Sevier Co, TN [P8763] [P10622]",
    "",
    "Sevier Co, TN [P8763] [P10622]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sterling, IL [P1038] [P1038]",
    "",
    "",
    "",
    "Andrews, TX [P1104] [P1104]",
    "Whitewater, WI [P1390] [P1390]",
    "",
    "",
    "",
    "",
    "Raleigh, NC [P62457]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Richardson Cove Cem. [P40156]",
    "",
    "",
    "Holders Grove Cem [P43918]",
    "",
    "",
    "",
    "",
    "Worthington, MN [P1385] [P8130]",
    "",
    "Ottawa, IL [P0978] [P42879]",
    "Spearfish, SD [P1630] [P43363]",
    "Ottawa, IL [P0978] [P42879]",
    "Ottawa, IL [P0978] [P42879]",
    "Midland, MI [P1243] [P43130]",
    "",
    "Worthington, MN [P1385] [P8130]",
    "",
    "",
    "",
    "",
    "Worthington, MN [P1385] [P8130]",
    "Hutchinson, KS [P1145] [P43036]",
    "Lewisburg, PA [P1448] [P43185]",
    "",
    "Ottawa, IL [P0978] [P42879]",
    "",
    "Dustin, OK [P3051]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Fremont, NE [P20606]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Milledgeville, GA [P20671]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P62437]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Oakland, CA [P1098] [P1098]",
    "",
    "Columbus, IN [P1553] [P1553]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Columbus, IN [P1553] [P1553]",
    "",
    "Baraboo, WI [P1314] [P1314]",
    "",
    "Paragould, AR [P8746] [P21143]",
    "",
    "Gary, IN [P0942] [P0942]",
    "",
    "Hays, KS [P0878] [P0878]",
    "",
    "Twin Falls, ID [P1678] [P1678]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Killeen, TX [P0903] [P0903]",
    "",
    "",
    "Columbus, IN [P1553] [P1553]",
    "Cedar City, UT [P0871] [P0871]",
    "",
    "",
    "Shawnee, OK [P1539] [P1539]",
    "",
    "Twin Falls, ID [P1678] [P1678]",
    "Twin Falls, ID [P1678] [P1678]",
    "",
    "Ottawa, IL [P0978] [P0978]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Astoria, OR [P0897] [P0897]",
    "",
    "",
    "Alice, TX [P0964] [P0964]",
    "",
    "",
    "",
    "Marshalltown, IA [P8747] [P21144]",
    "Portsmouth, OH [P1388] [P1388]",
    "",
    "",
    "",
    "",
    "",
    "Battle Creek, MI [P1523] [P1523]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Ottawa, IL [P0978] [P0978]",
    "",
    "Washington Co, NC [P1772] [P1772]",
    "",
    "",
    "",
    "Ottawa, IL [P0978] [P0978]",
    "",
    "",
    "Buckhorn Twsp, Harnett Co, NC [P62969]",
    "",
    "",
    "",
    "",
    "Haywood, NC [P62814]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Caswell Co, NC [P62052]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Berkhamsted [P0232] [P7116]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502] [P11361]",
    "Harnett Co, NC [P9502] [P11361]",
    "",
    "Cumberland UnionBaptChurCem, Harnett Co, NC [P9671] [P11530]",
    "",
    "",
    "",
    "City Cem, Sanford, NC [P9731] [P11590]",
    "",
    "",
    "",
    "Riverside, CA [P4648]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Helena, MT [P0990] [P42888]",
    "Myrtle Beach, SC [P1661] [P43394]",
    "",
    "",
    "",
    "",
    "",
    "Cleveland Co, NC [P9965] [P11824]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Freehold, NJ",
    "Rutherford, NJ",
    "",
    "NY City, NY",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Wake Co, NC [P2651] [P41344]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Maybe Wake Co., NC [P3239] [P3239]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Portsmouth, VA [P9687] [P11546]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Chalk Level, Harnett Co, NC [P9645] [P11504]",
    "Harnett Co, NC [P9502] [P11361]",
    "Knoxville, TN [P1494] [P43228]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Golf Course Cem., Pigeon Forge",
    "",
    "Sevier Co, TN",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Died in North Carolina",
    "",
    "",
    "",
    "",
    "Anderson Co, TN; buried Sevier Co, TN, Shiloh Cem.",
    "Whole career 1969- at DOE Y-12 Plant in Oak Ridge, TN",
    "",
    "McCreary Co, KY, Bethel Baptist Cem.",
    "Sevier Co, TN, Shiloh Cem.",
    "",
    "",
    "",
    "",
    "",
    "Whitley Co, KY, Wolf Creek Cem.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "South Carolina",
    "Whitley Co, KY",
    "Whitley Co, KY, Wolf Creek Cem.",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem.",
    "",
    "McCreary Co, KY, Davenport-Ball Cemetery",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Washington Co, NC",
    "Whitley Co, KY, Wolf Creek Cem.",
    "Tyrrell Co, NC",
    "",
    "",
    "",
    "",
    "Washington Co, NC",
    "died August ?, 1843 (indistinct), and",
    "",
    "Colonial Militia, 1754",
    "",
    "",
    "",
    "Sevier Co, TN",
    "",
    "See Notes.",
    "Sevier Co, TN, Headrick Cem.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN",
    "Sevier Co, TN, Shiloh Cem.",
    "",
    "",
    "",
    "Sevier Co, TN, Galilee Cem., Seymour",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem.",
    "Blount Co, TN, Sherwood Memorial Cem.",
    "",
    "McCreary Co, KY",
    "Family lived Lantana, FL",
    "Whitley Co, KY, Jellico Baptist Creek Cem.",
    "Another Mary (?) Davenport married Zebedee Hassell, 3/15/1770",
    "",
    "Washington Co, NC",
    "",
    "",
    "",
    "",
    "",
    "Code: 0-10,   10-16,   16-26,   26-45,   45-up",
    "Whitley Co, KY, Jellico Creek Baptist Cem.",
    "",
    "",
    "Probably Washington Co, NC",
    "Sevier Co, TN, Shiloh Cem.",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem.",
    "",
    "",
    "",
    "Sevier Co, TN, Mattox Cem.",
    "McCreary Co, KY",
    "",
    "",
    "",
    "Tyrrell Co, NC",
    "",
    "",
    "",
    "Sevier C0, TN",
    "",
    "",
    "",
    "Kansas",
    "",
    "",
    "",
    "Pigeon Forge, Sevier Co, TN, Shiloh Cem.",
    "",
    "",
    "",
    "Whitley Co, KY, Wolf Creek Cem.",
    "Sevier Co, TN, Shiloh Cem.",
    "McCreary Co, KY, Bethel Baptist Cem.",
    "",
    "Tyrrell Co, NC",
    "Pigeon Forge, Sevier Co, TN, Shiloh Cem.",
    "",
    "Another, older Stephen m. Elizabeth Alexander, 1778",
    "",
    "",
    "",
    "",
    "",
    "",
    "Whitley Co, KY, Wolf Creek Cem.",
    "",
    "Knox Co, TN, Galilee Cem, Seymour",
    "Washington Co, NC",
    "",
    "",
    "",
    "Little Rock, Arkansas",
    "Whitley Co, KY, Speculate Wolf Creek Cem.",
    "",
    "Sevier C0, TN",
    "",
    "Borgetto, Sicily, Italy",
    "Living in April 1994",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Keene, NH",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Worthington, MN [P59624]",
    "",
    "New Hill, , , NC [P44296]",
    "Shallow Well, Lee Co, NC [P44476]",
    "",
    "Brickhaven, NC [P44354]",
    "Chatham Co, NC [P44068]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Whitley Co, KY, Bethel Baptist Cem [P8824] [P10683]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Greenville, SC [P0880] [P42786]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Shults-Whaley Cem., Hwy 321 [P9271] [P11130]",
    "Sevier C0, TN, Spurgeon Cem [P9326] [P11185]",
    "Sevier C0, TN, Webbs Creek Cem [P9414] [P11273]",
    "",
    "",
    "",
    "Huskey Cem [P9321] [P11180]",
    "",
    "Sevier CO, TN, Headrick Cem [P9290] [P11149]",
    "",
    "",
    "",
    "Los Angeles, CA [P1054] [P42950]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Evanston, WY [P0940] [P42841]",
    "",
    "Havre, MT [P1656] [P43389]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Memorial Cem, Hwy 401 S., Raleigh, NC [P10002] [P10002]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Mattox Cem. [P9195] [P11054]",
    "",
    "",
    "",
    "Cocke Co, TN, Rocky Creek Valentine Cem [P9417] [P11276]",
    "",
    "",
    "",
    "",
    "",
    "Pittsburg, PA [P9737] [P11596]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cameron, Lee County, NC [P10325] [P10325]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Rex Hospital, , Raleigh, NC [P9474] [P11333]",
    "Cocke Co, TN, Waters-Large Cem [P9278] [P11137]",
    "",
    "",
    "Sevier Co, TN, Proffitt Cem. [P9041] [P37049]",
    "Jackson Co, AL, McMahan Cem., McMahan Cove [P8791] [P10650]",
    "Sevier Co, TN, McMahan Cem., Pearl Valley [P8788] [P10647]",
    "Sevier Co, TN, Old McMahan Cem. [P9040] [P37047]",
    "Sevier Co, TN, Richardson Cove Cem. [P9035] [P10894]",
    "Cocke Co, TN [P8814] [P10673]",
    "",
    "",
    "Sevier Co, TN, Church in Forks Baptist Cem. [P9033] [P10892]",
    "Sevier Co, TN, Church in Forks Baptist Cem. [P9033] [P10892]",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Richardson Cove Cem. [P9035] [P10894]",
    "Sevier Co, TN, McMahan Cem. [P9252] [P11111]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Webbs Creek Cem. [P9273] [P11132]",
    "",
    "Sevier Co, TN [P8763] [P10622]",
    "Sevier Co, TN, Emerts Cove Cem. [P1863] [P43588]",
    "",
    "",
    "",
    "Sevier Co, TN [P8763] [P10622]",
    "",
    "Yancy Co, NC [P9051] [P10910]",
    "",
    "",
    "",
    "Jackson Co, TN [P9045] [P10904]",
    "Sevier Co, TN, Howard-Campbell Cem. [P9042] [P10901]",
    "",
    "Cocke Co, TN [P8814] [P10673]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Tenn. Technological Univ.: MS Edu. Psychology 1972 [P1713] [P43445]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Truelove Cem, Pascal Truelove Plc, Harnett Co, NC [P9516]",
    "",
    "",
    "Stockholm,Sweden",
    "",
    "Barking Abbey,Essex,England",
    "",
    "",
    "Peterborough,Castle",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Evesham",
    "",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P59944]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Newton, IA [P20223] [P38854]",
    "",
    "",
    "",
    "",
    "Newton, IA [P20223] [P38854]",
    "",
    "",
    "",
    "",
    "",
    "Wake Co?, NC",
    "",
    "",
    "Johnston Memorial Hospital, Johnston County, NC",
    "Durham Co, Durham, NC",
    "Johnston County, NC",
    "",
    "",
    "",
    "Harnett  Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "Unknown",
    "",
    "",
    "",
    "Mother was full-blooded Indian from Arkansas [P19355]",
    "",
    "",
    "",
    "",
    "Houston, AR",
    "",
    "Jackson Parish, LA [P63027]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier C0, TN, Burchfield Memorial Cem [P2436]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Union Co, GA [P44744]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Duncan, Harnett Co, NC [P9733] [P11592]",
    "",
    "",
    "Fuquay Varina, Wake Co, NC [P9957] [P11816]",
    "",
    "",
    "",
    "",
    "",
    "Chatham Co, NC [P44068]",
    "Chatham Co, NC [P44068]",
    "Fayetteville, Cumberland Co, NC [P44291]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Fowler Cemetery [P2040]",
    "",
    "",
    "Plainview, TX [P10558]",
    "Caguas, PR [P4653]",
    "",
    "",
    "",
    "",
    "Wake County, NC [P19494] [P54001]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Rolla, MO",
    "",
    "London, KY",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Ridings-Williams Cem. [P8777] [P21174] [P55849]",
    "",
    "",
    "",
    "Sevier Co, TN, Hendron's Chapel Cem. [P8905] [P21302] [P55990]",
    "Had 3 sons [P8904] [P21301] [P55989]",
    "Killed in streetcar collision, Knoxville, 1912 [P8910] [P21307] [P55995]",
    "",
    "",
    "",
    "Sevier Co, TN, Hendron's Chapel Cem. [P8905] [P21302] [P55990]",
    "",
    "",
    "Sevier Co, TN, Walnut Grove Cem. [P1882] [P1882] [P53259]",
    "Sevier Co, TN, Galilee Baptist Cem. [P8902] [P21299] [P55986]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett  Co, NC",
    "",
    "",
    "Wethersfield, Hartford, Ct.",
    "",
    "Wethersfield, Hartford, Ct.",
    "",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P59944]",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P59944]",
    "Sevier Co, TN, Shiloh Cem. [P59944]",
    "Sevier Co, TN, McMahan Cem. [P57322]",
    "",
    "Sevier Co, TN, Shiloh Cem. [P59944]",
    "",
    "Sevier Co, TN, Trundle Family Cem. [P53611]",
    "Sevier Co, TN, McMahan Cem. [P57322]",
    "Sevier Co, TN, Shiloh Cem. [P59944]",
    "Sevier Co, TN, Trundle Family Cem. [P53611]",
    "Virginia [P60040]",
    "Sevier Co, TN, Shiloh Cem. [P59944]",
    "Roane Co, TN, killed by Indians near Crab Orchard [P62060]",
    "Sevier Co, TN, Shiloh Cem. [P59944]",
    "Marshall, TX [P1407] [P8152]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Ridings-Williams Cem. [P1828] [P53128]",
    "",
    "Code:  5-10-15-20-30-40 [P19325] [P53815]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier CO, TN, Williams-Ridings Cem",
    "Holly SprsBptChur, Harnett Co, NC",
    "",
    "",
    "",
    "",
    "Berea, Marion Co, TX",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Tennessee",
    "",
    "",
    "Summerville, GA",
    "Harnett Co, NC",
    "",
    "",
    "",
    "Springfield, MA [P59678]",
    "",
    "",
    "",
    "Sevier C0, TN, Jos. &amp;amp;amp;amp; Salina Shults Cem [P62298]",
    "",
    "",
    "Sevier C0, TN, Williams Cem, Jones Cove [P62367]",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC",
    "",
    "",
    "",
    "Harnett Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Rome, Sumner, KS",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Washington Co, VA",
    "",
    "Cocke Co, TN, Shults Cem., Cosby",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "NY City, NY [P10198] [P10198]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN [P1726]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Ottawa, IL [P20143]",
    "Oshkosh, WI [P20116]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Worthington, MN [P4670]",
    "",
    "",
    "Dublin, GA [P4202]",
    "Ottawa, IL [P4282]",
    "Ogden, UT [P42034]",
    "",
    "Lake Charles, LA [P4658]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Van Wert, OH [P42043]",
    "",
    "",
    "",
    "",
    "",
    "Westminster,Palace,London,England [P19631] [P38260]",
    "",
    "",
    "London,England [P3470] [P3470]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "NJ [P9161]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cadillac, MI [P1618] [P43351]",
    "Kapaa, HI [P1614] [P43347]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Banner Cem. [P9303] [P21700] [P40358]",
    "Sevier Co, TN, Glades Lebanon Cem. [P9092] [P21489] [P40133]",
    "",
    "Sevier Co, TN, Williamsburg Cem. [P9096] [P21493] [P40138]",
    "Sevier Co, TN [P8763] [P21160] [P39797]",
    "",
    "Sevier C0, TN, Old Plemmons Cemetery, Greenbrier [P9376] [P21773] [P40435]",
    "",
    "",
    "Sevier Co, TN, White Oak Flats Cem. [P1890] [P1890] [P1890]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P1732] [P1732] [P1732]",
    "Sevier Co, TN, Cole Cem. [P9299] [P21696] [P40354]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Jackson, MI",
    "Toledo, OH",
    "",
    "Redding, CA",
    "",
    "",
    "",
    "",
    "Coldwater, MI",
    "McAlester, OK",
    "",
    "",
    "",
    "",
    "Kingsport, TN [P1505] [P1505]",
    "",
    "Sioux Falls, SD [P1459] [P1459]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Worcester, MA [P8742] [P21139]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Buncombe Co, NC [P3395] [P3395]",
    "Williston, ND [P20802] [P39438]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Lumberton, NC [P20074]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "NYC?, NY [P10210] [P10210]",
    "",
    "",
    "",
    "",
    "New York City, NY [P9776] [P11635]",
    "",
    "TN [P9980] [P11839]",
    "",
    "",
    "",
    "See Note [P10179] [P10179]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P44064]",
    "Andrews, TX [P1104] [P1104]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Lutesville, MO, Lincoln Cem. [P9257] [P11116]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Wake County, NC [P57664]",
    "",
    "",
    "Duncan Bpt, ChurCem, Harnett Co, NC [P10091] [P10091]",
    "Monroe, LA [P1563] [P43296]",
    "",
    "",
    "",
    "",
    "",
    "Marquette, MI [P20378] [P54973]",
    "",
    "",
    "",
    "",
    "",
    "Sanford, NC [P20602] [P55220]",
    "Guaynabo, PR [P20453] [P55056]",
    "Effingham, IL [P20756] [P55389]",
    "Marquette, MI [P20378] [P54973]",
    "",
    "New Ulm, MN [P20538] [P55149]",
    "",
    "",
    "Kendallville, IN [P20618] [P55237]",
    "Marquette, MI [P20378] [P54973]",
    "",
    "",
    "New Ulm, MN [P20538] [P55149]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Pigeon Forge Methodist Cem [P2327]",
    "Sevier Co, TN, Methodist Cem., Pigeon forge [P43851]",
    "",
    "",
    "Sevier Co, TN, Alderbranch Cem. [P2227]",
    "Sevier Co, TN, Emerts Cove Cem. [P42264]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cosby, TN, Holders Grove Cem. [P43870]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Middle Creek Methodist Cem. [P8868] [P21265] [P55949]",
    "Sevier Co, TN [P8763] [P21160] [P55834]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Bogart, Ga [P9583] [P21980] [P56736]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Richmond Co, NC [P44581]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Athens,Greece [P0067] [P0067] [P0067]",
    "",
    "",
    "Palermo,Italy [P0156] [P0156] [P0156]",
    "",
    "",
    "",
    "Athens,Greece [P0067] [P0067] [P0067]",
    "",
    "",
    "",
    "",
    "Tatoi,Near Athens,Greece [P0074] [P0074] [P0074]",
    "",
    "",
    "Salonika [P0151] [P0151] [P0151]",
    "Passaic, NJ [P10185] [P18928] [P53378]",
    "Poland [P10203] [P18946] [P53398]",
    "Shelby, NC [P20310]",
    "",
    "",
    "Palatka, FL [P1594] [P1594] [P52894]",
    "",
    "",
    "",
    "",
    "Pleasant Grove, BaptChur, Wake Co, NC [P9511] [P21908] [P40577]",
    "Clinton, IA [P1013] [P1013] [P36966]",
    "",
    "Napa, CA [P1298] [P1298] [P37222]",
    "Napa, CA [P1298] [P1298] [P37222]",
    "Borgetto, Sicily, Italy [P9600] [P21997] [P40669]",
    "",
    "",
    "",
    "#6 Via Deluvio, Borgetto, Sicily, Italy [P10213] [P18956] [P37585]",
    "Sicily, Italy [P9838] [P22235] [P40921]",
    "Sicily, Italy [P9838] [P22235] [P40921]",
    "Sicily, Italy [P9838] [P22235] [P40921]",
    "Sicily, Italy [P9838] [P22235] [P40921]",
    "New York City, NY [P9776] [P22173] [P40858]",
    "",
    "Sicily, Italy [P9838] [P22235] [P40921]",
    "",
    "Trenton, NJ [P9498] [P21895] [P40564]",
    "Sicily, Italy [P9838] [P22235] [P40921]",
    "Sicily, Italy [P9838] [P22235] [P40921]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Hot Springs, AR [P20438]",
    "",
    "",
    "",
    "Norfolk, NE [P20165]",
    "Syracuse, NY [P20411]",
    "Orlando, FL [P20287]",
    "",
    "Olean, NY [P20218]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Emerts Cove Cem. [P1863]",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Emerts Cove Cem. [P1863]",
    "",
    "Sevier Co, TN, Emerts Cove Cem. [P1863]",
    "Carter Co, TN [P9410]",
    "Sullivan Co, TN [P9411]",
    "Washington Co, MD [P9408]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Burks Co, PA [P8781]",
    "",
    "Sylacauga, AL [P0995] [P61088]",
    "",
    "Sevier Co, TN, Emerts Cove Cem. [P1863] [P1863] [P53163]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Greensboro, NC [P59911]",
    "",
    "Greensboro, NC [P59911]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Greensboro, NC [P59911]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P62437]",
    "NC [P59957]",
    "",
    "",
    "#6 Via Dilluvio, Borgetto, Sicily, Italy [P44679]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "#6 Via Dilluvio, Borgetto, Sicily, Italy [P44679]",
    "Zion, Mercer Co, NJ [P44569]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Zion, Mercer Co, NJ [P44569]",
    "",
    "Hopewell, NJ [P44142]",
    "",
    "",
    "St Alfonsis, Catholic Chur, Hopewell, NJ [P41308]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P62437]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Home, Durham, NC [P9813] [P22210]",
    "",
    "Durham Co, Durham, NC [P9907] [P22304]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sicily, Italy [P9838] [P11697]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Newport, TN [P20345] [P54937]",
    "",
    "",
    "Castle Pelesch,Sinaia,Romania [P63243]",
    "Villa Mar y Sol,Estoril,Portugal [P63345]",
    "",
    "",
    "Cannes,France [P63344]",
    "Sinaia,Romania [P63316]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Port of Spain, Trinidad, West Indies [P2806] [P57760]",
    "",
    "McColl, SC [P2767] [P57721]",
    "",
    "",
    "",
    "Sanford, Lee Co, NC [P3265] [P58219]",
    "",
    "",
    "",
    "",
    "",
    "Coamo, PR [P20091] [P54658]",
    "",
    "Hospital, Wake Co, NC [P3128] [P58082]",
    ""
]
scriptLoaded('dwr_db_I_death_place_15.js');
