// This file is generated

I_death_age_23 = [
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "56 years, 3 months, 15 days",
    "",
    "",
    "68 years, 10 months, 23 days",
    "",
    "",
    "",
    "70 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "76 years, 7 months, 7 days",
    "",
    "",
    "",
    "",
    "",
    "44 years, 6 months, 23 days",
    "",
    "44 years, 7 months, 10 days",
    "46 years, 7 months, 24 days",
    "",
    "more than 67 years, 11 months",
    "unknown",
    "",
    "50 years, 11 months, 4 days",
    "",
    "",
    "",
    "73 years",
    "",
    "",
    "",
    "",
    "90 years, 7 months, 29 days",
    "19 years, 17 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "77 years",
    "71 years, 7 months, 29 days",
    "77 years",
    "",
    "84 years, 1 month, 26 days",
    "54 years, 7 months, 27 days",
    "83 years, 28 days",
    "",
    "86 years, 3 months, 2 days",
    "",
    "",
    "",
    "",
    "61 years, 1 month, 27 days",
    "",
    "about 89 years, 3 months, 17 days",
    "85 years, 1 month, 1 day",
    "",
    "",
    "",
    "74 years, 1 month, 4 days",
    "49 years, 9 months, 6 days",
    "62 years, 4 months, 25 days",
    "",
    "",
    "",
    "62 years, 5 months, 9 days",
    "",
    "77 years, 10 months, 17 days",
    "",
    "88 years, 8 months, 13 days",
    "6 months, 16 days",
    "",
    "",
    "7 months",
    "85 years, 6 months, 29 days",
    "",
    "",
    "86 years, 5 months, 1 day",
    "about 44 years, 6 months, 19 days",
    "",
    "",
    "",
    "",
    "63 years, 9 months, 27 days",
    "",
    "",
    "",
    "33 years, 1 month, 1 day",
    "less than 62 years",
    "76 years, 9 months, 10 days",
    "",
    "",
    "75 years, 8 months, 9 days",
    "67 years, 6 months, 1 day",
    "",
    "72 years, 10 months, 20 days",
    "90 years, 3 months, 1 day",
    "87 years, 9 months, 9 days",
    "30 years, 27 days",
    "",
    "",
    "55 years, 5 months",
    "76 years, 2 months, 16 days",
    "81 years, 8 months",
    "",
    "",
    "",
    "",
    "87 years, 1 month, 23 days",
    "",
    "70 years, 4 months, 14 days",
    "39 years, 8 months, 25 days",
    "56 years, 1 month, 28 days",
    "",
    "72 years, 3 months, 21 days",
    "79 years, 11 months, 1 day",
    "more than 60 years",
    "",
    "",
    "",
    "",
    "63 years, 11 months, 14 days",
    "81 years, 8 months, 4 days",
    "",
    "unknown",
    "69 years, 9 months, 15 days",
    "unknown",
    "",
    "65 years, 11 months, 22 days",
    "",
    "",
    "",
    "",
    "70 years, 9 months, 27 days",
    "58 years, 9 months, 3 days",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "51 years, 6 months, 25 days",
    "",
    "",
    "unknown",
    "about 93 years, 4 months, 1 day",
    "",
    "44 years, 8 months, 7 days",
    "",
    "",
    "86 years, 1 month, 1 day",
    "87 years, 10 months",
    "",
    "63 years, 10 months, 11 days",
    "",
    "",
    "about 78 years, 1 month, 24 days",
    "",
    "",
    "unknown",
    "81 years, 10 months, 9 days",
    "",
    "",
    "unknown",
    "",
    "",
    "about 80 years, 9 months, 20 days",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "about 77 years, 3 months, 11 days",
    "",
    "",
    "78 years, 1 month, 11 days",
    "",
    "about 24 years, 11 months, 11 days",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "25 years, 7 months, 18 days",
    "",
    "78 years, 3 months, 18 days",
    "",
    "",
    "unknown",
    "",
    "45 years, 10 months, 5 days",
    "72 years, 2 months, 3 days",
    "69 years, 3 months, 14 days",
    "",
    "",
    "",
    "42 years",
    "",
    "",
    "",
    "",
    "46 years, 9 months, 16 days",
    "63 years, 11 months, 5 days",
    "",
    "",
    "",
    "",
    "58 years, 7 months, 28 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "76 years, 8 days",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "less than 68 years",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "85 years",
    "",
    "87 years, 4 months, 11 days",
    "",
    "",
    "",
    "",
    "",
    "37 years, 11 months, 2 days",
    "unknown",
    "",
    "",
    "",
    "65 years, 6 months, 29 days",
    "",
    "",
    "about 58 years, 9 months, 25 days",
    "67 years, 11 months, 5 days",
    "",
    "73 years, 5 months, 17 days",
    "",
    "",
    "",
    "",
    "",
    "57 years, 10 months, 28 days",
    "",
    "64 years, 4 months, 16 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "83 years, 6 months, 30 days",
    "",
    "",
    "",
    "",
    "",
    "more than 65 years",
    "",
    "",
    "87 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "68 years, 5 months, 27 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "28 years, 9 months, 5 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "52 years",
    "",
    "",
    "7 days",
    "",
    "",
    "",
    "",
    "",
    "76 years",
    "58 years, 22 days",
    "",
    "",
    "65 years",
    "42 years",
    "about 32 years, 9 months, 23 days",
    "",
    "",
    "",
    "",
    "",
    "48 years",
    "26 years",
    "",
    "unknown",
    "",
    "unknown",
    "less than 52 years",
    "",
    "about 93 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "70 years, 2 months, 28 days",
    "69 years, 5 months, 29 days",
    "",
    "56 years, 11 months, 1 day",
    "51 years",
    "38 years",
    "more than about 79 years",
    "",
    "",
    "29 years, 9 months, 17 days",
    "",
    "",
    "67 years, 11 months",
    "",
    "",
    "",
    "82 years, 3 months, 30 days",
    "65 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "84 years, 8 months, 19 days",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "49 years, 1 month, 22 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "about 48 years",
    "",
    "",
    "",
    "82 years, 10 months, 26 days",
    "",
    "",
    "",
    "",
    "about 54 years, 8 months, 20 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "91 years, 9 months, 15 days",
    "",
    "",
    "unknown",
    "",
    "89 years, 1 month",
    "",
    "63 years, 4 months, 3 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "46 years, 2 months, 11 days",
    "",
    "",
    "more than about 22 years",
    "",
    "72 years",
    "",
    "",
    "",
    "about 84 years, 4 months, 7 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "75 years, 6 months, 12 days",
    "",
    "",
    "about 26 years, 6 months, 13 days",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "80 years, 4 months, 6 days",
    "",
    "",
    "",
    "",
    "",
    "79 years, 5 months, 20 days",
    "about 52 years",
    "",
    "93 years",
    "",
    "",
    "",
    "47 years, 10 months, 28 days",
    "",
    "79 years",
    "47 years, 2 months",
    "",
    "",
    "",
    "unknown",
    "39 years",
    "",
    "",
    "",
    "45 years",
    "77 years, 3 months, 15 days",
    "",
    "53 years",
    "66 years, 6 months, 28 days",
    "greater than 110 years",
    "",
    "",
    "unknown",
    "72 years, 1 month, 5 days",
    "",
    "",
    "85 years",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "72 years, 4 months, 21 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "95 years, 8 months, 24 days",
    "",
    "88 years, 1 month, 13 days",
    "",
    "",
    "",
    "76 years, 1 month, 12 days",
    "63 years, 4 months, 15 days",
    "87 years, 9 months, 9 days",
    "54 years, 11 months, 2 days",
    "88 years, 11 months, 29 days",
    "48 years, 1 month, 17 days",
    "",
    "",
    "",
    "2 years, 6 months, 22 days",
    "",
    "32 years, 6 months, 1 day",
    "",
    "37 years",
    "",
    "36 years, 4 months, 5 days",
    "19 years, 9 months",
    "",
    "",
    "0 days",
    "17 days",
    "74 years, 10 months, 10 days",
    "93 years, 4 months, 23 days",
    "",
    "",
    "",
    "87 years, 1 month, 27 days",
    "85 years, 2 months, 23 days",
    "",
    "more than 47 years, 3 months",
    "79 years, 1 month, 25 days",
    "81 years, 10 months, 11 days",
    "",
    "",
    "",
    "53 years, 6 months, 5 days",
    "15 years, 4 months",
    "",
    "",
    "about 1 year, 1 month, 8 days",
    "72 years, 2 months, 6 days",
    "",
    "78 years, 5 months, 23 days",
    "44 years, 11 months",
    "87 years, 1 month, 27 days",
    "",
    "97 years, 4 months, 12 days",
    "75 years, 4 months, 21 days",
    "",
    "28 years, 4 months, 14 days",
    "78 years, 7 months, 13 days",
    "75 years, 8 months, 2 days",
    "68 years, 11 months, 4 days",
    "73 years, 7 months, 19 days",
    "about 66 years",
    "about 1 year, 5 days",
    "73 years, 8 months, 26 days",
    "77 years, 5 months, 6 days",
    "",
    "91 years, 7 months, 14 days",
    "",
    "57 years, 9 months, 17 days",
    "",
    "35 years, 8 months, 24 days",
    "",
    "19 years, 9 months, 12 days",
    "",
    "79 years, 5 months, 18 days",
    "78 years, 1 month, 11 days",
    "62 years, 11 months, 5 days",
    "",
    "76 years, 11 months",
    "",
    "66 years, 8 months, 24 days",
    "",
    "34 years, 6 months, 11 days",
    "83 years, 6 months, 28 days",
    "unknown",
    "",
    "72 years, 6 months, 26 days",
    "",
    "41 years, 5 months, 21 days",
    "6 months, 19 days",
    "",
    "85 years, 5 months, 14 days",
    "",
    "",
    "72 years, 9 months, 18 days",
    "",
    "",
    "",
    "47 years, 10 months, 10 days",
    "",
    "40 years, 4 months, 30 days",
    "36 years, 6 months, 26 days",
    "40 years, 11 months, 8 days",
    "63 years, 2 months, 19 days",
    "",
    "22 years, 1 month, 3 days",
    "76 years, 4 months, 3 days",
    "less than 4 years",
    "",
    "58 years, 11 months",
    "85 years, 25 days",
    "66 years, 8 months, 4 days",
    "74 years, 20 days",
    "76 years, 8 months, 15 days",
    "",
    "44 years, 6 months, 6 days",
    "27 years, 5 months, 4 days",
    "62 years, 7 months, 28 days",
    "65 years, 9 months, 9 days",
    "69 years, 2 months, 26 days",
    "",
    "",
    "89 years, 5 months, 6 days",
    "",
    "16 years, 6 months, 18 days",
    "80 years, 11 months, 14 days",
    "1 year, 11 months, 23 days",
    "",
    "",
    "less than 11 years",
    "62 years, 8 months, 4 days",
    "",
    "",
    "",
    "",
    "22 years, 7 months, 8 days",
    "66 years, 5 months, 14 days",
    "",
    "",
    "87 years, 11 months, 10 days",
    "",
    "84 years, 9 months, 19 days",
    "",
    "2 months, 16 days",
    "unknown",
    "about 0 days",
    "",
    "",
    "0 days",
    "0 days",
    "",
    "",
    "0 days",
    "0 days",
    "42 years, 8 months, 16 days",
    "68 years, 9 months, 27 days",
    "1 year, 15 days",
    "86 years, 3 months, 11 days",
    "",
    "69 years, 10 months, 7 days",
    "41 years, 2 months, 25 days",
    "94 years, 6 months, 19 days",
    "1 year, 9 months, 30 days",
    "73 years, 28 days",
    "",
    "",
    "",
    "60 years, 8 months, 22 days",
    "69 years, 7 months, 20 days",
    "82 years, 11 months, 21 days",
    "77 years, 6 months, 9 days",
    "51 years, 1 month, 15 days",
    "58 years, 5 months, 15 days",
    "45 years, 4 months",
    "74 years, 1 month, 2 days",
    "",
    "",
    "69 years, 4 months, 5 days",
    "61 years, 10 months, 21 days",
    "",
    "72 years, 2 months, 20 days",
    "about 84 years",
    "74 years, 1 month, 15 days",
    "84 years, 10 months, 24 days",
    "77 years, 5 months, 28 days",
    "64 years, 4 months, 5 days",
    "51 years, 9 months",
    "65 years, 6 months, 20 days",
    "less than 40 years",
    "",
    "63 years, 6 months, 30 days",
    "87 years, 1 month, 19 days",
    "66 years, 9 months, 29 days",
    "92 years, 8 months, 13 days",
    "74 years, 26 days",
    "",
    "70 years, 3 months, 22 days",
    "21 years, 1 month, 28 days",
    "",
    "",
    "92 years, 8 months, 25 days",
    "",
    "",
    "73 years, 9 months, 29 days",
    "",
    "5 years, 1 month, 27 days",
    "",
    "4 years, 10 months, 11 days",
    "79 years, 2 months, 15 days",
    "",
    "",
    "",
    "90 years, 1 month, 23 days",
    "21 years, 9 months, 20 days",
    "",
    "",
    "",
    "66 years, 2 months, 23 days",
    "1 year, 8 months, 5 days",
    "1 year, 2 months, 13 days",
    "89 years, 3 months, 25 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "more than 72 years, 1 month",
    "68 years, 8 months, 8 days",
    "70 years, 4 months, 17 days",
    "74 years, 10 months",
    "50 years, 9 days",
    "75 years, 5 months, 18 days",
    "30 years, 4 months, 23 days",
    "68 years, 5 months, 9 days",
    "65 years, 3 months, 10 days",
    "",
    "76 years, 10 months, 23 days",
    "",
    "74 years, 4 months, 4 days",
    "67 years, 8 months, 19 days",
    "69 years, 2 months, 29 days",
    "26 years, 11 months, 6 days",
    "81 years, 7 months, 3 days",
    "",
    "",
    "33 years, 10 months, 8 days",
    "",
    "",
    "65 years, 3 months, 2 days",
    "85 years, 2 months, 7 days",
    "41 years, 11 months, 4 days",
    "",
    "",
    "",
    "",
    "",
    "77 years, 6 months, 21 days",
    "",
    "unknown",
    "76 years, 2 months, 9 days",
    "",
    "",
    "57 years, 6 months, 10 days",
    "80 years, 5 months, 18 days",
    "",
    "",
    "",
    "",
    "more than 81 years, 2 months",
    "",
    "43 years, 11 months, 27 days",
    "72 years, 9 months, 10 days",
    "81 years, 10 months, 1 day",
    "",
    "67 years, 8 months, 30 days",
    "69 years, 4 months, 28 days",
    "72 years, 8 months, 17 days",
    "66 years, 11 months, 6 days",
    "82 years, 7 months, 28 days",
    "70 years, 2 months, 6 days",
    "",
    "80 years, 6 months, 25 days",
    "14 days",
    "92 years, 3 months, 20 days",
    "",
    "39 years, 7 months, 29 days",
    "60 years, 11 months, 6 days",
    "",
    "",
    "94 years, 7 months, 8 days",
    "",
    "66 years, 4 months, 14 days",
    "2 years, 8 months, 19 days",
    "",
    "",
    "",
    "",
    "81 years, 10 months, 28 days",
    "",
    "",
    "80 years, 2 months, 9 days",
    "85 years, 9 months, 28 days",
    "81 years, 6 months, 19 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "77 years, 10 months, 26 days",
    "83 years, 3 months, 18 days",
    "60 years, 3 months, 28 days",
    "unknown",
    "",
    "92 years, 7 months, 12 days",
    "",
    "unknown",
    "",
    "",
    "2 years, 8 months, 11 days",
    "",
    "79 years, 5 months, 26 days",
    "less than 10 years",
    "",
    "77 years, 6 months, 1 day",
    "72 years, 8 months, 12 days",
    "86 years, 1 day",
    "",
    "",
    "78 years, 5 months, 22 days",
    "33 years, 9 months, 29 days",
    "about 73 years, 4 months, 7 days",
    "4 months, 26 days",
    "83 years, 11 months, 19 days",
    "79 years, 7 months, 28 days",
    "",
    "3 months, 12 days",
    "",
    "44 years, 7 days",
    "81 years, 7 months, 29 days",
    "85 years, 5 days",
    "76 years, 4 months, 12 days",
    "30 years, 9 days",
    "54 years, 3 months, 24 days",
    "89 years, 5 months, 28 days",
    "",
    "",
    "",
    "88 years, 11 months, 11 days",
    "",
    "",
    "41 years, 22 days",
    "",
    "",
    "80 years, 28 days",
    "",
    "",
    "",
    "",
    "67 years, 2 months, 16 days",
    "64 years, 1 month, 16 days",
    "",
    "",
    "",
    "99 years, 3 days",
    "",
    "",
    "47 years",
    "",
    "",
    "",
    "58 years, 9 months, 28 days",
    "unknown",
    "unknown",
    "",
    "81 years, 10 months, 27 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "57 years",
    "",
    "",
    "89 years",
    "",
    "89 years, 13 days",
    "",
    "",
    "90 years",
    "57 years, 3 months, 12 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "88 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "less than about 73 years",
    "",
    "77 years, 6 months, 7 days",
    "",
    "",
    "",
    "",
    "85 years, 4 months, 7 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "67 years, 3 months, 28 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "about 81 years, 10 months",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "73 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "78 years, 7 months, 4 days",
    "less than 4 years, 5 months, 22 days",
    "",
    "unknown",
    "83 years, 4 months, 4 days",
    "",
    "",
    "43 years, 2 months, 12 days",
    "less than 60 years, 3 months, 10 days",
    "unknown",
    "19 years, 9 months, 21 days",
    "",
    "4 months, 23 days",
    "76 years, 6 months, 19 days",
    "",
    "",
    "",
    "",
    "19 years, 1 month, 10 days",
    "",
    "87 years, 5 months",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "less than about 76 years",
    "less than 60 years, 3 months, 8 days",
    "",
    "13 years, 2 months, 8 days",
    "unknown",
    "",
    "",
    "",
    "82 years, 5 months, 16 days",
    "21 years, 5 months, 21 days",
    "0 days",
    "",
    "",
    "26 years, 6 months, 1 day",
    "",
    "68 years, 10 months, 28 days",
    "3 years, 24 days",
    "",
    "",
    "",
    "unknown",
    "68 years, 10 months, 17 days",
    "",
    "87 years, 4 months, 11 days",
    "about 5 years",
    "",
    "",
    "89 years, 1 month, 21 days",
    "17 years, 11 months, 26 days",
    "unknown",
    "30 years, 8 months, 26 days",
    "",
    "",
    "",
    "",
    "63 years, 4 months, 20 days",
    "less than 30 years, 8 days",
    "98 years, 7 months, 23 days",
    "63 years, 5 months, 10 days",
    "unknown",
    "90 years, 7 months, 9 days",
    "20 years, 9 months, 16 days",
    "",
    "",
    "79 years, 9 months, 4 days",
    "",
    "1 month, 11 days",
    "77 years, 1 month, 4 days",
    "",
    "70 years, 9 months, 25 days",
    "",
    "",
    "72 years, 9 months, 2 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "91 years",
    "",
    "",
    "",
    "97 years, 4 months, 1 day",
    "",
    "",
    "",
    "63 years, 7 months, 4 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "77 years, 11 months, 5 days",
    "",
    "",
    "",
    "",
    "39 years, 8 months, 5 days",
    "",
    "70 years, 7 months, 17 days",
    "56 years, 1 month, 23 days",
    "",
    "",
    "73 years, 9 months, 1 day",
    "13 years, 6 months, 6 days",
    "",
    "67 years, 11 months, 3 days",
    "",
    "",
    "",
    "",
    "",
    "30 years, 8 months, 10 days",
    "",
    "",
    "",
    "greater than 110 years",
    "74 years, 1 month, 18 days",
    "",
    "",
    "68 years",
    "67 years",
    "",
    "about 60 years, 2 months, 24 days",
    "",
    "57 years",
    "",
    "",
    "unknown",
    "unknown",
    "unknown",
    "",
    "",
    "",
    "",
    "70 years, 3 months, 20 days",
    "",
    "",
    "76 years, 8 months, 4 days",
    "56 years, 1 month, 1 day",
    "",
    "4 years",
    "76 years",
    "63 years",
    "80 years",
    "81 years",
    "72 years",
    "84 years",
    "81 years, 6 months, 4 days",
    "40 years, 9 months, 19 days",
    "76 years, 9 months, 11 days",
    "72 years",
    "3 years",
    "69 years, 4 months, 17 days",
    "11 years",
    "68 years, 5 months, 14 days",
    "52 years, 1 month, 25 days",
    "67 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "33 years, 11 months, 3 days",
    "",
    "",
    "",
    "",
    "27 years, 2 months, 24 days",
    "",
    "52 years",
    "54 years, 5 months, 9 days",
    "",
    "",
    "88 years",
    "56 years, 8 months, 13 days",
    "",
    "",
    "",
    "",
    "62 years, 2 months, 23 days",
    "72 years",
    "",
    "67 years, 2 months, 25 days",
    "",
    "",
    "unknown",
    "",
    "unknown",
    "",
    "67 years, 6 months, 23 days",
    "",
    "56 years",
    "",
    "about 57 years, 7 months, 23 days",
    "20 years",
    "1 year",
    "0 days",
    "62 years, 11 months",
    "about 62 years",
    "",
    "0 days",
    "",
    "82 years, 7 months, 2 days",
    "48 years",
    "25 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "85 years, 2 months, 1 day",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "21 years, 10 months, 27 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "78 years, 3 months, 10 days",
    "",
    "",
    "",
    "",
    "85 years, 3 months, 16 days",
    "",
    "73 years, 7 months, 28 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "about 42 years, 9 months, 8 days",
    "67 years, 8 months, 7 days",
    "",
    "83 years, 5 months, 29 days",
    "71 years, 8 months, 27 days",
    "",
    "89 years",
    "72 years, 9 months, 23 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "86 years, 2 months, 16 days",
    "",
    "45 years",
    "",
    "",
    "",
    "61 years, 11 months, 21 days",
    "65 years, 10 months, 5 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "55 years, 11 months, 25 days",
    "",
    "2 months, 7 days",
    "",
    "",
    "84 years, 11 months, 24 days",
    "",
    "",
    "",
    "",
    "",
    "85 years, 10 months, 9 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "about 49 years",
    "68 years, 2 months, 4 days",
    "",
    "93 years, 3 months, 2 days",
    "",
    "",
    "59 years, 2 months, 6 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "73 years, 9 months, 3 days",
    "",
    "",
    "unknown",
    "",
    "64 years, 1 month, 26 days",
    "",
    "",
    "",
    "",
    "",
    "77 years, 10 months, 10 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "71 years, 6 months, 5 days",
    "",
    "",
    "",
    "",
    "80 years, 8 months, 7 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "83 years, 1 month",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "81 years, 11 months, 22 days",
    "",
    "",
    "74 years, 11 months, 2 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "35 years, 11 months, 5 days",
    "",
    "",
    "32 years, 6 months",
    "",
    "72 years, 8 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "76 years, 4 months, 21 days",
    "77 years, 10 months, 22 days",
    "unknown",
    "76 years, 7 months, 5 days",
    "75 years, 1 month, 14 days",
    "40 years, 3 months, 25 days",
    "72 years",
    "",
    "unknown",
    "76 years, 3 months, 2 days",
    "",
    "unknown",
    "69 years, 8 months, 16 days",
    "unknown",
    "87 years, 10 months",
    "90 years, 2 months, 24 days",
    "",
    "55 years, 8 months, 20 days",
    "66 years, 1 month, 1 day",
    "",
    "55 years, 9 months, 7 days",
    "",
    "",
    "",
    "62 years",
    "",
    "",
    "",
    "82 years, 4 months, 21 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "86 years, 3 months, 17 days",
    "",
    "",
    "",
    "81 years, 5 months, 26 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "53 years, 4 months, 9 days",
    "",
    "about 25 years, 10 months, 15 days",
    "",
    "",
    "",
    "",
    "59 years, 1 month",
    "unknown",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "87 years, 2 months, 12 days",
    "82 years, 4 months, 4 days",
    "",
    "",
    "",
    "",
    "",
    "84 years, 8 months, 3 days",
    "",
    "",
    "",
    "1 year",
    "",
    "67 years",
    "48 years",
    "63 years, 2 months, 12 days",
    "49 years, 10 months",
    "7 years",
    "58 years",
    "28 years",
    "13 years, 11 months, 6 days",
    "unknown",
    "17 years, 1 month, 17 days",
    "77 years",
    "47 years",
    "20 years",
    "38 years",
    "66 years",
    "81 years",
    "57 years",
    "27 years",
    "62 years",
    "59 years",
    "50 years",
    "unknown",
    "20 years",
    "21 years",
    "41 years",
    "56 years",
    "28 years, 6 months",
    "75 years",
    "24 years",
    "",
    "",
    "32 years",
    "30 years",
    "1 year",
    "",
    "19 years, 2 months, 17 days",
    "68 years",
    "77 years",
    "68 years",
    "40 years, 6 months, 9 days",
    "48 years",
    "",
    "68 years",
    "60 years",
    "60 years",
    "22 years",
    "59 years",
    "50 years, 1 month, 29 days",
    "51 years",
    "78 years, 5 months, 23 days",
    "22 years, 8 months, 17 days",
    "",
    "59 years",
    "47 years",
    "53 years",
    "15 years",
    "34 years, 6 months, 16 days",
    "48 years, 1 month",
    "49 years",
    "",
    "62 years",
    "22 years",
    "",
    "85 years, 3 months, 19 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "85 years",
    "",
    "",
    "",
    "73 years",
    "",
    "70 years",
    "",
    "62 years",
    "40 years",
    "",
    "77 years",
    "59 years",
    "",
    "",
    "",
    "65 years",
    "27 years, 10 months, 28 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "46 years",
    "",
    "",
    "",
    "",
    "",
    "less than 78 years, 11 months, 3 days",
    "45 years",
    "",
    "",
    "",
    "",
    "88 years, 7 months, 23 days",
    "",
    "",
    "76 years, 11 months, 16 days",
    "",
    "",
    "about 55 years, 5 months, 7 days",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "90 years",
    "92 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "about 52 years, 4 months, 9 days",
    "61 years, 25 days",
    "78 years, 11 months, 19 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "75 years",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "31 years, 5 months, 26 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "25 years, 19 days",
    "",
    "",
    "about 30 years",
    "36 years, 17 days",
    "",
    "74 years, 1 month, 28 days",
    "73 years",
    "",
    "79 years, 6 months",
    "66 years",
    "",
    "82 years",
    "45 years",
    "",
    "",
    "68 years, 5 months, 11 days",
    "",
    "80 years, 3 months, 16 days",
    "82 years, 3 months, 6 days",
    "31 years, 3 months, 21 days",
    "70 years, 3 months",
    "87 years, 5 months, 9 days",
    "unknown",
    "32 years, 10 months, 26 days",
    "",
    "60 years, 3 months, 11 days",
    "",
    "",
    "21 years",
    "unknown",
    "81 years",
    "79 years, 6 days",
    "",
    "82 years, 11 days",
    "",
    "75 years",
    "83 years",
    "about 77 years, 11 months, 19 days",
    "",
    "65 years",
    "",
    "",
    "68 years, 2 months, 5 days",
    "59 years",
    "76 years",
    "",
    "49 years",
    "0 days",
    "38 years",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "62 years, 3 months, 23 days",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "86 years, 5 months, 16 days",
    "",
    "",
    "",
    "",
    "",
    "71 years, 5 months, 17 days",
    "",
    "",
    "",
    "",
    "70 years",
    "77 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "76 years, 10 months, 2 days",
    "",
    "",
    "59 years, 10 months, 12 days",
    "",
    "",
    "82 years, 11 months, 13 days",
    "71 years, 1 month, 19 days",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "33 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "77 years",
    "",
    "",
    "",
    "",
    "",
    "71 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "46 years, 4 months, 2 days",
    "",
    "",
    "65 years, 10 months, 19 days",
    "66 years, 3 months, 25 days",
    "81 years, 3 months",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "62 years, 1 month, 5 days",
    "",
    "",
    "69 years",
    "",
    "",
    "between 28 years, 7 months, 1 day and 34 years, 7 months",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "unknown",
    "",
    "unknown",
    "about 74 years, 4 months, 3 days",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "60 years, 11 months, 24 days",
    "",
    "",
    "",
    "75 years, 1 month, 23 days",
    "",
    "25 years",
    "unknown",
    "21 years, 10 months, 11 days",
    "26 days",
    "",
    "",
    "",
    "",
    "1 year, 6 months, 17 days",
    "about 4 years",
    "63 years, 8 months",
    "",
    "95 years, 1 month, 9 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "66 years, 28 days",
    "65 years, 5 months, 9 days",
    "",
    "9 months, 16 days",
    "",
    "",
    "61 years, 8 months, 19 days",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "79 years, 6 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "10 years, 1 day",
    "",
    "",
    "17 years, 1 month, 11 days",
    "",
    "",
    "1 month, 19 days",
    "",
    "",
    "unknown",
    "",
    "",
    "84 years, 5 months, 12 days",
    "",
    "",
    "",
    "",
    "88 years, 1 month, 12 days",
    "77 years, 1 month, 16 days",
    "about 80 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "23 years, 8 months, 18 days",
    "84 years, 5 months, 5 days",
    "",
    "",
    "",
    "",
    "51 years, 30 days",
    "",
    "52 years",
    "",
    "",
    "",
    "77 years, 7 months, 24 days",
    "unknown",
    "",
    "",
    "85 years, 11 months, 21 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "76 years, 6 months, 24 days",
    "58 years, 9 months, 25 days",
    "",
    "79 years, 11 months, 9 days",
    "74 years, 8 months, 19 days",
    "",
    "",
    "",
    "",
    "20 years, 10 months, 20 days",
    "",
    "",
    "",
    "",
    "81 years, 4 months, 20 days",
    "unknown",
    "",
    "",
    "58 years, 1 month, 12 days",
    "",
    "",
    "",
    "83 years, 9 months, 28 days",
    "79 years, 10 months",
    "",
    "54 years, 3 months, 12 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "15 years",
    "60 years, 3 months, 15 days",
    "",
    "",
    "",
    "13 years, 5 months, 24 days",
    "",
    "unknown",
    "",
    "",
    "81 years, 13 days",
    "",
    "",
    "59 years, 10 months, 5 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "more than 70 years",
    "",
    "80 years, 7 months, 10 days",
    "",
    "",
    "",
    "53 years, 4 months, 18 days",
    "57 years, 6 months, 20 days",
    "71 years, 9 months, 15 days",
    "",
    "",
    "69 years, 2 months, 28 days",
    "",
    "",
    "",
    "",
    "",
    "66 years, 9 months, 11 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "73 years, 2 months, 24 days",
    "",
    "about 31 years",
    "between 42 years, 1 day and 47 years",
    "",
    "",
    "57 years, 6 months, 13 days",
    "61 years, 8 months, 14 days",
    "unknown",
    "",
    "56 years",
    "",
    "",
    "about 32 years, 9 months, 10 days",
    "76 years, 10 months, 22 days",
    "",
    "57 years, 2 months, 22 days",
    "39 years, 7 months",
    "",
    "49 years, 3 months, 8 days",
    "",
    "",
    "69 years, 7 months, 14 days",
    "",
    "75 years, 2 months",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "76 years, 3 months, 11 days",
    "13 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "36 years",
    "unknown",
    "",
    "35 years, 1 month, 3 days",
    "",
    "",
    "",
    "unknown",
    "68 years, 7 months, 13 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "67 years, 8 months, 8 days",
    "70 years, 4 months, 5 days",
    "",
    "",
    "65 years, 4 months, 12 days",
    "",
    "",
    "",
    "90 years, 16 days",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "less than 16 years, 11 months",
    "",
    "70 years",
    "",
    "86 years, 13 days",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "45 years",
    "unknown",
    "83 years",
    "",
    "",
    "unknown",
    "",
    "37 years",
    "",
    "",
    "",
    "",
    "46 years, 3 months",
    "78 years, 6 months, 26 days",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "57 years, 5 months, 12 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "66 years, 11 months, 29 days",
    "77 years, 10 months, 20 days",
    "",
    "",
    "",
    "",
    "",
    "71 years",
    "",
    "",
    "",
    "",
    "23 years, 4 months, 22 days",
    "23 years, 7 months, 30 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "68 years, 3 months, 7 days",
    "",
    "",
    "81 years, 6 months, 29 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "unknown",
    "unknown",
    "",
    "",
    "",
    "68 years",
    "11 days",
    "",
    "",
    "",
    "",
    "",
    "52 years",
    "",
    "91 years, 6 days",
    "",
    "48 years, 3 months, 28 days",
    "80 years, 6 months, 15 days",
    "",
    "",
    "86 years",
    "28 years, 9 months, 4 days",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "69 years, 6 months, 16 days",
    "",
    "",
    "",
    "",
    "",
    "46 years, 10 months, 7 days",
    "",
    "78 years, 4 months, 1 day",
    "",
    "",
    "53 years",
    "",
    "67 years, 9 months, 25 days",
    "unknown",
    "",
    "",
    "46 years, 2 months, 6 days",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "between 53 years and 62 years, 11 months, 30 days",
    "",
    "",
    "",
    "",
    "75 years, 1 month, 22 days",
    "",
    "",
    "",
    "",
    "72 years, 8 months, 8 days",
    "",
    "82 years, 6 months, 25 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "63 years, 5 months, 15 days",
    "",
    "42 years, 11 months, 8 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "86 years, 5 months, 1 day",
    "",
    "",
    "about 49 years, 2 months, 22 days",
    "53 years",
    "",
    "",
    "",
    "",
    "84 years, 18 days",
    "",
    "76 years, 10 months, 6 days",
    "75 years, 6 months, 4 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "66 years, 1 month, 2 days",
    "",
    "",
    "",
    "between 56 years, 2 days and 67 years, 1 day",
    "",
    "",
    "",
    "about 38 years",
    "",
    "between 53 years, 1 day and 64 years",
    "more than 71 years",
    "about 11 years, 8 months",
    "",
    "",
    "",
    "",
    "",
    "41 years",
    "",
    "",
    "81 years, 16 days",
    "",
    "",
    "82 years, 5 months, 22 days",
    "",
    "",
    "",
    "82 years, 9 months, 19 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "about 82 years, 1 month, 19 days",
    "about 68 years",
    "",
    "59 years, 3 months, 27 days",
    "",
    "76 years, 6 months, 17 days",
    "",
    "",
    "",
    "79 years, 11 months",
    "",
    "60 years, 7 months, 20 days",
    "unknown",
    "",
    "69 years, 2 months, 18 days",
    "80 years, 7 months, 5 days",
    "0 days",
    "",
    "20 years, 5 months",
    "",
    "75 years, 11 months, 20 days",
    "",
    "84 years",
    "33 years, 6 months",
    "unknown",
    "75 years",
    "",
    "80 years, 10 months, 4 days",
    "",
    "44 years",
    "",
    "",
    "",
    "67 years, 6 months, 7 days",
    "unknown",
    "",
    "about 69 years, 2 months, 17 days",
    "",
    "",
    "",
    "",
    "",
    "1 year, 4 months, 22 days",
    "",
    "",
    "58 years",
    "",
    "",
    "",
    "",
    "",
    "86 years, 7 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "26 years",
    "90 years, 4 months, 8 days",
    "",
    "76 years",
    "",
    "",
    "",
    "",
    "",
    "68 years, 3 months, 28 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "67 years",
    "",
    "",
    "49 years, 11 months, 4 days",
    "unknown",
    "",
    "",
    "about 51 years, 9 months",
    "",
    "",
    "unknown",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "73 years, 3 months, 20 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "about 72 years",
    "53 years, 6 months, 27 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "33 years, 4 months, 16 days",
    "unknown",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "40 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "78 years",
    "",
    "",
    "",
    "",
    "34 years",
    "52 years, 9 months, 1 day",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "37 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "107 years",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "84 years, 6 months, 17 days",
    "",
    "",
    "",
    "",
    "",
    "49 years, 5 months, 24 days",
    "3 years, 7 months, 19 days",
    "",
    "0 days",
    "unknown",
    "",
    "67 years, 1 month",
    "0 days",
    "1 month, 5 days",
    "48 years, 2 months, 11 days",
    "54 years, 8 months, 8 days",
    "1 month, 21 days",
    "65 years, 5 months, 25 days",
    "14 years, 8 months, 10 days",
    "",
    "26 years, 14 days",
    "22 years",
    "",
    "82 years, 4 months, 7 days",
    "18 years, 8 months, 16 days",
    "20 years, 2 months, 5 days",
    "77 years, 6 months, 21 days",
    "58 years, 9 months, 8 days",
    "67 years, 10 months, 23 days",
    "",
    "19 years, 9 months, 10 days",
    "",
    "1 year, 2 months, 8 days",
    "2 years, 5 months, 8 days",
    "29 years, 1 month, 20 days",
    "44 years, 2 months, 1 day",
    "55 years",
    "4 months, 9 days",
    "1 day",
    "51 years, 4 months, 5 days",
    "",
    "",
    "74 years, 7 months, 15 days",
    "",
    "",
    "42 years, 9 months, 5 days",
    "",
    "",
    "",
    "",
    "100 years, 7 months, 16 days",
    "68 years, 6 months, 9 days",
    "15 years, 6 months, 12 days",
    "",
    "0 days",
    "0 days",
    "",
    "",
    "1 year, 3 months, 27 days",
    "about 26 years",
    "15 years, 8 months, 25 days",
    "3 years, 2 months, 12 days",
    "69 years, 6 months, 16 days",
    "",
    "unknown",
    "1 month, 21 days",
    "0 days",
    "52 years, 2 months, 24 days",
    "55 years, 7 months",
    "0 days",
    "0 days",
    "49 years, 3 months, 23 days",
    "",
    "",
    "",
    "73 years, 5 months, 11 days",
    "(1 months, 1 days)",
    "",
    "",
    "",
    "",
    "51 years, 10 months, 20 days",
    "37 years, 3 months, 7 days",
    "75 years, 5 months, 18 days",
    "42 years, 8 months, 28 days",
    "",
    "",
    "",
    "unknown",
    "0 days",
    "0 days",
    "",
    "",
    "",
    "",
    "",
    "77 years, 9 months, 23 days",
    "77 years, 9 months, 23 days",
    "unknown",
    "",
    "91 years, 5 months, 5 days",
    "",
    "",
    "",
    "",
    "73 years, 7 months, 5 days",
    "",
    "53 years, 3 months, 28 days",
    "",
    "",
    "between 0 days and 1 day",
    "59 years, 8 months, 27 days",
    "",
    "",
    "",
    "",
    "unknown",
    "67 years, 2 months, 18 days",
    "72 years",
    "72 years",
    "52 years",
    "77 years",
    "68 years",
    "66 years",
    "62 years",
    "65 years",
    "71 years",
    "67 years",
    "1 year",
    "46 years",
    "88 years",
    "1 year",
    "58 years, 11 months, 16 days",
    "0 days",
    "83 years",
    "73 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "73 years",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "49 years, 9 months, 29 days",
    "86 years, 1 month, 17 days",
    "87 years, 1 month, 18 days",
    "",
    "",
    "",
    "",
    "",
    "64 years, 18 days",
    "",
    "",
    "37 years, 3 months, 6 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "73 years, 4 months, 16 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "88 years, 8 months, 18 days",
    "",
    "",
    "53 years, 1 month, 24 days",
    "",
    "",
    "",
    "91 years, 3 months",
    "unknown",
    "",
    "",
    "83 years, 7 months, 9 days",
    "85 years, 6 months, 7 days",
    "86 years",
    "",
    "",
    "65 years, 10 months, 23 days",
    "",
    "71 years, 8 months, 8 days",
    "",
    "",
    "",
    "",
    "",
    "42 years, 6 months, 30 days",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "76 years, 10 months, 30 days",
    "84 years, 6 months, 26 days",
    "unknown",
    "",
    "75 years, 3 months, 4 days",
    "",
    "",
    "",
    "",
    "",
    "69 years, 2 months, 15 days",
    "unknown",
    "",
    "more than 72 years, 4 months",
    "",
    "",
    "unknown",
    "",
    "unknown",
    "unknown",
    "",
    "53 years, 8 months, 1 day",
    "",
    "61 years, 6 months, 2 days",
    "",
    "83 years, 1 month, 22 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "80 years, 8 months, 27 days",
    "",
    "",
    "",
    "80 years, 4 months, 30 days",
    "",
    "68 years",
    "unknown",
    "",
    "unknown",
    "",
    "",
    "83 years, 7 months, 22 days",
    "",
    "",
    "67 years, 1 month, 6 days",
    "",
    "87 years, 4 months, 7 days",
    "",
    "65 years, 2 months, 27 days",
    "",
    "",
    "64 years, 4 months, 19 days",
    "",
    "",
    "65 years, 10 months, 21 days",
    "",
    "unknown",
    "",
    "",
    "unknown",
    "46 years, 4 months, 15 days",
    "",
    "",
    "",
    "",
    "82 years, 8 months, 10 days",
    "",
    "",
    "",
    "",
    "",
    "86 years, 8 months, 2 days",
    "",
    "unknown",
    "",
    "",
    "76 years",
    "",
    "",
    "",
    "unknown",
    "",
    "76 years, 3 months, 9 days",
    "unknown",
    "",
    "4 years, 11 months, 6 days",
    "",
    "",
    "",
    "",
    "",
    "62 years, 3 months, 7 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "about 23 years",
    "",
    "85 years, 7 months, 1 day",
    "unknown",
    "26 years, 24 days",
    "more than 76 years, 7 months, 23 days",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "64 years, 9 months, 14 days",
    "64 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "77 years, 9 months, 5 days",
    "",
    "",
    "75 years, 4 months, 18 days",
    "",
    "",
    "about 72 years",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "67 years, 13 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "55 years",
    "71 years, 11 months, 14 days",
    "",
    "",
    "",
    "",
    "about 71 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "65 years",
    "80 years",
    "",
    "92 years, 7 months, 22 days",
    "",
    "unknown",
    "",
    "80 years, 2 months, 6 days",
    "",
    "72 years, 9 months, 12 days",
    "unknown",
    "",
    "",
    "",
    "",
    "79 years, 11 months, 5 days",
    "",
    "unknown",
    "74 years",
    "",
    "",
    "",
    "unknown",
    "21 years, 5 months, 20 days",
    "",
    "",
    "unknown",
    "",
    "unknown",
    "",
    "",
    "",
    "74 years, 9 months, 12 days",
    "",
    "0 days",
    "",
    "unknown",
    "86 years, 6 months, 3 days",
    "",
    "",
    "",
    "0 days",
    "",
    "80 years, 9 months, 11 days",
    "",
    "",
    "",
    "",
    "",
    "87 years, 6 months, 3 days",
    "",
    "",
    "",
    "",
    "",
    "51 years, 8 months, 3 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "more than 65 years",
    "83 years, 28 days",
    "",
    "85 years, 3 months, 24 days",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "82 years",
    "1 year",
    "1 year",
    "23 years",
    "",
    "",
    "84 years",
    "",
    "61 years",
    "1 year",
    "63 years",
    "69 years",
    "",
    "86 years",
    "61 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "about 51 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "73 years, 3 months, 5 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "about 32 years, 6 days",
    "91 years",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "86 years, 2 months, 3 days",
    "30 years, 10 months, 4 days",
    "",
    "about 65 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "83 years, 6 months, 26 days",
    "",
    "22 years, 2 months, 5 days",
    "65 years, 7 months, 3 days",
    "",
    "",
    "69 years, 2 months, 6 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "76 years, 6 months, 18 days",
    "",
    "",
    "",
    "",
    "",
    "55 years, 2 months, 6 days",
    "",
    "",
    "0 days",
    "",
    "",
    "76 years, 5 months, 9 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "60 years, 28 days",
    "",
    "",
    "",
    "unknown",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "90 years, 3 months, 23 days",
    "",
    "",
    "",
    "",
    "",
    "75 years, 10 months, 19 days",
    "",
    "82 years, 7 months, 20 days",
    "about 44 years",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "87 years, 1 month, 30 days",
    "",
    "",
    "",
    "",
    "69 years, 11 months, 22 days",
    "69 years, 8 months, 23 days",
    "60 years, 10 months, 7 days",
    "",
    "",
    "",
    "",
    "",
    "18 years, 3 months, 23 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "56 years, 11 months, 18 days",
    "",
    "",
    "",
    "63 years, 8 months, 21 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "4 months, 28 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "about 65 years, 6 months",
    "78 years, 2 months, 22 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "72 years, 1 day",
    "",
    "",
    "",
    "86 years, 9 months, 1 day",
    "",
    "",
    "",
    "",
    "",
    "69 years, 2 months, 20 days",
    "",
    "",
    "",
    "",
    "",
    "64 years, 8 months, 20 days",
    "",
    "68 years, 6 months, 2 days",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "53 years, 27 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "52 years, 1 month, 18 days",
    "",
    "",
    "about 36 years, 8 months, 4 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "69 years, 10 months, 17 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "33 years, 3 months, 16 days",
    "65 years",
    "",
    "",
    "58 years, 10 months, 15 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "66 years, 10 months, 19 days",
    "unknown",
    "",
    "",
    "",
    "",
    "84 years, 7 months",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "86 years, 7 months, 18 days",
    "",
    "",
    "63 years, 8 months, 16 days",
    "unknown",
    "",
    "",
    "73 years",
    "",
    "less than 79 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "62 years, 10 months, 15 days",
    "",
    "",
    "",
    "",
    "90 years, 9 months, 19 days",
    "",
    "",
    "43 years, 4 months, 13 days",
    "60 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "5 years, 10 months, 8 days",
    "",
    "82 years, 3 months, 30 days",
    "unknown",
    "",
    "",
    "",
    "about 59 years, 5 months, 10 days",
    "21 years, 11 months, 2 days",
    "74 years, 6 months, 23 days",
    "",
    "2 years, 2 months, 5 days",
    "",
    "71 years, 11 months, 20 days",
    "84 years, 11 months, 6 days",
    "79 years, 5 months, 2 days",
    "unknown",
    "",
    "unknown",
    "94 years, 30 days",
    "83 years, 9 months, 16 days",
    "79 years, 19 days",
    "unknown",
    "60 years, 6 months, 12 days",
    "85 years, 25 days",
    "",
    "66 years, 11 months, 19 days",
    "51 years, 9 days",
    "unknown",
    "38 years, 2 months, 28 days",
    "unknown",
    "",
    "",
    "",
    "more than 93 years",
    "47 years, 4 months, 25 days",
    "",
    "unknown",
    "90 years, 1 day",
    "66 years, 2 months, 9 days",
    "",
    "",
    "",
    "",
    "about 60 years",
    "",
    "85 years, 3 months",
    "",
    "66 years",
    "89 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "73 years, 10 months, 18 days",
    "",
    "unknown",
    "",
    "about 90 years, 9 months",
    "more than 37 years",
    "",
    "",
    "",
    "73 years, 5 months, 29 days",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "75 years, 7 months, 26 days",
    "",
    "unknown",
    "unknown",
    "",
    "85 years",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "29 years",
    "56 years",
    "47 years",
    "",
    "",
    "unknown",
    "89 years, 2 months, 17 days",
    "about 52 years",
    "",
    "",
    "",
    "",
    "",
    "53 years",
    "80 years",
    "about 89 years",
    "about 50 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "70 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "76 years, 7 months, 7 days",
    "",
    "",
    "",
    "",
    "",
    "44 years, 6 months, 23 days",
    "",
    "44 years, 7 months, 10 days",
    "46 years, 7 months, 24 days",
    "",
    "more than 67 years, 11 months",
    "unknown",
    "",
    "50 years, 11 months, 4 days",
    "",
    "",
    "",
    "73 years",
    "",
    "",
    "",
    "",
    "90 years, 7 months, 29 days",
    "19 years, 17 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "77 years",
    "71 years, 7 months, 29 days",
    "77 years",
    "",
    "84 years, 1 month, 26 days",
    "54 years, 7 months, 27 days",
    "83 years, 28 days",
    "",
    "86 years, 3 months, 2 days",
    "",
    "",
    "",
    "",
    "61 years, 1 month, 27 days",
    "",
    "about 89 years, 3 months, 17 days",
    "85 years, 1 month, 1 day",
    "",
    "",
    "",
    "74 years, 1 month, 4 days",
    "49 years, 9 months, 6 days",
    "62 years, 4 months, 25 days",
    "",
    "",
    "",
    "62 years, 5 months, 9 days",
    "",
    "77 years, 10 months, 17 days",
    "",
    "88 years, 8 months, 13 days",
    "6 months, 16 days",
    "",
    "",
    "7 months",
    "85 years, 6 months, 29 days",
    "",
    "",
    "86 years, 5 months, 1 day",
    "about 44 years, 6 months, 19 days",
    "",
    "",
    "",
    "",
    "63 years, 9 months, 27 days",
    "",
    "",
    "",
    "33 years, 1 month, 1 day",
    "less than 62 years",
    "76 years, 9 months, 10 days",
    "",
    "",
    "75 years, 8 months, 9 days",
    "67 years, 6 months, 1 day",
    "",
    "72 years, 10 months, 20 days",
    "90 years, 3 months, 1 day",
    "87 years, 9 months, 9 days",
    "30 years, 27 days",
    "",
    "",
    "55 years, 5 months",
    "76 years, 2 months, 16 days",
    "81 years, 8 months",
    "",
    "",
    "",
    "",
    "87 years, 1 month, 23 days",
    "",
    "70 years, 4 months, 14 days",
    "39 years, 8 months, 25 days",
    "56 years, 1 month, 28 days",
    "",
    "72 years, 3 months, 21 days",
    "79 years, 11 months, 1 day",
    "more than 60 years",
    "",
    "",
    "",
    "",
    "63 years, 11 months, 14 days",
    "81 years, 8 months, 4 days",
    "",
    "unknown",
    "69 years, 9 months, 15 days",
    "unknown",
    "",
    "65 years, 11 months, 22 days",
    "",
    "",
    "",
    "",
    "70 years, 9 months, 27 days",
    "58 years, 9 months, 3 days",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "51 years, 6 months, 25 days",
    "",
    "",
    "unknown",
    "about 93 years, 4 months, 1 day",
    "",
    "44 years, 8 months, 7 days",
    "",
    "",
    "86 years, 1 month, 1 day",
    "87 years, 10 months",
    "",
    "63 years, 10 months, 11 days",
    "",
    "",
    "about 78 years, 1 month, 24 days",
    "",
    "",
    "unknown",
    "81 years, 10 months, 9 days",
    "",
    "",
    "unknown",
    "",
    "",
    "about 80 years, 9 months, 20 days",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "about 77 years, 3 months, 11 days",
    "",
    "",
    "78 years, 1 month, 11 days",
    "",
    "about 24 years, 11 months, 11 days",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "25 years, 7 months, 18 days",
    "",
    "78 years, 3 months, 18 days",
    "",
    "",
    "unknown",
    "",
    "45 years, 10 months, 5 days",
    "72 years, 2 months, 3 days",
    "69 years, 3 months, 14 days",
    "",
    "",
    "",
    "42 years",
    "",
    "",
    "",
    "",
    "46 years, 9 months, 16 days",
    "63 years, 11 months, 5 days",
    "",
    "",
    "",
    "58 years, 7 months, 28 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "76 years, 8 days",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "less than 68 years",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "85 years",
    "",
    "87 years, 4 months, 11 days",
    "",
    "",
    "",
    "",
    "",
    "37 years, 11 months, 2 days",
    "unknown",
    "",
    "",
    "",
    "65 years, 6 months, 29 days",
    "",
    "",
    "about 58 years, 9 months, 25 days",
    "67 years, 11 months, 5 days",
    "",
    "73 years, 5 months, 17 days",
    "",
    "",
    "",
    "",
    "",
    "57 years, 10 months, 28 days",
    "",
    "64 years, 4 months, 16 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "83 years, 6 months, 30 days",
    "",
    "",
    "",
    "",
    "",
    "more than 65 years",
    "",
    "",
    "87 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "68 years, 5 months, 27 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "52 years",
    "",
    "",
    "7 days",
    "",
    "",
    "",
    "",
    "",
    "76 years",
    "58 years, 22 days",
    "",
    "",
    "65 years",
    "42 years",
    "about 32 years, 9 months, 23 days",
    "",
    "",
    "",
    "",
    "",
    "48 years",
    "26 years",
    "",
    "unknown",
    "",
    "unknown",
    "less than 52 years",
    "",
    "about 93 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "70 years, 2 months, 28 days",
    "69 years, 5 months, 29 days",
    "",
    "56 years, 11 months, 1 day",
    "51 years",
    "38 years",
    "more than about 79 years",
    "",
    "",
    "29 years, 9 months, 17 days",
    "",
    "",
    "67 years, 11 months",
    "",
    "",
    "",
    "82 years, 3 months, 30 days",
    "65 years",
    "",
    "",
    "",
    "",
    "",
    "84 years, 8 months, 19 days",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "49 years, 1 month, 22 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "about 48 years",
    "",
    "",
    "",
    "82 years, 10 months, 26 days",
    "",
    "",
    "",
    "",
    "about 54 years, 8 months, 20 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "91 years, 9 months, 15 days",
    "",
    "",
    "unknown",
    "",
    "89 years, 1 month",
    "",
    "63 years, 4 months, 3 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "46 years, 2 months, 11 days",
    "",
    "",
    "more than about 22 years",
    "",
    "72 years",
    "",
    "",
    "",
    "about 84 years, 4 months, 7 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "75 years, 6 months, 12 days",
    "",
    "",
    "about 26 years, 6 months, 13 days",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "80 years, 4 months, 6 days",
    "",
    "",
    "",
    "",
    "",
    "79 years, 5 months, 20 days",
    "about 52 years",
    "",
    "93 years",
    "",
    "",
    "",
    "47 years, 10 months, 28 days",
    "",
    "79 years",
    "47 years, 2 months",
    "",
    "",
    "",
    "unknown",
    "39 years",
    "",
    "",
    "",
    "45 years",
    "77 years, 3 months, 15 days",
    "",
    "53 years",
    "66 years, 6 months, 28 days",
    "greater than 110 years",
    "",
    "",
    "unknown",
    "72 years, 1 month, 5 days",
    "",
    "",
    "85 years",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "72 years, 4 months, 21 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "95 years, 8 months, 24 days",
    "",
    "88 years, 1 month, 13 days",
    "",
    "",
    "",
    "76 years, 1 month, 12 days",
    "63 years, 4 months, 15 days",
    "87 years, 9 months, 9 days",
    "54 years, 11 months, 2 days",
    "88 years, 11 months, 29 days",
    "48 years, 1 month, 17 days",
    "",
    "",
    "",
    "2 years, 6 months, 22 days",
    "",
    "32 years, 6 months, 1 day",
    "",
    "37 years",
    "",
    "36 years, 4 months, 5 days",
    "19 years, 9 months",
    "",
    "",
    "0 days",
    "17 days",
    "74 years, 10 months, 10 days",
    "93 years, 4 months, 23 days",
    "",
    "",
    "",
    "87 years, 1 month, 27 days",
    "85 years, 2 months, 23 days",
    "",
    "more than 47 years, 3 months",
    "79 years, 1 month, 25 days",
    "81 years, 10 months, 11 days",
    "",
    "",
    "",
    "53 years, 6 months, 5 days",
    "15 years, 4 months",
    "",
    "",
    "about 1 year, 1 month, 8 days",
    "72 years, 2 months, 6 days",
    "",
    "78 years, 5 months, 23 days",
    "44 years, 11 months",
    "87 years, 1 month, 27 days",
    "",
    "97 years, 4 months, 12 days",
    "75 years, 4 months, 21 days",
    "",
    "28 years, 4 months, 14 days",
    "78 years, 7 months, 13 days",
    "75 years, 8 months, 2 days",
    "68 years, 11 months, 4 days",
    "73 years, 7 months, 19 days",
    "about 66 years",
    "about 1 year, 5 days",
    "73 years, 8 months, 26 days",
    "77 years, 5 months, 6 days",
    "",
    "91 years, 7 months, 14 days",
    "",
    "57 years, 9 months, 17 days",
    "",
    "35 years, 8 months, 24 days",
    "",
    "19 years, 9 months, 12 days",
    "",
    "79 years, 5 months, 18 days",
    "78 years, 1 month, 11 days",
    "62 years, 11 months, 5 days",
    "",
    "76 years, 11 months",
    "",
    "66 years, 8 months, 24 days",
    "",
    "34 years, 6 months, 11 days",
    "83 years, 6 months, 28 days",
    "unknown",
    "",
    "72 years, 6 months, 26 days",
    "",
    "41 years, 5 months, 21 days",
    "6 months, 19 days",
    "",
    "85 years, 5 months, 14 days",
    "",
    "",
    "72 years, 9 months, 18 days",
    "",
    "",
    "",
    "47 years, 10 months, 10 days",
    "",
    "40 years, 4 months, 30 days",
    "36 years, 6 months, 26 days",
    "40 years, 11 months, 8 days",
    "63 years, 2 months, 19 days",
    "",
    "22 years, 1 month, 3 days",
    "76 years, 4 months, 3 days",
    "less than 4 years",
    "",
    "58 years, 11 months",
    "85 years, 25 days",
    "66 years, 8 months, 4 days",
    "74 years, 20 days",
    "76 years, 8 months, 15 days",
    "",
    "44 years, 6 months, 6 days",
    "27 years, 5 months, 4 days",
    "62 years, 7 months, 28 days",
    "65 years, 9 months, 9 days",
    "69 years, 2 months, 26 days",
    "",
    "",
    "89 years, 5 months, 6 days",
    "",
    "16 years, 6 months, 18 days",
    "80 years, 11 months, 14 days",
    "1 year, 11 months, 23 days",
    "",
    "",
    "less than 11 years",
    "62 years, 8 months, 4 days",
    "",
    "",
    "",
    "",
    "22 years, 7 months, 8 days",
    "66 years, 5 months, 14 days",
    "",
    "",
    "87 years, 11 months, 10 days",
    "",
    "84 years, 9 months, 19 days",
    "",
    "2 months, 16 days",
    "unknown",
    "about 0 days",
    "",
    "",
    "0 days",
    "0 days",
    "",
    "",
    "0 days",
    "0 days",
    "42 years, 8 months, 16 days",
    "68 years, 9 months, 27 days",
    "1 year, 15 days",
    "86 years, 3 months, 11 days",
    "",
    "69 years, 10 months, 7 days",
    "41 years, 2 months, 25 days",
    "94 years, 6 months, 19 days",
    "1 year, 9 months, 30 days",
    "73 years, 28 days",
    "",
    "",
    "",
    "60 years, 8 months, 22 days",
    "69 years, 7 months, 20 days",
    "82 years, 11 months, 21 days",
    "77 years, 6 months, 9 days",
    "51 years, 1 month, 15 days",
    "58 years, 5 months, 15 days",
    "45 years, 4 months",
    "74 years, 1 month, 2 days",
    "",
    "",
    "69 years, 4 months, 5 days",
    "61 years, 10 months, 21 days",
    "",
    "72 years, 2 months, 20 days",
    "about 84 years",
    "74 years, 1 month, 15 days",
    "84 years, 10 months, 24 days",
    "77 years, 5 months, 28 days",
    "64 years, 4 months, 5 days",
    "51 years, 9 months",
    "65 years, 6 months, 20 days",
    "less than 40 years",
    "",
    "63 years, 6 months, 30 days",
    "87 years, 1 month, 19 days",
    "66 years, 9 months, 29 days",
    "92 years, 8 months, 13 days",
    "74 years, 26 days",
    "",
    "70 years, 3 months, 22 days",
    "21 years, 1 month, 28 days",
    "",
    "",
    "92 years, 8 months, 25 days",
    "",
    "",
    "73 years, 9 months, 29 days",
    "",
    "5 years, 1 month, 27 days",
    "",
    "4 years, 10 months, 11 days",
    "79 years, 2 months, 15 days",
    "",
    "",
    "",
    "90 years, 1 month, 23 days",
    "21 years, 9 months, 20 days",
    "",
    "",
    "",
    "66 years, 2 months, 23 days",
    "1 year, 8 months, 5 days",
    "1 year, 2 months, 13 days",
    "89 years, 3 months, 25 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "more than 72 years, 1 month",
    "68 years, 8 months, 8 days",
    "70 years, 4 months, 17 days",
    "74 years, 10 months",
    "50 years, 9 days",
    "75 years, 5 months, 18 days",
    "30 years, 4 months, 23 days",
    "68 years, 5 months, 9 days",
    "65 years, 3 months, 10 days",
    "",
    "76 years, 10 months, 23 days",
    "",
    "74 years, 4 months, 4 days",
    "67 years, 8 months, 19 days",
    "69 years, 2 months, 29 days",
    "26 years, 11 months, 6 days",
    "81 years, 7 months, 3 days",
    "",
    "",
    "33 years, 10 months, 8 days",
    "",
    "",
    "65 years, 3 months, 2 days",
    "85 years, 2 months, 7 days",
    "41 years, 11 months, 4 days",
    "",
    "",
    "",
    "",
    "",
    "77 years, 6 months, 21 days",
    "",
    "unknown",
    "76 years, 2 months, 9 days",
    "",
    "",
    "57 years, 6 months, 10 days",
    "80 years, 5 months, 18 days",
    "",
    "",
    "",
    "",
    "more than 81 years, 2 months",
    "",
    "43 years, 11 months, 27 days",
    "72 years, 9 months, 10 days",
    "81 years, 10 months, 1 day",
    "",
    "67 years, 8 months, 30 days",
    "69 years, 4 months, 28 days",
    "72 years, 8 months, 17 days",
    "66 years, 11 months, 6 days",
    "82 years, 7 months, 28 days",
    "70 years, 2 months, 6 days",
    "",
    "80 years, 6 months, 25 days",
    "14 days",
    "92 years, 3 months, 20 days",
    "",
    "39 years, 7 months, 29 days",
    "60 years, 11 months, 6 days",
    "",
    "",
    "94 years, 7 months, 8 days",
    "",
    "66 years, 4 months, 14 days",
    "2 years, 8 months, 19 days",
    "",
    "",
    "",
    "",
    "81 years, 10 months, 28 days",
    "",
    "",
    "80 years, 2 months, 9 days",
    "85 years, 9 months, 28 days",
    "81 years, 6 months, 19 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "77 years, 10 months, 26 days",
    "83 years, 3 months, 18 days",
    "60 years, 3 months, 28 days",
    "unknown",
    "",
    "92 years, 7 months, 12 days",
    "",
    "unknown",
    "",
    "",
    "2 years, 8 months, 11 days",
    "",
    "79 years, 5 months, 26 days",
    "less than 10 years",
    "",
    "77 years, 6 months, 1 day",
    "72 years, 8 months, 12 days",
    "86 years, 1 day",
    "",
    "",
    "78 years, 5 months, 22 days",
    "33 years, 9 months, 29 days",
    "about 73 years, 4 months, 7 days",
    "4 months, 26 days",
    "83 years, 11 months, 19 days",
    "79 years, 7 months, 28 days",
    "",
    "3 months, 12 days",
    "",
    "44 years, 7 days",
    "81 years, 7 months, 29 days",
    "85 years, 5 days",
    "76 years, 4 months, 12 days",
    "30 years, 9 days",
    "54 years, 3 months, 24 days",
    "89 years, 5 months, 28 days",
    "",
    "",
    "",
    "88 years, 11 months, 11 days",
    "",
    "",
    "41 years, 22 days",
    "",
    "",
    "80 years, 28 days",
    "",
    "",
    "",
    "",
    "67 years, 2 months, 16 days",
    "64 years, 1 month, 16 days",
    "",
    "",
    "",
    "99 years, 3 days",
    "",
    "",
    "47 years",
    "",
    "",
    "",
    "58 years, 9 months, 28 days",
    "unknown",
    "unknown",
    "",
    "81 years, 10 months, 27 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "57 years",
    "",
    "",
    "89 years",
    "",
    "89 years, 13 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "88 years",
    "",
    "",
    "",
    "54 years, 10 months, 25 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "less than about 73 years",
    "",
    "77 years, 6 months, 7 days",
    "",
    "",
    "",
    "",
    "85 years, 4 months, 7 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "67 years, 3 months, 28 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "about 81 years, 10 months",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "73 years",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "78 years, 7 months, 4 days",
    "less than 4 years, 5 months, 22 days",
    "",
    "unknown",
    "83 years, 4 months, 4 days",
    "",
    "",
    "43 years, 2 months, 12 days",
    "less than 60 years, 3 months, 10 days",
    "unknown",
    "19 years, 9 months, 21 days",
    "",
    "4 months, 23 days",
    "76 years, 6 months, 19 days",
    "",
    "",
    "",
    "",
    "19 years, 1 month, 10 days",
    "",
    "87 years, 5 months",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "less than about 76 years",
    "less than 60 years, 3 months, 8 days",
    "",
    "13 years, 2 months, 8 days",
    "unknown",
    "",
    "",
    "",
    "82 years, 5 months, 16 days",
    "21 years, 5 months, 21 days",
    "0 days",
    "",
    "",
    "26 years, 6 months, 1 day",
    "",
    "68 years, 10 months, 28 days",
    "3 years, 24 days",
    "",
    "",
    "",
    "unknown",
    "68 years, 10 months, 17 days",
    "",
    "87 years, 4 months, 11 days",
    "about 5 years",
    "",
    "",
    "89 years, 1 month, 21 days",
    "17 years, 11 months, 26 days",
    "unknown",
    "30 years, 8 months, 26 days",
    "",
    "",
    "",
    "",
    "63 years, 4 months, 20 days",
    "less than 30 years, 8 days",
    "98 years, 7 months, 23 days",
    "63 years, 5 months, 10 days",
    "unknown",
    "90 years, 7 months, 9 days",
    "20 years, 9 months, 16 days",
    "",
    "",
    "79 years, 9 months, 4 days",
    "",
    "1 month, 11 days",
    "77 years, 1 month, 4 days",
    "",
    "70 years, 9 months, 25 days",
    "",
    "",
    "72 years, 9 months, 2 days",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "unknown",
    "",
    "",
    "",
    "",
    "",
    "",
    "91 years",
    "",
    "",
    "",
    "97 years, 4 months, 1 day",
    "",
    "",
    "",
    "63 years, 7 months, 4 days",
    "",
    "",
    "",
    "",
    "72 years, 7 months, 1 day",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "77 years, 11 months, 5 days",
    "",
    "",
    "",
    "",
    "39 years, 8 months, 5 days",
    "",
    "70 years, 7 months, 17 days",
    "56 years, 1 month, 23 days",
    "",
    "",
    "73 years, 9 months, 1 day",
    "13 years, 6 months, 6 days",
    "",
    "67 years, 11 months, 3 days",
    "",
    "",
    "",
    "",
    "",
    "30 years, 8 months, 10 days",
    "",
    "",
    "",
    "greater than 110 years",
    "74 years, 1 month, 18 days",
    "",
    "",
    "68 years",
    "67 years",
    "",
    "about 60 years, 2 months, 24 days",
    "",
    "57 years",
    "",
    "",
    "unknown"
]
scriptLoaded('dwr_db_I_death_age_23.js');
