// This file is generated

I_death_place_14 = [
    "Poplar Bluff, MO [P20768] [P55402]",
    "",
    "",
    "",
    "",
    "",
    "Tower of London,Tower Green,London,England [P19663] [P54187]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P2618] [P57572]",
    "",
    "",
    "",
    "",
    "Roseboro, NC [P2836] [P57790]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Rex Hospital, Raleigh, NC [P2799] [P57753]",
    "",
    "",
    "",
    "Harnett Co, NC [P2618] [P57572]",
    "Raleigh, NC [P2640] [P57594]",
    "Cokesbury Meth, Chur Cem, Harnett Co, NC [P2948] [P57902]",
    "",
    "Iron Mountain, MI [P1369]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Ottawa, IL [P20143] [P38772]",
    "",
    "",
    "Ottawa, IL [P20143] [P38772]",
    "",
    "Athens, GA [P20185] [P38815]",
    "Ottawa, IL [P20143] [P38772]",
    "Towns Co, GA [P9933]",
    "",
    "Union Co, GA [P10284]",
    "",
    "",
    "Pleasant Grove, Rest Home,  Wake Co, NC [P9628] [P22025]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Alexandria, LA",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co?, NC",
    "",
    "",
    "",
    "",
    "",
    "Winston Salem, NC [P10026]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Trenton, NJ [P9498]",
    "",
    "",
    "",
    "Sumter, AL [P9939]",
    "Dickinson, ND [P8720]",
    "",
    "",
    "",
    "",
    "",
    "Duluth, MN [P1584]",
    "Martinsville, VA [P1362]",
    "",
    "",
    "",
    "",
    "",
    "Duluth, MN [P1584]",
    "",
    "",
    "",
    "Montrose, CO [P20020]",
    "",
    "Grand Forks, ND [P20055]",
    "",
    "",
    "",
    "Claiborne Co, TN, Sycamore Creek area [P2182] [P56559]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Carter Co, TN [P2526]",
    "",
    "Harnett Co., NC [P9544]",
    "High Point Hospital, High Point, NC [P9811]",
    "",
    "Home Plc, Harnett Co, NC [P9485]",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "Durham Co, Durham, NC [P9907]",
    "Harnett Co, NC [P9502]",
    "",
    "Harnett Co, NC [P9502]",
    "Harnett Co, NC [P9502]",
    "Harnett Co, NC [P9502]",
    "Moses Cone Hospital, Greensboro, NC [P9873]",
    "",
    "",
    "Hwy 42 West, , Wake Co, NC [P9639]",
    "",
    "Durham Co, Durham, NC [P9907]",
    "Mamers, Harnett Co, NC [P9555]",
    "",
    "",
    "",
    "Mamers, , Harnett Co, NC [P9655]",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Home, Cary, Wake Co, NC [P9903]",
    "High Point Hospital, High Point, NC [P9811]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cardoss Castle,Firth of Clyde,Scotland [P0550]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sicily, Italy [P9838]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Thomas Cem. [P1851]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN",
    "Not in 1870 census",
    "Sevier Co, TN, Alder Branch Cem.",
    "Sevier Co, TN",
    "Sevier Co, TN, Atchley Cem.",
    "",
    "",
    "Sevier Co, Tn",
    "Sevier Co, TN",
    "Sevier Co, TN, Alderbranch Cem.",
    "Possibly J. R. Atchley, Alderbranch Cem., died",
    "Loudon Co, VA",
    "",
    "Sevier Co, TN",
    "",
    "",
    "Sevier Co, TN, Alderbranch Cem.",
    "",
    "Sevier Co, TN, Red Bank Cem.",
    "Sevier Co, TN, Shiloh Cem.",
    "Sevier Co, TN, Alder Branch Cem.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Berlin, NH [P1146] [P1146] [P37133]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Tower of London,Tower Green,London,England [P0349] [P0349]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cosby, TN, Holders Grove Cem [P9009] [P21406] [P56104]",
    "",
    "",
    "Sevier Co, TN, Trundle Family Cem. [P8798] [P21195] [P55872]",
    "",
    "Sevier Co, TN, behind Shults Grove Methodist Cem. [P1857] [P1857]",
    "Jefferson Co, Tn, Duggan Fam. Burying Ground [P8935] [P21332]",
    "",
    "",
    "2n Sgt Tenn Mounted Inf, War 1812 [P8787] [P21184]",
    "Sevier Co, TN, Mt. Pleasant Cem. [P1896] [P1896]",
    "",
    "Sevier Co, TN, Mt. Pleasant Cem., Jones Cove [P8941] [P21338]",
    "Sevier Co, TN, Allen Cem. [P8932] [P21329]",
    "",
    "",
    "Sevier Co, TN, Henry's Crossroads Cem. [P8933] [P21330]",
    "",
    "Sevier Co, TN [P8763] [P21160]",
    "Sevier CO, Tennessee [P8957] [P21354]",
    "",
    "Sevier Co, TN, TN, Mt. Pleasant Cem., Jones Cove [P8942] [P21339]",
    "Sevier Co, TN, Emerts Cove Cem., unmarked [P9298] [P21695]",
    "",
    "Knox Co, TN, Thorn Grove Cem. [P8940] [P21337]",
    "Sevier Co, TN [P8763] [P21160]",
    "",
    "",
    "",
    "Harnett Co, NC [P9502] [P21899] [P56646]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Columbus, MS [P1167] [P1167]",
    "",
    "",
    "Tyrrell County, North Carolina [P8774] [P21171]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "San Angelo, TX [P1330] [P1330]",
    "",
    "",
    "Marquette, MI [P20378]",
    "San Diego, CA [P20058]",
    "Morristown, TN [P20597]",
    "",
    "Sevier Co, TN, Shults Grove Cem. [P9137] [P21534] [P40183]",
    "",
    "",
    "",
    "Macedonia BapChurCem, Harnett Co, NC [P2694] [P57648]",
    "",
    "Estoril,Portugal [P0385] [P0385] [P0385]",
    "",
    "",
    "Hospital in KY [P3077]",
    "",
    "Cosby, TN, Holders Grove Cem [P2125]",
    "",
    "",
    "Tampa, Florida [P10188] [P50648]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "Harnett Co, NC [P9502]",
    "Guayama, PR [P1148]",
    "",
    "",
    "Macedonia BapChurCem, Harnett Co, NC [P9578]",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "",
    "Harnett  Co, NC [P9507]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Topeka, Shawnee Co, KS [P19572] [P54087]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, White Oak Flats Cem. [P1890] [P1890] [P1890]",
    "Sevier CO, TN, Shults Cem 11.2 mi from Gatlinburg [P9267] [P21664] [P56388]",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN [P8763] [P21160] [P55834]",
    "",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P1732] [P1732] [P53032]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Wake Co?, NC",
    "",
    "",
    "Living, Harnett Co, NC",
    "",
    "",
    "",
    "",
    "",
    "Parkers Creek, Harnett Co, NC [P9791] [P52257]",
    "",
    "Ottawa, IL [P20143] [P54715]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "McAlester, OK [P20271] [P54856]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "NC",
    "Washington Co, VA",
    "",
    "",
    "Washington Co, VA",
    "",
    "",
    "",
    "Harnett Co, NC",
    "",
    "Macedonia Bpt ChurCem, Harnett Co., NC",
    "",
    "",
    "Harnett Co. NC",
    "",
    "Harnett Co. NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC",
    "Cameron, NC",
    "Cumberland Co?, NC",
    "",
    "Harnett Co, NC",
    "",
    "Chatham Co, NC",
    "",
    "",
    "Northampton, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Emerts Cove Cem. [P42264]",
    "St. James Palace,London,England [P0125] [P0125] [P49703]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "NC [P20842]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Hopewell, NJ",
    "",
    "Palermo, Sicily",
    "",
    "",
    "",
    "",
    "Owen Co, Jefferson Twsp, IN [P44591]",
    "Sterling, IL [P41882]",
    "",
    "Living in Knightdale, NC 266-1767 [P44766]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Point Pleasant, WV [P1451] [P43188]",
    "",
    "",
    "Sevier Co, TN [P8763] [P21160] [P39797]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Mount Vernon, WA [P1001] [P61094]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sunset Cem., Cleveland Co, Shelby, NC [P19551] [P38180]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Wake Co, NC",
    "",
    "Harnett Co, NC",
    "",
    "",
    "",
    "Harnett Co, NC",
    "",
    "Fuquay Varina, NC",
    "",
    "",
    "",
    "Macedonia Bpt, Chur Cem, Harnett Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "Macedonia BapChurCem, Harnett Co, NC",
    "",
    "",
    "Harnett Co?, NC",
    "",
    "",
    "",
    "",
    "Harnett Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "NC",
    "",
    "",
    "",
    "Macedonia BapChurCem, Harnett Co, NC",
    "Harnett Co, NC",
    "",
    "",
    "",
    "",
    "Wake Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Macedonia BapChurCem, Harnett Co, NC",
    "Harnett Co, NC",
    "",
    "",
    "",
    "",
    "Macedonia BapChurCem?, Harnett Co, NC",
    "",
    "",
    "Harnett Co, NC",
    "",
    "House Creek Township, Wake Co, NC",
    "",
    "",
    "Harnett Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Grand Junction, CO [P1626] [P1626] [P1626]",
    "",
    "",
    "",
    "",
    "",
    "Louisville, KY",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Kokomo, IN",
    "",
    "",
    "",
    "",
    "Sevier Co, TN",
    "",
    "Duluth, MN [P4854] [P59808]",
    "",
    "Mooresville, NC",
    "",
    "Russell Co, VA",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Oxnard, CA",
    "",
    "",
    "",
    "",
    "",
    "",
    "Baltimore, MD",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "New Philadelphia, OH",
    "Portland, OR",
    "Honolulu, HI",
    "Fairfax Co, VA",
    "",
    "Hawkins Co, TN",
    "",
    "",
    "",
    "",
    "",
    "",
    "Blount Co, TN, Clarks Grove Cem. [P2498] [P57452]",
    "",
    "",
    "",
    "",
    "Whitley Co, KY, Bethel Baptist Cem",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Raleigh, NC [P9524]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Ottawa, IL [P20143] [P38772]",
    "",
    "",
    "",
    "Paris,France [P3554] [P3554]",
    "",
    "",
    "",
    "",
    "Waterloo-Cedar Falls, IA [P42040]",
    "Coffeyville, KS [P4374]",
    "",
    "",
    "Marshall, MN [P42036]",
    "",
    "",
    "",
    "Orlando, FL [P4429]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Marshall, MN [P42036]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "NC [P1749]",
    "",
    "",
    "Bunn Level, , Harnett Co, NC [P9977]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Adjuntas, PR [P20436] [P39068]",
    "",
    "Ottawa, IL [P20143] [P38772]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Ottawa, IL [P20143] [P38772]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Midland, MI [P20392] [P39024]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Home Plc, Harnett Co, NC [P2601] [P41294]",
    "",
    "",
    "",
    "",
    "",
    "Troy, AL [P41955]",
    "Troy, AL [P41955]",
    "Troy, AL [P41955]",
    "Troy, AL [P41955]",
    "Troy, AL [P41955]",
    "Troy, AL [P41955]",
    "Troy, AL [P41955]",
    "Palm Coast, FL [P10554]",
    "Troy, AL [P41955]",
    "Troy, AL [P41955]",
    "Palm Coast, FL [P10554]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Trundle Family Cem. [P8798]",
    "",
    "",
    "",
    "",
    "Tennessee, probably Monroe Co. [P8878]",
    "",
    "Sevier Co, TN, Trundle Family Cem. [P8798]",
    "Knox Co, TN, Grassy Valley Community [P8850]",
    "Sevier Co, TN, Trundle Family Cem. [P8798]",
    "",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P1732]",
    "",
    "",
    "",
    "Roane Co, TN (now Loudon Co) [P8888]",
    "Cumberland Co, VA [P8856]",
    "Sevier Co, TN, Trundle Family Cem. [P8798]",
    "Sevier Co, TN, Trundle Family Cem. [P8798]",
    "",
    "Venice,Italy [P0216] [P0216] [P0216]",
    "",
    "",
    "",
    "",
    "Windsor Castle,Windsor,Berkshire,England [P3544] [P58498]",
    "Augusta Lodge,Windsor,Berkshire,England [P3580] [P58534]",
    "Cavendish Square,,London,England [P3619] [P58573]",
    "The Hague [P3618] [P58572]",
    "London,England [P3470] [P58424]",
    "Clarence House,St. James [P3573] [P58527]",
    "Kensington Palac [P3576] [P58530]",
    "St. James Palace,,,England [P19595] [P54112]",
    "",
    "Celle [P3630] [P58584]",
    "Claremont House,Esher,Surrey,England [P3556] [P58510]",
    "Furstenhof,Hanover [P3584] [P58538]",
    "Ludwigsburg [P3571] [P58525]",
    "",
    "",
    "",
    "Sidmouth,Devon,,England [P3550] [P58504]",
    "Monaco [P3628] [P58582]",
    "Gloucester House [P3629] [P58583]",
    "Frankfurt,-am-Main [P3574] [P58528]",
    "Kew Palace [P3547] [P58501]",
    "St. James Palac [P19590] [P54107]",
    "",
    "",
    "",
    "",
    "",
    "Herrenhausen [P3575] [P58529]",
    "",
    "Madrid,Spain [P3656] [P58610]",
    "Rutland House,Arlington St.,London,England [P3568] [P58522]",
    "Leicester-House,,London,England [P3617] [P58571]",
    "Leicester House [P19596] [P54113]",
    "",
    "",
    "",
    "Kensington,Palace,London,England [P3442] [P58396]",
    "",
    "Osnabruck [P3632] [P58586]",
    "Kensington,Palace,London,England [P3442] [P58396]",
    "Windsor Castle,Windsor,Berkshire,England [P3544] [P58498]",
    "Windsor Castle,Berkshire,England [P3446] [P58400]",
    "Paris,France [P3554] [P58508]",
    "",
    "",
    "",
    "London,,,England [P19597] [P54114]",
    "Christiansborg,Denmark [P3625] [P58579]",
    "Carlton House [P19586] [P54102]",
    "",
    "",
    "",
    "Gloucester House,Piccadilly,London,England [P3577] [P58531]",
    "",
    "Hanau [P3623] [P58577]",
    "",
    "",
    "Kew Palace [P3547] [P58501]",
    "",
    "",
    "",
    "Vicarage Place,Kensington [P3578] [P58532]",
    "",
    "Monbijou Palace,,Berlin,Germany [P3634] [P58588]",
    "Osborne House,Isle of Wight,England [P3443] [P58397]",
    "London,,,England [P19597] [P54114]",
    "Windsor Castle,Windsor,Berkshire,England [P3544] [P58498]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Fowler Cem. [P8898]",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Fowler Cem. [P8898]",
    "",
    "",
    "Sicily, Italy [P2954] [P41637]",
    "",
    "",
    "Sevier Co, TN [P8763] [P21160] [P39797]",
    "",
    "Sevier Co, TN [P8763] [P21160] [P39797]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sunset Cem., Shelby, Cleveland Co, NC",
    "",
    "",
    "",
    "",
    "Sterling, IL [P1038] [P61131]",
    "",
    "",
    "",
    "Andrews, TX [P1104] [P61197]",
    "Whitewater, WI [P1390] [P61481]",
    "",
    "",
    "",
    "",
    "Raleigh, NC [P2640] [P57594]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Richardson Cove Cem. [P19226] [P37855]",
    "",
    "",
    "Holders Grove Cem [P2438] [P41210]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Worthington, MN [P1385] [P1385] [P1385]",
    "",
    "Ottawa, IL [P0978] [P0978] [P0978]",
    "Spearfish, SD [P1630] [P1630] [P1630]",
    "Ottawa, IL [P0978] [P0978] [P0978]",
    "Ottawa, IL [P0978] [P0978] [P0978]",
    "Midland, MI [P1243] [P1243] [P37195]",
    "",
    "Worthington, MN [P1385] [P1385] [P1385]",
    "",
    "",
    "",
    "",
    "Worthington, MN [P1385] [P1385] [P1385]",
    "Hutchinson, KS [P1145] [P1145] [P37132]",
    "Lewisburg, PA [P1448] [P1448] [P1448]",
    "",
    "Ottawa, IL [P0978] [P0978] [P0978]",
    "",
    "",
    "",
    "",
    "",
    "Dustin, OK [P62803]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Fremont, NE [P59718]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Milledgeville, GA [P59785]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P2618] [P57572]",
    "",
    "",
    "See note.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Oakland, CA [P1098] [P61191]",
    "",
    "Columbus, IN [P1553] [P61644]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Columbus, IN [P1553] [P61644]",
    "",
    "Baraboo, WI [P1314] [P61406]",
    "",
    "Paragould, AR [P8746] [P51107]",
    "",
    "Gary, IN [P0942] [P61035]",
    "",
    "Hays, KS [P0878] [P60971]",
    "",
    "Twin Falls, ID [P1678] [P61769]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Killeen, TX [P0903] [P60996]",
    "",
    "",
    "Columbus, IN [P1553] [P61644]",
    "Cedar City, UT [P0871] [P60964]",
    "",
    "",
    "Shawnee, OK [P1539] [P61630]",
    "",
    "Twin Falls, ID [P1678] [P61769]",
    "Twin Falls, ID [P1678] [P61769]",
    "",
    "Ottawa, IL [P0978] [P61071]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Astoria, OR [P0897] [P60990]",
    "",
    "",
    "Alice, TX [P0964] [P61057]",
    "",
    "",
    "",
    "Marshalltown, IA [P8747] [P51108]",
    "Portsmouth, OH [P1388] [P61479]",
    "",
    "",
    "",
    "",
    "",
    "Battle Creek, MI [P1523] [P61614]",
    "",
    "Columbus, GA-AL",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Beckley, WV [P1461]",
    "Buenos Aires,Argentina",
    "",
    "",
    "",
    "",
    "",
    "Ottawa, IL [P0978] [P61071]",
    "",
    "Washington Co, NC [P1772] [P61863]",
    "",
    "",
    "",
    "Ottawa, IL [P0978] [P61071]",
    "",
    "",
    "Borgetto, Sicily, Italy",
    "Borgetto, Sicily, Italy",
    "Buckhorn Twsp, Harnett Co, NC [P3231] [P58185]",
    "",
    "",
    "",
    "",
    "Haywood, NC [P3065] [P58019]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Caswell Co, NC [P1965] [P54172]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Marshall, MN [P1556]",
    "Savannah, GA [P1452]",
    "Merced, CA [P1510]",
    "",
    "",
    "",
    "Berkhamsted [P0232] [P0232] [P0232]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502] [P21899] [P40568]",
    "Harnett Co, NC [P9502] [P21899] [P40568]",
    "",
    "Cumberland UnionBaptChurCem, Harnett Co, NC [P9671] [P22068] [P40747]",
    "",
    "",
    "",
    "City Cem, Sanford, NC [P9731] [P22128] [P40811]",
    "",
    "",
    "",
    "Riverside, CA [P20499] [P39131]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Helena, MT [P0990] [P0990] [P36951]",
    "Myrtle Beach, SC [P1661] [P1661] [P1661]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cleveland Co, NC [P9965] [P22362] [P41059]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Nr Cassel,France [P8718]",
    "",
    "#6 Via Dilluvio, Borgetto, Sicily, Italy [P10215]",
    "",
    "",
    "",
    "Sevier Co, TN, White Oak Flats Cem. [P1890]",
    "",
    "",
    "",
    "",
    "",
    "Freehold, NJ [P3300]",
    "Rutherford, NJ [P3297]",
    "",
    "NY City, NY [P3314]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Portsmouth, VA [P9687] [P22084] [P40764]",
    "",
    "",
    "",
    "",
    "",
    "Santa Fe, NM",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Chalk Level, Harnett Co, NC [P9645] [P22042] [P40719]",
    "Harnett Co, NC [P9502] [P21899] [P40568]",
    "Sevier Co, TN, Mt. Pleasant Cem., Jones Cove [P8941]",
    "Sevier Co, TN, Shiloh Cem. [P1732]",
    "Knoxville, TN [P1494] [P1494] [P37320]",
    "Wethersfield, Hartford, CT [P10134]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Golf Course Cem., Pigeon Forge [P20871]",
    "",
    "Sevier Co, TN [P1726]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Died in North Carolina [P20902]",
    "",
    "",
    "",
    "",
    "Anderson Co, TN; buried Sevier Co, TN, Shiloh Cem. [P20817]",
    "Whole career 1969- at DOE Y-12 Plant in Oak Ridge, TN [P20808]",
    "",
    "McCreary Co, KY, Bethel Baptist Cem. [P20837]",
    "Sevier Co, TN, Shiloh Cem. [P20829]",
    "",
    "",
    "",
    "",
    "",
    "Whitley Co, KY, Wolf Creek Cem. [P1767]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "South Carolina [P20919]",
    "Whitley Co, KY [P1735]",
    "Whitley Co, KY, Wolf Creek Cem. [P1767]",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P20829]",
    "",
    "McCreary Co, KY, Davenport-Ball Cemetery [P2549]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Washington Co, NC [P20861]",
    "Whitley Co, KY, Wolf Creek Cem. [P1767]",
    "Tyrrell Co, NC [P1771]",
    "",
    "",
    "",
    "",
    "Washington Co, NC [P20861]",
    "died August ?, 1843 (indistinct), and [P1988]",
    "",
    "Colonial Militia, 1754 [P1825]",
    "",
    "",
    "",
    "Sevier Co, TN [P1726]",
    "",
    "See Notes. [P20821]",
    "Sevier Co, TN, Headrick Cem. [P20903]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN [P1726]",
    "Sevier Co, TN, Shiloh Cem. [P20829]",
    "",
    "",
    "",
    "Sevier Co, TN, Galilee Cem., Seymour [P20904]",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P20829]",
    "Blount Co, TN, Sherwood Memorial Cem. [P20830]",
    "",
    "McCreary Co, KY [P20845]",
    "Family lived Lantana, FL [P1728]",
    "Whitley Co, KY, Jellico Baptist Creek Cem. [P20894]",
    "Another Mary (?) Davenport married Zebedee Hassell, 3/15/1770 [P20911]",
    "",
    "Washington Co, NC [P20861]",
    "",
    "",
    "",
    "",
    "",
    "Code: 0-10,   10-16,   16-26,   26-45,   45-up [P19376]",
    "Whitley Co, KY, Jellico Creek Baptist Cem. [P20889]",
    "",
    "",
    "Probably Washington Co, NC [P2342]",
    "Sevier Co, TN, Shiloh Cem. [P20829]",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P20829]",
    "",
    "",
    "",
    "Sevier Co, TN, Mattox Cem. [P2311]",
    "McCreary Co, KY [P20845]",
    "",
    "",
    "",
    "Tyrrell Co, NC [P1771]",
    "",
    "",
    "",
    "Sevier C0, TN [P20883]",
    "",
    "",
    "",
    "Kansas [P20874]",
    "",
    "",
    "",
    "Pigeon Forge, Sevier Co, TN, Shiloh Cem. [P20826]",
    "",
    "",
    "",
    "Whitley Co, KY, Wolf Creek Cem. [P1767]",
    "Sevier Co, TN, Shiloh Cem. [P20829]",
    "McCreary Co, KY, Bethel Baptist Cem. [P20837]",
    "",
    "Tyrrell Co, NC [P1771]",
    "Pigeon Forge, Sevier Co, TN, Shiloh Cem. [P20826]",
    "",
    "Another, older Stephen m. Elizabeth Alexander, 1778 [P19382]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Whitley Co, KY, Wolf Creek Cem. [P1767]",
    "",
    "Knox Co, TN, Galilee Cem, Seymour [P20896]",
    "Washington Co, NC [P20861]",
    "",
    "",
    "",
    "Little Rock, Arkansas [P2551]",
    "Whitley Co, KY, Speculate Wolf Creek Cem. [P20854]",
    "",
    "Sevier C0, TN [P20883]",
    "",
    "Borgetto, Sicily, Italy [P2716]",
    "Living in April 1994 [P19565]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Keene, NH [P20526]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Worthington, MN [P20520] [P55130]",
    "",
    "New Hill, , , NC [P2904] [P41591]",
    "Shallow Well, Lee Co, NC [P3115] [P41769]",
    "",
    "Brickhaven, NC [P2973] [P41655]",
    "Chatham Co, NC [P2624] [P41317]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Lawrence Co, TN",
    "",
    "",
    "",
    "",
    "",
    "Whitley Co, KY, Bethel Baptist Cem [P8824] [P21221] [P39858]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Greenville, SC [P0880] [P0880] [P0880]",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Shults-Whaley Cem., Hwy 321 [P9271] [P21668] [P40326]",
    "Sevier C0, TN, Spurgeon Cem [P9326] [P21723] [P40381]",
    "Sevier C0, TN, Webbs Creek Cem [P9414] [P21811] [P40475]",
    "",
    "",
    "",
    "Huskey Cem [P9321] [P21718] [P40376]",
    "",
    "Sevier CO, TN, Headrick Cem [P9290] [P21687] [P40345]",
    "",
    "",
    "",
    "Los Angeles, CA [P1054] [P1054] [P36990]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Evanston, WY [P0940] [P0940] [P0940]",
    "",
    "Havre, MT [P1656] [P1656] [P1656]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Memorial Cem, Hwy 401 S., Raleigh, NC [P10002] [P18745] [P37374]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Mattox Cem. [P9195] [P21592] [P40247]",
    "",
    "",
    "",
    "Cocke Co, TN, Rocky Creek Valentine Cem [P9417] [P21814] [P40478]",
    "",
    "",
    "",
    "",
    "",
    "Pittsburg, PA [P9737] [P22134] [P40818]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cameron, Lee County, NC [P10325] [P19068] [P37697]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Rex Hospital, , Raleigh, NC [P9474] [P21871] [P40539]",
    "Cocke Co, TN, Waters-Large Cem [P9278] [P21675] [P40333]",
    "",
    "",
    "Sevier Co, TN, Proffitt Cem. [P9041] [P21438] [P40080]",
    "Jackson Co, AL, McMahan Cem., McMahan Cove [P8791] [P21188] [P39825]",
    "Sevier Co, TN, McMahan Cem., Pearl Valley [P8788] [P21185] [P39822]",
    "Sevier Co, TN, Old McMahan Cem. [P9040] [P21437] [P40079]",
    "Sevier Co, TN, Richardson Cove Cem. [P9035] [P21432] [P40074]",
    "Cocke Co, TN [P8814] [P21211] [P39848]",
    "",
    "",
    "Sevier Co, TN, Church in Forks Baptist Cem. [P9033] [P21430] [P40072]",
    "Sevier Co, TN, Church in Forks Baptist Cem. [P9033] [P21430] [P40072]",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Richardson Cove Cem. [P9035] [P21432] [P40074]",
    "Sevier Co, TN, McMahan Cem. [P9252] [P21649] [P40306]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Webbs Creek Cem. [P9273] [P21670] [P40328]",
    "",
    "Sevier Co, TN [P8763] [P21160] [P39797]",
    "Sevier Co, TN, Emerts Cove Cem. [P1863] [P1863] [P1863]",
    "",
    "",
    "",
    "Sevier Co, TN [P8763] [P21160] [P39797]",
    "",
    "Yancy Co, NC [P9051] [P21448] [P40090]",
    "",
    "",
    "",
    "Jackson Co, TN [P9045] [P21442] [P40084]",
    "Sevier Co, TN, Howard-Campbell Cem. [P9042] [P21439] [P40081]",
    "",
    "Cocke Co, TN [P8814] [P21211] [P39848]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Tenn. Technological Univ.: MS Edu. Psychology 1972 [P1713] [P1713] [P1713]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Truelove Cem, Pascal Truelove Plc, Harnett Co, NC [P9516] [P21913]",
    "",
    "",
    "Stockholm,Sweden [P3536]",
    "",
    "Barking Abbey,Essex,England [P19795]",
    "",
    "",
    "Peterborough,Castle [P19730]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Evesham [P19667]",
    "",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P20829] [P55469]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Wake Co?, NC [P3138]",
    "",
    "",
    "Johnston Memorial Hospital, Johnston County, NC [P3229]",
    "Durham Co, Durham, NC [P3023]",
    "",
    "Johnston County, NC [P3430]",
    "",
    "",
    "",
    "Harnett  Co, NC [P19481]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Unknown [P2832]",
    "",
    "",
    "",
    "Mother was full-blooded Indian from Arkansas [P57259]",
    "",
    "",
    "",
    "",
    "Houston, AR [P20980]",
    "",
    "Jackson Parish, LA [P3290] [P58244]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier C0, TN, Burchfield Memorial Cem [P62285]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Union Co, GA [P3400] [P41811]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Duncan, Harnett Co, NC [P9733] [P22130] [P40814]",
    "",
    "",
    "Fuquay Varina, Wake Co, NC [P9957] [P22354] [P41050]",
    "",
    "",
    "",
    "",
    "",
    "Chatham Co, NC [P2624] [P41317]",
    "Chatham Co, NC [P2624] [P41317]",
    "Fayetteville, Cumberland Co, NC [P2895] [P41582]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Fowler Cemetery [P62123]",
    "",
    "",
    "Plainview, TX [P4481] [P4481]",
    "Caguas, PR [P20504] [P39136]",
    "",
    "",
    "",
    "",
    "Wake County, NC [P41401]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Rolla, MO [P20254]",
    "",
    "London, KY [P20482]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Ridings-Williams Cem. [P8777] [P10636]",
    "",
    "",
    "",
    "Sevier Co, TN, Hendron's Chapel Cem. [P8905] [P10764]",
    "Had 3 sons [P8904] [P10763]",
    "Killed in streetcar collision, Knoxville, 1912 [P8910] [P10769]",
    "",
    "",
    "",
    "Sevier Co, TN, Hendron's Chapel Cem. [P8905] [P10764]",
    "",
    "",
    "Sevier Co, TN, Walnut Grove Cem. [P1882] [P43607]",
    "Sevier Co, TN, Galilee Baptist Cem. [P8902] [P10761]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett  Co, NC [P19481]",
    "",
    "",
    "Wethersfield, Hartford, Ct. [P3277]",
    "",
    "Wethersfield, Hartford, Ct. [P3277]",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P20829] [P55469]",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P20829] [P55469]",
    "Sevier Co, TN, Shiloh Cem. [P20829] [P55469]",
    "Sevier Co, TN, McMahan Cem. [P19398] [P53895]",
    "",
    "Sevier Co, TN, Shiloh Cem. [P20829] [P55469]",
    "",
    "Sevier Co, TN, Trundle Family Cem. [P19210] [P53689]",
    "Sevier Co, TN, McMahan Cem. [P19398] [P53895]",
    "Sevier Co, TN, Shiloh Cem. [P20829] [P55469]",
    "Sevier Co, TN, Trundle Family Cem. [P19210] [P53689]",
    "Virginia [P20925] [P55575]",
    "Sevier Co, TN, Shiloh Cem. [P20829] [P55469]",
    "Roane Co, TN, killed by Indians near Crab Orchard [P1973] [P54260]",
    "Sevier Co, TN, Shiloh Cem. [P20829] [P55469]",
    "Marshall, TX [P1407] [P1407] [P1407]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Ridings-Williams Cem. [P43557]",
    "",
    "Code:  5-10-15-20-30-40 [P41114]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier CO, TN, Williams-Ridings Cem [P2220]",
    "Holly SprsBptChur, Harnett Co, NC [P2672]",
    "",
    "",
    "",
    "",
    "Berea, Marion Co, TX [P3223]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Tennessee [P20895]",
    "",
    "",
    "Summerville, GA [P20257]",
    "Harnett Co, NC [P2618]",
    "",
    "",
    "",
    "Springfield, MA [P20569] [P55183]",
    "",
    "",
    "",
    "Sevier C0, TN, Jos. &amp;amp;amp;amp; Salina Shults Cem [P2450] [P57404]",
    "",
    "",
    "Sevier C0, TN, Williams Cem, Jones Cove [P2534] [P57488]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P2618]",
    "Holland-Grand Haven, MI",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P2618]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Anderson, IN",
    "",
    "",
    "",
    "",
    "",
    "Davenport, IA",
    "",
    "",
    "",
    "",
    "Paris, TN",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Rome, Sumner, KS [P3218]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Washington Co, VA [P2556]",
    "",
    "Cocke Co, TN, Shults Cem., Cosby [P19322]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "NY City, NY [P10198] [P18941] [P37570]",
    "",
    "",
    "",
    "",
    "",
    "Richmond, KY",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN [P61817]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Ottawa, IL [P59236]",
    "Oshkosh, WI [P59209]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Tyler, TX",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Worthington, MN [P20520] [P39152]",
    "",
    "",
    "Dublin, GA [P20064] [P38693]",
    "Ottawa, IL [P20143] [P38772]",
    "Ogden, UT [P20665] [P39299]",
    "",
    "Lake Charles, LA [P20509] [P39141]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Piney Grove, Bapt Chur, Wake Co, NC",
    "",
    "Harnett Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Home Plc, , Raleigh, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Van Wert, OH [P20676] [P39310]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "NJ [P2700] [P41391]",
    "",
    "Cadillac, MI [P1618] [P1618] [P1618]",
    "Kapaa, HI [P1614] [P1614] [P1614]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "Wake Co, NC [P9535]",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "Cokesbury, Harnett Co, NC [P9675]",
    "",
    "",
    "Cokesbury, Harnett Co, NC [P9675]",
    "",
    "",
    "Depot Street, Fuquay Springs, NC [P10011]",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "",
    "",
    "Home, Cokesbury Road, Harnett Co, NC [P9529]",
    "",
    "",
    "",
    "",
    "Sevier Co, TN [P8763]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Elizabeth City, NC [P1549]",
    "Safford, AZ [P0873]",
    "Lake County, IL [P1203]",
    "",
    "Red Bluff, CA [P1209]",
    "Poplar Bluff, MO [P1663]",
    "",
    "Lake County, IL [P1203]",
    "Chillicothe, OH [P1150]",
    "",
    "Poplar Bluff, MO [P1663]",
    "Poplar Bluff, MO [P1663]",
    "",
    "",
    "Southington, CT [P10138]",
    "",
    "Southerning, CT [P10132]",
    "New Bern?, NC [P10136]",
    "",
    "John Brown Plc, , Harnett Co, NC [P9491]",
    "Clayton, Johnston Co, NC [P10105]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "NC [P1749]",
    "",
    "Moncure Methodist Cem, Moncure, NC [P9819]",
    "",
    "Wethersfield, Hartford, CT [P10134]",
    "",
    "Wethersfield, Hartford, CT [P10134]",
    "",
    "",
    "",
    "",
    "",
    "NC [P1749]",
    "",
    "",
    "Near Chalk Level, Northern Harnett Co, NC [P9666]",
    "",
    "",
    "",
    "",
    "Newington, CT [P10131]",
    "",
    "",
    "Apex, Wake Co, NC [P9821]",
    "",
    "Haywood, , Chatham Co, NC [P9817]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Jackson, MI [P20451]",
    "Toledo, OH [P20141]",
    "",
    "Redding, CA [P20397]",
    "",
    "",
    "",
    "",
    "Coldwater, MI [P20268]",
    "McAlester, OK [P20271]",
    "",
    "",
    "",
    "",
    "Kingsport, TN [P1505] [P61596]",
    "",
    "Sioux Falls, SD [P1459] [P61550]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Worcester, MA [P8742] [P51103]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Lumberton, NC [P59166]",
    "",
    "",
    "",
    "Bydgoszcz, Poland [P10206]",
    "",
    "",
    "",
    "",
    "",
    "",
    "NYC?, NY [P10210] [P18953] [P37582]",
    "",
    "",
    "",
    "",
    "New York City, NY [P9776] [P22173] [P40858]",
    "",
    "TN [P9980] [P22377] [P41074]",
    "",
    "",
    "",
    "See Note [P10179] [P18922] [P37551]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P2618] [P41311]",
    "Andrews, TX [P1104] [P61197]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Lutesville, MO, Lincoln Cem. [P9257] [P21654] [P40311]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Wake County, NC [P19494] [P54001]",
    "",
    "",
    "Duncan Bpt, ChurCem, Harnett Co, NC [P10091] [P18834] [P37463]",
    "Monroe, LA [P1563] [P1563] [P37359]",
    "",
    "",
    "",
    "",
    "",
    "Marquette, MI [P4523]",
    "",
    "",
    "",
    "",
    "",
    "Sanford, NC [P41977]",
    "Guaynabo, PR [P4601]",
    "Effingham, IL [P42107]",
    "Marquette, MI [P4523]",
    "",
    "New Ulm, MN [P4690]",
    "",
    "",
    "Kendallville, IN [P4777]",
    "Marquette, MI [P4523]",
    "",
    "",
    "New Ulm, MN [P4690]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Pigeon Forge Methodist Cem [P19369] [P37998]",
    "Sevier Co, TN, Methodist Cem., Pigeon forge [P2140] [P2140]",
    "",
    "",
    "Sevier Co, TN, Alderbranch Cem. [P19289] [P37918]",
    "Sevier Co, TN, Emerts Cove Cem. [P20944] [P39580]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cosby, TN, Holders Grove Cem. [P2248] [P2248]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Middle Creek Methodist Cem. [P8868] [P37010]",
    "Sevier Co, TN [P8763] [P10622]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Bogart, Ga [P9583] [P11442]",
    "",
    "",
    "",
    "",
    "Sevier Co, TN",
    "",
    "",
    "",
    "",
    "",
    "Waterloo-Cedar Falls, IA",
    "Akron, OH",
    "",
    "Richmond Co, NC [P3225] [P3225]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Frederick Co, MD [P8867]",
    "",
    "",
    "",
    "",
    "Sevier Co, TN [P8763]",
    "Frederick Co, MD [P8867]",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Banner Cem. [P9303]",
    "",
    "",
    "Sevier Co, TN, Old Roberts Cem., Richardson's Cove [P8815]",
    "",
    "",
    "",
    "Sevier Co, TN, Middle Creek Methodist Cem. [P8868]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Anderson Co, TN, Black Cem., Claxton",
    "",
    "",
    "",
    "",
    "Dallas, TX",
    "San Diego, CA",
    "Guaynabo, PR",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "TX",
    "See his Will, dtd 1790",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Wake Co, NC",
    "",
    "",
    "Wake Co, NC",
    "",
    "",
    "",
    "",
    "Wake Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Living 1993",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Monroe, WI",
    "",
    "",
    "",
    "Plattsburgh, NY",
    "",
    "",
    "Lincoln, IL",
    "",
    "",
    "Oxford, MS",
    "Muskegon, MI",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Billings, MT",
    "",
    "Corbin, KY",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Passaic, NJ [P10185] [P10185]",
    "Poland [P10203] [P10203]",
    "Shelby, NC [P59406]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Palatka, FL [P1594] [P43327]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Hot Springs, AR [P59539]",
    "",
    "",
    "",
    "Norfolk, NE [P59258]",
    "Syracuse, NY [P59511]",
    "Orlando, FL [P59383]",
    "",
    "Olean, NY [P59311]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Emerts Cove Cem. [P1863] [P1863]",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Emerts Cove Cem. [P1863] [P1863]",
    "",
    "Sevier Co, TN, Emerts Cove Cem. [P1863] [P1863]",
    "Carter Co, TN [P9410] [P21807]",
    "Sullivan Co, TN [P9411] [P21808]",
    "Washington Co, MD [P9408] [P21805]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Burks Co, PA [P8781] [P21178]",
    "",
    "Sylacauga, AL [P0995] [P0995] [P50436]",
    "",
    "Sevier Co, TN, Emerts Cove Cem. [P1863] [P43588]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Greensboro, NC [P20796] [P55433]",
    "",
    "Greensboro, NC [P20796] [P55433]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Greensboro, NC [P20796] [P55433]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P2618] [P57572]",
    "NC [P20842] [P55484]",
    "",
    "",
    "",
    "",
    "#6 Via Dilluvio, Borgetto, Sicily, Italy [P3331] [P3331]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "#6 Via Dilluvio, Borgetto, Sicily, Italy [P3331] [P3331]",
    "Zion, Mercer Co, NJ [P3213] [P41783]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Zion, Mercer Co, NJ [P3213] [P41783]",
    "",
    "Hopewell, NJ [P2717] [P41408]",
    "",
    "",
    "St Alfonsis, Catholic Chur, Hopewell, NJ [P19479] [P38108]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P2618] [P57572]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Home, Durham, NC [P9813] [P52281]",
    "",
    "Durham Co, Durham, NC [P9907] [P52384]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sicily, Italy [P9838] [P22235] [P40921]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Cole Cem.",
    "Newport, TN [P4489]",
    "",
    "",
    "Castle Pelesch,Sinaia,Romania [P3526] [P58480]",
    "Villa Mar y Sol,Estoril,Portugal [P3646] [P58600]",
    "",
    "",
    "Cannes,France [P3645] [P58599]",
    "Sinaia,Romania [P3610] [P58564]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Port of Spain, Trinidad, West Indies [P44216]",
    "",
    "McColl, SC [P44183]",
    "",
    "",
    "",
    "Sanford, Lee Co, NC [P44621]",
    "",
    "",
    "",
    "",
    "",
    "Coamo, PR [P4229]",
    "",
    "Hospital, Wake Co, NC [P44489]",
    "",
    "",
    "Lee Co, NC [P44305]",
    "Vance Co, NC [P41554]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Brunswick County NC [P44752]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Raleigh, NC [P44084]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Ashtabula, OH [P1332]",
    "",
    "",
    "Norfolk, NE [P1002]",
    "Tower of London,London,England",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Home Plc, , Raleigh, NC [P2697] [P57651]",
    "NC [P20842] [P55484]",
    "Green Lawn, , Fuquay-Varina, NC [P2725] [P57679]",
    "NC [P20842] [P55484]",
    "",
    "",
    "",
    "",
    "",
    "Del Rio, TX [P1482] [P52782]",
    "Del Rio, TX [P1482] [P52782]",
    "",
    "",
    "",
    "Unknown [P2832] [P57786]",
    "",
    "",
    "Lee Co, NC [P2915] [P57869]",
    "",
    "Ottawa, IL [P20143] [P54715]",
    "NC [P20842] [P55484]",
    "",
    "NC [P20842] [P55484]",
    "",
    "",
    "",
    "",
    "",
    "Cumberland Co, (Harnett), NC [P19545] [P54057]",
    "",
    "",
    "",
    "Harnett  Co, NC [P19481] [P53987]",
    "",
    "Cameron, NC [P19559] [P54072]",
    "Raeford, NC [P3439] [P58393]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett  Co, NC [P19481] [P53987]",
    "",
    "",
    "",
    "",
    "",
    "Cumberland Co, (Harnett), NC [P19545] [P54057]",
    "",
    "",
    "",
    "",
    "Grainger Co, TN, Shiloh Cem. [P9020]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Elkhart, IN [P20273]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Wake Co, NC [P44093]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P44064]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, White Oak Flats Cem. [P1890]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Milwaukee, WI [P1372] [P61463]",
    "",
    "NC [P1749] [P61840]",
    "",
    "",
    "",
    "",
    "Shelbyville, TN [P1289] [P61381]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Wake Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502] [P21899] [P40568]",
    "",
    "",
    "Cocke Co, TN, Shults Cem., Cosby [P9151] [P21548] [P40198]",
    "",
    "",
    "",
    "Wethersfield, Hartford, Ct. [P63015]",
    "",
    "",
    "Hatfield, Hampshire, Mass. [P63022]",
    "",
    "",
    "Essex, England [P63024]",
    "Providence, , Rhode Island [P63025]",
    "Wethersfield, Hartford, Ct. [P63015]",
    "England [P63303]",
    "Wethersfield, Hartford, Ct. [P63015]",
    "Wethersfield, Hartford, Ct. [P63015]",
    "",
    "Hadley, Hampshire, Mass. [P58236]",
    "Shalford, Essex, England [P63017]",
    "Ct. [P63020]",
    "",
    "Colchester, Essex, England [P63014]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Boogertown Cem. [P9056]",
    "",
    "",
    "",
    "",
    "Madrid, Spain [P21017] [P39654]",
    "",
    "Sandusky, OH [P20445] [P55047]",
    "Visalia, CA [P20593] [P55210]",
    "",
    "",
    "",
    "Manhattan, KS [P1449] [P1449] [P37295]",
    "Las Cruces, NM [P1552] [P1552] [P37350]",
    "",
    "",
    "",
    "Ottawa, IL [P59236]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Clearlake, CA [P1666] [P1666] [P1666]",
    "Hutchinson, MN [P1576] [P1576] [P37366]",
    "",
    "",
    "Spencer, IA [P1199] [P1199] [P37171]",
    "",
    "",
    "",
    "Kokomo, IN [P1345] [P1345] [P1345]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Campbellsville, KY [P1648] [P1648] [P1648]",
    "Harriman, TN [P1173] [P1173] [P37154]",
    "Campbellsville, KY [P1648] [P1648] [P1648]",
    "",
    "",
    "",
    "",
    "",
    "Santa Fe, NM [P1032] [P1032] [P36979]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Towns Co, GA [P9933] [P22330] [P41024]",
    "",
    "",
    "",
    "Albany, NY [P1446] [P1446] [P37294]",
    "",
    "",
    "Greensboro, NC [P20796] [P55433]",
    "",
    "",
    "Pottsville, PA [P0864] [P0864] [P0864]",
    "",
    "",
    "Silver City, NM [P1545] [P1545] [P37348]",
    "",
    "",
    "",
    "Sevier Co, TN, Alderbranch Cem. [P9111] [P21508] [P40154]",
    "",
    "",
    "Fayetteville, AR [P1136] [P1136] [P1136]",
    "Sevier Co, TN [P8763] [P21160] [P39797]",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Alder Branch Cem. [P8809] [P21206] [P39843]",
    "",
    "",
    "",
    "Fargo, ND [P0916] [P0916] [P36914]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ",,,Ireland [P0486] [P0486] [P36782]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "South Hill, Virginia [P2842] [P57796]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cambridge, MA [P1036] [P1036] [P36982]",
    "",
    "",
    "",
    "Henderson, Vance Co, NC [P10304] [P19047] [P37676]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Lancaster Co, PA (now York Co, PA)",
    "",
    "",
    "Wilmington, OH [P59832]",
    "",
    "",
    "Hilo, HI [P59548]",
    "Portales, NM [P59338]",
    "",
    "",
    "",
    "",
    "Olive Branch Cem, Kipling, Harnett Co, NC [P9946]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Family Graveyard, Harnett Co, NC [P9945]",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "",
    "",
    "",
    "",
    "(Harnett Co), NC [P10050]",
    "",
    "",
    "Harnett  Co, NC [P9507]",
    "Cokesbury United, Meth Chur, Harnett Co, NC [P9719]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "",
    "Cotten Cem, Harnett Co, NC [P10052]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Hinesville, GA",
    "",
    "",
    "",
    "",
    "",
    "Fargo, ND",
    "",
    "",
    "",
    "",
    "Emporia, KS",
    "",
    "",
    "",
    "",
    "Ottawa, IL",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Worthington, MN",
    "",
    "",
    "Beaumont, TX",
    "",
    "",
    "",
    "Andrews, TX",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Port St. Lucie, FL",
    "",
    "Emporia, KS",
    "",
    "",
    "Andrews, TX",
    "",
    "Summerville, GA",
    "",
    "",
    "Andrews, TX",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Andrews, TX",
    "Summerville, GA",
    "Summerville, GA",
    "Worthington, MN",
    "",
    "",
    "",
    "Moberly, MO",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Dixon, IL [P20537]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Point Pleasant, WV [P4731]",
    "",
    "",
    "",
    "",
    "",
    "Dover, DE [P20237]",
    "Terre Haute, IN [P20494]",
    "",
    "Dixon, IL [P20537]",
    "",
    "",
    "",
    "Bemidji, MN [P1543]",
    "Rome, GA [P20708]",
    "Selinsgrove, PA [P20533]",
    "",
    "Marshall, MN [P20667]",
    "",
    "",
    "",
    "",
    "Tuskegee, AL [P4515]",
    "",
    "",
    "",
    "",
    "",
    "Cookeville, TN [P20747]",
    "",
    "",
    "Whitley Co, KY, Wolf Creek Cem. [P1767]",
    "",
    "",
    "",
    "Cooksville,Near Toronto,Ontario,Canada [P0560] [P42656]",
    "",
    "",
    "",
    "",
    "",
    "Donegal Bay,County Sligo,Ireland [P0086] [P0086] [P0086]",
    "Stockholm,Sweden [P0094] [P0094] [P0094]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Stevens Point, WI [P20622] [P55242]",
    "Anderson, SC [P1007]",
    "Morgantown, WV [P20301] [P38933]",
    "West Virginia [P2102] [P2102]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P20829] [P39465]",
    "Sevier Co, TN, Shiloh Cem. [P20829] [P39465]",
    "",
    "Sevier Co, TN, Shiloh Cem. [P20829] [P39465]",
    "",
    "",
    "Allegan, MI [P1207] [P43094]",
    "Burlington, IA [P0977] [P42878]",
    "",
    "",
    "Tower of London,London,England [P3757] [P58711]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Howard View Cem [P2439] [P57393]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Howard-Campbell Cem. [P19231] [P53712]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Greenwich,,England [P0339] [P0339] [P0339]",
    "",
    "",
    "",
    "Del Rio, TX [P1482] [P52782]",
    "",
    "Newberry, SC [P20371] [P54966]",
    "",
    "Anchorage, AK [P20291] [P54878]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Birkhall",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Fowler Cem. [P62099]",
    "",
    "Whitley Co, KY, Wolf Creek Cem. [P8769]",
    "",
    "",
    "",
    "",
    "Thomasville, GA [P59496]",
    "Arlington, VA [P51054]",
    "",
    "",
    "Springfield, MO [P59523]",
    "",
    "Bridgeton, NJ [P59324]",
    "",
    "",
    "",
    "",
    "Pecos, TX [P59323]",
    "",
    "Raleigh-Cary, NC [P59852]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Wilmington, OH [P1611] [P43344]",
    "",
    "Harnett Co, NC",
    "Harnett Co, NC",
    "Truelove FamCem, Harnett Co, NC",
    "Harnett Co., NC",
    "Huskey Cem",
    "",
    "Olive Branch Cem, Kipling, Harnett Co, NC",
    "",
    "",
    "Public Cem, Hwy 55 N., Fuquay-Varina, NC",
    "",
    "Sevier C0, TN, Huskey Cem",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Crowder Mountain, Gaston Co, NC",
    "Ft Worth, TX [P9973]",
    "Cameron, Lee County, NC [P10325] [P50799]",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Webbs Creek Cem.",
    "",
    "Little Rock, AR [P59772]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Fort Walton Beach, FL [P1518] [P61609]",
    "",
    "",
    "",
    "Greenville, SC [P0880]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem.",
    "",
    "",
    "",
    "",
    "",
    "Minot, ND [P1587] [P61678]",
    "Arlington, VA [P1126] [P61219]",
    "",
    "Sevier Co, TN, Fowler Cem. [P8898] [P51274]",
    "",
    "Keene, NH [P1392] [P61483]",
    "",
    "",
    "Sunset Cem., Cleveland Co, Shelby, NC [P9963] [P52446]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Roswell, NM [P1346] [P61438]",
    "Poplar Bluff, MO [P1663] [P61754]",
    "",
    "",
    "",
    "",
    "",
    "Tower of London,Tower Green,London,England [P0349] [P60579]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502] [P51939]",
    "",
    "",
    "",
    "",
    "Roseboro, NC [P9720] [P52178]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Rex Hospital, Raleigh, NC [P9683] [P52138]",
    "",
    "",
    "",
    "Harnett Co, NC [P9502] [P51939]",
    "Raleigh, NC [P9524] [P51963]",
    "Cokesbury Meth, Chur Cem, Harnett Co, NC [P9832] [P52302]",
    "",
    "Iron Mountain, MI",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Ottawa, IL [P0978] [P42879]",
    "",
    "",
    "Ottawa, IL [P0978] [P42879]",
    "",
    "Athens, GA [P1023] [P42919]",
    "Ottawa, IL [P0978] [P42879]",
    "Towns Co, GA",
    "",
    "Union Co, GA",
    "",
    "",
    "Pleasant Grove, Rest Home,  Wake Co, NC [P2744]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Winston Salem, NC",
    "",
    "",
    "",
    "",
    "Trenton, NJ",
    "",
    "",
    "",
    "Sumter, AL",
    "Dickinson, ND",
    "",
    "",
    "",
    "",
    "",
    "Duluth, MN",
    "Martinsville, VA",
    "",
    "",
    "",
    "",
    "",
    "Duluth, MN",
    "",
    "",
    "",
    "Montrose, CO [P0854]",
    "",
    "Grand Forks, ND [P0889]",
    "",
    "",
    "",
    "Claiborne Co, TN, Sycamore Creek area [P9066] [P51459]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Carter Co, TN [P9410]",
    "",
    "Harnett Co., NC",
    "High Point Hospital, High Point, NC",
    "",
    "Home Plc, Harnett Co, NC",
    "",
    "",
    "",
    "",
    "Harnett Co, NC",
    "",
    "Durham Co, Durham, NC",
    "Harnett Co, NC",
    "",
    "Harnett Co, NC",
    "Harnett Co, NC",
    "Harnett Co, NC",
    "Moses Cone Hospital, Greensboro, NC",
    "",
    "",
    "Hwy 42 West, , Wake Co, NC",
    "",
    "Durham Co, Durham, NC",
    "Mamers, Harnett Co, NC",
    "",
    "",
    "",
    "Mamers, , Harnett Co, NC",
    "",
    "",
    "Harnett Co, NC",
    "",
    "Harnett Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "Home, Cary, Wake Co, NC",
    "High Point Hospital, High Point, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cardoss Castle,Firth of Clyde,Scotland",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sicily, Italy",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Thomas Cem.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Berlin, NH [P20303] [P38935]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Tower of London,Tower Green,London,England [P19663]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cosby, TN, Holders Grove Cem [P2125] [P55932]",
    "",
    "",
    "Sevier Co, TN, Trundle Family Cem. [P19210] [P53689]",
    "",
    "Sevier Co, TN, behind Shults Grove Methodist Cem. [P20940]",
    "Jefferson Co, Tn, Duggan Fam. Burying Ground [P2051]",
    "",
    "",
    "2n Sgt Tenn Mounted Inf, War 1812 [P1903]",
    "Sevier Co, TN, Mt. Pleasant Cem. [P20976]",
    "",
    "Sevier Co, TN, Mt. Pleasant Cem., Jones Cove [P2057]",
    "Sevier Co, TN, Allen Cem. [P2048]",
    "",
    "",
    "Sevier Co, TN, Henry's Crossroads Cem. [P2049]",
    "",
    "Sevier Co, TN [P1726]",
    "Sevier CO, Tennessee [P2073]",
    "",
    "Sevier Co, TN, TN, Mt. Pleasant Cem., Jones Cove [P2058]",
    "Sevier Co, TN, Emerts Cove Cem., unmarked [P19437]",
    "",
    "Knox Co, TN, Thorn Grove Cem. [P2056]",
    "Sevier Co, TN [P1726]",
    "",
    "",
    "",
    "Harnett Co, NC [P2618] [P57572]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Dumas, TX [P8748] [P21145] [P39782]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Columbus, MS [P20323]",
    "",
    "",
    "Tyrrell County, North Carolina [P19208]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "San Angelo, TX [P20468]",
    "",
    "",
    "Marquette, MI [P1228]",
    "San Diego, CA [P0892]",
    "Morristown, TN [P1475]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Shults Grove Cem. [P19310] [P37939]",
    "",
    "",
    "",
    "Macedonia BapChurCem, Harnett Co, NC [P9578] [P52022]",
    "",
    "Estoril,Portugal [P19696] [P38325]",
    "",
    "",
    "Hospital in KY [P9961]",
    "",
    "",
    "",
    "Cosby, TN, Holders Grove Cem [P9009]",
    "",
    "",
    "Tampa, Florida [P63041]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC",
    "Harnett Co, NC",
    "Guayama, PR",
    "",
    "",
    "Macedonia BapChurCem, Harnett Co, NC",
    "",
    "Harnett Co, NC",
    "",
    "",
    "Harnett  Co, NC",
    "",
    "",
    "",
    "",
    "Harnett  Co, NC [P9507] [P21904] [P40573]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Topeka, Shawnee Co, KS [P10309] [P50781]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, White Oak Flats Cem. [P20970] [P39606]",
    "Sevier CO, TN, Shults Cem 11.2 mi from Gatlinburg [P19411] [P53910]",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN [P1726] [P53026]",
    "",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P20829] [P55469]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Parkers Creek, Harnett Co, NC [P62677]",
    "",
    "Ottawa, IL [P0978] [P61071]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "McAlester, OK [P1112] [P61205]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Emerts Cove Cem. [P1863] [P1863] [P53163]",
    "St. James Palace,London,England [P3567] [P58521]",
    "",
    "",
    "",
    "",
    "",
    "Staunton-Waynesboro, VA [P1152] [P1152] [P1152]",
    "Ottawa, IL [P0978] [P0978] [P0978]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "NC [P1749]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Owen Co, Jefferson Twsp, IN [P10119] [P18862] [P53306]",
    "Sterling, IL [P1038] [P1038] [P50859]",
    "",
    "Living in Knightdale, NC 266-1767 [P10310] [P19053] [P53516]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Point Pleasant, WV [P10571]",
    "",
    "",
    "Sevier Co, TN [P1726] [P1726]",
    "",
    "",
    "",
    "",
    "",
    "Mount Vernon, WA [P59257]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sunset Cem., Cleveland Co, Shelby, NC [P9963] [P11822]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Grand Junction, CO [P20732] [P39367]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Duluth, MN [P1584] [P61675]",
    "",
    "",
    "Blount Co, TN, Clarks Grove Cem. [P9382] [P51807]",
    "",
    "Raleigh, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Ottawa, IL [P0978] [P42879]",
    "",
    "",
    "",
    "Paris,France [P0112] [P6996]",
    "",
    "",
    "",
    "",
    "Waterloo-Cedar Falls, IA [P1561] [P1561] [P52861]",
    "Coffeyville, KS [P1073] [P1073] [P51244]",
    "",
    "",
    "Marshall, MN [P1556] [P1556] [P52856]",
    "",
    "",
    "",
    "Orlando, FL [P1129] [P1129] [P51860]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Marshall, MN [P1556] [P1556] [P52856]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "NC",
    "",
    "",
    "Bunn Level, , Harnett Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Adjuntas, PR [P1293] [P8039]",
    "",
    "Ottawa, IL [P0978] [P42879]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Ottawa, IL [P0978] [P42879]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Midland, MI [P1243] [P43130]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Home Plc, Harnett Co, NC [P9485] [P11344]",
    "",
    "",
    "",
    "",
    "",
    "Troy, AL [P1450] [P1450] [P52750]",
    "Troy, AL [P1450] [P1450] [P52750]",
    "Troy, AL [P1450] [P1450] [P52750]",
    "Troy, AL [P1450] [P1450] [P52750]",
    "Troy, AL [P1450] [P1450] [P52750]",
    "Troy, AL [P1450] [P1450] [P52750]",
    "Troy, AL [P1450] [P1450] [P52750]",
    "Palm Coast, FL [P0931] [P0931] [P50372]",
    "Troy, AL [P1450] [P1450] [P52750]",
    "Troy, AL [P1450] [P1450] [P52750]",
    "Palm Coast, FL [P0931] [P0931] [P50372]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Trundle Family Cem.",
    "",
    "",
    "",
    "",
    "Tennessee, probably Monroe Co.",
    "",
    "Sevier Co, TN, Trundle Family Cem.",
    "Knox Co, TN, Grassy Valley Community",
    "Sevier Co, TN, Trundle Family Cem.",
    "",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem.",
    "",
    "",
    "",
    "Roane Co, TN (now Loudon Co)",
    "Cumberland Co, VA",
    "Sevier Co, TN, Trundle Family Cem.",
    "Sevier Co, TN, Trundle Family Cem.",
    "",
    "Venice,Italy [P3658] [P3658]",
    "",
    "",
    "",
    "",
    "Windsor Castle,Windsor,Berkshire,England [P0102] [P60332]",
    "Augusta Lodge,Windsor,Berkshire,England [P0138] [P60368]",
    "Cavendish Square,,London,England [P0177] [P60407]",
    "The Hague [P0176] [P60406]",
    "London,England [P0028] [P60258]",
    "Clarence House,St. James [P0131] [P60361]",
    "Kensington Palac [P0134] [P60364]",
    "St. James Palace,,,England [P0178] [P60408]",
    "",
    "Celle [P0188] [P60418]",
    "Claremont House,Esher,Surrey,England [P0114] [P60344]",
    "Furstenhof,Hanover [P0142] [P60372]",
    "Ludwigsburg [P0129] [P60359]",
    "",
    "",
    "",
    "Sidmouth,Devon,,England [P0108] [P60338]",
    "Monaco [P0186] [P60416]",
    "Gloucester House [P0187] [P60417]",
    "Frankfurt,-am-Main [P0132] [P60362]",
    "Kew Palace [P0105] [P60335]",
    "St. James Palac [P0143] [P60373]",
    "",
    "",
    "",
    "",
    "",
    "Herrenhausen [P0133] [P60363]",
    "",
    "Madrid,Spain [P0214] [P60444]",
    "Rutland House,Arlington St.,London,England [P0126] [P60356]",
    "Leicester-House,,London,England [P0175] [P60405]",
    "Leicester House [P0179] [P60409]",
    "",
    "",
    "",
    "Kensington,Palace,London,England [P0000] [P60230]",
    "",
    "Osnabruck [P0190] [P60420]",
    "Kensington,Palace,London,England [P0000] [P60230]",
    "Windsor Castle,Windsor,Berkshire,England [P0102] [P60332]",
    "Windsor Castle,Berkshire,England [P0004] [P60234]",
    "Paris,France [P0112] [P60342]",
    "",
    "",
    "",
    "London,,,England [P0180] [P60410]",
    "Christiansborg,Denmark [P0183] [P60413]",
    "Carlton House [P0113] [P60343]",
    "",
    "",
    "",
    "Gloucester House,Piccadilly,London,England [P0135] [P60365]",
    "",
    "Hanau [P0181] [P60411]",
    "",
    "",
    "Kew Palace [P0105] [P60335]",
    "",
    "",
    "",
    "Vicarage Place,Kensington [P0136] [P60366]",
    "",
    "Monbijou Palace,,Berlin,Germany [P0192] [P60422]",
    "Osborne House,Isle of Wight,England [P0001] [P60231]",
    "London,,,England [P0180] [P60410]",
    "Windsor Castle,Windsor,Berkshire,England [P0102] [P60332]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Fowler Cem.",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Fowler Cem.",
    "",
    "",
    "Sicily, Italy [P9838] [P11697]",
    "",
    "",
    "Sevier Co, TN [P1726] [P1726]",
    "",
    "Sevier Co, TN [P1726] [P1726]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sterling, IL [P59293]",
    "",
    "",
    "",
    "Andrews, TX [P59358]",
    "Whitewater, WI [P59628]",
    "",
    "",
    "",
    "",
    "Raleigh, NC [P9524] [P51963]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ""
]
scriptLoaded('dwr_db_I_death_place_14.js');
