// This file is generated

I_death_place_8 = [
    "",
    "Harnett Co, NC [P9502] [P11361]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Monroe, WI [P1077] [P42972]",
    "",
    "",
    "",
    "Plattsburgh, NY [P1257] [P43142]",
    "",
    "",
    "Lincoln, IL [P1103] [P42994]",
    "",
    "",
    "Oxford, MS [P1496] [P43230]",
    "Muskegon, MI [P0949] [P42850]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Billings, MT [P1237] [P43124]",
    "",
    "Corbin, KY [P1440] [P8185]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Allen Cem. [P43766]",
    "Crossville, TN [P4911]",
    "",
    "Topeka, KS [P42064]",
    "Topeka, KS [P42064]",
    "",
    "",
    "Topeka, KS [P42064]",
    "Topeka, KS [P42064]",
    "",
    "Topeka, KS [P42064]",
    "",
    "",
    "",
    "Topeka, KS [P42064]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Clarksdale, MS [P41888]",
    "Cookeville, TN [P42100]",
    "Marshall, TX [P41936]",
    "",
    "",
    "",
    "",
    "",
    "Racine, WI [P4491]",
    "",
    "Cookeville, TN [P42100]",
    "",
    "",
    "",
    "Cookeville, TN [P42100]",
    "",
    "Poplar Bluff, MO [P42118]",
    "",
    "",
    "Clearlake, CA [P4932]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Coyacan, Mexico City, Mexico [P44572]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Del Rio, TX",
    "",
    "",
    "",
    "",
    "Okinawa Island, South Pacific",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett  Co, NC",
    "",
    "",
    "Raleigh, , , NC",
    "",
    "Harnett Co. NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Atchley Cem.",
    "Sevier CO, TN, Pleasant Hill Cem",
    "",
    "Durham Co, Durham, NC",
    "Harnett Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Home Plc Cem., Roseboro, NC",
    "",
    "",
    "Harnett Co, NC",
    "",
    "Wake Co, NC",
    "",
    "",
    "",
    "Rex Hospital, Raleigh, Wake Co, NC",
    "Macedonia BapChurCem, Harnett Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Durham Co, Durham, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Macedonia BapChurCem, Harnett Co, NC",
    "Wake Medical Center, Wake Co, Raleigh, NC",
    "",
    "Laurels of Forest Glenn Rest Home, Garner, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett  Co, NC",
    "Macedonia BapChurCem, Harnett Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "McPherson, KS [P10561]",
    "",
    "",
    "",
    "Pittsburg, KS [P41898]",
    "Gettysburg, PA [P42011]",
    "Fort Dodge, IA [P4459]",
    "",
    "",
    "Albert Lea, MN [P4552]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Raleigh, Wake Co, NC",
    "",
    "(likely in) NC or AL [P44425]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Rome,,Italy",
    "",
    "Wilanow,Nr.,Warsaw,Poland",
    "",
    "",
    "Nashville, TN [P1653]",
    "West Palm Beach, FL [P1550]",
    "Nashville, TN [P1653]",
    "Frederick, MD [P1577]",
    "Fayetteville, AR [P1136]",
    "",
    "Ashtabula, OH [P1332]",
    "Ashtabula, OH [P1332]",
    "Nashville, TN [P1653]",
    "Shreveport, LA [P1015]",
    "",
    "Clearlake, CA [P1666]",
    "Milledgeville, GA [P1560]",
    "Nashville, TN [P1653]",
    "Saginaw, MI [P1677]",
    "Cortland, NY [P1531]",
    "",
    "Shreveport, LA [P1015]",
    "",
    "Johnstown, PA [P1638]",
    "Branson, MO [P0979]",
    "",
    "",
    "",
    "Sevier Co, TN, Cole Cem. [P9299] [P11158]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Ashtabula, OH [P20470] [P39102]",
    "",
    "",
    "Norfolk, NE [P20165] [P38794]",
    "Tower of London,London,England [P0315] [P42484]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Macedonia BapChurCem, Harnett Co, NC [P62501]",
    "",
    "Grainger Co, TN, Shiloh Cem. [P2136] [P2136]",
    "",
    "",
    "",
    "",
    "",
    "Elkhart, IN [P1114] [P1114] [P37097]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, White Oak Flats Cem. [P20970] [P39606]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Baptist Grove Church, Harnett Co, NC [P62975]",
    "",
    "Burley, ID [P59495]",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P62437]",
    "Wake/Harnett Co, NC [P57719]",
    "",
    "",
    "Indiana, PA [P59498]",
    "",
    "",
    "Bermondsey Abbey [P58766]",
    "",
    "",
    "",
    "",
    "",
    "Wake Co, NC [P9535] [P11394]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Boogertown Cem. [P19242] [P37871]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Lancaster Co, PA (now York Co, PA) [P9311] [P11170]",
    "",
    "",
    "",
    "",
    "",
    "Olive Branch Cem, Kipling, Harnett Co, NC [P3062] [P41744]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Family Graveyard, Harnett Co, NC [P3061] [P41743]",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P2618] [P41311]",
    "",
    "",
    "",
    "",
    "",
    "(Harnett Co), NC [P19557] [P38186]",
    "",
    "",
    "Harnett  Co, NC [P19481] [P38110]",
    "Cokesbury United, Meth Chur, Harnett Co, NC [P2835] [P41522]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P2618] [P41311]",
    "",
    "",
    "Cotten Cem, Harnett Co, NC [P3168] [P3168]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Hinesville, GA [P1227] [P43114]",
    "",
    "",
    "",
    "",
    "",
    "Fargo, ND [P0916] [P42822]",
    "",
    "",
    "",
    "",
    "Emporia, KS [P1469] [P43204]",
    "",
    "",
    "",
    "",
    "Ottawa, IL [P0978] [P42879]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Worthington, MN [P1385] [P8130]",
    "",
    "",
    "Beaumont, TX [P1348] [P8094]",
    "",
    "",
    "",
    "Andrews, TX [P1104] [P42995]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Port St. Lucie, FL [P1521] [P43255]",
    "",
    "Emporia, KS [P1469] [P43204]",
    "",
    "",
    "Andrews, TX [P1104] [P42995]",
    "",
    "Summerville, GA [P1097] [P42989]",
    "",
    "",
    "Andrews, TX [P1104] [P42995]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Andrews, TX [P1104] [P42995]",
    "Summerville, GA [P1097] [P42989]",
    "Summerville, GA [P1097] [P42989]",
    "Worthington, MN [P1385] [P8130]",
    "",
    "",
    "",
    "Moberly, MO [P1008] [P42905]",
    "",
    "",
    "",
    "",
    "",
    "Dixon, IL [P1408] [P1408] [P1408]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Point Pleasant, WV [P1451] [P1451] [P1451]",
    "",
    "",
    "",
    "",
    "",
    "Dover, DE [P1075] [P1075] [P37012]",
    "Terre Haute, IN [P1357] [P1357] [P37247]",
    "",
    "Dixon, IL [P1408] [P1408] [P1408]",
    "",
    "",
    "",
    "Bemidji, MN [P8750] [P21147] [P39784]",
    "Rome, GA [P1601] [P1601] [P1601]",
    "Selinsgrove, PA [P1404] [P1404] [P37271]",
    "",
    "Marshall, MN [P1556] [P1556] [P37352]",
    "",
    "",
    "",
    "",
    "Tuskegee, AL [P1218] [P1218] [P1218]",
    "",
    "",
    "",
    "",
    "",
    "Cookeville, TN [P1641] [P1641] [P1641]",
    "",
    "",
    "Whitley Co, KY, Wolf Creek Cem. [P8769] [P21166] [P39803]",
    "",
    "Truelove Cem, Hall Co, GA [P3147] [P58101]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Anderson, SC [P20170] [P38800]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Birkhall [P0124] [P7008]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Whitley Co, KY, Wolf Creek Cem. [P1767] [P1767]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "HomePlc, Harnett Co, NC",
    "",
    "",
    "",
    "NC",
    "",
    "Harnett Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "Benton Co., Tn.",
    "",
    "",
    "Harnett or Wake Co, NC",
    "",
    "New Hill, , , NC",
    "",
    "",
    "Goldsboro, NC",
    "",
    "Living 1993",
    "Dallas, TX",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC",
    "",
    "Harnett Co, NC",
    "",
    "Rushing Creek cemetery, Big Sandy,TN",
    "",
    "",
    "",
    "Portales, NM",
    "",
    "",
    "",
    "",
    "London,England",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Public Cem, Hwy 55 N, Fuquay-Varina, NC",
    "",
    "",
    "File as being in Kentucky in 1800, also",
    "",
    "",
    "Washington Co, NC",
    "Probably Washington Co, NC",
    "",
    "Harnett Co, NC [P9502] [P11361]",
    "Harnett Co, NC [P9502] [P11361]",
    "Truelove FamCem, Harnett Co, NC [P10045] [P10045]",
    "Harnett Co., NC [P9544] [P11403]",
    "Huskey Cem [P9321] [P11180]",
    "",
    "Olive Branch Cem, Kipling, Harnett Co, NC [P9946] [P11805]",
    "",
    "",
    "Public Cem, Hwy 55 N., Fuquay-Varina, NC [P10046] [P10046]",
    "",
    "Sevier C0, TN, Huskey Cem [P9076] [P10935]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Crowder Mountain, Gaston Co, NC [P9766] [P11625]",
    "Ft Worth, TX [P3089] [P3089]",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Webbs Creek Cem. [P9273] [P11132]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Greenville, SC [P20046] [P38675]",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P1732] [P43464]",
    "",
    "Staten Island, NY [P44338]",
    "",
    "",
    "",
    "",
    "Hopewell, NJ [P44142]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Princeton, NJ [P44658]",
    "",
    "",
    "",
    "Rutherford, NJ [P44648]",
    "",
    "",
    "",
    "",
    "See Note [P44646]",
    "Rex Hospital, Wake Co, Raleigh, NC [P44050]",
    "",
    "",
    "Zion, NJ [P44337]",
    "",
    "",
    "",
    "Hopewell, NJ [P44142]",
    "",
    "Princeton, NJ [P44658]",
    "Borgetto, Sicily, Italy [P44141]",
    "",
    "",
    "",
    "",
    "",
    "Hopewell, NJ [P44142]",
    "",
    "",
    "",
    "Aldermanbury, London, England [P10346]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Iron Mountain, MI [P1369] [P8114]",
    "Alexandria, MN [P59793]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Towns Co, GA [P9933] [P11792]",
    "",
    "Union Co, GA [P10284] [P10284]",
    "",
    "",
    "Pleasant Grove, Rest Home,  Wake Co, NC [P9628] [P22025] [P40700]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Alexandria, LA [P4264]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co?, NC [P44090]",
    "",
    "",
    "",
    "",
    "",
    "Winston Salem, NC [P10026] [P10026]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Trenton, NJ [P9498] [P11357]",
    "",
    "",
    "",
    "Sumter, AL [P9939] [P11798]",
    "Dickinson, ND [P8720] [P10579]",
    "",
    "",
    "",
    "",
    "",
    "Duluth, MN [P1584] [P43317]",
    "Martinsville, VA [P1362] [P8107]",
    "",
    "",
    "",
    "",
    "",
    "Duluth, MN [P1584] [P43317]",
    "",
    "Montrose, CO [P20020] [P38649]",
    "",
    "Grand Forks, ND [P20055] [P38684]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Carter Co, TN [P2526] [P41252]",
    "",
    "Harnett Co., NC [P9544] [P11403]",
    "High Point Hospital, High Point, NC [P9811] [P11670]",
    "",
    "Home Plc, Harnett Co, NC [P9485] [P11344]",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502] [P11361]",
    "",
    "Durham Co, Durham, NC [P9907] [P11766]",
    "Harnett Co, NC [P9502] [P11361]",
    "",
    "Harnett Co, NC [P9502] [P11361]",
    "Harnett Co, NC [P9502] [P11361]",
    "Harnett Co, NC [P9502] [P11361]",
    "Moses Cone Hospital, Greensboro, NC [P9873] [P11732]",
    "",
    "",
    "Hwy 42 West, , Wake Co, NC [P9639] [P11498]",
    "",
    "Durham Co, Durham, NC [P9907] [P11766]",
    "Mamers, Harnett Co, NC [P9555] [P11414]",
    "",
    "",
    "",
    "Mamers, , Harnett Co, NC [P9655] [P11514]",
    "",
    "",
    "Harnett Co, NC [P9502] [P11361]",
    "",
    "Harnett Co, NC [P9502] [P11361]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Home, Cary, Wake Co, NC [P9903] [P11762]",
    "High Point Hospital, High Point, NC [P9811] [P11670]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cardoss Castle,Firth of Clyde,Scotland [P0550] [P42648]",
    "",
    "",
    "",
    "",
    "",
    "Truelove Cem, Hall Co, GA [P10031]",
    "",
    "",
    "",
    "",
    "Ft Worth, TX [P9973]",
    "",
    "",
    "",
    "",
    "",
    "Raleigh, NC [P9524]",
    "",
    "",
    "",
    "LA [P10173]",
    "",
    "Wake County, NC [P9594]",
    "Pasadena, Los Angeles Co, CA [P10267]",
    "",
    "",
    "Union/Towns Co, GA [P10286]",
    "Harnett Co, NC [P9502]",
    "Rex Hospital, , Raleigh, NC [P9474]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Died as a young child, no data [P10268]",
    "",
    "",
    "",
    "Lowell, NC [P9758]",
    "",
    "",
    "Surry Country, NC [P9926]",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "Cleveland Co, NC [P9965]",
    "",
    "TN? [P9807]",
    "Cumberland Co, Northern Div, NC [P9804]",
    "",
    "",
    "",
    "Near Jonesboro, , , NC [P9887]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Raleigh, NC [P9524]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Granville Co, NC [P8863]",
    "",
    "Home plc, , Harnett Co, NC [P9536]",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "Harnett Co., NC [P9544]",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Roxboro, , , NC [P9592]",
    "Harnett Co, NC [P9502]",
    "",
    "",
    "",
    "",
    "Dustin, Hughes Co, OK [P10272]",
    "",
    "",
    "",
    "",
    "",
    "Cleveland Co, NC [P9965]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Charleston Hospital, SC [P9771]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Greensville, SC [P9883]",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Dallas?, TX [P9979]",
    "Sumter, AL [P9939]",
    "Harnett Co, NC [P9502]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cleveland Co, NC [P9965]",
    "",
    "Raleigh, NC [P9524]",
    "",
    "",
    "",
    "Raleigh, NC [P9524]",
    "Jonesboro, , , NC [P9789]",
    "",
    "",
    "",
    "",
    "",
    "Deceased [P10152]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Delhi, LA [P10332]",
    "Greesboro, NC [P9971]",
    "",
    "",
    "",
    "",
    "Parkers Creek, Harnett Co, NC [P9791]",
    "",
    "",
    "",
    "",
    "Martin Co, Rutherford Twsp, IN [P10117]",
    "Harnett Co, NC [P9502]",
    "Wake County, NC [P9594]",
    "",
    "",
    "",
    "",
    "",
    "Wake County, NC [P9594]",
    "Mazie Truelove-Betts Home, Raleigh, NC [P9577]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "Harnett  Co, NC? [P9916]",
    "",
    "",
    "",
    "Thomasville, , , NC [P9679]",
    "",
    "",
    "",
    "",
    "Union Co?, GA [P10281]",
    "",
    "",
    "Cleveland Co, NC [P9965]",
    "",
    "",
    "Apex Cemetary, Apex, Wake Co, NC [P9595]",
    "",
    "Macedonia BaptChurCem, Harnett Co, NC [P9674]",
    "Macedonia Bpt ChurCem, Harnett, NC [P9677]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Haywood Co, NC [P1888]",
    "",
    "",
    "",
    "",
    "",
    "Lowell, NC (Near Gastonia) [P9763]",
    "Sunset Cem., Cleveland Co, Shelby, NC [P9963]",
    "Sunset Cem., Cleveland Co, Shelby, NC [P9963]",
    "",
    "",
    "Shelby, NC [P1154]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Revolutionary War [P9714]",
    "Indian Territory, (McAlister), OK [P9920]",
    "",
    "",
    "Harnett Co., NC [P9544]",
    "Mary Elizabeth, Hosp, Raleigh, NC [P9710]",
    "Harnett Co, NC [P9502]",
    "",
    "Gastonia, NC [P9396]",
    "",
    "",
    "Battle wounds - civil war [P9895]",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "Houston, AR [P10328]",
    "",
    "",
    "",
    "",
    "Buncombe Co, NC [P10279]",
    "",
    "Towns Co, GA [P9933]",
    "",
    "seenote [P10033]",
    "",
    "",
    "",
    "",
    "Towns Co, GA [P9933]",
    "Hall Co, GA [P10306]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Raleigh, , Wake Co, NC [P9607]",
    "Truelove Cem, Hall County, GA [P10030]",
    "",
    "GA? [P10291]",
    "",
    "",
    "",
    "Trenton, N.J. [P9630]",
    "Durham, , , NC [P9579]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Fayetteville, NC [P9523]",
    "Raleigh, NC [P9524]",
    "",
    "",
    "Cokesbury, , Harnett Co, NC [P9784]",
    "",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Towns or Union Co, GA [P10283]",
    "",
    "Summerville Presbyterian Church, Harnett Co, NC [P9996]",
    "",
    "New Hanover Regional, Med Center, Willington, NC [P9631]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Raleigh, NC [P9524]",
    "Raleigh, , , NC [P9521]",
    "Raleigh, , , NC [P9521]",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "NC [P1749]",
    "",
    "",
    "",
    "",
    "Wewoko, Seminole Co, OK [P9922]",
    "",
    "",
    "",
    "",
    "Cleveland Co, NC [P9965]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cokesbury Chur Cem, Harnett Co, NC [P9923]",
    "",
    "",
    "",
    "Harnett Co., NC [P9544]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Jackson Parish, LA [P10174]",
    "Delhi, LA [P10332]",
    "",
    "",
    "",
    "",
    "",
    "Bogart, , , GA [P9573]",
    "",
    "",
    "",
    "",
    "Wake Co, NC [P9535]",
    "Thomasville, NC [P9685]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Duncan Area, , Harnett Co, NC [P9527]",
    "",
    "",
    "Rehabilitation Center, near Crabtree Valley, Raleigh, NC [P9575]",
    "",
    "",
    "",
    "",
    "",
    "",
    "seenotes [P10032]",
    "",
    "NC [P1749]",
    "Piny Grove, Bpt ChurCem, Wake Co, NC [P9522]",
    "",
    "",
    "",
    "Home Plc, Cokesbury Rd, Harnett Co, NC [P9517]",
    "John Brown Plc, , Harnett Co, NC [P9491]",
    "",
    "",
    "",
    "",
    "",
    "Wake Co, NC [P9535]",
    "",
    "Star, NC [P9587]",
    "",
    "Northern Harnett Co, NC [P9786]",
    "New Hill, , , NC [P9788]",
    "",
    "",
    "Fayetteville, Cumberland Co, NC [P9779]",
    "Harnett Co., NC [P9544]",
    "Cleveland Co, NC [P9965]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Home plc, Myrtle Beach 29577 (Socustee), Horry Co, SC [P9488]",
    "",
    "",
    "",
    "",
    "",
    "Durham Gen Hospital, Durham, NC [P9589]",
    "",
    "",
    "",
    "",
    "Sumter, AL [P9939]",
    "",
    "Memphis, Shelby Co,Tenn [P10337]",
    "Harnett Co, NC [P9502]",
    "",
    "",
    "Cumberland Co, (Harnett Co), NC [P9723]",
    "",
    "",
    "",
    "",
    "",
    "Montania [P10153]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Raleigh, Wake Co, NC [P9735]",
    "",
    "",
    "",
    "",
    "Raleigh, NC [P9524]",
    "",
    "Florence, SC [P0950]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Jackson Parish, LA [P10174]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "",
    "",
    "",
    "",
    "Duncan, NC - Harnett Co [P9711]",
    "",
    "",
    "Lillington, Harnett Co, NC [P9914]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "",
    "",
    "",
    "",
    "Cleveland Co, NC [P9965]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "OK [P10269]",
    "",
    "",
    "",
    "Parkers Creek, , Harnett Co, NC [P9513]",
    "",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "Granville Co, NC [P8863]",
    "Cumberland Co, (Harnett Co), NC [P9723]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Jonesboro, , , NC [P9789]",
    "",
    "",
    "Home Plc, Hwy 42, Harnett Co, NC [P9525]",
    "",
    "",
    "Daugthers, 809 Holland Rd, Fuquay-Varina, NC [P9480]",
    "",
    "",
    "",
    "Lumberton, Cancer Center, Lumberton, NC [P9501]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Louisburg?, Franklin Co, NC [P9828]",
    "",
    "",
    "seenote [P10033]",
    "Harnett Co, NC [P9502]",
    "",
    "Summerville, NC [P10008]",
    "",
    "Kennett, MO [P1635]",
    "",
    "",
    "",
    "Rex Hospital, Raleigh, Wake County, NC [P9540]",
    "",
    "",
    "Golden Gate Park, Nation Cem., San Francisco, CA [P10308]",
    "",
    "Zoar Baptist Church Cem, Cleveland Co, Shelby, NC [P10093]",
    "LA [P10173]",
    "Trenton, NJ [P9498]",
    "",
    "Unknown, see notes [P10270]",
    "",
    "",
    "",
    "",
    "Bunn Level, Harnett Co, NC [P9918]",
    "East Bend Bapt Church, East Bend, Yadkin, NC [P9967]",
    "Topeka, KS [P1592]",
    "Greesboro, NC [P9971]",
    "",
    "Sun City West, AZ [P9974]",
    "",
    "East Bend Bapt Church, East Bend, Yadkin, NC [P9967]",
    "",
    "Atlanta, GA [P1029]",
    "",
    "Topeka, KS [P1592]",
    "Greensboro, , , NC [P9545]",
    "",
    "Greensboro, , , NC [P9545]",
    "",
    "",
    "",
    "",
    "",
    "Sicily, Italy [P9838] [P11697]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Thomas Cem. [P1851] [P43578]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Dover, DE",
    "",
    "",
    "",
    "",
    "",
    "seenote",
    "Sevier Co, TN [P43458]",
    "Not in 1870 census [P43732]",
    "Sevier Co, TN, Alder Branch Cem. [P43648]",
    "Sevier Co, TN [P43458]",
    "Sevier Co, TN, Atchley Cem. [P43675]",
    "",
    "",
    "Sevier Co, Tn [P8787]",
    "Sevier Co, TN [P43458]",
    "Sevier Co, TN, Alderbranch Cem. [P2227]",
    "Possibly J. R. Atchley, Alderbranch Cem., died [P41045]",
    "Loudon Co, VA [P43681]",
    "",
    "Sevier Co, TN [P43458]",
    "",
    "",
    "Sevier Co, TN, Alderbranch Cem. [P2227]",
    "",
    "Sevier Co, TN, Red Bank Cem. [P43860]",
    "Sevier Co, TN, Shiloh Cem. [P4990]",
    "Sevier Co, TN, Alder Branch Cem. [P43648]",
    "",
    "Delhi, LA",
    "",
    "East Bend Bapt Church, East Bend, Yadkin, NC",
    "",
    "",
    "",
    "",
    "",
    "Lancaster Co, PA (now York Co, PA)",
    "",
    "",
    "",
    "",
    "",
    "",
    "Pfalz, Bayern, Germany",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Summerville Presbyterian Church, Lillington, Harnett Co, NC",
    "",
    "",
    "GA",
    "Whitley Co, KY, Jellico Creek Baptist Cem.",
    "Macedonia BapChurCem, Harnett Co, NC",
    "",
    "Angier, Harnett Co, NC",
    "",
    "",
    "Greenlawn Cemetary?, Fuquay-Varina, NC",
    "",
    "",
    "Duncan, NC",
    "",
    "",
    "",
    "Harnett Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC",
    "Harnett Co, NC",
    "Veteran's Hosp, Fayettville, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "Macedonia Bapt, ChurCem, Harnett Co, NC",
    "By Oakwinn's FunHm, Lillington, NC",
    "Harnett Co, Buckhorn Twsp, NC",
    "Harnett Co, NC",
    "",
    "",
    "Angier, Harnett Co, NC",
    "?Cary, NC",
    "",
    "",
    "",
    "",
    "Poland",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Dandridge, TN, Hills Methodist Cem",
    "",
    "",
    "",
    "",
    "",
    "Memorial Cem, Hwy 401 S., Raleigh, NC [P3118]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Living in Dustin, OK in 1982",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC",
    "",
    "",
    "",
    "Whitley Co, KY, now McCreary Co, KY",
    "",
    "",
    "",
    "",
    "",
    "",
    "McCreary Co, KY, Bethel Baptist Cem.",
    "",
    "",
    "",
    "",
    "Kensington,Palace,London,England",
    "Richmond Palace,,England",
    "",
    "Whitehall Palace,,England",
    "St. James Palace,London,England",
    "",
    "Rome,,Italy",
    "Greenwich Palace",
    "St. James Palace,London,England",
    "Whitehall Palace,,England",
    "Whitehall Palace,,England",
    "St. James Palace,London,England",
    "Leicester House,London,England",
    "Carisbrooke,Castle,Isle of Wight,England",
    "",
    "St. Cloud",
    "",
    "",
    "Frascati,,Italy",
    "St. James Palace,,England",
    "Whitehall Palace",
    "Rome,,Italy",
    "Theobalds Park,Hertfordshire,Herts,England",
    "St. Germain-,en-Laye,France",
    "",
    "St. Germain-,en-Laye,France",
    "",
    "Linlithgow",
    "Stanwell Park,Middlesex,England",
    "Whitehall Palace,,England",
    ",England",
    "",
    "Dunfermline",
    "Greenwich Palace",
    "Kensington,Palace,England",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Tower of London,Tower Green,London,England [P0349] [P0349] [P36724]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "Ludlow Castle [P0318]",
    "",
    "",
    "",
    "",
    "",
    "Bishops Hatfield,Herts,England [P0329]",
    "",
    "Greenwich,Palace,England [P0328]",
    "Eltham Palace,,England [P0326]",
    "Richmond Palace,London,England [P0268]",
    "",
    "Living [P10082]",
    "Richmond Palace,,England [P0267]",
    "Richmond Palace,,England [P0267]",
    "Richmond Palace,Richmond Surrey,England [P0312]",
    "Whitehall,London,England [P0325]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Tudor Cem., Emerts Cove [P9207]",
    ",,England [P0320]",
    "",
    "",
    "",
    "",
    "Methven Castle [P0319]",
    "Westhorpe,Suffolk,England [P0327]",
    "Sevier Co, TN, Shults Grove Cem. [P9137]",
    "St. James Palace,,England [P0269]",
    "",
    "",
    "",
    "",
    "",
    "Greenwich,,England [P0339]",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, behind Shults Grove Methodist Cem. [P1857] [P1857] [P1857]",
    "Jefferson Co, Tn, Duggan Fam. Burying Ground [P8935] [P21332] [P39973]",
    "",
    "",
    "2n Sgt Tenn Mounted Inf, War 1812 [P8787] [P21184] [P39821]",
    "Sevier Co, TN, Mt. Pleasant Cem. [P1896] [P1896] [P1896]",
    "",
    "Sevier Co, TN, Mt. Pleasant Cem., Jones Cove [P8941] [P21338] [P39979]",
    "Sevier Co, TN, Allen Cem. [P8932] [P21329] [P39969]",
    "",
    "",
    "Sevier Co, TN, Henry's Crossroads Cem. [P8933] [P21330] [P39971]",
    "",
    "Sevier Co, TN [P8763] [P21160] [P39797]",
    "Sevier CO, Tennessee [P8957] [P21354] [P39996]",
    "",
    "Sevier Co, TN, TN, Mt. Pleasant Cem., Jones Cove [P8942] [P21339] [P39980]",
    "Sevier Co, TN, Emerts Cove Cem., unmarked [P9298] [P21695] [P40353]",
    "",
    "Knox Co, TN, Thorn Grove Cem. [P8940] [P21337] [P39978]",
    "Sevier Co, TN [P8763] [P21160] [P39797]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Columbus, MS [P1167] [P1167] [P37152]",
    "",
    "",
    "Tyrrell County, North Carolina [P8774] [P21171] [P39808]",
    "",
    "",
    "",
    "",
    "San Angelo, TX [P1330] [P1330] [P1330]",
    "",
    "",
    "",
    "",
    "Marquette, MI [P20378] [P39010]",
    "San Diego, CA [P20058] [P38687]",
    "Morristown, TN [P20597] [P39231]",
    "",
    "",
    "Hospital in KY [P3077] [P41759]",
    "Cosby, TN, Holders Grove Cem [P2125] [P2125]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Fayetteville, , Cumberland Co, NC [P9869]",
    "",
    "",
    "The place",
    "Raleigh, , , NC [P9521]",
    "",
    "",
    "",
    "Harnett Co, NC [P9502] [P11361]",
    "Harnett Co, NC [P9502] [P11361]",
    "Guayama, PR [P1148] [P43039]",
    "",
    "",
    "Macedonia BapChurCem, Harnett Co, NC [P9578] [P11437]",
    "",
    "Harnett Co, NC [P9502] [P11361]",
    "",
    "",
    "Harnett  Co, NC [P9507] [P37126]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Het Loo,Apeldoorn [P58784]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Wake Co?, NC [P44499]",
    "",
    "",
    "Living, Harnett Co, NC [P41573]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "Buckhorn Township, Harnett Co, NC [P9835]",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "",
    "NC [P1749]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Johonston County, NC [P10313]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Clayton, Johnston Co, NC [P10105]",
    "",
    "Berea, Marion Co, TX [P10107]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Pleasant Grove, Rest Home, Wake Co, NC [P9504]",
    "Living 1993, Harnett Co, NC [P10073]",
    "Oakwood Cemetary, Wake Co, Raleigh, NC [P10315]",
    "",
    "",
    "Cameron, Lee County, NC [P10325]",
    "",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "Wake Mem Hosp., Raleigh, NC [P9620]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "National Cemetary, Arlington, VA [P9627]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Beaver Dam Twsp, Richmond Co, NC [P9648]",
    "",
    "Harnett Co, NC [P9502]",
    "Harnett Co, NC [P9502]",
    "Richmond Co, NC [P10109]",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "Harnett Co, NC [P9502]",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "Harnett Co, NC [P9502]",
    "Harnett Co, NC [P9502]",
    "",
    "Midland, Cabarrus Co, NC [P9624]",
    "",
    "Wake/Harnett Co, NC [P9649]",
    "",
    "Duncan, , Harnett Co, NC [P9538]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Johnson County, NC [P10312]",
    "",
    "",
    "Duncan Bapt Chur?, Harnett Co, NC [P9865]",
    "NC [P1749]",
    "",
    "Harnett Co, NC [P9502]",
    "Centers, Rest Home, Harnett Co, NC [P9653]",
    "",
    "McCall, , SC [P9652]",
    "",
    "",
    "Harnett Co?, NC [P9532]",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "Mamers, , Harnett Co, NC [P9655]",
    "",
    "",
    "",
    "",
    "Harnett Co?, NC [P9532]",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "Wake County, NC [P9594]",
    "Harnett Co, NC [P9502]",
    "Civil War, Drury's Bluff, VA [P10078]",
    "",
    "",
    "",
    "",
    "Harnett Co. NC [P9702]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Wayne Co, NC [P10108]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Durham Co, NC [P9859]",
    "",
    "",
    "Harnett Co, NC [P9502]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Durham Co, Durham, NC [P9907]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "McCall, SC [P9642]",
    "",
    "Harnett Co, NC [P9502]",
    "Harnett Co, NC [P9502]",
    "Wilmington, NC [P1156]",
    "Cumberland Co, NC [P9505]",
    "Richmond Co, NC [P10109]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "NC [P42180]",
    "Washington Co, VA [P44016]",
    "",
    "",
    "Washington Co, VA [P44016]",
    "",
    "",
    "",
    "Harnett Co, NC [P44064]",
    "",
    "Macedonia Bpt ChurCem, Harnett Co., NC [P44159]",
    "",
    "",
    "Harnett Co. NC [P44225]",
    "",
    "Harnett Co. NC [P44225]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P44064]",
    "Cameron, NC [P3178]",
    "Cumberland Co?, NC [P44385]",
    "",
    "Harnett Co, NC [P44064]",
    "",
    "Chatham Co, NC [P44068]",
    "",
    "",
    "Northampton, NC [P44537]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "St. Marys, PA",
    "",
    "Mobile, AL",
    "Sevier Co, TN, White Oak Flats Cem.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Rolla, MO [P1093]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Goleszow, Poland",
    "NC [P20842] [P39478]",
    "",
    "",
    "",
    "Pittsburg, PA",
    "",
    "",
    "Hopewell, NJ [P44142]",
    "",
    "Palermo, Sicily [P44340]",
    "East Bend, Yadkin, NC [P19552] [P54065]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Hackensack, NJ [P3315] [P58269]",
    "",
    "Passaic, NJ [P3301] [P58255]",
    "Poland [P3319] [P58273]",
    "",
    "",
    "",
    "",
    "",
    "Wake Co, NC [P44093]",
    "",
    "Harnett Co, NC [P44064]",
    "",
    "",
    "",
    "Harnett Co, NC [P44064]",
    "",
    "Fuquay Varina, NC [P44392]",
    "",
    "",
    "",
    "Macedonia Bpt, Chur Cem, Harnett Co, NC [P44155]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Macedonia BapChurCem, Harnett Co, NC [P44128]",
    "",
    "",
    "Harnett Co?, NC [P44090]",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P44064]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "NC [P42180]",
    "",
    "",
    "",
    "Macedonia BapChurCem, Harnett Co, NC [P44128]",
    "Harnett Co, NC [P44064]",
    "",
    "",
    "",
    "",
    "Wake Co, NC [P44093]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Macedonia BapChurCem, Harnett Co, NC [P44128]",
    "Harnett Co, NC [P44064]",
    "",
    "",
    "",
    "",
    "Macedonia BapChurCem?, Harnett Co, NC [P44360]",
    "",
    "",
    "Harnett Co, NC [P44064]",
    "",
    "House Creek Township, Wake Co, NC [P44092]",
    "",
    "",
    "Harnett Co, NC [P44064]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Louisville, KY [P41975]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Kokomo, IN [P4632]",
    "",
    "",
    "",
    "",
    "Sevier Co, TN [P43458]",
    "",
    "Mooresville, NC [P4234]",
    "",
    "Russell Co, VA [P43663]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Oxnard, CA [P41892]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Baltimore, MD [P42085]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "New Philadelphia, OH [P42124]",
    "Portland, OR [P42052]",
    "Honolulu, HI [P4233]",
    "Fairfax Co, VA [P43662]",
    "",
    "Hawkins Co, TN [P41160]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Whitley Co, KY, Bethel Baptist Cem [P1940]",
    "",
    "",
    "",
    "",
    "Jonesboro, NC [P9793] [P22190]",
    "",
    "",
    "",
    "",
    "",
    "Raleigh, NC [P9524] [P11383]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Ann Arbor, MI [P1391] [P1391]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "NC [P1749] [P43481]",
    "",
    "",
    "Bunn Level, , Harnett Co, NC [P9977] [P11836]",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Middle Creek Cem. [P2500]",
    "Sevier Co, TN, Shiloh Cem. [P20829]",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Trundle Family Cem. [P8798] [P10657]",
    "",
    "",
    "",
    "",
    "Tennessee, probably Monroe Co. [P8878] [P10737]",
    "",
    "Sevier Co, TN, Trundle Family Cem. [P8798] [P10657]",
    "Knox Co, TN, Grassy Valley Community [P8850] [P10709]",
    "Sevier Co, TN, Trundle Family Cem. [P8798] [P10657]",
    "",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P1732] [P43464]",
    "",
    "",
    "",
    "Roane Co, TN (now Loudon Co) [P8888] [P10747]",
    "Cumberland Co, VA [P8856] [P10715]",
    "Sevier Co, TN, Trundle Family Cem. [P8798] [P10657]",
    "Sevier Co, TN, Trundle Family Cem. [P8798] [P10657]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Fowler Cem. [P8898] [P10757]",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Fowler Cem. [P8898] [P10757]",
    "",
    "",
    "",
    "Sunset Cem., Shelby, Cleveland Co, NC [P42318]",
    "",
    "",
    "",
    "",
    "",
    "Osgood, NC [P10018] [P50461]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Durham, NC [P1634] [P61725]",
    "",
    "",
    "",
    "",
    "",
    "Fayetteville Hosptial, Cumberland Co, NC [P9680] [P52134]",
    "",
    "",
    "Siler City, Chatham Co, NC [P10358] [P50835]",
    "",
    "",
    "McLeod Hospital, Florence, SC [P9550] [P51991]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Paris,,,France [P0039] [P0039]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "See note. [P44659]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Lake County, IL [P1203] [P1203]",
    "Victoria, TX [P1071] [P1071]",
    "State College, PA [P1423] [P1423]",
    "",
    "",
    "",
    "",
    "",
    "Rockland, ME [P0956] [P0956]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Palatka, FL [P1594] [P1594]",
    "",
    "",
    "",
    "Vicksburg, MS [P1380] [P1380]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Butte, MT [P1045] [P1045]",
    "",
    "",
    "",
    "Sevierville, TN [P1290] [P1290]",
    "",
    "",
    "",
    "",
    "",
    "Ottawa, IL [P0978] [P0978]",
    "",
    "",
    "",
    "",
    "",
    "Lake City, FL [P1102] [P1102]",
    "",
    "Arlington, VA [P1126] [P1126]",
    "",
    "Naples, FL [P1273] [P1273]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Lexington Park, MD [P1301] [P1301]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Palatka, FL [P1594] [P1594]",
    "Kokomo, IN [P1345] [P1345]",
    "",
    "",
    "",
    "Columbus, GA-AL [P4279]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Beckley, WV [P1461] [P43197]",
    "Buenos Aires,Argentina [P3763]",
    "",
    "",
    "",
    "",
    "Borgetto, Sicily, Italy [P44141]",
    "Borgetto, Sicily, Italy [P44141]",
    "",
    "Marshall, MN [P1556] [P43289]",
    "Savannah, GA [P1452] [P43189]",
    "Merced, CA [P1510] [P43244]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Nr Cassel,France [P8718] [P10577]",
    "",
    "#6 Via Dilluvio, Borgetto, Sicily, Italy [P10215] [P10215]",
    "",
    "",
    "",
    "Sevier Co, TN, White Oak Flats Cem. [P1890] [P43615]",
    "",
    "Freehold, NJ [P3300] [P3300]",
    "Rutherford, NJ [P3297] [P3297]",
    "",
    "NY City, NY [P3314] [P41799]",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502] [P11361]",
    "",
    "",
    "Santa Fe, NM [P41881]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Troy, AL [P1450] [P1450]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Del Rio, TX [P8744] [P51105]",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Mt. Pleasant Cem., Jones Cove [P8941] [P37023]",
    "Sevier Co, TN, Shiloh Cem. [P1732] [P43464]",
    "Wethersfield, Hartford, CT [P10134] [P10134]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Shady Grove Baptist Cem. [P9053] [P21450]",
    "",
    "",
    "Sevier Co, TN, Boogertown Cem. [P9056] [P21453]",
    "Sevier Co, TN, White Oak Flats Cem. [P1890] [P1890]",
    "",
    "",
    "Sevier Co, TN, Boogertown Cem. [P9056] [P21453]",
    "",
    "Sevier Co, TN, White Oak Flats Cem. [P1890] [P1890]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Walnut Grove Cem. [P1882] [P1882]",
    "",
    "",
    "",
    "",
    "Sevier Co, TN [P8763] [P21160]",
    "",
    "",
    "Sevier Co, TN, Proffitt Cem. [P9041] [P21438]",
    "Sevier Co, TN, Red Bank Cem. [P9057] [P21454]",
    "",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P1732] [P1732]",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P44064]",
    "",
    "",
    "",
    "Waterloo-Cedar Falls, IA [P20672]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Golf Course Cem., Pigeon Forge [P20871] [P39507]",
    "",
    "Sevier Co, TN [P1726] [P1726]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Died in North Carolina [P20902] [P39538]",
    "",
    "",
    "",
    "",
    "Anderson Co, TN; buried Sevier Co, TN, Shiloh Cem. [P20817] [P39453]",
    "Whole career 1969- at DOE Y-12 Plant in Oak Ridge, TN [P20808] [P39444]",
    "",
    "McCreary Co, KY, Bethel Baptist Cem. [P20837] [P39473]",
    "Sevier Co, TN, Shiloh Cem. [P20829] [P39465]",
    "",
    "",
    "",
    "",
    "",
    "Whitley Co, KY, Wolf Creek Cem. [P1767] [P1767]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "South Carolina [P20919] [P39555]",
    "Whitley Co, KY [P1735] [P1735]",
    "Whitley Co, KY, Wolf Creek Cem. [P1767] [P1767]",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P20829] [P39465]",
    "",
    "McCreary Co, KY, Davenport-Ball Cemetery [P2549] [P2549]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Washington Co, NC [P20861] [P39497]",
    "Whitley Co, KY, Wolf Creek Cem. [P1767] [P1767]",
    "Tyrrell Co, NC [P1771] [P1771]",
    "",
    "",
    "",
    "",
    "Washington Co, NC [P20861] [P39497]",
    "died August ?, 1843 (indistinct), and [P1988] [P1988]",
    "",
    "Colonial Militia, 1754 [P1825] [P1825]",
    "",
    "",
    "",
    "Sevier Co, TN [P1726] [P1726]",
    "",
    "See Notes. [P20821] [P39457]",
    "Sevier Co, TN, Headrick Cem. [P20903] [P39539]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN [P1726] [P1726]",
    "Sevier Co, TN, Shiloh Cem. [P20829] [P39465]",
    "",
    "",
    "",
    "Sevier Co, TN, Galilee Cem., Seymour [P20904] [P39540]",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P20829] [P39465]",
    "Blount Co, TN, Sherwood Memorial Cem. [P20830] [P39466]",
    "",
    "McCreary Co, KY [P20845] [P39481]",
    "Family lived Lantana, FL [P1728] [P1728]",
    "Whitley Co, KY, Jellico Baptist Creek Cem. [P20894] [P39530]",
    "Another Mary (?) Davenport married Zebedee Hassell, 3/15/1770 [P20911] [P39547]",
    "",
    "Washington Co, NC [P20861] [P39497]",
    "",
    "",
    "",
    "",
    "",
    "Code: 0-10,   10-16,   16-26,   26-45,   45-up [P19376] [P38005]",
    "Whitley Co, KY, Jellico Creek Baptist Cem. [P20889] [P39525]",
    "",
    "",
    "Probably Washington Co, NC [P2342] [P2342]",
    "Sevier Co, TN, Shiloh Cem. [P20829] [P39465]",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P20829] [P39465]",
    "",
    "",
    "",
    "Sevier Co, TN, Mattox Cem. [P2311] [P2311]",
    "McCreary Co, KY [P20845] [P39481]",
    "",
    "",
    "",
    "Tyrrell Co, NC [P1771] [P1771]",
    "",
    "",
    "",
    "Sevier C0, TN [P20883] [P39519]",
    "",
    "",
    "",
    "Kansas [P20874] [P39510]",
    "",
    "",
    "",
    "Pigeon Forge, Sevier Co, TN, Shiloh Cem. [P20826] [P39462]",
    "",
    "",
    "",
    "Whitley Co, KY, Wolf Creek Cem. [P1767] [P1767]",
    "Sevier Co, TN, Shiloh Cem. [P20829] [P39465]",
    "McCreary Co, KY, Bethel Baptist Cem. [P20837] [P39473]",
    "",
    "Tyrrell Co, NC [P1771] [P1771]",
    "Pigeon Forge, Sevier Co, TN, Shiloh Cem. [P20826] [P39462]",
    "",
    "Another, older Stephen m. Elizabeth Alexander, 1778 [P19382] [P38011]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Whitley Co, KY, Wolf Creek Cem. [P1767] [P1767]",
    "",
    "Knox Co, TN, Galilee Cem, Seymour [P20896] [P39532]",
    "Washington Co, NC [P20861] [P39497]",
    "",
    "",
    "",
    "Little Rock, Arkansas [P2551] [P41264]",
    "Whitley Co, KY, Speculate Wolf Creek Cem. [P20854] [P39490]",
    "",
    "Sevier C0, TN [P20883] [P39519]",
    "Borgetto, Sicily, Italy [P2716] [P41407]",
    "Living in April 1994 [P19565] [P38194]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Keene, NH [P20526] [P39158]",
    "",
    "",
    "",
    "Lawrence Co, TN [P2331]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Shiloh Cem. [P1732] [P1732] [P53032]",
    "",
    "",
    "",
    "Cokesbury, , Harnett Co, NC [P9784] [P22181] [P56957]",
    "",
    "",
    "Jefferson City, MO [P1633] [P1633] [P52933]",
    "",
    "",
    "Hattiesburg, MS [P1662] [P1662] [P52962]",
    "",
    "Henderson, Vance Co, NC [P10304] [P19047] [P53509]",
    "Wooster, OH [P1617] [P1617] [P52917]",
    "Jefferson City, MO [P1633] [P1633] [P52933]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Truelove Cem, Pascal Truelove Plc, Harnett Co, NC [P9516] [P21913] [P40583]",
    "",
    "",
    "Stockholm,Sweden [P3536] [P3536]",
    "",
    "Barking Abbey,Essex,England [P19795] [P38424]",
    "",
    "",
    "Peterborough,Castle [P19730] [P38359]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Evesham [P19667] [P38296]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Wake Co?, NC [P3138] [P3138]",
    "",
    "",
    "Johnston Memorial Hospital, Johnston County, NC [P3229] [P3229]",
    "Durham Co, Durham, NC [P3023] [P41705]",
    "",
    "Johnston County, NC [P3430] [P3430]",
    "",
    "",
    "",
    "Harnett  Co, NC [P19481] [P38110]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Unknown [P2832] [P41519]",
    "",
    "",
    "Houston, AR [P20980] [P39616]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett  Co, NC [P9507] [P21904]",
    "",
    "Harnett Co, NC [P9502] [P21899]",
    "",
    "",
    "",
    "",
    "",
    "John Brown Plc, Harnett Co, NC [P9670] [P22067]",
    "",
    "Harnett Co, NC [P9502] [P21899]",
    "Home plc, , Harnett Co, NC [P9536] [P21933]",
    "",
    "Harnett Co, NC [P9502] [P21899]",
    "Macedonia Bpt, ChurCem, Harnett Co, NC [P9551] [P21948]",
    "",
    "John Brown Plc, Harnett Co, NC [P9670] [P22067]",
    "",
    "",
    "",
    "Harnett Co, NC [P9502] [P21899]",
    "",
    "",
    "Lives in Lillington, Harnett Co, NC [P10069] [P18812]",
    "",
    "Harnett  Co, NC [P9507] [P21904]",
    "Wake Co, NC [P9535] [P21932]",
    "Lives in Christina Light, Harnett Co, NC [P10068] [P18811]",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502] [P21899]",
    "Home Plc, Cokesbury Area, Harnett Co, NC [P9661] [P22058]",
    "Harnett Co, NC [P9502] [P21899]",
    "",
    "Wilson Hospital, NC [P9738] [P22135]",
    "Depot Street, Fuquay Springs, NC [P10011] [P18754]",
    "Harnett Co., NC [P9544] [P21941]",
    "",
    "Western Wake Hospital, Wake County, Cary, NC [P10072] [P18815]",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502] [P21899]",
    "",
    "Wake Mem Hosp., Raleigh, NC [P9620] [P22017]",
    "340 W.Academy St, Fuquay-Varina, NC 27526 [P9641] [P22038]",
    "",
    "",
    "",
    "Vetrians Hospital [P10065] [P18808]",
    "Harnett Co, NC [P9502] [P21899]",
    "",
    "",
    "Lives in Greensboro [P10067] [P18810]",
    "",
    "Home Plc, Harnett Co, NC [P9485] [P21882]",
    "",
    "Harnett Co, NC [P9502] [P21899]",
    "",
    "NC [P1749] [P1749]",
    "Harnett  Co, NC [P9507] [P21904]",
    "",
    "Harnett  Co, NC [P9507] [P21904]",
    "Harnett  Co, NC [P9507] [P21904]",
    "Harnett Co, NC [P9502] [P21899]",
    "",
    "",
    "Harnett Co, NC [P9502] [P21899]",
    "",
    "Lives in California [P10070] [P18813]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cocke Co, TN, Shults Cem., Cosby [P9151] [P21548]",
    "",
    "",
    "",
    "Janesville, WI [P0944] [P0944]",
    "Rolla, MO [P1093] [P1093]",
    "",
    "",
    "",
    "Troy, AL [P1450] [P1450]",
    "",
    "",
    "",
    "",
    "Granbury, TX [P1434] [P1434]",
    "",
    "",
    "",
    "Ottawa, IL [P0978] [P0978]",
    "",
    "Pullman, WA [P1320] [P1320]",
    "",
    "",
    "",
    "",
    "Longview-Kelso, WA [P1341] [P1341]",
    "",
    "Troy, AL [P1450] [P1450]",
    "Kendallville, IN [P1501] [P1501]",
    "Ottawa, IL [P0978] [P0978]",
    "",
    "Ada, OK [P1366] [P1366]",
    "Worthington, MN [P1385] [P1385]",
    "Rolla, MO [P1093] [P1093]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Ottawa, IL [P0978] [P0978]",
    "Lafayette, IN [P1502] [P1502]",
    "Reno-Sparks, NV [P1101] [P1101]",
    "",
    "Ottawa, IL [P0978] [P0978]",
    "",
    "",
    "",
    "",
    "Reno-Sparks, NV [P1101] [P1101]",
    "",
    "",
    "Savannah, GA [P1452] [P1452]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Medford, OR [P1493] [P1493]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Rolla, MO [P20254] [P38886]",
    "",
    "London, KY [P20482] [P39114]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "London,,England [P0378] [P0378]",
    "",
    "",
    "",
    "",
    "",
    "McAlester, OK [P1112] [P1112]",
    "",
    "",
    "Harnett  Co, NC [P19481] [P38110]",
    "",
    "",
    "Wethersfield, Hartford, Ct. [P3277] [P41794]",
    "",
    "Wethersfield, Hartford, Ct. [P3277] [P41794]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier CO, TN, Williams-Ridings Cem [P2220] [P2220]",
    "Holly SprsBptChur, Harnett Co, NC [P2672] [P41363]",
    "",
    "",
    "",
    "",
    "Berea, Marion Co, TX [P3223] [P3223]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Tennessee [P20895] [P39531]",
    "",
    "",
    "Summerville, GA [P20257] [P38889]",
    "Harnett Co, NC [P2618] [P41311]",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P2618] [P41311]",
    "Holland-Grand Haven, MI [P4380]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P2618] [P41311]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Anderson, IN [P41972]",
    "",
    "",
    "",
    "",
    "Davenport, IA [P4680]",
    "",
    "",
    "",
    "",
    "Paris, TN [P10562]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Rome, Sumner, KS [P3218] [P3218]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Washington Co, VA [P2556] [P2556]",
    "",
    "Cocke Co, TN, Shults Cem., Cosby [P19322] [P37951]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Richmond, KY [P4520]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Tyler, TX [P4166]",
    "Durham, NC",
    "Durham, NC",
    "",
    "Central Carolina Hospital, Sanford, Lee Co, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Buckingham,Palace,London,England [P0006] [P0006]",
    "",
    "",
    "",
    "",
    "Piney Grove, Bapt Chur, Wake Co, NC [P44080]",
    "",
    "Harnett Co, NC [P44064]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Home Plc, , Raleigh, NC [P44130]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Plattsburgh, NY [P1257] [P1257] [P52557]",
    "Wooster, OH [P1617] [P1617] [P52917]",
    "Sevier County, Tenn around 1810 and died there [P9429] [P21826]",
    "",
    "",
    "",
    "",
    "",
    "Lantana, Florida [P9186] [P21583]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Tennessee [P1808] [P1808]",
    "",
    "",
    "",
    "Sevier Co, TN, Plemmons Cem. [P9370] [P21767]",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Headrick Cem. [P1816] [P1816]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier CO, TN, Old Plemmons Cemetery, Greenbrier [P9371] [P21768]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502] [P11361]",
    "",
    "Wake Co, NC [P9535] [P11394]",
    "",
    "",
    "Harnett Co, NC [P9502] [P11361]",
    "Cokesbury, Harnett Co, NC [P9675] [P11534]",
    "",
    "",
    "Cokesbury, Harnett Co, NC [P9675] [P11534]",
    "",
    "",
    "Depot Street, Fuquay Springs, NC [P10011] [P10011]",
    "",
    "",
    "Harnett Co, NC [P9502] [P11361]",
    "",
    "Harnett Co, NC [P9502] [P11361]",
    "",
    "",
    "",
    "Home, Cokesbury Road, Harnett Co, NC [P9529] [P11388]",
    "",
    "",
    "",
    "",
    "Sevier Co, TN [P8763] [P10622]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Macedonia BapChurCem, Harnett Co, NC [P9578] [P21975]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Macedonia BapChurCem, Harnett Co, NC [P9578] [P21975]",
    "",
    "",
    "Harnett Co, NC [P9502] [P21899]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Fowler Cem. [P8898] [P21295]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Buckhorn Twsp, Harnett Co, NC",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC",
    "Hudson, NY",
    "",
    "Wilmington, DE-MD-NJ",
    "Lee Co, NC",
    "",
    "",
    "",
    "",
    "Harnett Co, NC",
    "",
    "",
    "",
    "",
    "Lives Chalk Level, Harnett Co, NC",
    "",
    "",
    "",
    "Lee Co, NC",
    "Harnett Co?, NC",
    "Harnett Co?, NC",
    "",
    "Harnett Co?, NC",
    "Harnett Co., NC",
    "Moncure, Chatham Co, NC",
    "",
    "",
    "Kansas",
    "",
    "",
    "",
    "Greensboro, NC",
    "Lumberton, NC",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Elizabeth City, NC [P1549] [P43282]",
    "Safford, AZ [P0873] [P42779]",
    "Lake County, IL [P1203] [P43090]",
    "",
    "Red Bluff, CA [P1209] [P43096]",
    "Poplar Bluff, MO [P1663] [P43396]",
    "",
    "Lake County, IL [P1203] [P43090]",
    "Chillicothe, OH [P1150] [P43041]",
    "",
    "Poplar Bluff, MO [P1663] [P43396]",
    "Poplar Bluff, MO [P1663] [P43396]",
    "",
    "",
    "Southington, CT [P10138] [P10138]",
    "",
    "Southerning, CT [P10132] [P10132]",
    "New Bern?, NC [P10136] [P10136]",
    "",
    "John Brown Plc, , Harnett Co, NC [P9491] [P37123]",
    "Clayton, Johnston Co, NC [P10105] [P10105]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "NC [P1749] [P43481]",
    "",
    "Moncure Methodist Cem, Moncure, NC [P9819] [P11678]",
    "",
    "Wethersfield, Hartford, CT [P10134] [P10134]",
    "",
    "Wethersfield, Hartford, CT [P10134] [P10134]",
    "",
    "",
    "",
    "",
    "",
    "NC [P1749] [P43481]",
    "",
    "",
    "Near Chalk Level, Northern Harnett Co, NC [P9666] [P11525]",
    "",
    "",
    "",
    "",
    "Newington, CT [P10131] [P10131]",
    "",
    "",
    "Apex, Wake Co, NC [P9821] [P11680]",
    "",
    "Haywood, , Chatham Co, NC [P9817] [P11676]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Jackson, MI [P20451] [P39083]",
    "Toledo, OH [P20141] [P38770]",
    "",
    "Redding, CA [P20397] [P39029]",
    "",
    "",
    "",
    "",
    "Coldwater, MI [P20268] [P38900]",
    "McAlester, OK [P20271] [P38903]",
    "Miami, Florida [P3298]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Albuquerque, NM [P1398] [P52698]",
    "Bydgoszcz, Poland [P10206] [P10206]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cocke County, TN [P9166] [P21563]",
    "",
    "",
    "",
    "",
    "",
    "Durham, NC [P1634] [P1634]",
    "Apex, , , NC [P9546] [P21943]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Centers Rest Home, Harnett Co, NC [P10142] [P18885]",
    "",
    "",
    "",
    "",
    "Johnston Co NC [P10320] [P19063]",
    "",
    "",
    "Durham, NC [P1634] [P1634]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Married (2) ?; 2 girls, 1 boy total [P8969] [P21366]",
    "",
    "",
    "",
    "Sevier Co, TN, Ridings-Williams Cem. [P8777] [P21174]",
    "Sevier Co, TN [P8763] [P21160]",
    "",
    "Nephew Joel Williams moved to Texas, stayed with them for a time [P8966] [P21363]",
    "Sevier Co, TN, Old Shults Cem., past Shults Grove [P8943] [P21340]",
    "",
    "",
    "Sevier Co, TN, Thomas Cem. [P1851] [P1851]",
    "Sevier CO, Tennessee [P8957] [P21354]",
    "White Pine, Rankin, &amp;amp;amp;quot;the Gulf&amp;amp;amp;quot; [P9001] [P21398]",
    "Sevier Co, TN, Williams-Ridings Cem. [P8970] [P21367]",
    "",
    "Sevier Co, TN, Williams-Ridings Cem. [P8970] [P21367]",
    "Sevier Co, TN, Fowler Cem. [P8898] [P21295]",
    "",
    "",
    "",
    "",
    "Sevier Co, TN [P8763] [P21160]",
    "",
    "Sevier Co, TN, Old Shults Cem., past Shults Grove [P8943] [P21340]",
    "",
    "",
    "Texarkana, TX [P8988] [P21385]",
    "",
    "",
    "",
    "",
    "Probably Cocke Co, TN [P1845] [P1845]",
    "",
    "",
    "Sevier Co, TN, Williams-Ridings Cem. [P8970] [P21367]",
    "Conditions allowed only to 5th grade in school, but was avid reader [P1725] [P1725]",
    "",
    "",
    "",
    "Sevier Co, TN, Shady Grove Baptist Cem. [P9053] [P21450]",
    "Sevier C0, TN, Williams-Ridings Cem [P8963] [P21360]",
    "Sevier Co, TN, Williams-Ridings Cem. [P8970] [P21367]",
    "",
    "",
    "Sevier Co, TN, Williams-Ridings Cem. [P8970] [P21367]",
    "",
    "Sevier Co, Huff Cem. [P9286] [P21683]",
    "",
    "",
    "",
    "",
    "Jorden had earlier lived in Haywood Co, NC up to 1820, at least [P8984] [P21381]",
    "West Virginia [P8986] [P21383]",
    "",
    "Cocke Co, TN, Union Cem., Newport [P8958] [P21355]",
    "Sevier C0, TN [P1796] [P1796]",
    "",
    "",
    "Sevier Co, TN, Fowler Cemetery [P8924] [P21321]",
    "Sevier Co, TN [P8763] [P21160]",
    "but this conflicts with Dillard (1821); [P8978] [P21375]",
    "Sevier Co, TN, Ridings-Williams Cem. [P8777] [P21174]",
    "",
    "",
    "West Virginia [P8986] [P21383]",
    "",
    "Sevier Co, TN, Fowler Cem. [P8898] [P21295]",
    "",
    "Sevier Co, TN, Webbs Creek Methodist Cem. [P8961] [P21358]",
    "Sevier C0, TN, P. W. Shults Cem (only 3 graves) [P8956] [P21353]",
    "married November 17, 1882. [P9060] [P21457]",
    "Cocke Co, TN [P8814] [P21211]",
    "Sevier Co, TN, Williams-Ridings Cem. [P8970] [P21367]",
    "",
    "",
    "Sevier Co, TN, old Shults Cem., behind Shults Grove [P9160] [P21557]",
    "",
    "Sevier Co, TN, Williams-Ridings Cem. [P8970] [P21367]",
    "Sevier Co, TN, Ridings-Williams Cem. [P8777] [P21174]",
    "",
    "Sevier Co, TN, Ridings-Williams Cem. [P8777] [P21174]",
    "",
    "",
    "Sevier Co, TN, Williamsburg Cem. [P9096] [P21493]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Holders Grove Cem [P9322] [P21719]",
    "",
    "",
    "",
    "Sevier Co, TN, Proffitt Cem., Jones Cove [P9214] [P21611]",
    "",
    "",
    "",
    "",
    "",
    "Kokomo, IN [P20483] [P55089]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Paris,,,France [P0039] [P0039]",
    "",
    "",
    "",
    "",
    "Morven,,,Scotland [P0044] [P0044]",
    "",
    "Sandringham,Norfolk,England [P0023] [P0023]",
    "Sandringham,Norfolk,England [P0023] [P0023]",
    "",
    "",
    "",
    "Wood Farm,Wolferton,Norfolk,England [P0045] [P0045]",
    "",
    "Harewood House,Yorkshire,,England [P0043] [P0043]",
    "",
    "",
    "",
    "",
    "",
    "Near,Wolverhampton,England [P0079] [P0079]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN [P43458]",
    "",
    "",
    "",
    "",
    "",
    "East Stroudsburg, PA [P1118] [P1118]",
    "",
    "Waterloo-Cedar Falls, IA [P42040]",
    "Akron, OH [P4430]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1415 Pointer Road, Roxboro , Person Co, NC [P9707] [P22104]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Nice [P0398] [P0398]",
    "Starnbergersee,Near Schloss,Berg [P0403] [P0403]",
    "Sarvar,Hungary [P0258] [P0258]",
    "",
    "",
    "Schloss,Nymphenburg,Germany [P0247] [P0247]",
    "",
    "Near,Munich [P0405] [P0405]",
    "Bamberg,Germany [P0407] [P0407]",
    "",
    "",
    "Harnett Co, NC [P9502] [P21899] [P56646]",
    "",
    "Fuquay-Varina, NC [P9744] [P22141] [P56913]",
    "",
    "Bradley Cem, Harnett Co, NC [P9745] [P22142] [P56914]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Frederick Co, MD [P8867] [P10726]",
    "",
    "",
    "",
    "",
    "Sevier Co, TN [P8763] [P10622]",
    "Frederick Co, MD [P8867] [P10726]",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Banner Cem. [P9303] [P11162]",
    "",
    "",
    "Sevier Co, TN, Old Roberts Cem., Richardson's Cove [P8815] [P10674]",
    "",
    "",
    "",
    "Sevier Co, TN, Middle Creek Methodist Cem. [P8868] [P37010]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Anderson Co, TN, Black Cem., Claxton [P43829]",
    "",
    "",
    "",
    "Dallas, TX [P42110]",
    "San Diego, CA [P4196]",
    "Guaynabo, PR [P4601]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "TX [P44459]",
    "See his Will, dtd 1790 [P44413]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Wake Co, NC [P44093]",
    "",
    "",
    "Wake Co, NC [P44093]",
    "",
    "",
    "",
    "",
    "Wake Co, NC [P44093]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Living 1993 [P44547]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P44064]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Monroe, WI [P4378]",
    "",
    "",
    "",
    "Plattsburgh, NY [P4549]",
    "",
    "",
    "Lincoln, IL [P4403]",
    "",
    "",
    "Oxford, MS [P4773]",
    "Muskegon, MI [P4253]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Billings, MT [P4532]",
    "",
    "Corbin, KY [P4720]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Allen Cem. [P8932] [P21329] [P56019]",
    "Crossville, TN [P1645] [P1645] [P52945]",
    "",
    "Topeka, KS [P1592] [P1592] [P52892]",
    "Topeka, KS [P1592] [P1592] [P52892]",
    "",
    "",
    "Topeka, KS [P1592] [P1592] [P52892]",
    "Topeka, KS [P1592] [P1592] [P52892]",
    "",
    "Topeka, KS [P1592] [P1592] [P52892]",
    "",
    "",
    "",
    "Topeka, KS [P1592] [P1592] [P52892]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Clarksdale, MS [P1059] [P1059] [P51090]",
    "Cookeville, TN [P1641] [P1641] [P52941]",
    "Marshall, TX [P1407] [P1407] [P52707]",
    "",
    "",
    "",
    "",
    "",
    "Racine, WI [P1193] [P1193] [P52493]",
    "",
    "Cookeville, TN [P1641] [P1641] [P52941]",
    "",
    "",
    "",
    "Cookeville, TN [P1641] [P1641] [P52941]",
    "",
    "Poplar Bluff, MO [P1663] [P1663] [P52963]",
    "",
    "",
    "Clearlake, CA [P1666] [P1666] [P52966]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Coyacan, Mexico City, Mexico [P10100] [P18843] [P53285]",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Emerts Cove Cem. [P1863] [P1863] [P1863]",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Emerts Cove Cem. [P1863] [P1863] [P1863]",
    "",
    "Sevier Co, TN, Emerts Cove Cem. [P1863] [P1863] [P1863]",
    "Carter Co, TN [P9410] [P21807] [P40470]",
    "Sullivan Co, TN [P9411] [P21808] [P40471]",
    "Washington Co, MD [P9408] [P21805] [P40468]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Burks Co, PA [P8781] [P21178] [P39815]",
    "",
    "",
    "",
    "McPherson, KS [P1234] [P1234] [P52534]",
    "",
    "",
    "",
    "Pittsburg, KS [P1090] [P1090] [P51431]",
    "Gettysburg, PA [P1527] [P1527] [P52827]",
    "Fort Dodge, IA [P1161] [P1161] [P52212]",
    "",
    "",
    "Albert Lea, MN [P1260] [P1260] [P52560]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "(likely in) NC or AL [P9941] [P22338] [P57129]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Nashville, TN",
    "West Palm Beach, FL",
    "Nashville, TN",
    "Frederick, MD",
    "Fayetteville, AR",
    "",
    "Ashtabula, OH",
    "Ashtabula, OH",
    "Nashville, TN",
    "Shreveport, LA",
    "",
    "Clearlake, CA",
    "Milledgeville, GA",
    "Nashville, TN",
    "Saginaw, MI",
    "Cortland, NY",
    "",
    "Shreveport, LA",
    "",
    "Johnstown, PA",
    "Branson, MO",
    "",
    "",
    "",
    "Sevier Co, TN, Cole Cem. [P2415]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Ashtabula, OH [P1332] [P8078]",
    "",
    "",
    "Norfolk, NE [P1002] [P42899]",
    "Tower of London,London,England [P10541]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Macedonia BapChurCem, Harnett Co, NC [P9578] [P21975]",
    "",
    "Grainger Co, TN, Shiloh Cem. [P9020] [P37043]",
    "",
    "",
    "",
    "",
    "Elkhart, IN [P20273] [P38905]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, White Oak Flats Cem. [P1890] [P43615]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Baptist Grove Church, Harnett Co, NC [P10121] [P18864]",
    "",
    "Burley, ID [P1247] [P1247]",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502] [P21899]",
    "Wake/Harnett Co, NC [P9649] [P22046]",
    "",
    "",
    "Indiana, PA [P1250] [P1250]",
    "",
    "",
    "Bermondsey Abbey [P0370] [P0370]",
    "",
    "",
    "",
    "",
    "",
    "Wake Co, NC [P44093]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sevier Co, TN, Boogertown Cem. [P9056] [P10915]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Lancaster Co, PA (now York Co, PA) [P2427]",
    "",
    "",
    "",
    "",
    "Olive Branch Cem, Kipling, Harnett Co, NC [P9946] [P11805]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Family Graveyard, Harnett Co, NC [P9945] [P11804]",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502] [P11361]",
    "",
    "",
    "",
    "",
    "",
    "(Harnett Co), NC [P10050] [P10050]",
    "",
    "",
    "Harnett  Co, NC [P9507] [P37126]",
    "Cokesbury United, Meth Chur, Harnett Co, NC [P9719] [P11578]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P9502] [P11361]",
    "",
    "",
    "Cotten Cem, Harnett Co, NC [P10052] [P10052]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Hinesville, GA [P4522]",
    "",
    "",
    "",
    "",
    "",
    "Fargo, ND [P4220]",
    "",
    "",
    "",
    "",
    "Emporia, KS [P41969]",
    "",
    "",
    "",
    "",
    "Ottawa, IL [P4282]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Worthington, MN [P4670]",
    "",
    "",
    "Beaumont, TX [P4635]",
    "",
    "",
    "",
    "Andrews, TX [P4404]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Port St. Lucie, FL [P42006]",
    "",
    "Emporia, KS [P41969]",
    "",
    "",
    "Andrews, TX [P4404]",
    "",
    "Summerville, GA [P4397]",
    "",
    "",
    "Andrews, TX [P4404]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Andrews, TX [P4404]",
    "Summerville, GA [P4397]",
    "Summerville, GA [P4397]",
    "Worthington, MN [P4670]",
    "",
    "",
    "",
    "Moberly, MO [P4310]",
    "",
    "",
    "",
    "",
    "",
    "Dixon, IL [P20537] [P39170]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Point Pleasant, WV [P4731] [P41956]",
    "",
    "",
    "",
    "",
    "",
    "Dover, DE [P20237] [P38868]",
    "Terre Haute, IN [P20494] [P39126]",
    "",
    "Dixon, IL [P20537] [P39170]",
    "",
    "",
    "",
    "Bemidji, MN [P1543] [P37347]",
    "Rome, GA [P20708] [P39343]",
    "Selinsgrove, PA [P20533] [P39166]",
    "",
    "Marshall, MN [P20667] [P39301]",
    "",
    "",
    "",
    "",
    "Tuskegee, AL [P4515] [P4515]",
    "",
    "",
    "",
    "",
    "",
    "Cookeville, TN [P20747] [P39382]",
    "",
    "",
    "Whitley Co, KY, Wolf Creek Cem. [P1767] [P1767]",
    "",
    "Truelove Cem, Hall Co, GA [P10031] [P50476]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Anderson, SC [P1007] [P42904]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Birkhall [P44888]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Whitley Co, KY, Wolf Creek Cem. [P8769] [P10628]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Harnett Co, NC [P44064]",
    "Harnett Co, NC [P44064]",
    "Truelove FamCem, Harnett Co, NC [P44522]",
    "Harnett Co., NC [P44101]",
    "Huskey Cem [P43917]",
    "",
    "Olive Branch Cem, Kipling, Harnett Co, NC [P44430]",
    "",
    "",
    "Public Cem, Hwy 55 N., Fuquay-Varina, NC [P44523]",
    "",
    "Sevier C0, TN, Huskey Cem [P2192]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ""
]
scriptLoaded('dwr_db_I_death_place_8.js');
